- pkg/common/metadata/metadata.go
- pkg/didcomm/protocol/decorator/decorator.go
- pkg/didcomm/protocol/exchange/exchange.go
- pkg/didcomm/protocol/exchange/exchange_test.go
- pkg/didcomm/transport/transport_interface.go
- pkg/internal/didcomm/transport/mock/mock_transport.go
Implement following DID exchange client APIs documented in Aries spec.
1. Generate Invitation with Public DID or service endpoints
2. Send Exchange Request
3. Send Exchange Response
Closes #12 
> feat: did-comm : Implement DID Exchange client APIs

- .gitignore
- Makefile
- pkg/didcomm/transport/http/outbound.go
- pkg/didcomm/transport/http/outbound_test.go
- scripts/generate_test_keys.sh
- scripts/openssl_env.sh
- test/fixtures/openssl/openssl.cnf
Add HTTPS Outbound capability for Aries Agents to safely communicate between each other.
This implements the HTTP(S) Aries-RFC 25:
https://github.com/hyperledger/aries-rfcs/tree/master/features/0025-didcomm-transports#https
Only HTTPS will be supported for secured communications.
It support the DID Exchange Protocol 1.0 as per Aries-RFC 23:
https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange
To support unit-tests, sample test keys were generated using the openssl tool
Future work (to be implemented):
* Inbound HTTPS capability
* Implement the Pack/Unpack messaging capability
as described in Aries-RFC 19:
https://github.com/hyperledger/aries-rfcs/tree/master/features/0019-encryption-envelope
closes issue #8
Signed-off-by: Baha Shaaban …
> feat: Add Outbound HTTPS transport layer

- pkg/storage/connection/connstore.go
- pkg/storage/docstore/docstore.go
The Aries Framework should support pluggable storage(e.g file store, embedded db store, cloud store, etc.) for DID documents along with Connections(pairwise mapping).
This change defines the interface for the doc storage.
Closes #22 
> feat: Doc Storage interface definition

- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/http/outbound_test.go
- pkg/didcomm/transport/http/support_test.go
Similar to the Outbound transport capability
This change adds support for the Inbound transport cabaility
as per the Aries Agent exchange communcation RFC-23 and 25
Closes: #8
> feat: add HTTP Inbound transport capability

- pkg/common/log/api.go
-provided logging interface
-log levels supported - CRITICAL, ERROR, WARNING, INFO, DEBUG, where
INFO is default logging level
-logging provider implementation can be used to provide custom logging
provider
-Story: #21
> feat: logging interface

- pkg/internal/common/logging/metadata/callerInfo.go
- pkg/internal/common/logging/metadata/callerInfo_test.go
- pkg/internal/common/logging/metadata/level.go
- pkg/internal/common/logging/metadata/level_test.go
- pkg/internal/common/logging/metadata/opts.go
- pkg/internal/common/logging/metadata/opts_test.go
- pkg/internal/common/logging/metadata/util_test.go
- pkg/internal/common/logging/metadata/utils.go
- added module based log levels implementation where default log level is INFO
- added module and log level based caller info feature which shows caller function
names in log lines for given module and level configured.
- logger opts implementation is added which can be used by logger implementation
- Story: #21
> feat: moduled levels and caller infos for logging

- pkg/internal/common/logging/metadata/opts.go
- pkg/internal/common/logging/metadata/opts_test.go
- pkg/internal/common/logging/modlog/deflog.go
- pkg/internal/common/logging/modlog/deflog_test.go
- pkg/internal/common/logging/modlog/logtestutils.go
- pkg/internal/common/logging/modlog/modlog.go
- pkg/internal/common/logging/modlog/modlog_test.go
- pkg/internal/common/logging/modlog/provider.go
- pkg/internal/common/logging/modlog/provider_test.go
- defLog : default implementation of moduled logger built on top
of go 'log' package.
- modLog: moduled level based logger implementation wrapping custom logger implementation.
- Story: #21
> feat: default logger implementation

- go.mod
- go.sum
- pkg/didmethod/peer/store.go
- pkg/didmethod/peer/store_test.go
Implementation of Peer DID backing store spec (https://openssi.github.io/peer-did-method-spec/index.html#backing-storage) without conflict resolution
Implements #47
> feat: Peer DID Document store

- scripts/check_unit.sh
Removed parallel flag from go test command to run unit-tests.
Closes #62
> test: remove parallel flag from unit test

- go.mod
- go.sum
- pkg/didmethod/peer/did.go
- pkg/didmethod/peer/did_test.go
As defined in the [Spec.](https://openssi.github.io/peer-did-method-spec/index.html#method-specific-identifier), Peer did Identifier is generated. 
ABNF Syntax for Peer DID:
peer-did = "did:peer:" numalgo encalgo "-" numbasis 
numalgo = "1" 
encalgo = "1" 
numbasis = 64*HEXDIGCI 
HEXDIGCI = HEXDIG / "a" / "b" / "c" / "d" / "e" / "f"
The numbasis is generated from [Genesis Version](https://openssi.github.io/peer-did-method-spec/index.html#dfn-genesis-version) of the Peer DID. 
> feat: Generate Peer Did Identifier

- README.md
Badge for `goreportcard` shows an error when rendered on the [README](https://github.com/hyperledger/aries-framework-go/blob/master/README.md)
> Fix goreportcard badge

- pkg/didmethod/peer/did.go
- pkg/didmethod/peer/did_test.go
The receiving agent should have the capability to validate the DID Document against the name-string component of the DID Identifier.
closes #48
> Validate peer DID identifier 

- .golangci.yml
- pkg/common/log/logger_test.go
- pkg/didcomm/protocol/exchange/exchange_test.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/http/outbound_test.go
- pkg/didcomm/transport/http/support_test.go
- pkg/didmethod/peer/resolver_test.go
- pkg/didmethod/peer/store_test.go
- pkg/internal/common/logging/metadata/util_test.go
- pkg/storage/leveldb/leveldb_store_test.go
Update golangci to lint test files.
Fix lint warnings in test files.
Closes: #84
> ci: include test files in linter

- pkg/didmethod/peer/did.go
- pkg/didmethod/peer/did_test.go
Implement the exported method that will create the peer DID via newDID.
newDid() method creates the peer DID as per the spec : [https://openssi.github.io/peer-did-method-spec/index.html#method-specific-identifier](url)
closes #76
> feat: create NewDID which can embed peer DID into genesis doc

- pkg/didcomm/protocol/exchange/exchange.go
- pkg/didcomm/protocol/exchange/exchange_test.go
- pkg/framework/aries/api/factory.go
- pkg/framework/aries/default.go
- pkg/framework/aries/factory/transport/transport_factory.go
- pkg/framework/aries/factory/transport/transport_factory_test.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- Add New(opts) function which takes in the options to configuration
- Support outbound transport configuration
Closes #78
> feat: Framework Init - base template with Outbound transport config

- pkg/didmethod/httpbinding/resolver.go
- pkg/didmethod/httpbinding/resolver_test.go
```
This change adds support of Universal  HTTP DID Resolver
```
**Title:**
Universal  HTTP DID Resolver
This is a part of #99 and allows for Universal HTTP DID Resolver.
**Summary:**
This PR adds a definition of Universal  HTTP(s) DID Resolver which is based on standard `http.Client` HTTP client. It's used for making HTTP GET request and reading the DID document from the reply.
> feat: Universal HTTP DID Resolver

- pkg/didmethod/peer/resolver.go
- pkg/didmethod/peer/resolver_test.go
- pkg/framework/didresolver/api.go
- pkg/framework/didresolver/didresolver.go
- pkg/framework/didresolver/didresolver_test.go
Closes #65
* Make optional all args to DidMethod.Read() (aside from the DID)
* Add didresolver.ErrNotFound sentinel error to indicate when DID was not found
* Add GoDocs to `didresolver.DidMethod`
> refactor: #65 DidMethod.Read()

- pkg/framework/aries/api/factory.go
- pkg/framework/aries/factory/transport/transport_factory.go
- pkg/framework/aries/factory/transport/transport_factory_test.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
Add HTTP Client as the default transport provider
Closes #83 
> feat: Default Outbound Transport Provider

- cmd/aries-agentd/main.go
- cmd/aries-agentd/main_test.go
- pkg/didcomm/dispatcher/dispatcher.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/transport_interface.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- Message handler routes the messages to Protocol services depending on the message type
- The handler uses dispatcher.Service.Accept to redirect the inbound transfer
- HTTP server in main() uses inbound handlers from context
Closes #141 
> feat: Inbound Message Handler/Dispatcher

- cmd/aries-agentd/main_test.go
- pkg/framework/aries/default.go
- pkg/framework/aries/framework_test.go
- pkg/restapi/restapi_test.go
Intermittently the test cases fail due to levelDB resource unavailability as parallel tests lock on file system.
Updated test cases to update path through global variable. This global variable will be removed once config are handled through struct (#148 and #175).
Closes #191 
> test: Update leveldb path for test run

- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
Currently the protocol services are loaded in context.New() as protocols require ctx. This change moves that to framework.New() and creates a ctx object in framework.New() function.
Closes #189 
> refactor: Load Protocol Services in framework.New()

- cmd/aries-agentd/main.go
- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/transport_interface.go
- pkg/framework/aries/default.go
- pkg/framework/aries/defaults/defaults.go
- pkg/framework/aries/defaults/defaults_test.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/restapi/restapi_test.go
- Create interface for InboundTransport
- Provide HTTP InboundTransport based on the new interface
- Add HTTPInboundTransport as the default inbound transport provider
- Start the inbound transport in while creating a new framework
- Remove code from reference agent to build and start the HTTP inbound transport
Closes #188 
> feat: DIDComm Inbound Transport Initiation in framework.New()

- .circleci/config.yml
- .golangci.yml
- cmd/aries-agentd/main_test.go
- pkg/common/log/provider.go
- pkg/didcomm/crypto/jwe/authcrypt/authcrypt.go
- pkg/didcomm/crypto/jwe/authcrypt/encrypt.go
- pkg/doc/did/doc.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
- pkg/framework/aries/default.go
- pkg/internal/common/logging/metadata/opts.go
- pkg/internal/common/logging/metadata/utils.go
- pkg/internal/common/logging/modlog/logtestutils.go
- scripts/check_lint.sh
- Upgrade to golangci-lint v1.18
- Enable gochecknoglobals, nolen and dupl
- Disallow naked returns
- Resolve warnings
Noted TODOs to review global usage.
Closes: #205
Closes: #216
> Enable go linter suite

- pkg/client/didexchange/client.go
- pkg/client/didexchange/models.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/operation/didexchange/models/invitation.go
- added `/connections/{id}/accept-request` controller rest-api endpoint
- added accept exchange request in did-exchange client
- closes #170
> feat: Controller API for Accept Exchange Request

- pkg/didcomm/crypto/crypter.go
- pkg/didcomm/crypto/jwe/authcrypt/authcrypt_test.go
- pkg/didcomm/crypto/jwe/authcrypt/decrypt.go
completes #122 
Decrypt() function was taking a list of recipients as an array, this is not necessary as the recipient will decrypt with a private/public key pair
this change refactors Decrypt to take in this key pair as argument
> refactored Decrypt() with recipient keyPair

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_extension_switch_test.go
- pkg/doc/verifiable/credential_extension_test.go
- pkg/doc/verifiable/credential_test.go
According to @troyronda:
we should add an additional test case to provide an illustration of how a developer could choose which template to use.
decode into a basic verifiable credential
based on type info in the basic verifiable credential, decode into the more specialized type.
i.e., keep this test function that you created in this PR and add another one to illustrate the above.
Story: #218
> test: example selecting VC template based on basic one

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/operation/didexchange/models/invitation.go
- added connection.remove() endpoint in client and rest API
- all except connection query endpoints are changed to HTTP POST
- improved test coverage for `pkg/restapi/operation/didexchange`
- related to #247
> feat:added missing endpoints in controller API

- pkg/didcomm/crypto/crypter.go
- pkg/didcomm/crypto/crypter_test.go
- pkg/didcomm/crypto/jwe/authcrypt/authcrypt.go
- pkg/didcomm/crypto/jwe/authcrypt/authcrypt_test.go
- pkg/didcomm/crypto/jwe/authcrypt/decrypt.go
- pkg/didcomm/crypto/jwe/authcrypt/encrypt.go
the Crypter interface should not reference Golang's crypt/chacha20poly1035 package, it should allow for any crypto implementation to be used instead of being limited
> remove chacha dependency from crypter interface

- cmd/aries-agentd/main_test.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/framework/aries/framework.go
- pkg/internal/common/logging/metadata/opts_test.go
- scripts/check_unit.sh
* remove time.Sleep() from tests and listen for port to be available.
* random port generation (allows run tests in parallel)
Issue: https://github.com/hyperledger/aries-framework-go/issues/167
> refactoring: remove sleep & listen available & random port generation

- cmd/aries-agentd/main_test.go
The unit-test build in ubuntu fails with timeout error, where as it passes in macOS build. Increased the server timeout check to 2seconds from 1seconds.
> test: Increase main startup timeout to 2 seconds

- pkg/didmethod/peer/resolver_test.go
- pkg/didmethod/peer/store.go
- pkg/didmethod/peer/store_test.go
- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/framework/didresolver/didresolver_test.go
Currently DID Document supports only one proof. Add support for multiple proofs to DID Document. Also, change signatureValue to proofValue.
Closes #324
> feature: Add support for multiple proofs to DID Document

- pkg/didcomm/dispatcher/api.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
Added Register/Unregister Action/Msg event APIs to Protocol Services. These were implemented in as part of Issue #276 and PR #327.
Closes #332 
> feat: Update Protocol Service API with Event handling functions (Register/Unregister)

- pkg/didcomm/crypto/legacy/authcrypt/authcrypt.go
- pkg/didcomm/crypto/legacy/authcrypt/authcrypt_test.go
- pkg/didcomm/crypto/legacy/authcrypt/decrypt.go
- pkg/didcomm/crypto/legacy/authcrypt/encrypt.go
Implements the legacy authcrypt decrypter, following on from #139, the encrypter.
Fixes: #294
> feat: Legacy Authcrypt Decrypter

- pkg/didcomm/crypto/jwe/authcrypt/authcrypt.go
- pkg/didcomm/crypto/jwe/authcrypt/authcrypt_test.go
- pkg/didcomm/crypto/jwe/authcrypt/common.go
- pkg/didcomm/crypto/jwe/authcrypt/decrypt.go
- pkg/didcomm/crypto/jwe/authcrypt/decrypt_jwk.go
- pkg/didcomm/crypto/jwe/authcrypt/decrypt_jwk_test.go
- pkg/didcomm/crypto/jwe/authcrypt/encrypt.go
- pkg/didcomm/crypto/jwe/authcrypt/encrypt_jwk.go
- pkg/didcomm/crypto/jwe/authcrypt/encrypt_jwk_test.go
closes #302 
with this change, the Envelope encryption RFC can be updated to reflect the new (JWE compliment) format.
[aries issue  # 133](https://github.com/hyperledger/aries-rfcs/issues/133) will be updated to reflect the updated JWE format.
> feat: replace oid with spk(JWK) for sender public key

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- Support to consume DIDExchange service events in DID Exchange Client
- For now auto executing the callbacks for action events and logging for message events
Closes #249 
> feat: DIDExchange Client - Consume Service events

- pkg/client/didexchange/client_test.go
We have to feed proper did documents into service (has to have at least one public key)
> bug: Fix TestServiceEvents client test

- cmd/aries-agentd/startcmd/start_test.go
Small fix related to https://github.com/hyperledger/aries-framework-go/pull/290
While merging master into my own branch it looks like I missed some duplicated code which I had already refactored into a function to be used in a few different places. This duplicated code also had the wrong timeout (1 second instead of 2).
> Removed some duplicated code

- pkg/client/didexchange/client_test.go
- pkg/internal/mock/common/did/mock_creator.go
Client package tests should use common did creator
> chore: Client package tests should use common did creator

- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- Update Endpoint() to retun uri prefix (Added http as default framework only supports http)
- Added a Error logger for HTTP 500 cases for easier debugging
> refactor: Return "http://" uri prefix for HTTP Inbound transport

- pkg/doc/signature/ed25519signature2018/suite.go
- pkg/doc/signature/proof/data.go
- pkg/doc/signature/proof/data_test.go
- pkg/doc/signature/proof/proof.go
- pkg/doc/signature/proof/proof_test.go
- pkg/doc/signature/proof/utils.go
- pkg/doc/signature/proof/utils_test.go
The following algorithm specifies how to create the data that is used to generate or verify a digital signature.
Closes #243
> feat: Implement Create Verify Hash Algorithm

- pkg/doc/signature/proof/data.go
- pkg/doc/signature/proof/proof.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/signature/signer/signer_test.go
- pkg/doc/signature/verifier/verifier.go
- pkg/doc/signature/verifier/verifier_test.go
Linked Data document signatures are verified using Signature Verification Algorithm:
- fetch and verify the public key in the signature using key resolver
- call the Create Verify Hash Algorithm in order to create data that is used to generate or verify a digital signature
- verify signature in the proof against data created in the step above
Closes #245
> feat: Implement Linked Data Signature Verfication Algorithm

- .github/workflows/test-suite.yml
- Makefile
- scripts/run_vc_test_suite.sh
A workflow is added to GitHub Actions to enable test suite execution.
The VC test suite artifact directory is also moved under build.
Note: the test suite only runs when associated packages are changed.
> ci: run VC test suite

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_extension_switch_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/test-suite/config.json
- pkg/doc/verifiable/test-suite/verifiable_suite_test.go
closes #358
VC Test Suite statistics:
- 57 passing
- 19 pending
- 18 failing
The reasons for failing:
- JWT suite errors, ES256K support required (#381 )
- Cannot generate JWT from Verifiable Credential without the signature (#372 )
- Support of Verifiable Presentation (#371 )
- Several inconsistencies in VC Test Suite: [#96](https://github.com/w3c/vc-test-suite/issues/96), [#97](https://github.com/w3c/vc-test-suite/issues/97), [#98](https://github.com/w3c/vc-test-suite/issues/98)
The reasons for pending:
- Not implemented support of Zero Knowledge Proof (#180 ), `zkp` test suite is disabled for now.
> fix: VC data model and JWT to pass the test suite

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/internal/mock/wallet/mock_wallet.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/wallet/api.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
Replaced wallet.CreateKey with CreateEncryptionKey, since it's an encryption key (curve25519) and introduced a new CreateSigningKey method that actually creates signing keys (ed25519).
Updated references/usages to use correct keys.
> refactor: split wallet CreateKey into CreateSigningKey & CreateEncryptionKey

- pkg/didcomm/dispatcher/api.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- Currently the callback handles 2 scenario's : Continue with Processing and Fail processing. Both these are handled by Callback using Err field (nil to continue and err to fail).
- This Change will separate these 2 behaviours and provide separate APIs for the scenarios.
Closes #436 
> refactor: DIDExchange Event - Separate API for Continue and Stop

- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
closes #416
This change to remove the directly assessing first public key from the did doc. Instead it will loop through and fetch the key which is supported by the didcomm message protocol.
> refactor: Get public key in didexchange state

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_jwt.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- pkg/doc/verifiable/credential_jwt_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/jwt_unsecured.go
- pkg/doc/verifiable/jwt_unsecured_test.go
- pkg/doc/verifiable/support_test.go
- pkg/doc/verifiable/test-suite/verifiable_suite_test.go
closes #372
As a result, 2 VC Test Suite tests are passing.
As go-jose does not support unsecured JWT serialization, a workaround solution is used. [#264](https://github.com/square/go-jose/issues/264)is filed but was rejected by the authors of the go-jose.
> feat: Unsecured JWT from Verifiable Credential

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/common/service/event.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/dispatcher/api.go
- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/dispatcher/mock_outbound.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- test/bdd/agent_steps.go
- Move messages and events out of dispatcher pkg to separate pkgs
Closes #342 
> refactor: Move messages and events code from dispatcher pkg

- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
For now we will be using ed25519 signature suite to sign the message since we are currently using ed25519 signing keys only.
Closes #450
> feat: Implement SignMessage in the wallet

- pkg/didcomm/common/service/event.go
- pkg/didcomm/protocol/didexchange/event.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- test/bdd/agent_steps.go
- Currently the type of that is map[string]interface{}. The consumer would need to know the keys for each protocol and also they would need to cast to a type for each of those keys.
- Update this to interface{} type. That would require the consumers to know the type for each protocol. The each protocol can have an interface that will have functions for different properties.
Closes #457 
> refactor: Properties variable in Action/Msg event struct

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/common/service/event.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/transport_interface.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- added `ToVerKeys` from envelope to DID comm message, so that it can be
accessed inside service handles.
- DID exchange service needs these keys for persistence related changes
- service handle to accept pointer of DIDCommMsg 
( **reason**: `hugeParam: msg is heavy (80 bytes)`)
- closes #462 
> feat: Verification keys in DIDComm message

- pkg/didcomm/common/service/service.go
- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/transport_interface.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- reverted recent changes due to which inbound message handler had
access to whole envelope
- closes #478
> refactor: inbound message handlers to access messages only

- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/framework/aries/api/protocol.go
- pkg/framework/aries/api/wallet.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/internal/mock/wallet/mock_wallet.go
- pkg/wallet/api.go
Did exchange service has to sign connection response. Add signer to did exchange service context.
Closes #476
> refactor: Add signer to did exchange service context

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/common/service/errors.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/common/service/service_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/framework/context/context.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
This function will be reusable for introduce protocol as well
* threadID function as part of service.DIDCommMsg
> refactor: made threadID function part of service.DIDCommMsg

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/test-suite/verifiable_suite_test.go
closes #371
In this PR, the data model of Verifiable Credential is defined. It's checked by VC Test Suite to pass tests from **basic**  suite.
In the follow-up PR #483 , JWT proof support will be added to the Verifiable Presentations.
> feat: Verifiable Presentation data model

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/framework/context/context.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- Add following APIs to handle the messages in service layer.
- HandleInbound(DIDCommMsg)
- HandleOutbound(DIDCommMsg, Destination)
- Remove outbound related fields from DIDCommMsg struct
Closes #490 
> refactor: Split service.Handle function for Inbound/Outbound type

- cmd/aries-agentd/startcmd/start.go
- cmd/aries-agentd/startcmd/start_test.go
- pkg/restapi/restapi.go
- pkg/restapi/restapi_test.go
- pkg/restapi/webhook/webhook.go
- pkg/restapi/webhook/webhook_test.go
#200 
Aries-agentd now has the ability to send notification via a webhook. Clients are subscribed through a command line argument. Currently the server just sends sample messages every two seconds.
> feat: Webhook for aries-agentd

- pkg/didcomm/protocol/didexchange/service.go
- pkg/framework/aries/api/protocol.go
- pkg/framework/aries/default.go
- pkg/framework/aries/framework.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/framework/didresolver/api.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/internal/mock/didresolver/mock_didresolver.go
Expose DID resolver in didexchange service context. It is required for supporting public DIDs.
Closes #489
> refactor: Add DID resolver to didexchange service context

- pkg/didcomm/common/service/service.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
* `HandleInbound` and `stateFromName` methods implementation
* state interface was changed (Execute function was separated into ExecuteInbound and ExecuteOutbound)
Issue: https://github.com/hyperledger/aries-framework-go/issues/464
> feat: Introduce protocol service implementation

- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/models/invitation.go
- Removed didex service.Handle() API invocation from REST API.
- Instead used client.HandleInvitation() API.
> refactor: Remove DIDExchange Service Handle API invocation from RestAPI pkg

- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/persistence_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/restapi/operation/didexchange/didexchange_test.go
2 tests are turned off as they are already refactored as part of issue-397. 
This pr is the sub part of issue-397. In order to break down the pr and make it easy to review. 
closes #527
> feat: persistence layer for storing and retrieving connection record details 

- cmd/aries-agentd/startcmd/start.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/restapi.go
- pkg/restapi/restapi_test.go
- pkg/restapi/webhook/payloads.go
- pkg/restapi/webhook/webhook.go
- pkg/restapi/webhook/webhook_test.go
Closes #472 
Webhook notifier now sends arbitrary JSON messages. The ticker was removed.
The actual triggering of webhook notifications has to be done in another story since the REST Api is still in-progress.
> feat: Webhook notifier now sends JSON

- pkg/framework/aries/defaults/defaults_test.go
TestWithDBPath failed on AZP. This test now passes on AZP by
using a non-writable path.
> fix: db path test failure

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- Remove action events for exResponse and exAck message types
- Refactor Events test cases
- Add missing test cases
- Renamed prefixes for message type from Connection to DIDExchange
Closes #571 
> refactor: DIDExchange - Remove Action Events for exResponse and exAck type

- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/restapi/operation/didexchange/didexchange_test.go
Bob -> Invitee:
Bob receives an invitation from Alice
Bob creates and stores the connection Record {ConnectionID->uuid ,ThreadID -> uuid, Recipient, ServiceEndpoint, state -> invited, Theirlabel: invitation )
Store the mapping of {MyNS+ThreadID to ConnectionID}
Sends an automatic Exchange Request to Alice (using the ThreadID created in the step 3. )
Update the connectionRecord { state -> requested, Mydid-> from request}
Alice -> Inviter
Alice create the connection Record using the ThreadID in the request plus TheirNS {ConnectionID->uuid ,ThreadID :thid, state -> requested, TheirDID->did from request, TheirLabel-> from request }
Mapping (TheirNS+Thid -> ConnectionID)
Alice prepares the exchange Response to Bob (using the ThreadID created in the step 3. )
Update the connectionRecord { state …
> feat: Update the service and state to consume the persistence layer method

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/common_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_extension_switch_test.go
- pkg/doc/verifiable/credential_jws.go
- pkg/doc/verifiable/credential_jws_test.go
- pkg/doc/verifiable/credential_jwt.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- pkg/doc/verifiable/credential_jwt_test.go
- pkg/doc/verifiable/credential_jwt_unsecured.go
- pkg/doc/verifiable/credential_jwt_unsecured_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/support_test.go
closes #327
This PR brings the following improvements to the Verifiable Credential (VC):
- Keep extra fields of raw VC in a map (motivated by  [issue 22533](https://github.com/golang/go/issues/22533)); this leverages the extensibility of the data model and allows more strict serialization of the VC.
- Use stricter types in `Credential`: issuer, context, type (used generic `interface{}` or `[]interface{}` before).
- Simplify JWT decoding. Previously, JWT decoding resulted in returning `*rawCredential` and serialized JSON (`[]byte`) of VC. Now it returns only serialized JSON which is then unmarshalled to `rawCredential`.
> refactor: Serialization of Verifiable Credential with extended data model

- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- Added goroutine as State execution was executing in calling agents inbound thread. This would resulted in agent invoking next call before calling agent executing previous thread.
> fix: Execute state handling in a goroutine

- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/models.go
- pkg/restapi/webhook/payloads.go
- Moved webhook model inside didex package
- Wrapped connection details in webhook specific model
Part of #583 
> refactor: DIDEx Rest Notification - Wrapped Connection in RestAPI specific model

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/persistence_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
Currently, RestAPI message handle the tests fail intermittently. The connectionID retrieved from events used to fetch connection data from database. There is a possibility that the data in db gets updated before consumer calls the
db. This would make previous state data getting lost and consumer would receive same state notification twice.
- Save connection data after state execution.
- Add new API to get connection based on connectionID and stateID.
Closes #607 
> fix: Get Connection details based on state 

- cmd/aries-agentd/startcmd/start.go
- cmd/aries-agentd/startcmd/start_test.go
- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/framework/aries/default.go
- pkg/framework/aries/defaults/defaults.go
- pkg/framework/aries/defaults/defaults_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/restapi_test.go
- test/bdd/agent_sdk_steps.go
Closes #572 
Added a command line flag for specifying the external inbound host name. The external address is what's returned when you call Endpoint() on an Inbound object.
Fixed some small typos and formatting issues I found.
> Fix service endpoint in create invitation response

- images/agent/Dockerfile
- test/bdd/agent_controller_steps.go
- test/bdd/bddtests_test.go
- test/bdd/fixtures/agent/docker-compose.yml
- after fixing #572, agents will use external host while creating
invitations. This fixes issue with controller REST API test where
communication between agents were failing.
- closes #629
> feat: Controller API bddtests to verify completed state

- .gitignore
- Makefile
- README.md
- cmd/aries-agentd/main.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- scripts/generate-openapi-demo-specs.sh
- scripts/generate-openapi-spec.sh
- scripts/run_openapi_demo.sh
- test/bdd/fixtures/demo/openapi/.env
- test/bdd/fixtures/demo/openapi/docker-compose-demo.yml
Added below targets
- _`make generate-demo-specs`_ : generates demo specs for each demo agents
- _`make run-openapi-demo`_ : starts swagger ui docker containers using generated
spec as base.
- Part of #94
Once started, below links can be used to play with agents
**Alice Demo Agent :** http://localhost:8089/openapi/
**Bob Demo Agent :** http://localhost:9089/openapi/
Existing images/containers built for bdd tests are reused for demo.
> feat: OpenAPI user interface for demo

- cmd/aries-agentd/startcmd/start.go
- cmd/aries-agentd/startcmd/start_test.go
- images/agent/Dockerfile
- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/restapi.go
- pkg/restapi/restapi_test.go
- test/bdd/fixtures/agent/docker-compose.yml
Closes #552 
Invitation label is now passed via a command line argument.
> RestAPI - Get label value in CreateInvitation

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/persistence_test.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/internal/mock/storage/mock_store.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/operation/didexchange/models/invitation.go
- pkg/storage/leveldb/leveldb_store.go
- pkg/storage/leveldb/leveldb_store_test.go
- pkg/storage/store.go
- added Iterator() to store api interface to get iterator for given range.
- added query connections feature in connection recorder and client
- controller REST API to query all connections through client
- REST API to filter connections by state
- remaining query criteria will be applied as part of #655
- closes #429 
> feat: Query connections feature

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/client/didexchange/models.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/models/invitation.go
- test/bdd/agent_controller_steps.go
- added one more verification step in controller tests to verify
completed connection against connections list.
- moved state based filter logic from REST API to client
- removed openapi annotations from client model
- reverted exported service model `ConnectionRecord` from client 
- closes #429
> feat: bdd tests for get all connections

- Makefile
- Adds sample-webhook-docker as dependency for run-openapi-demo
Closes #668
> fix: build webhook image for REST demo

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- test/bdd/agent_controller_steps.go
- test/bdd/agent_sdk_steps.go
- test/bdd/context.go
- test/bdd/did_exchange_steps.go
- Support to return ID in HandleInbound API for correlating messages
Closes #537 
> refactor: Return ID in service.HandleInbound API

- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- The Recieve Invitation API saves and approves the invitation recieved. Updated Accept Invitation API to return error message.
> refactor: Accept Invitation API - Return error message

- test/bdd/agent_sdk_steps.go
- test/bdd/context.go
- test/bdd/did_exchange_steps.go
- test/bdd/features/didexchange_e2e_sdk.feature
- test/bdd/features/didexchange_public_did.feature
- Add DID exchange request approval step
- Derive connectionID from action event rather than message event
Closes #673 
> test: DIDExchange SDK BDD - Add exchange request approval step

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- pkg/doc/verifiable/jws.go
- pkg/doc/verifiable/jws_test.go
- pkg/doc/verifiable/jwt_unsecured.go
- pkg/doc/verifiable/jwt_unsecured_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_jwt_proof_test.go
- pkg/doc/verifiable/test-suite/verifiable_suite_test.go
Automatic detection of decoding of Verifiable Credential and Verifiable Presentation.
A user is not obligated to explicitly define the nature of input bytes when creating new VC or VP.
closes #514
> refactor: Automatic detection for decoding of VC and VP

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_jwt.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_jwt.go
- pkg/doc/verifiable/presentation_jwt_proof_test.go
Tests are added to verify the marshaling of VC/VP into JWS using EdDSA (Ed25519 signature algorithm).
closes #712
> test: JWS from VC/VP using EdDSA alg

- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
> refactor: DIDExchange - move connection record related methods out of service context

- pkg/client/didexchange/client.go
- pkg/didcomm/common/service/event.go
- pkg/didcomm/common/service/event_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- test/bdd/agent_sdk_steps.go
- test/bdd/features/didexchange_e2e_sdk.feature
- test/bdd/features/didexchange_public_did.feature
Currently we support "peer" DIDs in exchange request and response. We should also support public dids.
Closes #561
> feat: Add support for public dids in did-exchange protocol

- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/persistence_test.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/storage/mem/mem_store.go
- pkg/storage/mem/mem_store_test.go
- Add transient db search in query connection function
- Implement iterator in mem storage
Closes #722 
> fix: Query connection not returning transient data

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/operation/didexchange/models/invitation.go
- test/bdd/features/didexchange_e2e_controller.feature
- test/bdd/pkg/didexchange/didexchange_controller_steps.go
- test/bdd/webhook/main.go
- Currently action events are triggered before updating the state for the incoming message(invited/requested). Moved action event triggering point after state is updated, ie, invited and requested based on agent role (invitee/inviter).
- Added support to Accept Invitation through RestAPI client. Now, RestAPI triggers accept-invitation when it receives "invited" and accept-request on "requested" state from webhook notification.
Closes #690 
Closes #692 
> feat: DIDExchange RestAPI - Update state name for action callback and Support for Accept Invitation

- pkg/didcomm/packer/jwe/authcrypt/authcrypt.go
- pkg/didcomm/packer/jwe/authcrypt/decrypt_jwk_test.go
- pkg/didcomm/packer/jwe/authcrypt/encrypt_jwk.go
- pkg/didcomm/packer/jwe/authcrypt/encrypt_jwk_test.go
- pkg/didcomm/packer/jwe/authcrypt/pack.go
Rand reader is now a member variable.
Closes #748
> refactor: replace global in JWE Packer (for testing) with member

- pkg/didcomm/packager/package_test.go
- pkg/didcomm/packager/packager.go
- pkg/framework/aries/default.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/provider/mock_provider.go
WithPacker now takes at least 1 Packer(Creator for framework).
The first Packer is used for outbound, all Packers are used for
inbound.
Fixes #764
> refactor: Combine WithPacker and WithInboundPackers

- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/decorator/decorator.go
- pkg/didcomm/protocol/didexchange/models.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/internal/mock/vdr/didcreator/mock_creator.go
- pkg/restapi/operation/didexchange/didexchange_test.go
> feat: Add thread decorator in the exchange request and sign the exchange response with Invitation RecipientKeys

- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- Remove validation to check action event channel registration. The action events are no longer mandatory as clients can wait for message events.
- The consumer can handle events either through action or message event. In case of message event, consumer can call Accept APIs to continue the execution.
Closes #753 
> refactor: DIDExchange Service - Action Event refactor

- docs/rest/agent_docker.md
- docs/test/bdd_tests.md
Fixed bunch of references to what used to be called `agent-rest` (the agent docker image), now called `agent-rest-docker`.
Tested against:
* `make all`
* `make run-openapi-demo`
> fix: references to 'agent-rest' -> 'agent-rest-docker'

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/vdri/peer/creator.go
- test/bdd/pkg/didresolver/didresolver_steps.go
Did doc service definitions should support recipientKeys, routingKeys and priority within service definition.
Closes #818
> feat: Add did-comm service conventions to did doc

- cmd/aries-agent-rest/startcmd/start_test.go
- pkg/restapi/errors/errors.go
- pkg/restapi/errors/errors_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/operation/didexchange/models/invitation.go
- test/bdd/pkg/didexchange/didexchange_controller_steps.go
- different HTTP Status code for error scenarios
- generic error message body
- closes #756
> feat: error handling in controller REST API

- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/internal/mock/vdri/mock_registry.go
We are currently picking first key of type Ed25519VerificationKey2018 from did document public keys for:
-- sender verification key
-- recipient keys in destination
Refactor current logic to read above mentioned keys from recipient keys in did-communication service for both peer and public did documents.
Closes #822
> refactor: Integrate did-communication service conventions

- .gitignore
- Makefile
- pkg/client/introduce/client_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states_test.go
* gomock instead of  custom mock (introduce protocol)
Part of https://github.com/hyperledger/aries-framework-go/issues/269
> refactor: Introduce - replace custom mock with gomock

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_extension_switch_test.go
- pkg/doc/verifiable/credential_extension_test.go
- pkg/doc/verifiable/credential_jws_test.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- pkg/doc/verifiable/credential_jwt_unsecured_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/test-suite/verifiable_suite_test.go
refactor: Selection of Verifiable Credential extensions based on the basic Credential
Simplified `NewCredential()` which decodes a base VC. Extensions can make extra decoding based on the VC and/or decoded JSON bytes returned.
Added `NewExtCredential()` which can be used when there are several VC with extended data model and we can build concrete extended VC depending on the e.g. `type` and `context` of the VC. 
closes #263
> refactor: creation of VC which extends base data model

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/common_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_extension_switch_test.go
- pkg/doc/verifiable/credential_jwt.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/json.go
- pkg/doc/verifiable/json_test.go
Here we add examples of VC encoding. VC base model extension is shown by 2 ways:
- struct embedding
- using `ExtraFields` map
Struct embedding does not work properly for now (#847 is created), so it's recommended to use `ExtraFields` map for extensions.
closes #831
> test: Construct Verifiable Credential object (encoding side)

- pkg/framework/aries/api/vdri/vdri.go
- pkg/framework/aries/framework.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/errors/errors.go
- pkg/restapi/operation/common/models.go
- pkg/restapi/operation/common/operation.go
- pkg/restapi/operation/common/operation_test.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/restapi.go
- pkg/vdri/httpbinding/resolver.go
- pkg/vdri/httpbinding/resolver_test.go
- pkg/vdri/httpbinding/vdri.go
- pkg/vdri/httpbinding/vdri_test.go
- pkg/vdri/peer/creator.go
- pkg/vdri/peer/creator_test.go
- pkg/vdri/peer/vdri.go
- pkg/vdri/registry.go
- pkg/vdri/registry_test.go
- test/bdd/features/didexchange_public_did.feature
- test/bdd/pkg/didresolver/didresolver_steps.go
- add rest endpoint `/vdri/create-public-did` to created public DIDs
using VDRI of agent
- VDRI Build() for httpbinding to create public DIDs using custom request
builders
- `/vdri/create-public-did` to accept optional `request header` parameter to add custom headers to 
request being sent to http binding endpoint.
- closes #845
> feat: Create Public DID (VDRI & REST support)

- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/protocol/decorator/decorator.go
- pkg/didcomm/transport/http/outbound.go
- pkg/didcomm/transport/http/outbound_test.go
- pkg/didcomm/transport/transport_interface.go
- pkg/didcomm/transport/ws/outbound.go
- pkg/didcomm/transport/ws/outbound_test.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/mock_transport.go
- Aries framework level option to set the transport return route value [none, all, thread]; Added the option at framework level(edge agent doesn't have inbound capability) rather than each DIDComm message type.
- Pass the framework option to Outbound Dispatcher
- Outbound dispatcher injects the transport decorator to the outbound message before packing
Part of #858 
> feat: Transport Return Route - Framework Configuration

- Makefile
- pkg/client/introduce/client.go
- pkg/client/introduce/client_test.go
- pkg/didcomm/protocol/introduce/models.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
* added tests for state machine behavior (`SkipProposal`, `Proposal`, `ProposalUnusual`,`SkipProposalWithRequest`,`ProposalWithRequest`,`ProposalUnusualWithRequest`)
* service logic was changed according to the dependency 
* state`s methods were implemented `ExecuteInbound`,`ExecuteOutbound`
Closes #802 https://github.com/hyperledger/aries-framework-go/issues/853
Part of #269
> feat: Introduce - add requesting state to the service

- pkg/didcomm/transport/ws/inbound.go
- pkg/didcomm/transport/ws/outbound_test.go
- pkg/didcomm/transport/ws/upgrade_js_wasm.go
- pkg/didcomm/transport/ws/upgrade_srv.go
The dependent package for WebSocket doesn't support Accept function for JS/WASM build. Split the function call in transport package based on the build target.
Closes #879 
> fix: Linter warning on websocket.Accept for JS/WASM build

- pkg/didcomm/common/service/service.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/http/outbound.go
- pkg/didcomm/transport/transport_interface.go
- pkg/didcomm/transport/ws/inbound.go
- pkg/didcomm/transport/ws/inbound_test.go
- pkg/didcomm/transport/ws/outbound.go
- pkg/didcomm/transport/ws/outbound_test.go
- pkg/didcomm/transport/ws/pool.go
- pkg/didcomm/transport/ws/pool_test.go
- pkg/didcomm/transport/ws/support_test.go
- pkg/framework/aries/example_test.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/mock_transport.go
- Add new function Start() to Outbound Transport : Called by framework by passin the context (similar to Inbound Transport)
- Add new function AriesFrameworkID() to Context : Framework uses this ID to map between inbound and outbound transport for duplex communication
- Update WebSocket transport implementation to support Duplex communication based on Transport Return Route config
closes #877  
> feat: WebSocket - Support Duplex communication based on Transport Return Route Feature

- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/packager/package_test.go
- pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go
- pkg/didcomm/transport/http/outbound.go
- pkg/didcomm/transport/transport_interface.go
- pkg/didcomm/transport/ws/outbound.go
- pkg/didcomm/transport/ws/outbound_test.go
- pkg/didcomm/transport/ws/pool.go
- pkg/didcomm/transport/ws/upgrade_js_wasm.go
- pkg/didcomm/transport/ws/upgrade_srv.go
- pkg/framework/aries/default.go
- pkg/framework/aries/default_test.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/internal/mock/didcomm/mock_transport.go
- pkg/internal/mock/kms/mock_kms_provider.go
- pkg/kms/crypto_box_test.go
- test/bdd/agent_sdk_steps.go
- test/bdd/features/aries_e2e_route_option.feature
- Remove default inbound transport creation in the framework
- New AcceptRecipient function in OutboundTransport : The framework first checks if connection exists for the recKey and use that connection regardless of the url to support edge agents
- Removed unused InboundTransportEndpoint dependencies in kms services
closes #915 
> refactor: Inbound transport optional

- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
Added the possibility to stop the protocol (introducer side). It covers the following usage:
* stop the protocol after receiving the Response message (first response)
* stop the protocol after receiving the Request message
Closes #922 
> feat: Introduce - implement behavior when introducer stops the protocol

- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
Added the possibility to stop the protocol (introducer side). It covers the following usage:
* stop the protocol after receiving the Response message (second response)
Closes #935 
> feat: Introduce - stops the protocol after receiving the second Response

- Makefile
- pkg/client/introduce/client_test.go
- pkg/didcomm/protocol/didexchange/models.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
* listening `digexchange` events
* forward an invitation is done by using OutboundDispatcher().Send
Closes #954 
> feat: Introduce - forward an invitation & notify the introduce

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/client/introduce/client.go
- pkg/client/introduce/client_test.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/dispatcher/api.go
- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
- pkg/didcomm/protocol/route/support_test.go
- pkg/framework/context/context.go
- pkg/internal/mock/didcomm/dispatcher/mock_outbound.go
- pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
* messages are sent by using `SendToDID(msg interface{}, myDID, theirDID string) error` function
* Handler interface was changed to: 
```
type Handler interface {
HandleInbound(msg *DIDCommMsg, myDID string, theirDID string) (string, error)
HandleOutbound(msg *DIDCommMsg, myDID, theirDID string) error
}
```
Closes #963  
> refactor: Introduce - send message logic

- pkg/didcomm/dispatcher/api.go
- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/protocol/route/models.go
- pkg/didcomm/protocol/route/service.go
- pkg/didcomm/protocol/route/service_test.go
- pkg/didcomm/protocol/route/support_test.go
- pkg/internal/mock/didcomm/dispatcher/mock_outbound.go
- Base structure for [Forward Message type](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0094-cross-domain-messaging/README.md#corerouting10forward)
closes #957 
> feat: Forward Message - Base structure implementation

- pkg/client/introduce/client.go
- pkg/client/introduce/client_test.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/introduce/models.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
- pkg/framework/aries/default.go
- pkg/framework/aries/framework.go
- pkg/internal/mock/vdri/mock_registry.go
* added the Introduce service to the framework
* parent threadID was missing in the `Copy` function
* removed useless logging
> refactor: Introduce - fixed issues in the client, framework, and service

- test/bdd/agent/agent_controller_steps.go
- test/bdd/agent/agent_sdk_steps.go
- test/bdd/bddtests_test.go
- test/bdd/features/introduce.feature
- test/bdd/pkg/didexchange/didexchange_sdk_steps.go
- test/bdd/pkg/didresolver/didresolver_steps.go
- test/bdd/pkg/introduce/introduce_sdk_steps.go
Added BDD tests for the introduce protocol. Almost each BDD test represents unit test e.g `@skip_proposal` is equal to `SkipProposal` in a unit test.
* skip_proposal
* skip_proposal_with_request
* skip_proposal_stop
* skip_proposal_stop_with_request
* skip_proposal_introducer_stop
* skip_proposal_introducer_stop_with_request
* proposal
* proposal_with_request
* proposal_unusual
* proposal_unusual_with_request
* proposal_no_invitation
* proposal_no_invitation_with_request
* proposal_stop
* proposal_stop_with_request
* proposal_stop_unusual
* proposal_stop_unusual_with_request
* proposal_introducer_stop
* proposal_introducer_stop_with_request
* proposal_introducer_second_stop
* proposal_introducer_second_stop_with_request
Closes https://github.com/hyperledger/aries-framework-go/issues/979 …
> test: Introduce - add BDD tests

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/client/didexchange/models.go
- pkg/common/connectionstore/connection_record.go
- pkg/common/connectionstore/connection_record_test.go
- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/persistence_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/internal/mock/didcomm/protocol/mock_protocol.go
- pkg/internal/mock/storage/mock_store.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- moved connection lookup logic out of DID exchange service to common package, so that it can be reused by client packages to lookup connection records.
- closes #1015
TODO: 
- save/updates logic to be moved as part of https://github.com/hyperledger/aries-framework-go/issues/1021
- connection and DID store to be merged as part of https://github.com/hyperledger/aries-framework-go/issues/1021
> feat: connection lookup logic moved out of didexhange service

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/common/connectionstore/connection_lookup.go
- pkg/common/connectionstore/connection_lookup_test.go
- pkg/common/connectionstore/connection_recorder.go
- pkg/common/connectionstore/connection_recorder_test.go
- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/persistence_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/framework/aries/framework_test.go
- pkg/internal/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/internal/mock/storage/mock_store.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- Connection Recorder, read-write connection store is moved out of
did-exchange service package.
- ConnectionRecorder extends ConnectionLookup, it adds write feature on
top of read-only ConnectionLook features.
- closes #1021
> feat: connection recorder out of did exchange service

- pkg/didcomm/common/service/service.go
- pkg/didcomm/common/service/service_test.go
- pkg/didcomm/dispatcher/api.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/protocol/generic/mock_generic_svc.go
- generic message handler when no registered service handles
given message type
- current Accept logic is based on message header.
- closes #1032
> feat: generic inbound handler

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_jws_test.go
- pkg/doc/verifiable/credential_jwt.go
- pkg/doc/verifiable/credential_jwt_unsecured_test.go
- pkg/doc/verifiable/credential_test.go
closes #1041
Additionally, support the case when `RefreshService` is defined as an array.
> refactor: null values in optional fields of Verifiable Credential

- cmd/aries-agent-rest/startcmd/start.go
- pkg/didcomm/dispatcher/api.go
- pkg/didcomm/msghandler/msghandler.go
- pkg/didcomm/msghandler/msghandler_test.go
- pkg/framework/aries/api/protocol.go
- pkg/framework/aries/default.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/msghandler/mock_msg_handler.go
- pkg/internal/mock/didcomm/protocol/generic/mock_generic_svc.go
- pkg/restapi/restapi.go
- pkg/restapi/restapi_test.go
- Added MessageHandler which is dynamic registrar for message service
registration
- MessageHandler option for Aries framework instantiation and REST API
instantiation.
- Context InboundHandler will dispatch handling to message services
registered to message handler if no matching protocol service found for
given message type
- closes #970
> feat: message handler for message service registration

- cmd/aries-agent-rest/startcmd/start.go
- pkg/didcomm/msghandler/msghandler.go
- pkg/internal/mock/didcomm/msghandler/mock_msg_handler.go
- pkg/restapi/internal/mocks/webhook/mock_webhook.go
- pkg/restapi/operation/common/models.go
- pkg/restapi/operation/common/msgservice.go
- pkg/restapi/operation/common/msgservice_test.go
- pkg/restapi/operation/common/operation.go
- pkg/restapi/operation/common/operation_test.go
- pkg/restapi/operation/didexchange/didexchange_test.go
- pkg/restapi/operation/handler.go
- pkg/restapi/restapi.go
- added below endpoints for message service register, unregister and
registered service list
`POST /message/register-service`
`POST /message/unregister-service`
`GET /message/services`
- closes #973
> feat: REST binding for message service registration and handling

- .gitignore
- Makefile
- cmd/aries-js-worker/aries-worker.js
- cmd/aries-js-worker/aries.js
- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/main.go
- cmd/aries-js-worker/main_test.go
- scripts/check_license.sh
- scripts/check_unit.sh
- scripts/check_unit_wasm.sh
Part of #1064 
* WASM callable with 'handleMsg'
* WASM posts results to 'handleResult'
* aries-worker.js: simple Web Worker wrapper around WASM
* aries.js: exposes user-facing APIs
* excluded `/gomocks` from the license check. Gomocks are auto-generated and are now being committed to the repo with the merge of #1068
The overall design is similar to that of the service events pattern: user-facing APIs submit a msg with an ID to the WASM and listen for a result referencing that same ID.
> feat: initial scaffolding for JS web worker

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/client/introduce/client.go
- pkg/client/introduce/client_test.go
- pkg/didcomm/common/service/did_comm_msg.go
- pkg/didcomm/common/service/did_comm_msg_test.go
- pkg/didcomm/common/service/service_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states_test.go
- pkg/didcomm/protocol/route/service_test.go
- pkg/framework/context/context.go
- pkg/restapi/operation/common/msgservice.go
- pkg/restapi/operation/didexchange/didexchange_test.go
The function was renamed according to the returned value.
> refactor: Rename NewDIDCommMsg function to NewDIDCommMsgMap

- .golangci.yml
- cmd/aries-js-worker/main.go
- cmd/aries-js-worker/main_test.go
- pkg/didcomm/transport/ws/support_test.go
- pkg/doc/verifiable/credential.go
- pkg/framework/aries/defaults/defaults.go
- pkg/framework/aries/defaults/defaults_js_wasm.go
- pkg/framework/aries/framework.go
- pkg/framework/context/context.go
- pkg/restapi/webhook/webhook_test.go
- scripts/check_lint.sh
- test/bdd/bddtests_test.go
- update golangci-lint to v1.23.1
- fix lint warnings
- fix build constraints on WASM js worker
- todo: fix lint warnings for new linters (currently disabled).
> ci: update golangci-lint

- pkg/doc/signature/proof/utils.go
- pkg/doc/signature/proof/utils_test.go
- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/common_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_extension_test.go
- pkg/doc/verifiable/credential_jwt.go
- pkg/doc/verifiable/credential_ldp.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/embedded_proof.go
- pkg/doc/verifiable/embedded_proof_test.go
- pkg/doc/verifiable/example_presentation_test.go
- pkg/doc/verifiable/jsonld.go
- pkg/doc/verifiable/linked_data_proof.go
- pkg/doc/verifiable/linked_data_proof_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_jws_test.go
- pkg/doc/verifiable/presentation_jwt.go
- pkg/doc/verifiable/presentation_jwt_proof_test.go
- pkg/doc/verifiable/presentation_jwt_test.go
- pkg/doc/verifiable/presentation_jwt_unsecured_test.go
- pkg/doc/verifiable/presentation_ldp.go
- pkg/doc/verifiable/presentation_ldp_test.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/support_test.go
- pkg/doc/verifiable/test-suite/verifiable_suite_test.go
- pkg/store/verifiable/store_test.go
- scripts/run_vc_test_suite.sh
closes #174
Support of Linked Data proofs with `Ed25519Signature2018 ` type and proof value inside `proofValue` element of the `proof`.
The follow-up PR to support JWS-based proof values is #1093 .
> feat: Linked Data proof of Verifiable Credential

- .golangci.yml
- cmd/aries-agent-rest/startcmd/start.go
- cmd/aries-js-worker/main.go
- pkg/didcomm/packer/jwe/authcrypt/decrypt_jwk.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/route/service.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/jwt_unsecured.go
- pkg/internal/common/logging/modlog/deflog.go
- pkg/internal/cryptoutil/legacy_utils.go
- pkg/internal/cryptoutil/utils.go
- pkg/storage/jsindexeddb/jsindexeddb.go
- pkg/vdri/registry.go
- test/bdd/agent/agent_sdk_steps.go
- test/bdd/dockerutil/compose.go
- test/bdd/pkg/didexchange/didexchange_controller_steps.go
- test/bdd/pkg/didexchange/didexchange_sdk_steps.go
- test/bdd/pkg/introduce/introduce_sdk_steps.go
- test/bdd/pkg/messaging/msgservice.go
- test/bdd/webhook/main.go
- Enables gomnd linter rules outside test files.
- Linter will catch magic numbers other than 0 and 1.
> ci: enable gomnd (magic number linting)

- pkg/didcomm/messaging/service/http/httpmsgsvc.go
- pkg/didcomm/messaging/service/http/httpmsgsvc_test.go
- pkg/didcomm/messaging/service/http/models.go
- `http.OverDIDComm` to convert incoming did comm messages matching
purposes to http request and calling http request handles.
- Implemented RFC-0335 DIDComm msg to request flow
- closes #1106
> feat: http over didcomm - DIDComm msg to http request

- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
Renamed error messages for the introduce protocol.
> refactor: Introduce - rename error messages

- pkg/client/introduce/example_test.go
- pkg/didcomm/messenger/messenger.go
- pkg/didcomm/messenger/messenger_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
- pkg/framework/aries/framework.go
- pkg/internal/gomocks/didcomm/messenger/mocks.go
Following functions were implemented:
* Send
* ReplyTo
* ReplyToNested
NOTE: This implementation allows us to use messenger. The next changes related to the messenger would be done under the hood and should not affect usage.
> feat: Messenger - implement ReplyTo and Send functions

- pkg/internal/mock/secretlock/mock_secretlock.go
- pkg/secretlock/api.go
- pkg/secretlock/secretlock.go
This API's main purpose is to encrypt (wrap) and decrypt (unwrap) keys written to/from the KMS
> Secretlock API + mock

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/protocol/route/service_test.go
- pkg/framework/aries/api/protocol.go
- pkg/framework/aries/example_test.go
- pkg/framework/aries/framework.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/provider/mock_provider.go
- pkg/restapi/operation/didexchange/didexchange.go
- pkg/restapi/operation/didexchange/didexchange_test.go
Support for multiple inbound transports was added as part of #1162. A new context method was added to provide Router Service endpoint.  This change updates the context method name which provides the service end point to be in sync with Router service endpoint.
> refactor: Update context.InboundTransportEndpoint to context.ServiceEndpoint

- pkg/controller/command/didexchange/command.go
- pkg/controller/command/didexchange/command_test.go
- pkg/controller/command/didexchange/models.go
- pkg/didcomm/protocol/didexchange/states_test.go
- added DIDExchange controller command
- part of #1176
TODO:
- migrate DID Exchange REST operation to use controller command
- move `pkg/restapi` to `controller/restapi`
> feat: did-exchange controller commands

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/signature/ed25519signature2018/suite.go
- pkg/doc/signature/ed25519signature2018/suite_test.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/signature/signer/signer_test.go
- pkg/doc/signature/verifier/verifier.go
- pkg/doc/signature/verifier/verifier_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/embedded_proof.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/linked_data_proof.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_ldp_test.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/support_test.go
- pkg/kms/legacykms/kms.go
- test/bdd/go.mod
#339
There will be additional PR to refactor the usage of private keys to build JWS from verifiable credential / presentation.
> refactor: do not pass private key to Sign() in linked data proofs

- cmd/aries-agent-rest/startcmd/start.go
By default, CORS is enabled for HTTP HEAD, GET and POST Methods - https://github.com/rs/cors/blob/fdcf4f9773b8d459d3ec085a8c91b34fcd17803d/cors.go#L48-L50
> fix: Added HTTP Delete method to the CORS whitelist

- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
> fix: Ignore Transport Return Route decorator for forward message

- pkg/didcomm/transport/ws/inbound.go
- pkg/didcomm/transport/ws/outbound.go
- pkg/didcomm/transport/ws/pool.go
- pkg/didcomm/transport/ws/upgrade_js_wasm.go
- pkg/didcomm/transport/ws/upgrade_srv.go
The web server, load balancer, network routers between the client and server closes the TCP keepalives connection. Added a new function to invoke Ping requests frequently to keep the connection alive
closes #1214 
> fix: Invoke websocket.Ping() function to keep the connection alive

- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/main.go
- cmd/aries-js-worker/src/aries.js
- cmd/aries-js-worker/src/worker-loader-node.js
- cmd/aries-js-worker/src/worker-loader-web.js
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- Aries.Start(opts) can be used to start aries in JS worker
sample :
`{"agent-default-label":"dem-js-agent","http-resolver-url":"","auto-accept":true,"outbound-transport":["ws","http"],"transport-return-route":"all","notifier-func-name":"sample-topic"}`
- Aries.Stop() can be used to stop aries
- Command controller can only be called between start and stop
- Register notifier using `Aries.waitForNotification("<topic-name>")`, make sure you use same `notifier-func-name` in aries opts.
> feat : Aries JS Worker Start/Stop and Notifier

- pkg/framework/aries/api/protocol.go
- pkg/framework/aries/default.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/secretlock/mock_secretlock.go
- pkg/secretlock/api.go
- pkg/secretlock/local/internal/cipher/util.go
- pkg/secretlock/local/internal/cipher/util_test.go
- pkg/secretlock/local/local_secret_lock.go
- pkg/secretlock/local/local_secret_lock_test.go
- pkg/secretlock/local/local_secret_masterkey_reader.go
- pkg/secretlock/local/masterlock/hkdf/master_secret_lock.go
- pkg/secretlock/local/masterlock/hkdf/master_secret_lock_test.go
This change includes reading a masterkey
from 2 sources:
1. masterKey loaded from env variable
2. masterKey loaded from local path
This change also includes password protection lock to encrypt
the master key for additional protection of keys.
closes #1146
> feat: Add (local) SecretLock implementation

- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/framework/aries/example_test.go
- pkg/internal/gomocks/storage/mocks.go
- pkg/mock/storage/mock_store.go
- pkg/storage/jsindexeddb/jsindexeddb.go
- pkg/storage/jsindexeddb/jsindexeddb_test.go
- pkg/storage/leveldb/leveldb_store.go
- pkg/storage/leveldb/leveldb_store_test.go
- pkg/storage/mem/mem_store.go
- pkg/storage/mem/mem_store_test.go
- pkg/storage/store.go
In order to support rotating keys from the storage (or deleting data in general),
there should be a storage service with Delete() function available
closes #1147
> feat: Create a new Storage type with Delete() function

- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/main.go
- cmd/aries-js-worker/src/aries.js
- cmd/aries-js-worker/src/worker-loader-node.js
- cmd/aries-js-worker/src/worker-loader-web.js
- use `aries.waitForNotification()` to subscribe for all the topics
- use `aries.waitForNotification(topics)` to subscribe by topics.
- removed "notifier-func-name" from aries start opts.
- closes #1259
> fix: aries-js-worker notifier to follow REST notifier behavior

- pkg/kms/localkms/localkms_reader.go
- pkg/kms/localkms/localkms_reader_test.go
- pkg/kms/localkms/localkms_writer.go
- pkg/kms/localkms/localkms_writer_test.go
To prepare for the default local KMS implementation, a store
Reader and Writer need to be created to help persisting KMS
key sets in a local storage.
This is pre step for the next patch that includes the full
local KMS implementation.
part of #1149
> feat: store Reader/Writer for default local KMS implementation

- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/src/aries.js
- `aries.startNotifier()` to return stop handle which can be used to
stop current notifier started.
- part of #1262
> feat:stop notifier feature in aries-js-worker

- pkg/controller/rest/rest.go
- pkg/controller/rest/route/operation.go
- added `application/json` mimetype for REST controller response
- closes #1272
> feat: mimetype for REST controller response

- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/main.go
- cmd/aries-js-worker/src/aries.js
- pkg/controller/controller.go
- removed aries startup from start() to constructor
- aries stop() replaced by destroy function
- each instance will have localized worker, message and notification map
- fixed ununsed startup opts
TODO - wait for aries startup before returning or using
event/callback/flag to indicate if aries started successfully.
> feat: aries js worker start from constructor

- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/main.go
- cmd/aries-js-worker/package.json
- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/aries.js
- cmd/aries-js-worker/src/worker-impl-rest.js
- cmd/aries-js-worker/src/worker-loader-rest.js
- cmd/aries-js-worker/webpack.config.rest.js
- Switching JS source from `../dist/web` to `../dist/rest` will make
aries js worker to run in rest agent client mode.
- Web worker will be using agent rest client endpoints instead of
aries wasm command handlers.
- Except worker javascript, all the other functionalities and interfaces
will remain same.
- added switch (to REST/WASM worker) feature in presentation html for
demonstration/testing.
//TODO :Currently incoming topics/messages should be looked up in
webhook URL of corresponding REST agent, javascript notifier listening
to webhook URL will be added in future.
> feat: rest client worker for aries JS

- pkg/didcomm/protocol/decorator/decorator.go
- pkg/didcomm/protocol/issuecredential/models.go
The following models were defined for the Issue Credential Protocol:
* ProposeCredential
* OfferCredential
* RequestCredential
* IssueCredential
Closes #1296 
> feat: Issue Credential - define models for the protocol

- README.md
See https://blog.golang.org/pkg.go.dev-2020
> chore: Changed godoc URL

- pkg/doc/verifiable/linked_data_proof.go
Currently there's no way to determine who created proof for JSON LD signature since creator field has been removed. Restoring Creator field back.
Closes #1338
> fix: Revert Creator for JSONLD signature

- pkg/doc/jose/common.go
- pkg/doc/jose/jws.go
- pkg/doc/jose/jws_test.go
- pkg/doc/jwt/jwt.go
- pkg/doc/jwt/jwt_test.go
- pkg/doc/jwt/support_test.go
- pkg/doc/jwt/verifier.go
- pkg/doc/jwt/verifier_test.go
closes #1264
This package will be initially used by `verifiable` and `signature` packages.
I already have adopted `verifiable` but do not want to include it to this PR in order to keep the PR as small as possible.
> feat: JWT library with flexible signers

- pkg/didcomm/messenger/messenger.go
- pkg/kms/legacykms/kms.go
- pkg/storage/jsindexeddb/jsindexeddb.go
- pkg/storage/jsindexeddb/jsindexeddb_test.go
- pkg/store/connection/connection_lookup.go
- pkg/store/connection/connection_lookup_test.go
- pkg/store/did/didconnection.go
- due to complications in dynamically adding objectstores under already
opened indexdb database, jsindexdb provider will have predefined list of
objectstores. `onupgradeevent` during very first creation of database
will create those object stores in advance.
- attempt to create store not defined in object store will not return
any error, instead it will create new database for that object store.
- closes #1309
> fix: multiple objectstores under same indexdb database

- cmd/aries-agent-rest/startcmd/start.go
- cmd/aries-agent-rest/startcmd/start_test.go
- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/worker-impl-rest.js
- enable REST server to support authorization token validation
- add token support to JS client
Closes: #1203, #1324
> feat: bearer authorization token support

- cmd/aries-js-worker/README.md
- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/src/aries.js
- cmd/aries-js-worker/src/worker-impl-rest.js
- new constructor opts `agent-rest-wshook` in rest client based aries js
worker. If provided then `aries.startNotifier` can be used to listen to
incoming messages
- closes #1370
> feat: notifiers support in  aries rest client js worker

- cmd/aries-js-worker/README.md
- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/main.go
- pkg/framework/aries/default_js_wasm.go
- pkg/framework/aries/defaults/defaults_js_wasm.go
- pkg/storage/jsindexeddb/jsindexeddb.go
- pkg/storage/jsindexeddb/jsindexeddb_test.go
- added dbpath option in aries start opts to avoid collision between
multiple aries instance in same browser(context).
- closes #1388
> feat: 'db-path' start option for aries js worker WASM

- cmd/aries-js-worker/README.md
- cmd/aries-js-worker/index.html
- cmd/aries-js-worker/main.go
- pkg/framework/aries/default_js_wasm.go
- pkg/storage/jsindexeddb/jsindexeddb.go
- pkg/store/verifiable/store.go
- added db namespace option in aries start opts to avoid collision between
multiple aries instance in same browser(context).
- closes #1388
> feat: 'db-namespace' start option for aries js worker WASM

- cmd/aries-js-worker/src/worker-impl-rest.js
- pkg/controller/webnotifier/webhook.go
- pkg/controller/webnotifier/webhook_test.go
- pkg/controller/webnotifier/webnotifier.go
- pkg/controller/webnotifier/websocket.go
- pkg/controller/webnotifier/websocket_test.go
- test/bdd/pkg/didexchange/didexchange_controller_steps.go
- test/bdd/pkg/messaging/messaging_controller_steps.go
- test/bdd/webhook/main.go
- in previous version, web notifier topics are used for resolving/building
URLs which was forcing subscribers to support path matching topic names
(challenge: topic name are private and dynamic based on usecases)
- changes: web notifiers will send message containing uniquer ID, Topic
Name and Raw JSON message to given webnotfier endpoint.
- This fixed issue in JS worker where it wasn't able to find topic of
incoming messages.
- closes #1323
> feat: webnotfiers to send topic information

- pkg/client/introduce/example_test.go
Function names now follow Godoc naming convention.
> chore: Introduce - example function names were changed

- test/bdd/agent/agent_controller_steps.go
- test/bdd/bddtests_test.go
- test/bdd/features/aries_e2e_route_option.feature
- test/bdd/features/aries_router_e2e_controller.feature
- test/bdd/features/didexchange_e2e_controller.feature
- test/bdd/features/didexchange_public_did.feature
- test/bdd/features/messaging_e2e_controller.feature
- test/bdd/pkg/context/context.go
- test/bdd/pkg/didexchange/didexchange_controller_steps.go
- test/bdd/pkg/messaging/messaging_controller_steps.go
- test/bdd/webhook/main.go
- migrated all controller tests to websocket notification to pull
events. This change is going to  improve test performance.
- one of the scenario in  generic messaging test will still use webhook URL to
keep webhook URL notification mechanism covered.
- closes #1402
> feat:  bddtests to use websocket notifiers

- pkg/didcomm/protocol/issuecredential/service.go
- pkg/didcomm/protocol/issuecredential/service_test.go
- pkg/didcomm/protocol/issuecredential/states.go
- pkg/didcomm/protocol/issuecredential/states_test.go
The following functions were added:
* `ActionContinue` allows to proceed working with the protocol
* `ActionStop` allows to stop the protocol
* `Actions` returns all available actions
Part of #1173 
> feat: Issue Credential - functions were exposed for the async usage

- cmd/aries-js-worker/src/agent-rest-client.js
- test/aries-js-worker/fixtures/.env
- test/aries-js-worker/fixtures/docker-compose.yml
- test/aries-js-worker/test/common.js
- test/aries-js-worker/test/vdri/vdri.js
- added `aries.createPublicDID` tests in both JS & WASM mode
- closes #1425
> feat: js bddtests for vdri

- pkg/controller/command/verifiable/command.go
- pkg/controller/rest/verifiable/operation_test.go
While saving, the system should just do basic valition without checking for signing to avoid passing signing details. The signing will be validated during presentation generation.
> refactor: Save VC - Skip signing validation

- pkg/client/introduce/client.go
- pkg/client/introduce/client_test.go
- pkg/didcomm/common/service/service.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/route/service.go
- pkg/didcomm/protocol/route/service_test.go
- pkg/internal/gomocks/client/introduce/mocks.go
- pkg/internal/gomocks/didcomm/common/service/mocks.go
- pkg/internal/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/internal/mock/didcomm/protocol/route/mock_route.go
`HandleOutbound` function returns useless value. This PR fixes it.
> refactor: Removes redundant return value (HandleOutbound)

- pkg/didcomm/protocol/issuecredential/service.go
- pkg/didcomm/protocol/issuecredential/service_test.go
- pkg/didcomm/protocol/issuecredential/states.go
- pkg/didcomm/protocol/issuecredential/states_test.go
* `requests attach` is populated from the inbound `OfferCredential` message
* `credentials attach` is populated from the inbound `RequestCredential` message
Part of #1173 
> feat: Issue Credential - adds an attachment to the message

- pkg/didcomm/protocol/issuecredential/service.go
- pkg/didcomm/protocol/issuecredential/service_test.go
When the Holder sends a request message the Issuer may respond with an IssueCredential message. We need a possibility to reject this IssueCredential message (on the Holder side).
Part of #1173 
> feat: Issue Credential - triggers an event after receiving IssueCredential

- pkg/doc/did/doc.go
> Fix: use v1 when context is empty

- pkg/client/issuecredential/client.go
- pkg/client/issuecredential/client_test.go
Implements  Issue Credential Client. Includes all possible methods.
Closes #1438 
> feat: Issue Credential - client implementation (part 2)

- pkg/didcomm/protocol/didexchange/service.go
Signed-off-by: pfeairheller <phil@scoir.com>
**Title:**
Fix a minor bug in didexchange service to allow for proper logging when connection is abandoned.
Closes: #1451 
Summary:
Updating the call to `createErrorEventProperties` to pass in the connectionID instead of the threadID.
> fix: use connectionID instead of threadID

- pkg/client/issuecredential/client.go
- pkg/didcomm/protocol/issuecredential/service.go
- pkg/didcomm/protocol/issuecredential/service_test.go
- pkg/didcomm/protocol/issuecredential/states.go
- pkg/didcomm/protocol/issuecredential/states_test.go
When the Holder receives a credential, the protocol saves it to the verifiable store.
Part of #1173 
> feat: Issue Credential - saves credential to the verifiable store

- pkg/client/outofband/client.go
- pkg/client/outofband/client_test.go
- pkg/client/outofband/models.go
- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
closes #1456
* client package for the [Out-Of-Band protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md) 
* `did.Parse(string)` helper function (see #20)
TODO: add support for the creation of Out-Of-Band [`invitation`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md#message-type-httpsdidcommorgoob-invitationverinvitation)
> feat: client pkg for out-of-band protocol

- pkg/didcomm/common/service/did_comm_msg.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states_test.go
* removed `Header` structure
Closes https://github.com/hyperledger/aries-framework-go/issues/1075
> refactor: Removes deprecated Header structure

- pkg/didcomm/protocol/presentproof/models.go
- pkg/didcomm/protocol/presentproof/service.go
The following models were added:
* ProposePresentation
* RequestPresentation
* Presentation
Closes #1482 
> feat: Present Proof - defines models for the protocol

- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
The following states were defined:
* request-sent (Verifier)
* presentation-received (Verifier)
* propose-presentation-received (Verifier)
* request-received (Prover)
* presentation-sent (Prover)
* propose-presentation-sent (Prover)
Closes #1486 
> feat: Present Proof - defines states for the protocol

- pkg/client/outofband/client.go
- pkg/client/outofband/models.go
- pkg/didcomm/protocol/outofband/models.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/internal/mock/didcomm/protocol/mock_protocol.go
closes #1478 
Skeleton for the Out-Of-Band protocol service.
* A single out-of-band `request` contains one or more (didcomm?) messages embedded in attachments
* the service needs to first run didexchange (which *may* reuse an existing connection)
* the service then needs to dispatch the embedded requests (assuming didcomm for now...) to their respective handlers
> feat: out-of-band protocol service skeleton

- pkg/kms/localkms/localkms.go
- pkg/kms/localkms/pubkey_export_import_test.go
- pkg/kms/localkms/pubkey_reader.go
Since default signing key templates have Tink specific prefix,
need to use RAW type to avoid adding a prefix. This will fix
verification with a keyset.Handle created from raw public key []byte
To unblock dev, the temporary fix is to manually change the key templates
in aries-framework-go code. A followup issue is created to use Tink
created key templates without a prefix when the templates are
available in Tink (#1489).
closes #1483
> fix: loading raw pub key to Tink keyset.Handle fails verification

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- Fixing interoperability issue where DIDs use string context value
instead of array. According to did spec we should support both.
- closes #1498
> feat: did schema - support multiple types for @context

- cmd/aries-agent-rest/startcmd/start.go
Fixed a potentially confusing typo in a function parameter name.
> refactor: Fix typo in function parameter name

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/controller/command/didexchange/command_test.go
- pkg/controller/rest/didexchange/operation_test.go
- pkg/store/connection/connection_recorder.go
- pkg/store/connection/connection_recorder_test.go
**Title:**
Implementation of removing the connection records from the stores
Closes #553 
Removes connection and it's mapping records across store and transient store.
Remove connection sequence in _pkg/store/connection/connection_recorder.go_ mirrors the save connection one. It removes all records for any state of the connection from the transient store, as well as did mappings records and namespace, threadID and connectionID mappings if there are some.
> feat: Support for RemoveConnection in DIDExchange clients

- pkg/didcomm/protocol/presentproof/service.go
- pkg/didcomm/protocol/presentproof/service_test.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
The following states were renamed:
* proposal-sent
* proposal-received
> refactor: Present Proof - states name were changed according to the RFC 0037

- cmd/aries-agent-rest/go.sum
- go.mod
- go.sum
- pkg/internal/cryptoutil/utils.go
- test/bdd/go.sum
Updated extra25519 package to a current `live` library.
closes #1514
> chore: update extra25519 key conversion library

- pkg/doc/did/doc.go
- pkg/doc/signature/ed25519signature2018/suite.go
- pkg/doc/signature/ed25519signature2018/suite_test.go
- pkg/doc/signature/proof/data.go
- pkg/doc/signature/proof/data_test.go
- pkg/doc/signature/proof/jws.go
- pkg/doc/signature/proof/jws_test.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/signature/verifier/verifier.go
- pkg/doc/signature/verifier/verifier_test.go
- pkg/doc/verifiable/embedded_proof.go
- pkg/doc/verifiable/embedded_proof_test.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/linked_data_proof.go
- pkg/doc/verifiable/linked_data_proof_test.go
- pkg/doc/verifiable/support_test.go
closes #1517
compactProof option is supported by Digitalbazaar library: https://github.com/digitalbazaar/jsonld-signatures/blob/531058bf1af7101bd261f540e4b875f3e5101076/lib/ProofSet.js#L90
This option will be used to solve https://github.com/hyperledger/aries-framework-go/issues/1415
> feat: Support compact proof option in signature suites

- pkg/didcomm/protocol/presentproof/service.go
- pkg/didcomm/protocol/presentproof/service_test.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
The following states were implemented:
* abandoning (inbound)
* request-received  (inbound)
* request-sent (outbound)
* presentation-sent  (inbound)
* proposal-sent (inbound)
Closes #1505 
> feat: Present Proof - state implementation for request sent/received

- pkg/didcomm/protocol/didexchange/models.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/internal/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/store/connection/connection_lookup.go
closes #1501
* defines a new type to start the did-exchange protocol with (suggestions on the name are welcome)
* out-of-band service refactored to use this new type
The did-exchange protocol service still accepts didexchange.Invitations - that would be removed in a followup PR.
> feat: refactor didexchange service to accept out-of-band invitation

- pkg/doc/verifiable/credential.go
- The Evidence type is of interface{}. The field in VC is set as pointer to Evidence type. ie, pointer to interface{}. Removed the pointer.
> fix: VC Evidence field type update

- pkg/didcomm/protocol/presentproof/service.go
- pkg/didcomm/protocol/presentproof/service_test.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
The following states were implemented:
* request-sent  (inbound )
* presentation-received  (inbound)
* proposal-sent (outbound)
* proposal-received (inbound )
Closes #1511 
> feat: Present Proof - state implementation for presentation/proposal-received

- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier.go
- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go
- pkg/doc/verifiable/credential_ldp_test.go
closes #1532
I added a piece of ECDSA P256 verification as it's not working using tink crypto.
See TODO at `TestNewCredentialFromLinkedDataProof_JsonWebSignature2020_ecdsaP256`  test.
Added a follow-up issue https://github.com/hyperledger/aries-framework-go/issues/1534.
> test: Add ECDSA P256 test of JsonWebSignature2020 suite

- pkg/client/didexchange/client_test.go
- pkg/client/didexchange/example_test.go
- pkg/client/outofband/client.go
- pkg/client/outofband/client_test.go
- pkg/client/route/example_test.go
- pkg/controller/command/didexchange/command_test.go
- pkg/didcomm/protocol/didexchange/models.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/framework/aries/api/protocol.go
- pkg/framework/aries/default.go
- pkg/internal/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/store/connection/connection_lookup.go
Working on the BDD tests for outofband+didexchange made me realize some mistaken assumptions I had about how the didexchange state machine works, and also that there were missing pieces to implement.
This PR will:
* Add `outofband.Client.AcceptRequest()` to receive `request`s received via out-of-band channels. It returns the new connection record's ID (similar to `didexchange.Client.HandleInvitation()`)
* Add `outofband.Service.AcceptRequest()` to accept another agent's request. This method returns the new connection record's ID.
* Add `outofband.Service.SaveRequest()` to save a request created by yourself
* Add `didexchange.Service.Save()` to save OOBInvitations created by yourself
* Hook `outofband.Service` into the framwork context's defaults …
> fix: outofband + didexchange

- pkg/doc/signature/proof/jws.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/example_credential_test.go
According to Linked Data Signatures specification for JSON-LD
("https://github.com/digitalbazaar/jsonld-signatures") proof value type
shouldn't be exluded while calculating checksum of proof value.
This problem was found while running signature verification tests with
signatures created by other systems using 'Ed25519Signature2018'.
- above specification may not apply for 'JsonWebSignature2020'.
Created issue #1548 to address this issue.
- closes #1549 
> feat: JWS signing/verification - include proof.Type in verification data

- cmd/aries-agent-rest/go.sum
- go.mod
- pkg/doc/did/doc.go
- pkg/doc/jose/jwk.go
- pkg/doc/jose/jwk_test.go
- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier.go
- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go
- pkg/doc/signature/verifier/verifier.go
- pkg/doc/verifiable/credential_ldp_test.go
- test/bdd/go.sum
For linked data signatures with `JwsVerificationKey2020` type, it's not enough information to make signature verification based on the public key bytes and a type (JwsVerificationKey2020). We need to know additionally what signature algorithm (and/or curve) was used - e.g. `ES256` or `EdDSA`.
In the case of DID documents, we can read this information from the public key if it's defined as `publicKeyJwk`.
As a result, we extend `PublicKey` struct with `Curve`, `Alg` and `KeyType` fields and use them in the signature verifier implementations (e.g. in `PublicKeyVerifierEC`).
closes #1527, #1513
> refactor: Support JwsVerificationKey2020 for DID public key

- .github/workflows/build.yml
- .github/workflows/test-suite.yml
> ci: ignore dependabot push branches

- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_test.go
> fix: Verifiable Presentation - update json schema to support context for string along with arrays

- pkg/doc/signature/signer/signer.go
- pkg/doc/signature/signer/signer_test.go
- pkg/doc/verifiable/example_credential_test.go
closes #1578
We put default `assertionMethod` into `proofPurpose`. At the follow-up issue https://github.com/hyperledger/aries-framework-go/issues/1586 we need to support it fully.
> fix: proofPurpose not used for credentials and presentations

- pkg/doc/signature/proof/jws.go
- pkg/doc/signature/proof/jws_test.go
- pkg/doc/verifiable/example_credential_test.go
closes #1577
This is a dirty PR to quickly unblock testing of interop scenario of "Verifying our VCs using third party endpoints".
To be implemented properly at the follow-up https://github.com/hyperledger/aries-framework-go/issues/1589.
> fix: wrong "alg" type in headers for JWS signer

- pkg/doc/signature/jsonld/processor.go
- pkg/doc/signature/jsonld/processor_test.go
- pkg/doc/signature/proof/data_test.go
- pkg/doc/signature/proof/jws.go
- pkg/doc/signature/suite/ecdsasecp256k1signature2019/suite.go
- pkg/doc/signature/suite/ed25519signature2018/suite.go
- pkg/doc/signature/suite/jsonwebsignature2020/suite.go
- pkg/doc/verifiable/jsonld.go
Previously: we weren't dropping undefined terms from RDFs.
Fix: changed normalization aproach through json-gold library so that it
returns parsing error whenever invalid data found in dataset.
Added error handling logic for invalid RDF data errors where aries json
ld processor is going to remove the invalid data from dataset and try
again recursively. (Following
https://github.com/digitalbazaar/jsonld.js/issues/199)
closes #1592
> feat: Handling invalid RDF in canonized JSON LD

- pkg/didcomm/common/service/destination.go
- pkg/didcomm/common/service/destination_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/vdri/httpbinding/vdri.go
- pkg/vdri/httpbinding/vdri_test.go
- pkg/vdri/peer/creator.go
- pkg/vdri/peer/creator_test.go
While working on #1568 I realized that service entries of type `did-communication` were not created properly in did documents (keys must be did:keys and must be inlined).
This PR:
* Fixes this bug in the `peer` and `httpbinding` VDRIs
* Fixes this bug in `didcomm/common/service/destination.go`
* Refactors the `didexchange` protocol service to use `service.Destination()` to get didcomm recipient keys
* Leaves a TODO to validate that the inlined keys are `did:key` (#1604)
> fix: inlined keys in did docs for didcomm

- pkg/doc/signature/jsonld/processor.go
- pkg/doc/signature/jsonld/processor_test.go
Invalid RDF was found causing miss matched node label prefix issues.
Fix :
In case of invalid RDF, json-ld object will be recreated from filtered
view , and recreated json-ld will be normalized to get new view with
updated node labels.
- Closes #1614
> fix: incorrect node label prefixes due to invalid RDF

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/signature/verifier/verifier.go
- pkg/doc/signature/verifier/verifier_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/embedded_proof_test.go
- pkg/doc/verifiable/linked_data_proof.go
- pkg/doc/verifiable/linked_data_proof_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_test.go
closes #1616
Motivated by https://github.com/hyperledger/aries-framework-go/pull/1607#discussion_r407601652,  https://github.com/hyperledger/aries-framework-go/pull/1607#discussion_r407667285 and https://github.com/hyperledger/aries-framework-go/pull/1607#discussion_r407790992
Additionally, recently exposed `verifier.SignatureSuite` is used directly by API consumers.
> refactor: API of signature verifier creation

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/common_test.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- test/bdd/features/verifiable_credential.feature
- test/bdd/pkg/verifiable/verifiable_steps.go
closes #1595
It should be also validated for the signature suites which use `JWK` from `verifier.PublicKey` in the VC BDD tests - https://github.com/hyperledger/aries-framework-go/issues/1596
> fix: assign JWK from PublicKey of DID to resolved PublicKey

- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/internal/mock/didcomm/protocol/route/mock_route.go
- pkg/mock/vdri/mock_registry.go
This PR fixes the following bugs in the didexchange protocol service when responding to oob invitations:
* label not set in outgoing request
* new recipient keys not registered in the router
> fix: didexchange handle inbound oob invitations

- pkg/doc/signature/suite/ecdsasecp256k1signature2019/public_key_verifier_test.go
- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go
- pkg/doc/signature/verifier/public_key_verifier.go
- pkg/doc/signature/verifier/public_key_verifier_test.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/linked_data_proof_test.go
closes #1609
Use case: if the public key in DID is defined without JWK:
```
{
"@context": ["https://w3id.org/security/v1"],
"id": "did:example:123456789abcdefghi#keys-1",
"type": "EcdsaSecp256k1VerificationKey2019",
"controller": "did:example:123456789abcdefghi",
"expires": "2017-02-08T16:02:20Z",
"publicKeyHex" : "034ee0f670fc96bb75e8b89c068a1665007a41c98513d6a911b6137e2d16f1d300"
}
```
then we can create JWK from those bytes in case of ECDSA and use this key for signature verification.
> refactor: support public key bytes in Ecdsa-based signature suite verifiers

- pkg/client/outofband/client.go
- pkg/client/outofband/client_test.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
> feat: outofband events

- pkg/client/introduce/client.go
- pkg/client/introduce/client_test.go
- pkg/client/introduce/doc.go
- pkg/client/introduce/example_test.go
- pkg/client/outofband/client.go
- pkg/client/outofband/client_test.go
- pkg/didcomm/common/service/destination.go
- pkg/didcomm/protocol/introduce/metadata.go
- pkg/didcomm/protocol/introduce/models.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/framework/aries/default.go
- pkg/framework/context/context.go
- test/bdd/features/introduce.feature
- test/bdd/pkg/context/context.go
- test/bdd/pkg/introduce/introduce_sdk_steps.go
- test/bdd/pkg/outofband/outofband_sdk_steps.go
closes #1568
This PR refactors the `introduce` implementations to use `out-of-band` instead of `did-exchange`.
It includes these additional fixes:
* `outofband.Client.Event` not assigned a value by constructor (added an extra assertion to the `TestNew` test case)
* `DIDCommAction` properties not set by outofband.Service (added additional assertions to the "fires off an action event" test)
* `outofband.Service`: inability to handle inbound outofband.Requests over DIDComm b/c the 'OOBMessage' property is unmarshalled as a `map[string]interface{} type` (added a `TestChooseTarget` set of tests)
And also:
* temporarily disabled generic DID syntax validation in `outofband.Client.CreateRequest()` because our sidetree implementation is outputting non-compliant DID IDs (TODO: #1642 ) …
> refactor: introduce protocol to use outofband

- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_common.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_decrypt.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_encrypt.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_enc_helper.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_concatkdf_kw_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_concatkdf_recipient_kuw.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_concatkdf_sender_kw.go
This is a second part of the ECDH-ES KW + AEAD crypto change.
It includes the core crypto logic for key wrapping and AEAD encryption
In a subtle package. This package is not meant to be used outside of ecdhes
package. Its use will be relavant in the next change.
Key wrapping is considered complete as part of this change.
part of ##1469
closes  #1472
closes  #1470
> feat: add Core ECDH-ES crypto logic

- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/register_ecdhes_aead_enc_helper.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/register_ecdhes_aead_enc_helper_test.go
Part 3 of ECDH-ES + AEAD logic. This change includes default
encHelper implementation needed to support the new primitives.
part of #1469
> feat: add encHelper implementation for ECDH-ES crypto logic

- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_aead_private_key_manager.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_aead_private_key_manager_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_aead_public_key_manager.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_aead_public_key_manager_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_common.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_common_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_decrypt_factory.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_encrypt_factory.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_factory_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_key_export.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_key_export_import_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_key_import.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_key_template.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_key_template_test.go
Part 4 of ECDH-ES + AEAD logic. This change concludes the outer layer of
the new Tink primitives required to execute ECDH-ES kw and AEAD content
encryption. This layer is exposed to the user of the primitives.
This change includes:
1. New key templates
2. Primitives factory + their Tink registration
3. Key managers
4. Public key exporter/importer
closes #1469
> feat: Add ECDH-ES+AEAD Tink factory, key managers and templates

- pkg/vdri/key/creator.go
- pkg/vdri/key/creator_test.go
- pkg/vdri/key/resolver.go
- pkg/vdri/key/resolver_test.go
- pkg/vdri/key/vdri.go
- pkg/vdri/key/vdri_test.go
Defines did:key methods (build and read) on vdri.
Closes #1537.
> feat: implement did:key method support on vdri

- pkg/doc/did/doc_test.go
- pkg/doc/jose/jwk.go
- pkg/doc/jose/jwk_test.go
closes #1660
We don't need to use `MarshalPKCS1PublicKey()` for `ed25519` and `ecdsa` public keys. We can return `ed25519.PublicKey` directly without any conversion and use `elliptic.Marshal()` for `*ecdsa.PublicKey` case.
> fix: WK.PublicKeyBytes() for ed25519 and ecdsa case

- pkg/client/presentproof/client.go
- pkg/controller/command/errors.go
- pkg/controller/command/issuecredential/command.go
- pkg/controller/command/issuecredential/models.go
- pkg/controller/command/presentproof/command.go
- pkg/controller/command/presentproof/command_test.go
- pkg/controller/command/presentproof/models.go
Adds `command` support for the Present Proof protocol.
Closes #1633 
> feat: Present Proof - adds command support

- .golangci.yml
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/rest/issuecredential/models.go
- pkg/controller/rest/issuecredential/operation.go
- pkg/controller/rest/issuecredential/operation_test.go
Adds `REST` support for the  Issue Credential protocol.
Closes #1650 
> feat: Issue Credential adds REST support

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/vdri/peer/did_test.go
closes #1662, #1646, #1663
1. Relative DID URLs in Verification Method-s are supported.
2. Marshal all verification methods of DID Doc.
> feat: Support relative DID URLs in verification methods

- pkg/doc/signature/suite/ecdsasecp256k1signature2019/public_key_verifier_test.go
- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go
- pkg/doc/signature/verifier/public_key_verifier.go
- pkg/doc/signature/verifier/public_key_verifier_test.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/support_test.go
- pkg/kms/localkms/localkms.go
- pkg/kms/localkms/pubkey_export_import_test.go
- pkg/kms/localkms/pubkey_reader.go
- pkg/kms/localkms/pubkey_writer.go
Revert updated Key templates in Kms Import/Export and use DER format for
signatures/verification.
Also replace all manual signatures/verifications to use DER format.
closes #1689
> refactor: KMS export key templates using DER format

- pkg/doc/signature/suite/ecdsasecp256k1signature2019/public_key_verifier_test.go
- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go
- pkg/doc/signature/suite/jsonwebsignature2020/suite_crypto_test.go
- pkg/doc/signature/verifier/public_key_verifier.go
- pkg/doc/signature/verifier/public_key_verifier_test.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/support_test.go
- pkg/kms/api.go
- pkg/kms/localkms/localkms.go
- pkg/kms/localkms/localkms_test.go
- pkg/kms/localkms/pubkey_export_import_test.go
- pkg/kms/localkms/pubkey_reader.go
- pkg/kms/localkms/pubkey_writer.go
To support JWS signature, LocalKMS now has this new key format.
DER key format is still available for X509 support.
closes #1703
> refactor: add support for IEEE1363 sig key format

- pkg/controller/command/verifiable/command.go
- pkg/controller/command/verifiable/command_test.go
- pkg/controller/rest/verifiable/operation_test.go
- pkg/didcomm/protocol/issuecredential/states_test.go
- pkg/store/verifiable/models.go
- pkg/store/verifiable/store.go
- pkg/store/verifiable/store_test.go
- test/aries-js-worker/test/verifiable/verifiable.js
- presentation/credentials to have more than just ID - added 'type', 'contexts'.
- these new fields can be used to query/filter records
- Closes #1708
> feat: presentation/credential records to have query/filter args

- pkg/doc/signature/jsonld/processor.go
- pkg/doc/signature/jsonld/processor_test.go
- pkg/doc/signature/proof/data.go
- pkg/doc/signature/proof/data_test.go
- pkg/doc/signature/proof/jws.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/signature/suite/ecdsasecp256k1signature2019/suite.go
- pkg/doc/signature/suite/ed25519signature2018/suite.go
- pkg/doc/signature/suite/jsonwebsignature2020/suite.go
- pkg/doc/signature/verifier/verifier.go
- pkg/doc/signature/verifier/verifier_test.go
- Added two options in jsonlod processor normalization process to
'remove all invalid RDFs' and 'remove only expected invalid RDFs'
- signers to use 'remove all' options
- verifiers to user 'remove only expected'
- Closes #1696
> feat: do not remove invalid data while verifying proofs

- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_factory_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_key_template_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_common.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_decrypt.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_encrypt.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_test.go
- pkg/didcomm/packer/jwe/authcrypt/authcrypt.go
- pkg/didcomm/packer/jwe/authcrypt/authcrypt_test.go
- pkg/didcomm/packer/jwe/authcrypt/pack.go
- pkg/didcomm/packer/jwe/authcrypt/unpack.go
- pkg/doc/jose/common.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_test.go
- pkg/doc/jose/jwe.go
- pkg/doc/jose/jwe_test.go
- pkg/doc/jose/jws.go
Using the new ECDH-ES + AEAD Tink key templates created in tinkcrypto package,
this change introduced JWE build + Encrypt() functionality to support Anoncrypt
JWE messages.
A follow up PR will introduce JWE Decryption
part of #1638
> feat: add JWE Encryption using new ECDH-ES+AEAD Tink templates

- pkg/doc/jose/common.go
- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
This change completes adding JWE build/parse support with new Tink key type.
With this change, it can be considered that Default JWE Anoncrypt using
NIST curve is complete.
closes #1638
closes #987
> feat: add JWE Decrypt support

- pkg/didcomm/packer/jwe/authcrypt/authcrypt_test.go
- pkg/didcomm/packer/jwe/authcrypt/pack.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
- pkg/doc/jose/jwe.go
- pkg/doc/jose/jwe_test.go
Also includes some minor spec conformity fixes and an update to the JWE serialize method to output flattened syntax when there's only one recipient in order to match go-jose's JWE serialize behaviour.
> test: JWE deserialize interop tests

- cmd/aries-js-worker/src/aries.js
- pkg/doc/signature/jsonld/processor_test.go
- pkg/doc/verifiable/example_presentation_test.go
- pkg/doc/verifiable/presentation.go
- pkg/store/verifiable/store.go
- pkg/store/verifiable/store_test.go
- VC id shouldn't be used as a store key  while saving verifiable
credentials since it is an optional field
- Verifiable presentation type and context can be compacted to string
from array if it has only one field.
- added more tests in json ld processor canonicalization to cover
compacted types and proper contexts
- increased default aries js worker timeout to 20 seconds
- Part of #1730
- Part of #1705
- Part of #1732
> feat: save credential and other fixes

- pkg/client/didexchange/event.go
- pkg/didcomm/protocol/decorator/decorator.go
- pkg/didcomm/protocol/decorator/decorator_test.go
- pkg/didcomm/protocol/didexchange/event.go
- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/persistence_test.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/didcomm/protocol/route/service.go
- pkg/didcomm/protocol/route/service_test.go
- pkg/framework/aries/api/protocol.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
- pkg/internal/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/internal/mock/didcomm/protocol/mock_protocol.go
- test/bdd/features/introduce.feature
- test/bdd/pkg/introduce/introduce_sdk_steps.go
This PR:
* Demonstrates automatic route registration immediately following an introduction between an edge agent and a router (`introduce` BDD test)
* Attaches a simple method to `decorator.AttachmentData` to fetch the bytes of an attachment (pending lots of TODOs)
* Add `OutboundMessageHandler()` to the framework's context. Used to dispatch outgoing messages embedded in outofband requests.
* Moves declaration of `client.didexchange.Event` to the service layer in order to access the connection ID following the successful completion of a didexchange protocol instance
* Exposes the didexchange service state IDs (outofband.Service needs one, and I've noticed copies of their values elsewhere in code)
closes #1493 
> feat: support embedded requests in outofband request messages

- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/jsonld.go
- pkg/doc/verifiable/jsonld_test.go
- pkg/doc/verifiable/support_test.go
#1705
Validate that a VC JSON-LD document only contains defined vocabulary.
Example Scenarios:
* “newProp”: “bar” added to VC or VP (where newProp is not in the contexts).
* “newProp”: “bar” added to Proof (where newProp is not in the contexts).
To be added in the follow-up PRs:
1) VP strict validation.
2) Ability to add supplement contexts on VC/VP parsing (in particular, JSON-LD context vocabulary extension).
> feat: VC strict validation based on JSON-LD context

- Makefile
- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/aries.js
- pkg/controller/rest/presentproof/operation.go
- scripts/check_js_integration.sh
- test/aries-js-worker/karma.conf.js
- test/aries-js-worker/package.json
- test/aries-js-worker/test/presentproof/presentproof.js
Adds wasm/rest js BDD tests for the Present Proof protocol.
This PR also adds a new `make` command. It runs the browser which allows us to see the wasm input logs in the browser console.
```
make bdd-test-js-local
```
Closes: #1751 
> feat: Present Proof - adds wasm/rest js BDD tests

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/jsonld.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_ldp_test.go
- pkg/doc/verifiable/presentation_test.go
closes #1705
Additionally, it was found out that Verifiable Presentation cannot have `RefreshService`  according to https://www.w3.org/2018/credentials/v1. Thus it was removed from `Presentation` model.
> feat: VP strict validation based on JSON-LD context

- pkg/controller/command/verifiable/command.go
- pkg/controller/command/verifiable/command_test.go
- pkg/controller/rest/verifiable/operation_test.go
- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
- pkg/store/verifiable/models.go
- pkg/store/verifiable/store.go
- pkg/store/verifiable/store_test.go
- credential type to preserve raw date values to avoid loss of
precisions
- credentials & presentation records to have subjecID/Holder info
- Generate presentation command to set holder info
- Closes #1767
- Closes #1770
- Closes #1773
- Closes #1774
> feat: credential issurance, expired date and other fixes

- pkg/client/introduce/client.go
- pkg/client/route/client.go
- pkg/client/route/client_test.go
- pkg/client/route/models.go
- pkg/client/route/models_test.go
- pkg/didcomm/protocol/introduce/metadata.go
- pkg/didcomm/protocol/introduce/models.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- pkg/didcomm/protocol/introduce/states_test.go
- pkg/didcomm/protocol/route/service.go
- pkg/didcomm/protocol/route/service_test.go
- test/bdd/agent/agent_sdk_steps.go
- test/bdd/bddtests_test.go
- test/bdd/features/redeemable_routes.feature
- test/bdd/pkg/didexchange/didexchange_sdk_steps.go
- test/bdd/pkg/introduce/introduce_sdk_steps.go
- test/bdd/pkg/outofband/outofband_sdk_steps.go
- test/bdd/pkg/redeemableroutes/redeemable_routes.go
- test/bdd/pkg/route/route_sdk_steps.go
closes #1741 
This PR demonstrates an application-level protocol on top of existing ones (introduce, routing, didexchange) where an introducer can request a "pre-approved" route from their router that an introducee may later redeem. The only change required at the protocol level was the addition of `goal` and `goal-code` to `introduce.Proposal`.
> feat: demonstration of redeemable routes

- .github/workflows/build.yml
- ci/version_var.sh
- the main repo will now only publish releases.
- external repo forks MAY publish snapshots by pushing to their own afg-publish branch.
> ci: enable publish in external repos

- docs/didcomm_router.md
Remove inbound transport limitation from the docs as #1124 been implemented.
> docs: DIDCommRouter - Remove inbound transport limitation

- pkg/client/outofband/client.go
- pkg/client/outofband/client_test.go
- pkg/client/outofband/doc.go
- pkg/client/outofband/example_test.go
- pkg/didcomm/protocol/didexchange/models.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/didcomm/protocol/presentproof/service.go
- test/bdd/features/presentproof.feature
- test/bdd/pkg/introduce/introduce_sdk_steps.go
- test/bdd/pkg/outofband/outofband_sdk_steps.go
- test/bdd/pkg/presentproof/presentproof_sdk_steps.go
- test/bdd/pkg/redeemableroutes/redeemable_routes.go
closes #1814
Note: `presentproof_sdk_steps.go#acceptRequestPresentation` was refactored because the JWS signature verification was failing for an as-yet unclear reason. Some of this method's assumptions[1] were strange to me, so I refactored and it started working. Please take a look.
[1]: it was assuming the first connection record retrieved from an agent's storage was the right one, and it was assuming consistency between these connection records and public DIDs registered in the BDD context by a different BDD package
> fix: do not fire didexchange event after accepting oob message

- pkg/didcomm/protocol/route/service.go
Config was returned after the route was unregistered.
> fix: Config was returned after the route was unregistered

- pkg/doc/verifiable/credential_extension_test.go
- pkg/doc/verifiable/credential_jws_test.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- pkg/doc/verifiable/credential_jwt_unsecured_test.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/linked_data_proof_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_jws_test.go
- pkg/doc/verifiable/presentation_jwt_proof_test.go
- pkg/doc/verifiable/presentation_jwt_test.go
- pkg/doc/verifiable/presentation_jwt_unsecured_test.go
- pkg/doc/verifiable/presentation_ldp_test.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/support_test.go
- pkg/doc/verifiable/testdata/context/trustbloc_example.jsonld
- pkg/doc/verifiable/testdata/context/vc_example.jsonld
closes #1753
In a follow-up PR, the same will be done for linked data proofs (`signature` package).
> test: Cache most commonly used VC contexts for tests

- pkg/didcomm/protocol/issuecredential/service_test.go
- pkg/didcomm/protocol/issuecredential/states_test.go
- pkg/doc/signature/proof/data_test.go
- pkg/doc/signature/proof/jws_test.go
- pkg/doc/signature/proof/proof.go
- pkg/doc/signature/proof/proof_test.go
- pkg/doc/signature/proof/utils_test.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/util/time.go
- pkg/doc/util/time_test.go
- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_jwt.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/example_presentation_test.go
- pkg/doc/verifiable/presentation_jwt_proof_test.go
- test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go
- test/bdd/pkg/verifiable/verifiable_steps.go
closes #1772
This is a re-opened PR from accidentally closed https://github.com/hyperledger/aries-framework-go/pull/1793
> ".000" millisecond precision in expirationDate and issuanceDate of credentials are getting removed/truncated while parsing.
For example, `2020-01-01T00:00:00.000Z` gets truncated to `2020-01-01T00:00:00Z` when formatted (marshalled) to string. It results in interoperability issues with e.g. JS libraries which provide VC with linked data proofs to validate.
In this PR, `TimeWithTrailingZeroMsec` is added that extends `time.Time` to handle this use case.
> feat: Credential and LDP dates to use custom object to avoid loss of data

- pkg/doc/util/time.go
- pkg/doc/util/time_test.go
https://github.com/hyperledger/aries-framework-go/issues/1772
> fix: add missed license header for util/time.go

- test/bdd/fixtures/agent-rest/.env
- test/bdd/fixtures/sidetree-mock/docker-compose.yml
Removes redundant docker env variables.
> chore: Removes redundant docker env variables

- pkg/controller/command/verifiable/command.go
- pkg/controller/command/verifiable/command_test.go
- pkg/controller/rest/verifiable/operation_test.go
- pkg/didcomm/protocol/issuecredential/states.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_extension_test.go
- pkg/doc/verifiable/credential_jws_test.go
- pkg/doc/verifiable/credential_jwt_proof_test.go
- pkg/doc/verifiable/credential_jwt_unsecured_test.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/example_presentation_test.go
- pkg/doc/verifiable/linked_data_proof.go
- pkg/doc/verifiable/linked_data_proof_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_jwt_proof_test.go
- pkg/doc/verifiable/presentation_ldp_test.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/support_test.go
- pkg/doc/verifiable/test-suite/verifiable_suite_test.go
- pkg/store/verifiable/store.go
- pkg/store/verifiable/store_test.go
- test/bdd/pkg/presentproof/presentproof_sdk_steps.go
- test/bdd/pkg/verifiable/verifiable_steps.go
closes #1839
The following is refactored:
1. Renaming of API functions:
- NewCredential()  -> ParseCredential()
- NewUnverifiedCredential -> ParseUnverifiedCredential()
- NewPresentation() -> ParsePresentation()
- NewUnverifiedPresentation() -> ParseUnverifiedPresentation() 
2. Return 2 values from NewCredential() - the second []byte is useless in the most of the cases.
> refactor: new VC/VP functions refactoring

- pkg/client/presentproof/client.go
- pkg/controller/command/presentproof/command.go
- pkg/controller/command/presentproof/models.go
- pkg/controller/rest/presentproof/models.go
- pkg/controller/rest/presentproof/operation.go
- pkg/controller/rest/presentproof/operation_test.go
- pkg/didcomm/protocol/presentproof/service.go
- pkg/didcomm/protocol/presentproof/service_test.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
- pkg/internal/gomocks/didcomm/protocol/presentproof/mocks.go
- test/aries-js-worker/test/didexchange/didexchange_e2e.js
- test/aries-js-worker/test/presentproof/presentproof.js
- test/aries-js-worker/test/vdri/vdri.js
- test/aries-js-worker/test/verifiable/verifiable.js
- test/bdd/features/presentproof.feature
- test/bdd/features/presentproof_controller.feature
- test/bdd/pkg/presentproof/presentproof_controller_steps.go
- test/bdd/pkg/presentproof/presentproof_sdk_steps.go
Present Proof saves the presentation to the verifiable store.
This PR also improves BDD/BDD-js tests by adding verifiable presentation payload.
> feat: Present Proof saves the presentation to the verifiable store

- pkg/doc/did/contexts.go
- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/jose/jwk.go
- pkg/doc/jose/jwk_test.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/example_credential_test.go
- pkg/doc/verifiable/linked_data_proof_test.go
- test/bdd/cmd/sidetree/main.go
- test/bdd/features/verifiable_credential.feature
- test/bdd/go.mod
- test/bdd/pkg/context/context.go
- test/bdd/pkg/didexchange/didexchange_controller_steps.go
- test/bdd/pkg/didresolver/didresolver_steps.go
- test/bdd/pkg/introduce/introduce_sdk_steps.go
- test/bdd/pkg/sidetree/sidetree.go
- test/bdd/pkg/verifiable/signer.go
- test/bdd/pkg/verifiable/verifiable_steps.go
- test/bdd/pkg/verifiable/verifier.go
closes #1596
This PR includes bugfix and extension of `jose.JWK`:
- added `JWKFromPublicKey()` function which takes a public key struct (e.g. `*ecdsa.PublicKey` and builds `JWK` from it
- fixed JSON marshalling for  secp256k1-based key.
For VC BDD tests, tinkcrypto/local KMS is used instead of legacy KMS.
Also, DID creation at sidetree is made less hardcoded, we can now create public keys with different types (previously `JwsVerificationKey2020` was hardcoded). This allows checking a different kind of VC Linked Data suites.
> test: JsonWebSignature2020 and EcdsaSecp256k1Signature2019 signature suites in VC BDD tests

- pkg/vdri/key/creator_test.go
- pkg/vdri/key/resolver_test.go
- pkg/vdri/key/vdri.go
- pkg/vdri/key/vdri_test.go
Removes unnecessary returning type (error) from the constructor of did key vdri.
> refactor: simplify did key constructor

- pkg/didcomm/protocol/issuecredential/models.go
- pkg/didcomm/protocol/issuecredential/service.go
In issue credential v2, protocol messages were changed. See this [RFC](https://github.com/hyperledger/aries-rfcs/blob/master/features/0453-issue-credential-v2/README.md)
> feat: Issue credential - changed message structures according to v2

- pkg/store/connection/connection_lookup.go
The `key` in DB was incorect `didconn_%s,%s_did:peer:1zQmXWSdspH9n2oFqciqEGQR`
> fix: Fixes didconn key prefix

- pkg/doc/signature/signer/signer_test.go
- pkg/doc/signature/suite/ed25519signature2018/public_key_verifier_test.go
- pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go
- pkg/doc/signature/verifier/public_key_verifier_test.go
- pkg/doc/util/signature/ecdsa.go
- pkg/doc/util/signature/ecdsa_test.go
- pkg/doc/util/signature/rsa.go
- pkg/doc/util/signature/rsa_test.go
#1852
Signature signers are used in the tests of the linked data proof package.
Signature signers package is not made an internal because it's used by two packages `verifiable` and `signature`.
Follow-up PR-s:
- add signer based on crypto/kms
- use signature singer in JWS related code
> refactor: use signature signers in linked data proof package

- pkg/didcomm/protocol/issuecredential/service.go
Signed-off-by: Aleksei Belezeko <aleksei.belezeko@t-systems.com>
In case of error during issuing credential process abandoning without any information about reason.
> feat: log error in case of abandoning of credential issuing process

- pkg/didcomm/packer/anoncrypt/pack.go
- pkg/didcomm/packer/anoncrypt/pack_test.go
- pkg/doc/jose/common.go
- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
- pkg/doc/jose/jwe.go
This change introduces the new Anoncrypt Packer. It is yet not the default packer
since didComm requires Authcrypt.
The packer also introduces the use of the Compact JWE Serialization for single recipient envelopes.
closes: #1798
> feature: create Anoncrypt Packer

- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/ecdhes_factory_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_common.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aes_aead_composite_encrypt.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aes_aead_composite_test.go
- pkg/didcomm/packer/anoncrypt/pack_test.go
- pkg/doc/jose/encrypter_decrypter_test.go
This change adds the single recipient headers to the AAD in the ECDHES
Tink primitive to AAD to support JWE encryption with a single recipient 
for Compact serialization.
closes #1872
> feat: support single recipient compact JWE format

- test/bdd/bddtests_test.go
- test/bdd/features/outofband_controller.feature
- test/bdd/pkg/outofband/outofband_controller_steps.go
- test/bdd/pkg/outofband/outofband_sdk_steps.go
This PR adds controller(REST API) BDD tests for the `outofband` protocol.
Closes #1891 
> feat: Outofband - adds controller(REST API) BDD tests

- pkg/storage/mysql/mysqlstore.go
- pkg/storage/mysql/mysqlstore_test.go
This reverts commit 26f807a9 (#1952)
And fixes nolint gosec warning.
Due to MySQL limitation, table names cannot be set as a bound variable in prepared statements.
> Revert "bug: remove nolint gosec and fix possible sql injection attack"

- pkg/controller/command/didexchange/command.go
- pkg/controller/command/didexchange/command_test.go
- pkg/controller/command/didexchange/models.go
- pkg/didcomm/protocol/didexchange/service.go
- test/aries-js-worker/test/didexchange/didexchange_e2e.js
- test/aries-js-worker/test/didexchange/edgeagent_mediator.js
- test/bdd/pkg/didexchange/didexchange_controller_steps.go
This PR adds notification support for the StateMsg and Action.
The topics you might listen to are:
* didexchange_actions
* didexchange_states
Closes #1950 
NOTE: no more `connections` topic
> feat: Common notifier for the didexchange

- go.mod
- go.sum
- pkg/storage/mysql/mysqlstore.go
- pkg/storage/mysql/mysqlstore_test.go
- scripts/check_unit.sh
Right now, sql store unit test are using sql mock : https://github.com/DATA-DOG/go-sqlmock 
As per the discussion with the team, seems like its not so viable option to choose. Therefore, update the the unit-test to use the mysql db instead of mock. 
Fix the below from the list 1948: 
- open a new sql.DB and exec the "USE" statement on that one. Assign it to the storage.Store: https://github.com/hyperledger/aries-framework-go/pull/1938/files#diff-5c03fdd2a42c9a160e4a9b056cb9db20R102
- mocking the database in tests
closes #1948 
> fix: Spool mysql instead of using mock

- go.mod
- pkg/didcomm/protocol/messagepickup/api.go
- pkg/didcomm/protocol/messagepickup/lockbox.go
- pkg/didcomm/protocol/messagepickup/models.go
- pkg/didcomm/protocol/messagepickup/service.go
- pkg/didcomm/protocol/messagepickup/service_test.go
**Title:**
proposed implementation for a messagebox feature
implements https://github.com/hyperledger/aries-framework-go/issues/811 service layer
Summary:
Introduction of a messagepickup service for storing messages until and edge agent collects.
I'd like to credit @pfeairheller for the original implementation.
Since this violates the ~500 line PR rule I wanted to get it out early for discussion.
I am still evaluating what BDD tests might be needed and will mark this current PR as draft.
I am making a corresponding PR to aries-rfcs, to update the type values of messages.
https://github.com/hyperledger/aries-rfcs/pull/500
> feat:  messagebox

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/didcomm/common/service/destination.go
- pkg/didcomm/protocol/didexchange/persistence.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/store/did/didconnection.go
fixes #1989 
* TODO [merge connection stores](https://github.com/hyperledger/aries-framework-go/issues/1004)
* TODO [decouple connection storage from DID exchange protocol](https://github.com/hyperledger/aries-framework-go/issues/943)
> fix: #1989 didexchange.Client.SaveConnection not saving did-key mappings to did store

- pkg/didcomm/protocol/mediator/service.go
> fix: Mediator forward message - skip fetching connectionID for logging

- cmd/aries-js-worker/src/aries.js
- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/client/didexchange/models.go
- pkg/controller/command/didexchange/command.go
- pkg/controller/command/didexchange/command_test.go
- pkg/controller/command/didexchange/models.go
- pkg/controller/rest/didexchange/models.go
- pkg/controller/rest/didexchange/operation.go
- pkg/controller/rest/didexchange/operation_test.go
- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/mock/didcomm/protocol/didexchange/mock_didexchange.go
- pkg/mock/vdri/mock_registry.go
- pkg/store/did/didconnection.go
- pkg/vdri/peer/store.go
- pkg/vdri/peer/store_test.go
- pkg/vdri/registry.go
fixes #1997 
* refactored SaveConnection() -> CreateConnection()
* Parameters are now: myDID string, theirDID *did.Doc, and options
* REST/Controller APIs refactored accordingly
* fix: did:peer vdri not returning vdriapi.ErrNotFound when deltas not
found
BDD tests TODO #1997 (but I've tested this change in another project's bdd tests)
> fix: #1997 didexchange.Client.SaveConnection not saving 'theirDID'

- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/aries.js
- pkg/client/messagepickup/client.go
- pkg/controller/command/mediator/command.go
- pkg/controller/command/mediator/command_test.go
- pkg/controller/command/mediator/models.go
- pkg/controller/rest/mediator/models.go
- pkg/controller/rest/mediator/operation.go
- pkg/controller/rest/mediator/operation_test.go
- pkg/didcomm/protocol/messagepickup/service.go
- pkg/framework/aries/default.go
- added JS, command, REST controller for mediator reconnect by sending
noop message to router
- Closes #2000
> feat: command controller for mediator reconnect

- cmd/aries-agent-mobile/go.sum
- cmd/aries-agent-rest/go.sum
- cmd/aries-js-worker/go.sum
- pkg/controller/rest/didexchange/models.go
- pkg/controller/rest/introduce/models.go
- pkg/controller/rest/issuecredential/models.go
- pkg/controller/rest/outofband/models.go
- pkg/controller/rest/presentproof/models.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
This PR fixes collisions related to Invitation and Action structures. 
What was the problem?
We have two `Invitation` structures in our framework (outofband and didexchange).
When we generate `swagger` it uses only one `Invitation` definition e.g '#/definitions/Invitation'.
Due to this collision the spec was incorrect.
The same was related to the `Action` structure.
Closes #1975 
> docs: Fixes openapi validation warnings

- pkg/didcomm/packer/anoncrypt/pack.go
- pkg/didcomm/packer/api.go
- pkg/didcomm/packer/authcrypt/pack.go
- pkg/didcomm/packer/authcrypt/pack_test.go
- pkg/doc/jose/common.go
- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
This change also introduces a thirdPartyKeysDB storage to store third party keys
It must be updated with the senderKey prior to Authcrypt.Decrypt() execution
closes #986
> feat: add Authcrypt packer using ECDH1PU

- pkg/didcomm/protocol/mediator/service.go
- pkg/didcomm/protocol/mediator/service_test.go
- pkg/didcomm/protocol/messagepickup/api.go
- pkg/didcomm/protocol/messagepickup/service.go
- pkg/framework/aries/default.go
- pkg/mock/didcomm/protocol/messagepickup/mock_messagepickup.go
**Title:**
mediator - message pick up integration
Summary:
We are attempting to integrate the message pick up and mediator services. So that when configured, the message pickup service can receive forward messages, from the mediator service and store them.
In our internal implementation of router/mediation, we used the `RegisterActionEvent` mechanism to register a channel and have the messages sent over to the message pickup service. This has been superseded by the use of `RegisterActionEvent` to allow businesses logic to be run during the RequestMessage flow during mediation.
We are looking for input on how best to proceed.
> mediator - message pick up integration

- scripts/generate-openapi-spec.sh
Allows generating openAPI spec outside the home directory.
for #2015 
> fix: Generate openapi spec

- pkg/internal/gomocks/store/verifiable/mocks.go
- pkg/store/verifiable/store.go
- pkg/store/verifiable/store_test.go
**Add methods to remove VC and VP from the store**
Currently, there is no way to remove issued VC and VP from the store so I've added required methods
> remove Verifiable Credentials and Presentations from store

- docs/concepts/00_what_is_hl_aries.md
- docs/concepts/01_terminologies.md
**Title:**
Add docs for IssueCredential
Closes https://github.com/hyperledger/aries-framework-go/issues/2031
**Summary**:
Added:
- protocol defintion
- terminologies
> docs: added issue credential protocol and related terminologies

- pkg/controller/command/verifiable/command.go
- pkg/controller/command/verifiable/command_test.go
- pkg/controller/command/verifiable/models.go
- pkg/controller/rest/verifiable/models.go
- pkg/controller/rest/verifiable/operation.go
- pkg/controller/rest/verifiable/operation_test.go
**Title:**
Update verifiable controllers
Closes https://github.com/hyperledger/aries-framework-go/issues/2034
Summary:
- Implement the two methods recently added to the verifiable store.
- updated the command controller
- updated the rest controller
> feat: updated verifiable controllers with the new methods

- pkg/didcomm/transport/http/support_test.go
Sometimes test is failed due to a timeout issue.
See https://github.com/hyperledger/aries-framework-go/runs/916239512#step:4:130
> test: Increases timeout

- cmd/aries-agent-rest/startcmd/start_test.go
- pkg/didcomm/protocol/presentproof/service.go
- pkg/didcomm/protocol/presentproof/service_test.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
- test/bdd/features/presentproof.feature
`Abandoned` state now cannot transit to the `done` state.
See [0454-present-proof-v2#states](https://github.com/hyperledger/aries-rfcs/tree/master/features/0454-present-proof-v2#states)
> The final states for both the prover and verifier are done or abandoned, and once reached, no further updates to the protocol instance are expected.
> feat: Present proof - fixes abandoned state transition to done

- docs/concepts/00_what_is_hl_aries.md
- docs/concepts/01_terminologies.md
**Title:**
Added docs for PresentProof protocol
Closes https://github.com/hyperledger/aries-framework-go/issues/2040
**Summary:**
Brief explanation of the protocol and its related terminologies.
> docs: added PresentProof protocol summary and related terms

- cmd/aries-agent-mobile/pkg/api/issuecredential.go
- cmd/aries-agent-mobile/pkg/wrappers/command/issuecredential.go
- cmd/aries-agent-mobile/pkg/wrappers/command/issuecredential_test.go
- cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/aries-agent-mobile/pkg/wrappers/rest/issuecredential.go
- cmd/aries-agent-mobile/pkg/wrappers/rest/issuecredential_test.go
**Title:**
Add new methods to the IssueCredential mobile wrappers
Closes https://github.com/hyperledger/aries-framework-go/issues/2061
**Summary:**
Adds the new `AcceptProblemReport` method introduced by https://github.com/hyperledger/aries-framework-go/pull/2057.
> feat: updated mobile bindings for IssueCredential protocol

- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/aries.js
- pkg/client/introduce/client.go
- pkg/client/introduce/client_test.go
- pkg/controller/command/introduce/command.go
- pkg/controller/command/introduce/command_test.go
- pkg/controller/command/introduce/models.go
- pkg/controller/rest/introduce/models.go
- pkg/controller/rest/introduce/operation.go
- pkg/controller/rest/introduce/operation_test.go
- pkg/didcomm/protocol/introduce/service.go
- pkg/didcomm/protocol/introduce/service_test.go
- pkg/didcomm/protocol/introduce/states.go
- test/bdd/features/introduce.feature
- test/bdd/pkg/introduce/introduce_sdk_steps.go
Adds action event support for the Introduce protocol. Now, if the protocol receives `ProblemReport` message an action event will be triggered.
> feat: Introduce - added action event support (ProblemReport)

- cmd/aries-agent-mobile/pkg/api/introduce.go
- cmd/aries-agent-mobile/pkg/wrappers/command/introduce.go
- cmd/aries-agent-mobile/pkg/wrappers/command/introduce_test.go
- cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go
- cmd/aries-agent-mobile/pkg/wrappers/rest/introduce.go
- cmd/aries-agent-mobile/pkg/wrappers/rest/introduce_test.go
**Title:**
Add new `AcceptProblem` report method.
Closes https://github.com/hyperledger/aries-framework-go/issues/2070
**Summary:**
Updated on
- interface
- remote agent
- local agent
> feat: added new Introduce controller method to mobile wrappers

- cmd/aries-agent-mobile/Makefile
**Title:**
Reduce final size of mobile bindings
Closes https://github.com/hyperledger/aries-framework-go/issues/2029
**Summary:**
Result of this change:
- Android => **42.2MB** down to **26.9MB**
- iOS => **126.3MB** down to **77.9MB**
> feat: reduced size of mobile bindings

- cmd/aries-agent-mobile/go.sum
- cmd/aries-agent-rest/go.sum
- go.mod
- go.sum
- pkg/doc/presexch/api.go
- pkg/doc/presexch/api_test.go
- pkg/doc/presexch/example_test.go
- test/bdd/go.sum
closes #2105
Initial support for evaluating presentation submissions against a set of definitions where no submission_requirements are considered. All input definitions are required.
> feat: #2105 presentation-exchange: get matching credentials

- cmd/aries-js-worker/go.sum
- pkg/doc/signature/suite/ed25519signature2018/suite.go
- pkg/kms/legacykms/kms.go
- pkg/vdri/registry.go
- pkg/vdri/verifiable_compat_test.go
fixes #2078 
fixes #2112
----
Set public key id to base58(pubSigKey) in vdri.Registry.Create() when using legacy KMS. This sets the key's ID in the resulting did.Doc in the proper format. This enables compatibility with the DID public key fetcher from the `verifiable` package (format must be "<did#keyID>").
Strip a leading "#" (if any) when searching for public sig keys in the BaseKMS' keystore to account for the above change.
Both these changes are done in code paths where legacy KMS is used and will (presumably) be eliminated once we deprecate it.
---
Whereas before this change peer DID docs were unmarshalled like this (note `authentication`):
<details><summary>Click</summary>
```json
{ …
```
> fix: #2078 #2112

- pkg/didcomm/protocol/didexchange/service.go
- test/bdd/pkg/outofband/outofband_sdk_steps.go
We missed adding `TheirLabel` to the connection record. This PR fixes it by adding `TheirLabel` to the record when requests received.
> feat: Added TheirLabel to the record when request received

- test/aries-js-worker/test/introduce/introduce.js
- test/bdd/pkg/redeemableroutes/redeemable_routes.go
BDD test sometimes fails due to error `routing config : failed to fetch routing configuration : router not registered`. See https://github.com/hyperledger/aries-framework-go/runs/993989706#step:5:3248
This PR increase timeout from 2 to 5 seconds.
The second issue was with the JS test.
This PR also fixes it.
> feat: Fixes BDD test (router not registered)

- pkg/client/presentproof/example_test.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
This PR adds examples for the `Present proof` protocol (basic flow).
Also, this PR fixes a bug related to `WillConfirm` property  (introduced in version 2.0)
The bug was about that `presentationSent` state did not send `Presentation` when `WillConfirm` was equal to `false`.
Part of #1791 
> feat: Present proof - adds examples

- pkg/client/presentproof/doc.go
This PR adds `godoc` for the Present Proof protocol.
Part of #1791 
> docs: Present Proof documentation (godoc)

- cmd/aries-js-worker/main.go
- pkg/didcomm/protocol/issuecredential/service.go
- pkg/didcomm/protocol/middleware/issuecredential/middlewares.go
- pkg/didcomm/protocol/middleware/issuecredential/middlewares_test.go
- pkg/didcomm/protocol/middleware/presentproof/middlewares.go
- pkg/didcomm/protocol/middleware/presentproof/middlewares_test.go
- pkg/didcomm/protocol/presentproof/service.go
- pkg/internal/gomocks/store/verifiable/mocks.go
- pkg/store/verifiable/models.go
- pkg/store/verifiable/store.go
- pkg/store/verifiable/store_test.go
- test/aries-js-worker/test/issuecredential/issuecredential.js
- test/aries-js-worker/test/presentproof/presentproof.js
We did not have a possibility to correlate `credentials` or `presentations` that were issued through the protocols with did-connections (participants who were involved in the process of issuing).
This PR fixes it by introducing two new fields in `verifiable.Record` structure. Those fields are not part of credentials/presentations and they do not have any impact on original VC/VP. Fields are being used as `other fields of interest.` according to `Record` structure.
> feat:  Verifiable - saves participant`s DIDs.

- test/bdd/pkg/introduce/introduce_controller_steps.go
- test/bdd/pkg/introduce/introduce_sdk_steps.go
BDD test was failing due to the deadline. It happens because of the missing event.
This PR fixes it by moving the listener before action.
> fix: Fixes deadline in BDD test

- pkg/didcomm/packager/package_test.go
- pkg/didcomm/packer/authcrypt/pack.go
- pkg/didcomm/packer/authcrypt/pack_test.go
- pkg/kms/localkms/kid_creator.go
- pkg/kms/localkms/localkms.go
- pkg/kms/localkms/localkms_test.go
- pkg/kms/localkms/localkms_writer.go
- pkg/kms/localkms/localkms_writer_test.go
- pkg/storage/base58wrapper/base58wrapper.go
- pkg/storage/base58wrapper/base58wrapper_test.go
- pkg/storage/couchdb/couchdbstore.go
> refactor: revert KID encoding back to base64URL and introduce base58 store wrapper

- pkg/storage/base58wrapper/base58wrapper_test.go
- pkg/storage/couchdb/couchdbstore_test.go
- pkg/storage/store_test.go
Sometimes unit tests are failing due to `conflict` error.
This PR fixes it by generating new keys instead of using constant ones.
> fix: Fixes unit test failure due to conflict error

- Makefile
- scripts/run-openapi-demo.sh
Signed-off-by: Jan Christoph Ebersbach <jan-christoph.eberbach@41ppl.com>
**Title:**
Add stop-openapi-demo target
Currently, there's only a target to start the demo but none to shut it down. Since stopping the demo by hand involves multiple commands executed in multiple directories, this new target should reduce the effort to stop the demo.
**Summary:**
Extended the Makefile with a stop-openapi-demo target.
> chore(make): add stop-openapi-demo target

- pkg/storage/mem/mem_store.go
- pkg/storage/mem/mem_store_test.go
- pkg/storage/store_test.go
The current implementation of `mem` storage has a bug in the `Iterator` method.
This bug can be reproduced only when storage is populated with the data.
The issue comes out when we are iterating over keys and the start key doesn't match.
In that case, the start index is equal to `0`. Which means that the iterator will return data starting from 0 index. e.g data[0:end_idx_match].
This PR fixes it by introducing zero index as a -1.
PR includes:
* Bugfix 
* Common test case (for all DBs)
* Test case for `mem` implementation.
> fix: Fixes mem store

- pkg/storage/base58wrapper/base58wrapper_test.go
- pkg/storage/couchdb/couchdbstore.go
- pkg/storage/couchdb/couchdbstore_test.go
- pkg/storage/providers_test.go
- scripts/check_js_integration.sh
- scripts/check_unit.sh
- scripts/couchdb-config/10-single-node.ini
- test/bdd/fixtures/agent-rest/couchdb-config/10-single-node.ini
- test/bdd/fixtures/agent-rest/docker-compose.yml
part of #2178 
**Summary**
Since v3, CouchDB does not create system databases (eg. `_users`) by default. This means that pinging the `_up` endpoint is not a sufficient smoke test, which means the CouchDB storage provider's constructor returns successfully. However, CouchDB might still not be fully ready by the time the framework wants to create a database (eg. the verifiable store) and this call fails because `_users` is still not there, which means the request is not authenticated.
-----
**Changes**
* Explicitly set CouchDB on single-node mode in our tests as per their documentation
* CouchDB provider now checks for availability of `_users` as a smoke test instead of querying `_up`.
* Upgraded CouchDB version in unit tests
----
**References**
* [Single mode …
> fix: #2178 CouchDB setup in BDD tests

- .github/workflows/build.yml
- pkg/storage/base58wrapper/base58wrapper_test.go
- pkg/storage/couchdb/couchdbstore.go
- pkg/storage/couchdb/couchdbstore_test.go
- pkg/storage/mysql/mysqlstore_test.go
- pkg/storage/providers_test.go
- pkg/storage/store_test.go
- scripts/check_unit.sh
Depends on #2180
Unit tests for storages were all ignoring failures (such as CouchDB or MySQL not running). This completely undermined confidence in any of these tests... a real mess.
This patch only ignores these tests when running in GitHub actions using the 'macOS-10.15' virtual environment. Issue #2183 was opened to track the problem of not running these tests in the macOS CI in the first place.
> fix: unit tests depending on docker

- pkg/kms/localkms/localkms_writer_test.go
Sometimes the test is failing randomly.
```
--- FAIL: TestLocalKMSWriter/error_case_-_import_duplicate_keysetID (0.00s)
localkms_writer_test.go:105: 
Error Trace:	localkms_writer_test.go:105
Error:      	Should not be: 0x5f
Test:       	TestLocalKMSWriter/error_case_-_import_duplicate_keysetID
```
According to the code, we are generating bytes randomly e.g `base64.RawURLEncoding.EncodeToString(random.GetRandomBytes(uint32(keySetIDLength)))`
Then we are checking that the first byte is not equal to `uint8('_')`.
Since `_` (underscore) is a character that can be used for base64 there is no guarantee that `_` will not be the first character.
This is the reason why the test is failing randomly.
Conclusion:
The test is redundant.
> test: Fixes local KMS writer test

- .github/workflows/build.yml
- pkg/didcomm/protocol/mediator/service.go
- pkg/didcomm/protocol/mediator/service_test.go
Currently, we are using the `go channel` to synchronize whether the `mediate-grant` message was received.
The problem here is that the `mediate-grant` message can be received on the different `node`. Which means we will fail due to timeout. This PR fixes it by saving data to DB.
> fix: Mediator - replacing a channel sync with the database sync

- pkg/storage/mysql/mysqlstore.go
- pkg/storage/store_test.go
The MySQL iterator implementation doesn't work as expected.
This PR fixes it by using a subquery to get proper results.
> fix: Fixes MySQL iterator

- test/bdd/features/aries_mediator_e2e_sdk.feature
- test/bdd/pkg/context/context.go
- test/bdd/pkg/didexchange/didexchange_sdk_steps.go
- test/bdd/pkg/introduce/introduce_controller_steps.go
- test/bdd/pkg/introduce/introduce_sdk_steps.go
- test/bdd/pkg/mediator/mediator_sdk_steps.go
- test/bdd/pkg/messaging/messaging_controller_steps.go
- test/bdd/pkg/outofband/outofband_sdk_steps.go
- test/bdd/pkg/redeemableroutes/redeemable_routes.go
- test/bdd/pkg/util/util.go
This PR includes:
* improves BDD tests with the router usage
* added one WebSocket listener which saves data to the channel (prevents from missing events)
Note: I have run these tests 100 times 99 of 100 were successful.
The reliability of these tests also depends on https://github.com/hyperledger/aries-framework-go/pull/2226
> refactor: Go BDD tests improvements

- .github/workflows/build.yml
Github is going to depreciate `set-env` functionality.
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This PR fixes it according to new changes.
> chore: Github - environment variables

- pkg/storage/couchdb/couchdbstore.go
- pkg/storage/couchdb/couchdbstore_test.go
To update Couchdb data we need revID. If `revID` is empty and we perform an update operation we will get an error `Document update conflict`. It happens because our `Put` operation is not consistent.
e.g 
```
revID = c.getRevID(key)
db.Put(key , {...revID...})
```
This PR fixes the problem of `document update conflict` by adding retry logic.
> fix: Couchdb - document update conflict

- pkg/mock/storage/mock_store.go
- pkg/storage/edv/documentprocessor/documentprocessor.go
- pkg/storage/edv/formatprovider/formatprovider.go
- pkg/storage/edv/formatprovider/formatprovider_test.go
- pkg/storage/edv/models.go
This new provider type allows for data to be stored in an underlying provider using the EDV document models.
> feat: SDS EDV format provider

- pkg/storage/edv/documentprocessor/documentprocessor.go
- pkg/storage/edv/documentprocessor/documentprocessor_test.go
- pkg/storage/edv/formatprovider/formatprovider.go
- pkg/storage/edv/models.go
Added a concrete document processor implementation. It can encrypt and decrypt between structured documents and encrypted documents.
closes #2249
> feat: EDV document processor implementation

- pkg/crypto/api.go
- pkg/crypto/tinkcrypto/crypto.go
- pkg/crypto/tinkcrypto/crypto_test.go
- pkg/crypto/tinkcrypto/key_wrapper.go
- pkg/crypto/tinkcrypto/key_wrapper_test.go
- pkg/crypto/tinkcrypto/primitive/composite/composite_common.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/subtle/ecdh1pu_aes_aead_composite_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_concatkdf_kw_test.go
- pkg/crypto/tinkcrypto/unwrap_support.go
- pkg/crypto/tinkcrypto/unwrap_support_test.go
- pkg/doc/jose/jwe.go
- pkg/mock/crypto/mock_crypto.go
This change introduces Wrap() and Unwrap() to Cryto api.
The functions work for ECDHES keys only for now. Future keys
(ECDH1PU, Ed25519) can be introduced in a future change.
It also includes setting APU and APV in the key derivation
process (they are set to empty `[]byte{}` in the current JWE
building process).
closes #2257
> refactor: add Wrap/Unwrap crypto functions

- pkg/doc/signature/jsonld/processor.go
- pkg/doc/signature/jsonld/processor_test.go
- pkg/doc/signature/proof/cache.go
- pkg/doc/signature/proof/data.go
- pkg/doc/signature/proof/data_test.go
- pkg/doc/signature/proof/jws.go
- pkg/doc/signature/proof/jws_test.go
- pkg/doc/signature/proof/support_test.go
- pkg/doc/signature/signer/signer_test.go
Added `jsonld. WithDocumentLoaderCache()` which can be used to pass cached JSON-LD contexts as pairs of URLs and JSON-LD context content (e.g. as string or `io.Reader`).
It can be used in combination with actively used `jsonld. WithDocumentLoader()`.
Current logic:
- if neither `DocumentLoader` nor `DocumentLoaderCache` is defined - do not set `DocumentLoader`JSON-LD option;
- if `DocumentLoader` is not defined - create it using `ld.NewCachingDocumentLoader()`;
- otherwise, check if `DocumentLoader` is caching one, if not, cteate a wrapping caching loader.
- apply cached contexts from `DocumentLoaderCache` to the cached document loader.
Checked that the tests from `signature` package can be run off-line (so there is no dependency on any online available JSON-LD contexts). This is achieved …
> feat: flexible cache for jsonld.Processor DocumentLoader

- cmd/aries-agent-rest/main.go
- docs/rest/openapi_demo.md
- pkg/controller/rest/rest.go
- open api demo schema changed to 'https' from 'http,https'
- closes #2239
> fix: incorrect content type in agent rest

- go.mod
- pkg/crypto/api.go
- pkg/crypto/tinkcrypto/crypto.go
- pkg/crypto/tinkcrypto/crypto_test.go
- pkg/crypto/tinkcrypto/key_wrapper.go
- pkg/crypto/tinkcrypto/key_wrapper_test.go
- pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export.go
- pkg/crypto/tinkcrypto/unwrap_support.go
- pkg/crypto/wrapkey_opts.go
- pkg/mock/crypto/mock_crypto.go
this change is necessary to consolidate ECDHES and ECDH1PU Tink keys
since key wrapping will not be executed by the Tink primitives.
closes #2271
> refactor: add ECDH-1PU to crypto Wrap/Unwrap

- cmd/aries-agent-mobile/main.go
- cmd/aries-agent-mobile/pkg/api/logger.go
- cmd/aries-agent-mobile/pkg/wrappers/config/options.go
- cmd/aries-agent-mobile/pkg/wrappers/logger/logger.go
To inject the logger client must implement `LoggerProvider` with one method `GetLogger`.  GetLogger should return the Logger interface.  GetLogger function receives `module` name e.g `aries-framework/introduce/service`. The client might have additional logic based on module name e.g disable/enable.
```
type LoggerProvider interface {
GetLogger(module string) Logger
}
type Logger interface {
Fatal(msg string)
Panic(msg string)
Debug(msg string)
Info(msg string)
Warn(msg string)
Error(msg string)
}
```
> feat: Adds possibility to inject logger (mobile)

- cmd/aries-agent-mobile/go.mod
- cmd/aries-agent-mobile/go.sum
- cmd/aries-agent-rest/go.sum
- pkg/doc/signature/proof/proof.go
- pkg/doc/signature/proof/proof_test.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/credential_ldp_test.go
- pkg/doc/verifiable/linked_data_proof.go
closes #2284
This PR adds support for the `capabilityChain` property in LD proofs. LD proofs with `capabilityChain` can be added with `verifiable.Credential.AddLinkedDataProof()` or more directly with `signer.DocumentSigner`. They can be verified with `verifiable.ParseCredential()` and `verifier.DocumentVerifier.Verify()`.
`capabilityChain` is used in [ZCAP-LD](https://w3c-ccg.github.io/zcap-ld/) with a `proofPurpose` of `capabilityDelegation`.
Note: [ZCAP-LD != Verifiable Credentials](https://github.com/w3c-ccg/zcap-ld/issues/6), so if the spec ever matures then we should add support for it in a new, separate API from `verifiable.Credential`.
> feat: #2284 add capabilityChain for LD Proofs

- cmd/aries-agent-mobile/go.mod
- cmd/aries-agent-mobile/go.sum
- cmd/aries-agent-rest/go.mod
- cmd/aries-agent-rest/go.sum
- cmd/aries-js-worker/go.mod
- cmd/aries-js-worker/go.sum
- go.mod
- go.sum
- pkg/doc/bbs/bbs12381g2pub/bbs.go
- test/bdd/go.mod
- test/bdd/go.sum
closes #2248
We substitute own impl of `Fr.Inverse()` in the [trunsbloc fork](https://github.com/trustbloc/bls12-381) with the one provided by kilic.
> refactor: Use Fr.Inverse() from kilic lib

- cmd/aries-agent-mobile/go.sum
- cmd/aries-agent-mobile/pkg/api/storage.go
- cmd/aries-agent-mobile/pkg/wrappers/command/aries.go
- cmd/aries-agent-mobile/pkg/wrappers/config/options.go
- cmd/aries-agent-mobile/pkg/wrappers/storage/storage.go
- cmd/aries-agent-mobile/pkg/wrappers/storage/storage_test.go
Adds the possibility to inject storage.
Clients can implement and provide their own storage implementation.
To do that the `StorageProvider` interface must be implemented:
```
// StorageProvider defines storage interface.
type StorageProvider interface {
// OpenStore opens a store with given name space and returns the handle
OpenStore(name string) (Store, error)
// CloseStore closes store of given name space
CloseStore(name string) error
// Close closes all stores created under this store provider
Close() error
}
// Store is the storage interface.
type Store interface {
// Put stores the key and the record
Put(k string, v []byte) error
// Get fetches the record based on key
Get(k string) ([]byte, error)
// Iterator returns an iterator for the latest snapshot of the
// underlying store
// …
```
> feat: Adds the possibility to inject storage (mobile)

- pkg/kms/webkms/headers_opts.go
- pkg/kms/webkms/remotekms.go
- pkg/kms/webkms/remotekms_test.go
This change introduced a new optional function passed to remotekms.New()
This new option allows calling a function to potentially call an
authorization server and setup auth info as http headers. This function
should be created by the user of the framework. The absence of this option
means the remoteKMS is not setting any authorization info in the headers.
This change also removed 'secret' and 'controller' http headers as these
should not be dictated by the framework.
It also includes some minor refactoring like placing CreateKeystore()
above New() as a keystore is required before creating a new remoteKMS instance.
part of #2307
> feat: add HeadersOpt optional function to remoteKMS New()

- pkg/storage/edv/restprovider.go
The unique property of the "store name" indexed attribute was incorrectly set to true, which was preventing multiple documents from storing successfully.
> fix: EDV REST provider store indexed attribute creation

- pkg/client/messaging/client.go
- pkg/client/messaging/client_test.go
- pkg/client/messaging/doc.go
- pkg/client/messaging/msgservice.go
- pkg/client/messaging/msgservice_test.go
- pkg/controller/command/messaging/command.go
- pkg/controller/command/messaging/command_test.go
- added client package for messaging features so that any command
controller can reuse basic messaging feature to avoid code duplication
and re-work.
- closes #2323
> feat: client for messaging

- pkg/mock/edv/edv.go
- pkg/storage/edv/encryptedformatter_test.go
- pkg/storage/edv/restprovider.go
- pkg/storage/edv/restprovider_test.go
- pkg/storage/formattedstore/formattedstore_test.go
- When calling the EDV REST provider's Put(k, v) method with a key that already exists in the store, it now updates the underlying document with v.
- Updated log messages to be on one line.
- Moved getAllDocuments down so that it's in the same place as the other unexported methods.
> feat: EDV REST provider can now update documents

- pkg/crypto/api.go
- pkg/crypto/tinkcrypto/crypto.go
- pkg/crypto/tinkcrypto/crypto_test.go
- pkg/crypto/tinkcrypto/key_wrapper.go
- pkg/crypto/webkms/remotecrypto.go
- pkg/crypto/webkms/remotecrypto_test.go
- pkg/crypto/webkms/wrapkey_util.go
- pkg/crypto/webkms/wrapkey_util_test.go
- pkg/crypto/wrapkey_opts.go
- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypt_test.go
- pkg/doc/jose/encrypter.go
- pkg/kms/webkms/headers_opts.go
- pkg/kms/webkms/remotekms.go
- pkg/kms/webkms/remotekms_test.go
feat: add remoteCrypto implementation
This change introduces remoteCrypto implementation of crypot.Crypto
It includes utility functions to transform key wrapping structs in
to serializable (marshalable) instances ready to be consumed by the
key server.
It also updates key wrapping optional function WithKH() to support
adding a sending key as *crypto.PublicKey on top of the already
supported *keyset.Handle and ecdsa.PublicKey
This change completes the implementaiton of WebKMS.
Closes #2307
> feat: add remoteCrypto implementation

- pkg/storage/edv/models/models.go
- pkg/storage/edv/restprovider.go
- pkg/storage/edv/restprovider_test.go
- Added an option to enable a performance optimization that can be enabled if being used with an EDV server that supports it.
- Removed a comment with a ToDo regarding dealing with a potential edge-case issue since I've now realized that the design of the EDV provider already prevents it from happening in the first place.
> feat: Add option to EDV REST provider to get full document on query

- pkg/storage/edv/encryptedformatter.go
- pkg/storage/edv/restprovider.go
- pkg/storage/edv/restprovider_test.go
- pkg/storage/formattedstore/batchwrite.go
- pkg/storage/formattedstore/batchwrite_test.go
- pkg/storage/formattedstore/formattedstore.go
- pkg/storage/formattedstore/formattedstore_test.go
In an earlier commit, the EDV document IDs were changed so that instead of being randomly generated, they're instead based off hashes (computed by an encrypted hash function - HMAC) of the friendly keys. This means that querying the vault to get the document IDs in the EDV REST provider Get and Delete methods is no longer required, which will provide a big performance improvement.
> feat: Eliminate unnecessary query calls in EDV REST provider

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_bbs.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_test.go
I faced this problem during BBS+ interop testing with Mattr. They generate VCs which have the following type definition:
```
"type": [
"PermanentResidentCard",
"VerifiableCredential"
]
```
Current JSON schema check of VC rejects this (as it expects `VerifiableCredential` be the first element of the list) what is not mandatory according to https://www.w3.org/TR/vc-data-model/#types.
closes #2387
> fix: correct check of "type" field of VC and VP

- pkg/doc/presexch/api.go
Defines `Presentation Submission` fields according to spec. See https://identity.foundation/presentation-exchange/#presentation-submission
> feat: Defines Presentation Submission fields according to spec

- pkg/controller/rest/vdr/operation.go
**Title:**
Change VDS endpoint order to support records endpoint correctly (/vdr/did/records)
Previous order of VDS endpoints treated `/vdr/did/records` endpoint as `/vdr/did/{id}`, so the result of `GET /vdr/did/records` was `{"code":4000,"message":"invalid id"}`. 
The solution is simply moving `/vdr/did/{id}` endpoint under `/vdr/did/records`, to change priority of request handling.
**Summary:**
I just changed the order of endpoints
> Fix - change vds endpoint order to support records endpoint correctly

- pkg/doc/jose/encrypt_test.go
- pkg/doc/jose/encrypter.go
> refactor: remove redundant kid from recipient's EPK  json in JWE

- pkg/doc/presexch/definition.go
- pkg/doc/presexch/definition_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_bbs.go
- pkg/doc/verifiable/credential_bbs_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/example_credential_test.go
- test/bdd/features/issue_credential.feature
BBS+ selective disclosure extended examples with a more constrained set of claims in the derived credential.
Another changes/fixes:
- verify VC structure at `verifiable.ParseUnverifiableCredential`. Use case: find that BBS+ reveal doc missing mandatory fields like `issuer`.
closes #2410
> test: BBS+ selective disclosure extended examples

- pkg/doc/presexch/README.md
- pkg/doc/presexch/api_test.go
- pkg/doc/presexch/definition.go
- pkg/doc/presexch/definition_test.go
- pkg/doc/presexch/example_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
Adds Presentation Exchange samples.
> docs: Presentation Exchange - adds samples

- pkg/newstorage/newstorage.go
This was supposed to be exported all along.
> fix: Export PageSize in QueryOptions

- cmd/aries-agent-mobile/go.sum
- cmd/aries-agent-rest/go.sum
- cmd/aries-js-worker/go.sum
- component/storage/jsindexeddb/go.sum
- component/storage/leveldb/go.sum
- go.mod
- go.sum
- pkg/doc/signature/suite/bbsblssignature2020/suite.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/signer_test.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/suite.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/suite_test.go
- pkg/doc/verifiable/credential_bbs_test.go
- pkg/doc/verifiable/example_credential_test.go
- test/bdd/go.sum
When creating BBS+ selective disclosure, only BBS+ Signatures converted to BBS+ Signature proofs are left in the result document (e.g. VC). Other signatures are removed as otherwise, their check would fail because of test data mismatch on the verification stage.
Also, we now produce selective disclosure for all present BBS+ Signatures (before we did this for the very first one found in the `proof` list).
closes #2440
> fix: Leave BBS+ Selective Disclosure proofs only

- pkg/controller/controller_test.go
- pkg/controller/webnotifier/webhook_test.go
Fixes unit tests error (bind: address already in use)
> fix: Unit tests error (bind: address already in use)

- pkg/crypto/tinkcrypto/crypto.go
- pkg/crypto/tinkcrypto/key_wrapper.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/subtle/ecdh_aes_aead_composite_test.go
- pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export.go
- pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export_import_test.go
This change includes eporting the public key from ECDH Tink key templates
based on the key type and curve
closes #1806
closes #1637
> feat: X25519 ECDH export pub key

- pkg/doc/signature/jsonld/processor.go
- pkg/doc/signature/jsonld/processor_test.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go
- pkg/doc/verifiable/example_credential_test.go
When the input VC document has the same `id` of two fields, output BBS+ Signature Proof of VC (selective disclosure) may contain invalid substituted fields.
The issue is filed in json-gold library ([link](https://github.com/piprate/json-gold/issues/44)). It works properly at JSON-LD playground ([link](https://tinyurl.com/y3ypdrcj)). So current PR provides a workaround solution - to replace duplicated IDs with generated unique IDs before JSON-LD framing and then replacing IDs back.
closes #2460
> fix: BBS+ Selective Disclosure output fields mix

- pkg/kms/localkms/localkms.go
This change allows a local KMS instance to be created with a prefixed store namespace
closes #2435
> feat: support KMS with prefixed store namespace

- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
- pkg/doc/util/jwkkid/kid_creator.go
This fixes a problem when using Flattened serialization of a JWE (using a single recipient).
Decryption fails when AAD is not empty because the authentication data is not properly 
rebuilt when calling Decrypt().
This change also increases unit-test cases to cover Full (with AAD), Flattened (with AAD) and Compact(no AAD) serializations.
Closes #2496
> fix: single recipient JWE with AAD decrypt error

- component/newstorage/go.mod
While you could technically still import the module, the incorrect format was causing it to not be read correctly, so it would get listed as "indirect" when being imported.
> fix: Incorrectly formatted new storage interface go module file

- component/newstorage/batchedstore/go.mod
- component/newstorage/batchedstore/go.sum
- component/newstorage/formattedstore/go.mod
- component/newstorage/formattedstore/go.sum
- Use proper revision for mock store module imports.
- Also removed replace directives.
These changes are needed to make the mock storage implementation properly importable.
> chore: Use proper revision for mock store module imports

- component/newstorage/batchedstore/go.mod
- component/newstorage/batchedstore/go.sum
- Use proper revision for formatted store module imports.
- Also removed replace directives.
These changes are needed to make modules that imported formatted store properly importable.
> chore: Use proper revision for formatted store module imports

- spi/go.mod
- spi/storage/storage.go
Creates a Service Provider Interface (SPI) as a module.
- Copies the interface from newstorage.
- In a followup: remove the interface from newstorage.
> feat: create initial spi module

- cmd/aries-js-worker/go.sum
- pkg/client/didexchange/client.go
- pkg/client/messaging/client.go
- pkg/client/messaging/client_test.go
- pkg/client/outofband/client.go
- pkg/controller/command/messaging/command_test.go
- pkg/controller/rest/messaging/operation_test.go
- pkg/didcomm/common/service/destination_test.go
- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/packager/package_test.go
- pkg/didcomm/packager/packager.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/mediator/service.go
- pkg/didcomm/protocol/mediator/service_test.go
- pkg/didcomm/transport/ws/pool.go
- pkg/didcomm/transport/ws/pool_test.go
- pkg/doc/did/doc.go
- pkg/doc/did/helpers.go
- pkg/doc/did/helpers_test.go
- pkg/framework/aries/framework_test.go
- pkg/mock/diddoc/mock_diddoc.go
- pkg/store/did/didconnection_test.go
- pkg/vdr/fingerprint/fingerprint.go
- pkg/vdr/peer/creator.go
- pkg/vdr/peer/creator_test.go
- test/bdd/pkg/messaging/messaging_steps.go
- test/bdd/pkg/sidetree/sidetree.go
Add support for [RFC0360](https://github.com/hyperledger/aries-rfcs/blob/master/features/0360-use-did-key/README.md) for interop.
Fixed:
* out-of-band invitations
* did-exchange invitations and signature computation
* mediator-coordination
* DIDComm service types when creating did:peer
* dispatchers and transports (converting b/w did:key and raw pub key bytes)
> feat: RFC0360 use-did-key

- pkg/kms/webkms/remotekms.go
- pkg/kms/webkms/remotekms_test.go
- test/bdd/fixtures/agent-rest/.env
This PR updates `CreateAndExportPubKeyBytes` in remotekms to use a single call to the remote KMS service. It was done mainly because of performance considerations.
> refactor: CreateAndExportPubKeyBytes in remotekms

- pkg/crypto/tinkcrypto/key_wrapper.go
- pkg/didcomm/packer/anoncrypt/pack.go
- pkg/didcomm/packer/anoncrypt/pack_test.go
- pkg/didcomm/packer/authcrypt/pack.go
- pkg/didcomm/packer/authcrypt/pack_test.go
- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypt_test.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
- pkg/doc/jose/jwe.go
- pkg/doc/jose/jwe_test.go
This changes adds JWE integrity checks to help verify the recipients and/or the sender.
It also fixes the encrypter's AEAD's AAD content for single recipient envelopes where it used to contain
only the two main JWE Protected headers (enc and typ). It now includes the single recipient's
merged headers into the protected header (ie: epk, apu, apv, typ, enc, kid and alg).
closes #2513
> feat: add integrity headers in JWE/DIDComm

- component/storageutil/cachedstore/cachedstore.go
- component/storageutil/cachedstore/cachedstore_test.go
- component/storageutil/formattedstore/formattedstore.go
- component/storageutil/formattedstore/formattedstore_test.go
- component/storageutil/go.mod
- component/storageutil/go.sum
- Added a new "wrapper" store provider that allows for automatic caching of data.
- Removed caching option from FormatedProvider since the functionality is now redundant, since a CachedProvider can wrap a FormatProvider.
closes #2479
> feat: Cached provider

- test/component/storage/storage.go
Updated common storage tests to accommodate implementations that require setting a store configuration before storing tags.
> fix: Update common storage tests to accommodate more implementations

- pkg/client/didexchange/client_test.go
- pkg/controller/command/didexchange/command_test.go
- pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go
- pkg/doc/util/jwkkid/kid_creator.go
- pkg/doc/util/jwkkid/kid_creator_test.go
- pkg/kms/localkms/kid_creator_test.go
- test/bdd/features/didexchange_e2e_sdk.feature
This change fixes go-jose's Ed25519 JWK Thumbprint value used in the KMS KID creation.
It also includes a check for emptiness of the key bytes with calling CreateKID() and
fixed related unit tests in the framework.
Finally the webkms bdd tests are commented out since the remote kms server requires
an udpate. They will be uncommented in a future revision when the server image tag
is updated with a revision of aries-framework-go that contains this change.
closes #2530
> fix: wrong Ed25519 KID value

- component/storage/edv/go.mod
- component/storage/edv/go.sum
- component/storage/indexeddb/go.mod
- component/storage/indexeddb/go.sum
- component/storage/indexeddb/indexeddb.go
- component/storageutil/go.mod
- component/storageutil/go.sum
- Fixed an issue where doing a query on a store with no values in it would result in an error instead of returning an iterator with no results (which is the expected behaviour).
- Fixed an issue where querying a store after deleting a key could still return those deleted keys since the tag map was not being updated on key deletion.
- Added comment above the IndexedDB SetStoreConfig method to make it clear that a store configuration must be set in order to make use of the Query method.
- Improved error message in cases where someone tries to store tags or do a query without a store configuration set.
- Updated common storage tests version, which includes new tests to check for the cases above.
> fix: IndexedDB query issues

- pkg/doc/did/doc.go
- pkg/doc/jsonld/jsonld.go
- pkg/doc/jsonld/jsonld_test.go
- pkg/doc/signature/jsonld/processor.go
- pkg/doc/signature/jsonld/processor_test.go
- pkg/doc/signature/suite/bbsblssignature2020/support_test.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/support_test.go
- pkg/doc/verifiable/credential_extension_switch_test.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/example_presentation_test.go
- pkg/doc/verifiable/jsonld.go
- pkg/doc/verifiable/jsonld_test.go
- pkg/doc/verifiable/linked_data_proof_test.go
- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_test.go
- pkg/doc/verifiable/support_test.go
- pkg/doc/verifiable/testdata/context/context1.jsonld
- pkg/doc/verifiable/testdata/context/context2.jsonld
- pkg/doc/verifiable/testdata/context/context3.jsonld
- pkg/doc/verifiable/testdata/context/context4.jsonld
- pkg/doc/verifiable/testdata/context/context5.jsonld
- pkg/doc/verifiable/testdata/context/context6.jsonld
- test/bbs/src/support_jsonld_loader.go
- test/bdd/pkg/verifiable/verifiable_steps.go
- SetCredentials is also modified to require a parsed credential object or a compact JWS. A followup PR will move the compact JWS detection into the credential object.
- A common jsonld utility package is created. A followup PR will change the default behavior to use a document loader without remote loading in the framework.
> chore: remove remote context loading from verifiable tests

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/client/vcwallet/kmsclient.go
- pkg/client/vcwallet/kmsclient_test.go
- pkg/client/vcwallet/profile.go
- pkg/client/vcwallet/profile_test.go
VC wallet client can be initialized with following key manager options.
`passphrase` : if client chooses to use passphrase for localkms.
`secret lock service`: if client chooses to use its own secret lock service.
`keyServerURL`: if client chooses to user remotekms (webkms).
**wallet.Open() :** accepts one of the below params to instantiate key
manager client and unlock wallet for use.
`auth token`: auth token to be part of header for remote kms calls
to key server.
`passphrase` : if client chooses to use passphrase for localkms.
secret lock service: if client chooses to use its own secret lock
service.
`expiration`: time duration for which token has to be active
**wallet.Close()**: expires token and removes key manager client instance.
Signed-off-by: sudesh.shetty …
> feat: VC wallet client - KMS client &  open/close

- pkg/doc/util/jwkkid/kid_creator.go
- pkg/doc/util/jwkkid/kid_creator_test.go
- pkg/kms/api.go
- pkg/kms/localkms/localkms.go
- pkg/kms/localkms/localkms_test.go
- pkg/kms/localkms/privkey_import.go
- pkg/kms/localkms/pubkey_export_import_test.go
- pkg/kms/localkms/pubkey_reader.go
- pkg/kms/localkms/pubkey_writer.go
This change also adds new kms type for BBS+ keys.
closes #2549
> feat:KMS support for BBS+ keys: support Public key export, Private Key Import

- pkg/vdr/fingerprint/fingerprint.go
- pkg/vdr/fingerprint/fingerprint_test.go
- pkg/vdr/key/creator.go
- pkg/vdr/key/resolver.go
- pkg/vdr/key/resolver_test.go
> refactor: make fingerprint function generic to return multicodec code

- test/component/storage/storage.go
Fixes an issue where one of the common storage tests would result in the wrong path being tested for storage implementations that require setting a store config before doing a query.
> test: fix for common storage query test

- pkg/vdr/key/creator.go
- pkg/vdr/key/creator_test.go
- pkg/vdr/key/resolver.go
- pkg/vdr/key/resolver_test.go
This adds bbs to the resolver. Followups are needed for other
key types and to create a did:key for bbs.
> feat: add bbs to did:key resolver

- pkg/doc/signature/verifier/public_key_verifier.go
- pkg/doc/signature/verifier/public_key_verifier_test.go
- detects and transforms from empty nodes
- needs followup for signing operation to transform to empty nodes #2585
> fix: bbs empty node transformation during verify

- component/storage/indexeddb/indexeddb.go
- component/storage/indexeddb/indexeddb_test.go
- The IndexedDB provider now creates a tag map when opening a store, so it no longer requires a call to SetStoreConfig to use tags + querying (it never really needed to in the first place).
- Removed some redundant unit tests.
> feat: IndexedDB provider - create tag map on store open

- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_key_template_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_nistpkw_private_key_manager.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_x25519kw_private_key_manager.go
before this change, creating new keyset.Handle for Primitive execution key took (on MacOS):
=== RUN   TestECDHESKeyTemplateSuccess/Test_create_ECDH_NIST_P-256_KW_with_AES256-GCM_key_templates_test
ecdh_key_template_test.go:76: time spent in ECDH keyTemplateWithCEK: 5.425µs
ecdh_key_template_test.go:81: time spent in ECDH keyTemplateWithCEK + NewHandle(): 7.15322ms
=== RUN   TestECDHESKeyTemplateSuccess/Test_create_ECDH_NIST_P-384_KW_AES256-GCM_key_templates_test
ecdh_key_template_test.go:76: time spent in ECDH keyTemplateWithCEK: 4.686µs
ecdh_key_template_test.go:81: time spent in ECDH keyTemplateWithCEK + NewHandle(): 5.828677ms
=== RUN   TestECDHESKeyTemplateSuccess/Test_create_ECDH_NIST_P-521_KW_AES256-GCM_key_templates_test
ecdh_key_template_test.go:76: time spent in ECDH …
> perf: boost ECDH key creation for Primitive execution

- pkg/controller/command/verifiable/command.go
> fix: typo in derive credential controller

- pkg/client/presentproof/client.go
- pkg/client/presentproof/client_test.go
- pkg/client/presentproof/example_test.go
- pkg/controller/command/presentproof/command.go
- pkg/didcomm/protocol/middleware/presentproof/middlewares.go
- pkg/didcomm/protocol/middleware/presentproof/middlewares_test.go
- pkg/didcomm/protocol/presentproof/middleware.go
- pkg/didcomm/protocol/presentproof/service.go
- pkg/didcomm/protocol/presentproof/service_test.go
- pkg/framework/aries/default.go
- pkg/internal/gomocks/didcomm/protocol/middleware/presentproof/mocks.go
- test/bdd/features/presentproof.feature
- test/bdd/pkg/presentproof/presentproof_sdk_steps.go
By default, we will sign the presentation with `BbsBlsSignature2020` (if a signature is needed). Also, it can be changed by providing an option e.g `WithAddProofFn`. 
> feat: Present proof - signs the presentation

- pkg/doc/util/jwkkid/kid_creator.go
- pkg/vdr/fingerprint/fingerprint.go
- pkg/vdr/fingerprint/fingerprint_test.go
- pkg/vdr/key/creator.go
- pkg/vdr/key/creator_test.go
- pkg/vdr/key/resolver.go
- pkg/vdr/key/resolver_test.go
- pkg/vdr/key/vdr.go
This change introduces NIST P ECDSA and BBS did:key creation
And did:key resolution for ECDSA keys.
closes #2319
> feat: add BBS and NISTP did key creation

- test/aries-js-worker/fixtures/docker-compose.yml
The error  `rm: cannot remove 'test/aries-js-worker/keys/tls': Permission denied` was related to the docker.
Due to folder (`tls`) absence when we mount a volume the `tls` folder was created automatically by docker. It was the root cause of `Permission denied` error. 
> chore: Fixes permission denied (linux)

- pkg/doc/presexch/api.go
- pkg/doc/presexch/api_test.go
- pkg/doc/presexch/example_test.go
Generalized credential parsing options, hence enabling a user to specify a public key fetcher. Used in downstream projects (eg. [rp adapter](https://github.com/trustbloc/edge-adapter/blob/6587a7111ada6bd16386bbcd9d97806d6cfb373a/pkg/restapi/rp/operation/credentials.go#L38)).
> feat: presexch - parse VCs with proofs

- component/storage/indexeddb/indexeddb.go
- spi/storage/storage.go
- test/component/storage/storage.go
- Also added common storage tests for storage of binary data and ensuring store names are case-insensitive.
- Clarified comments on some storage interface methods.
> fix: IndexedDB storage not storing/retrieving binary data correctly

- spi/storage/storage.go
Fixes a minor issue with the Close helper method where it had inconsistent log messages depending on whether you passed in a custom logger or not.
> fix: Inconsistent iterator close log message

- component/storage/indexeddb/indexeddb.go
- spi/storage/storage.go
- test/component/storage/storage.go
- Updated interface comments on tags to explicitly state that tags cannot contain ':' characters due to a conflict with the query syntax.
- Added unit tests to check for this and ensure an error is thrown when this occurs.
- Added other various unit tests and improved some existing ones.
- Updated IndexedDB implementation to ensure that tags don't contain ':' characters. There's a go mod replace directive that causes the latest unit test code to always be run, so the IndexedDB implementation had to be fixed in this commit.
> test: Added additional common storage unit tests

- pkg/controller/rest/vdr/operation.go
**Title:**
Fixed the part where the swagger api and the rest controller api did not match.
The rest controller REST API is '/vdr/did/create', whereas the swagger API is '/vdr/create', so the swagger API is changed to '/vdr/did/create'.
**Summary:**
Change the swagger API in vdr rest controller. ('/vdr/create' -> '/vdr/did/create')
> Fixed the swagger API comment.

- component/storageutil/batchedstore/batchedstore_test.go
- component/storageutil/formattedstore/exampleformatters/base64formatter.go
- component/storageutil/formattedstore/exampleformatters/noopformatter.go
- component/storageutil/formattedstore/formattedstore.go
- component/storageutil/formattedstore/formattedstore_test.go
- component/storageutil/go.mod
- component/storageutil/go.sum
This change allows the formatted storage provider to support a formatter that generates formatted keys in a non-deterministic manner. This is to support the EDV encrypted formatter which, in a commit in the near future, will support random encrypted document IDs.
> feat: Formatted storage provider support for non-deterministic keys

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/wallet/contents.go
- pkg/wallet/contents_test.go
- pkg/wallet/kmsclient.go
- pkg/wallet/kmsclient_test.go
- pkg/wallet/models.go
- pkg/wallet/profile.go
- pkg/wallet/profile_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- all common internal source inside `pkg/client/vcwallet` moved to
`pkg/wallet`. This new package will be reused by upcoming command
controllers.
- `vcwallet.New()` to unlock wallet during instantiation, where existing
instances of same wallet will be locked.
- some refactoring for SDK binding for better client experience.
> feat: new common wallet package

- component/storageutil/formattedstore/formattedstore.go
- component/storageutil/formattedstore/formattedstore_test.go
- component/storageutil/go.mod
- component/storageutil/go.sum
- Updated common storage test module commit tags. The updated common storage tests include tests to ensure this bug is fixed.
- Also did some minor refactoring to reduce code duplication.
> fix: Formatted storage provider batch method fails in some cases

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- added prove interface based on universal wallet prove interface
(https://w3c-ccg.github.io/universal-wallet-interop-spec/#prove).
- support for both stored and raw credential arguments.
- Closes #2680
> feat: vc wallet prove interface

- pkg/client/vcwallet/client_test.go
- pkg/wallet/contents.go
- pkg/wallet/contents_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- wallet user specific VDR which goes through user saved DIDs first
before going through VDR provider.
- duplicate content error (to avoid accidental replace of wallet contents)
- use uuid if JSON LD data model id is missing.
- validate DID resolution data models while saving instead of during
signing.
- Closes #2698
> feat: VC wallet - wallet content based VDR

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/wallet/contents.go
- pkg/wallet/contents_test.go
- pkg/wallet/kmsclient.go
- pkg/wallet/kmsclient_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- Support for key Data model from
https://w3c-ccg.github.io/universal-wallet-interop-spec/#Key
- Wallet will never save key data model in content store, instead it will extract and import private key into user profile kms.
- For base58 import, support for Ed25519VerificationKey2018 &
Bls12381G1Key2020
- For jwk import, support for Curves - Ed25519, P-256, P-384,
BLS12381G2
- KID logic: for jwk, `jwk.kid` will be used (fallback to key document
`id` fragment)
- KID logic: for base58, key document `id` fragment
- added key, did, vc data model based issue/prove tests in client tests
- closes #2707
TODO: BLS12381G2 private key jwk support
> feat: VC wallet - support for key model

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/doc/presexch/definition.go
- pkg/wallet/contents.go
- pkg/wallet/models.go
- pkg/wallet/query.go
- pkg/wallet/query_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- Support for QueryByFrame & QueryByExample credential queries.
- Support for mixed and multiple query support
inline with universal wallet query, vp-request-spec credential queries.
TODO: Adding proof to result & DID Auth support
Closes #2717
> feat: VC Wallet - QueryByFrame & QueryByExample

- pkg/client/outofband/client.go
- pkg/client/outofband/client_test.go
- pkg/controller/command/outofband/command_test.go
- pkg/crypto/primitive/bbs12381g2pub/internal/kilic/bls12-381/swu_custom.go
- pkg/didcomm/protocol/outofband/models.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/signer_test.go
Push 1:
- accept old and new outofband message format
- did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/out-of-band/1.0/invitation is accepted as an old invitation message type
Push 2:
- Currently `afgo` used to only look for a `service` field in the invitation message, but `acapy` sends `services` instead of `service`. Added that to the OOB Invitation struct to support parsing `services` and choose a target accordingly.
- Solves #2675 
Signed-off-by: Haardik Haardik haardik.haardik@securekey.com
> fix: fixes for outofband interop with acapy

- pkg/controller/rest/verifiable/models.go
- pkg/controller/rest/verifiable/operation.go
Title:
update openapi spec for verifiable presentation
Summary:
add rest API '/verifiable/presentation/generatebyid' into swagger openapi spec.
> fix: update openapi spec for verifiable presentation

- pkg/controller/command/verifiable/command.go
- pkg/controller/command/verifiable/command_test.go
**Title:**
Improve the order of resolving DID document when signing a VC or generating a VP.
If caches DID, local storage be looked first.
**Summary:**
Before modifying, when signing a VC or generating a VP, looked at the VDR Registry first to get the DID document, and if it's not there, looked at local storage. It can affect performance.
So, I modified that when getting the DID document, looked at the local storage first, and if it's not there, looked at VDR Registry.
+Incorrect error codes and messages have been additionally supplemented.
> Improve the order of resolving DID document when signing a VC or generating a VP.

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/mock/storage/mock_store.go
- pkg/wallet/contents.go
- pkg/wallet/contents_test.go
- pkg/wallet/options.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- added collection data model data mapping to VC wallet
- all wallet contents can be mapped to an existing collection in wallet
content store
- fixed issue in getAll which exposes db key prefix in list of wallet
contents
- Closes #2741
> feat: collections data model & content mapping

- component/storage/leveldb/leveldb.go
- component/storage/leveldb/leveldb_test.go
Implemented the LevelDB storage provider's GetOpenStores, GetBulk, and Batch methods. The GetBulk and Batch implementations are basic/naive ones for now. In a future PR they will be improved upon.
> feat: Naive implementation of additional LevelDB storage methods

- pkg/client/outofband/client.go
- pkg/didcomm/common/service/destination.go
- pkg/didcomm/common/service/messenger.go
- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/packager/package_test.go
- pkg/didcomm/packager/packager.go
- pkg/didcomm/packer/anoncrypt/pack.go
- pkg/didcomm/packer/anoncrypt/pack_test.go
- pkg/didcomm/packer/authcrypt/pack.go
- pkg/didcomm/packer/authcrypt/pack_test.go
- pkg/didcomm/packer/legacy/authcrypt/unpack.go
- pkg/didcomm/protocol/didexchange/models.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/protocol/outofband/service.go
- pkg/didcomm/protocol/outofband/service_test.go
- pkg/didcomm/transport/media_type.go
- pkg/didcomm/transport/transport_interface.go
- pkg/framework/aries/framework.go
- pkg/framework/context/context.go
- pkg/store/connection/connection_lookup.go
- pkg/store/connection/connection_lookup_test.go
- pkg/store/connection/connection_recorder_test.go
This PR makes the outbound dispatcher fetch the receiving agent's supported media types from the existing connection record.
Other changes:
* Renamed "MediaTypes" -> "MediaTypeProfiles"
* the framework was falling back to the envelope media type in the inbound didexchange `request` message if the did doc embedded in the message did not contain an `accept` property. This behaviour has been removed. The media type profile is solely determined by either a) the OOB invitation (has precedence), or b) the `service` block's `accept` property
> fix: media types not fetched from connection when initiating protocol

- Makefile
- pkg/client/messaging/client_test.go
- pkg/didcomm/protocol/decorator/decorator.go
- pkg/didcomm/protocol/decorator/decorator_default.go
- pkg/didcomm/protocol/decorator/decorator_interop.go
- pkg/didcomm/protocol/decorator/decorator_private_test.go
- pkg/didcomm/protocol/decorator/decorator_test.go
- pkg/didcomm/protocol/didexchange/didex_default.go
- pkg/didcomm/protocol/didexchange/didex_interop.go
- pkg/didcomm/protocol/didexchange/models.go
- pkg/didcomm/protocol/didexchange/service.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/did/serialize_default.go
- pkg/doc/did/serialize_interop.go
- pkg/doc/jose/jwk.go
- pkg/doc/jose/jwk_test.go
Part of #2495:
- DID exchange `completed` state
- Attachment signatures: Sign/Verify methods for attachment decorators
that use base64 payloads.
- Additional fixes that are locked behind a build flag.
The build flag `interop` enables "breaking" interop fixes - fixes
for interop that break compliance with specs/RFCs, and are
temporary workarounds to allow for interop testing before
interop partners fully update their implementations.
The fixes behind the flag are:
- Accept did:sov did doc in didexchange request, and store it like
a peer did
- Generate a did:sov did doc as a peer did for didexchange response
- DID Doc method to serialize into a non-spec-compliant 'hybrid' format
when attaching it to a didexchange message.
> feat: didexchange interop with aca-py, with afgo as responder

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/mock/storage/mock_store.go
- pkg/wallet/contents.go
- pkg/wallet/contents_test.go
- pkg/wallet/kmsclient.go
- pkg/wallet/options.go
- pkg/wallet/profile.go
- pkg/wallet/profile_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- for upcoming EDV integration, wallet interfaces expectes auth token
for accessing wallet contents too.
- `storage.openStore()` occurs during `wallet.Open()` and `store.cloe()`
occurs during `wallet.Close()`
- wallet open will unlock key manager and open database.
- wallet close will remove keyemaner and close database.
- all wallet interfaces now requires auth token.
- wallet content based VDR will expect auth token.
- Closes #2745
> feat: auth based access wallet store

- pkg/client/vcwallet/client_test.go
- pkg/didcomm/protocol/middleware/presentproof/middlewares_test.go
- pkg/doc/presexch/api.go
- pkg/doc/presexch/api_test.go
- pkg/doc/presexch/definition.go
- pkg/doc/presexch/definition_test.go
- pkg/doc/presexch/example_test.go
- pkg/wallet/query_test.go
- pkg/wallet/wallet_test.go
- test/aries-js-worker/test/presentproof/presentproof.js
- test/bdd/pkg/presentproof/presentproof_sdk_steps.go
- test/bdd/pkg/presentproof/testdata/request_presentation_bbs.json
The `schema.uri` in presentation definitions should be the full URI to the type's definition (jsonschema or jsonld), not just the context. [Reference](https://github.com/decentralized-identity/presentation-exchange/issues/134#issuecomment-721624167).
TODO - #2756 
> fix: presentation-exchange schema.uri matching

- pkg/wallet/contents.go
- pkg/wallet/contents_test.go
- pkg/wallet/kmsclient.go
- pkg/wallet/options.go
- pkg/wallet/storage.go
- pkg/wallet/storage_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- added more unlock wallet options to use all aries webkms & EDV
customization opts.
- can be used to pass auth & authz based http headers for EDV & web kms
- closes #2763
> feat: wallet open options for webkms & EDV

- pkg/crypto/tinkcrypto/key_wrapper.go
- pkg/crypto/tinkcrypto/testdata/alice_epk_ref.json
- pkg/crypto/tinkcrypto/testdata/alice_key_ref.json
- pkg/crypto/tinkcrypto/testdata/bob_key_ref.json
- pkg/crypto/tinkcrypto/testdata/ecdh_1pu.json
- pkg/crypto/tinkcrypto/testdata/recipient_ref.json
- pkg/crypto/tinkcrypto/wrap_support.go
- pkg/crypto/tinkcrypto/wrap_support_test.go
- pkg/internal/cryptoutil/utils.go
- pkg/internal/cryptoutil/utils_test.go
and add ECDH-1PU test against the draft's test vector
closes #2766
> fix: ECDH-1PU key derivation logic

- pkg/controller/command/errors.go
- pkg/mock/kms/mock_kms.go
- pkg/wallet/contents_test.go
- pkg/wallet/profile.go
- pkg/wallet/profile_test.go
- pkg/wallet/storage.go
- pkg/wallet/storage_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
-EDV encryption & MAC key IDs cannot be passed as profile settings for
localkms users since wallet creates local kms internally based on user's
secret lock service. So wallet has to expose an API to generate EDV keys
in wallet kms.
- Closes #2768
> feat: apis to create keys in wallet kms

- pkg/controller/command/verifiable/command.go
**Title:**
Add PublicKeyFetcher for validating the verifiable credential.
#1316
**Summary:**
Previously, since there was no PulicKeyFetcher, there was no way to separately validate a Validate Credential, but it can be verified by adding PublicKeyFetcher.
> Re: Add public key fetcher for validating the verifiable credential.

- docs/encrypted_storage.md
> fix: Remove old text from encrypted storage documentation

- pkg/doc/jose/jwk.go
- pkg/doc/jose/jwk_test.go
Updated as per https://w3c-ccg.github.io/ldp-bbs2020/#example-4-jwk-encoded-bls12-381-g2-key
> fix: BBS+ JWK values of crv and kty

- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/aries.js
- pkg/controller/command/jsonld/context/command.go
- pkg/controller/command/jsonld/context/command_test.go
- pkg/controller/rest/jsonld/context/operation.go
- pkg/doc/jsonld/document_loader.go
- test/aries-js-worker/test/contexts.js
- test/aries-js-worker/test/issuecredential/issuecredential.js
- test/aries-js-worker/test/jsonld/context/jsonld_context.js
- test/aries-js-worker/test/presentproof/presentproof.js
* added BDD tests for js context API bindings
* removed `jsonld` section from URL path for adding context
* switched to `json.RawMessage` for `Content` field in `ContextDocument` type
> test: BDD tests for context API js bindings

- pkg/crypto/tinkcrypto/crypto.go
- pkg/crypto/tinkcrypto/crypto_test.go
- pkg/crypto/tinkcrypto/primitive/aead/aead_key_templates.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_key_template.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_key_template_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_nistpkw_private_key_manager_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_nistpkw_public_key_manager_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_x25519kw_private_key_manager_test.go
- pkg/crypto/tinkcrypto/primitive/composite/ecdh/ecdh_x25519kw_public_key_manager_test.go
- pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export.go
- pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export_import_test.go
- pkg/crypto/tinkcrypto/primitive/composite/register_ecdh_aead_enc_helper.go
- pkg/crypto/tinkcrypto/primitive/composite/register_ecdh_aead_enc_helper_test.go
- pkg/crypto/webkms/remotecrypto_test.go
- pkg/doc/jose/common.go
- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypt_test.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
And also support converting an EC public key into an ECDH Tink key using CBC+HMAC AEAD.
closes #2832
> feat: use CBC+HMAC in ECDH Tink key and Crypto service

- pkg/crypto/tinkcrypto/primitive/aead/subtle/aes_cbc_test.go
- pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export.go
- pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export_import_test.go
- pkg/crypto/tinkcrypto/primitive/composite/register_ecdh_aead_enc_helper.go
- pkg/didcomm/packer/anoncrypt/pack.go
- pkg/didcomm/packer/authcrypt/pack.go
- pkg/doc/jose/decrypter.go
- pkg/doc/jose/encrypt_test.go
- pkg/doc/jose/encrypter.go
- pkg/doc/jose/encrypter_decrypter_test.go
This change enables the commented out test for full compatibility with ECDH-1PU draft4 Appendix B example.
It also includes the following changes:
* fixes CBC+HMAC keys extracted from the ECDH cek. The keys were inversed.
* moved recipients' kids list from AAD to APV (recipients) protectedHeader
* use originalProtectedHeaders if populated instead of protectedHeader when building authData. To avoid marshal/unmarshal calls from changing the json order.
* ECDH-1PU messages with multi-recipients can now read the sender kid (skid) from APU if skid wass empty since it's an optional header.
closes #2850
> feat: enable ecdh-1pu draft4 JWE decryption test

- component/storage/indexeddb/indexeddb.go
- component/storage/leveldb/leveldb.go
Fixes a race condition in the IndexedDB and LevelDB storage providers that causes tags to be lost when storing data in parallel.
> fix: Race condition in IndexedDB and LevelDB storage providers

- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/packager/packager.go
- pkg/didcomm/packager/packager_test.go
- pkg/didcomm/packer/anoncrypt/pack.go
- pkg/didcomm/packer/api.go
- pkg/didcomm/packer/authcrypt/pack.go
- pkg/didcomm/transport/media_type.go
- pkg/framework/aries/default.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/framework/context/context.go
- pkg/framework/context/context_test.go
This change sets the media type priority based on the destination according to Aries RFCs 19, 44 and 587.
It sets the JWE message's CTY header based on the received media type.
It also updates the default authcrypt packing sender key type to be AES256CBCHS512.
closes #1112 (packer is selected based on mediaTypeProfile)
closes #272 (key type is managed by the kms)
closes #749 (diffrent keys are supported by the packers, except LegacyPacker that supports ED25519 keys only)
closes #2858 (SendToDID now can be used without a DID connection, as it was before)
> feat: support packer selection based on destination MediaType

- pkg/didcomm/protocol/didexchange/states.go
> fix: typo fix in didexchange interop did doc attachment signing

- .github/dependabot.yml
- the other gomod in the repo need to be updated in sync.
> chore: disable dependabot PRs on gomod

- pkg/doc/presexch/definition.go
Also include context needed for test harness tests.
> fix: presexch shouldn't use only the final schema match when checking for schema match

- pkg/didcomm/protocol/issuecredential/properties.go
- pkg/didcomm/protocol/presentproof/properties.go
Populates a fresh, local map instead of editing a map that's shared
across threads.
Fixes #2417
> fix: avoid a data race in eventprops.All()

- spi/storage/storage.go
Updated documentation to specify what happens in certain cases:
Batch: If the operations slice is empty or nil, an error is returned.
Close: It can be called repeatedly on the same store multiple times without causing an error.
> docs: Update storage interface documentation

- cmd/aries-agent-mobile/go.mod
- cmd/aries-agent-rest/go.mod
- cmd/aries-js-worker/go.mod
- component/storage/indexeddb/indexeddb.go
- component/storageutil/mem/mem.go
- test/bdd/go.mod
- test/component/go.mod
- test/component/go.sum
- test/component/storage/storage.go
- Added new tests to ensure correct behaviour for the Store.Batch and Store.Close methods per the recently updated interface documentation.
- Added close calls for all of the stores that get created in the tests. This is important for storage implementations that maintain connections to databases. By closing these stores after each test, those implementations should be able to safely call TestAll without exhausting the connection limit and causing test failures.
- Updated storage implementations (as needed) to pass the new tests.
> test: Updates and improvements to storage test suite

- pkg/mock/storage/mock_store.go
- pkg/store/ld/context_store.go
- pkg/store/ld/context_store_test.go
- spi/storage/storage.go
- Clarified expected behaviour of storage interface implementations
- Added missing call to Provider.SetStoreConfig for the context store.
- Removed the workaround for MySQL, which is no longer needed.
> docs: Updates to storage interface documentation

- cmd/aries-agent-mobile/go.mod
- cmd/aries-agent-rest/go.mod
- cmd/aries-agent-rest/go.sum
- cmd/aries-js-worker/go.mod
- cmd/aries-js-worker/go.sum
- test/bdd/go.mod
- test/component/go.mod
- test/component/go.sum
- test/component/storage/storage.go
- Updated common storage tests to check and make sure that stores can query without requiring a store configuration (indexes). The interface says that indexes are recommended for large stores, but it doesn't say that they're always required, so storage providers should ensure that they can function without them.
> test: Added tests to ensure that store config is optional for queries

- cmd/aries-js-worker/go.mod
- cmd/aries-js-worker/go.sum
- test/component/storage/storage.go
- Added new storage tests to ensure that SetStoreConfig and GetStoreConfig are also case-insensitive with respect to the store name.
- Added an option to skip all query sorting tests, along with a parameter for only skipping query sorting tests that don't set a store configuration. This is needed for testing storage providers that don't support sorts on queries (or that can only do it when a store configuration is set).
- Reworked the Iterator TotalItems tests option to be an opt-out rather than an opt-in for consistency with the new option mentioned above. This option is now called SkipIteratorTotalItemTests as a result.
- With that newly reworked SkipIteratorTotalItemTests option, there's a new parameter to allow TotalItems checks to occur, but only if a store configuration is set this …
> feat: More storage tests and options

- pkg/controller/command/kms/command.go
- pkg/controller/command/verifiable/command.go
- pkg/controller/command/verifiable/command_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/doc/signature/proof/proof.go
- pkg/doc/signature/suite/bbsblssignature2020/public_key_verifier_test.go
- pkg/doc/signature/verifier/public_key_verifier.go
- pkg/doc/util/time.go
- pkg/doc/util/time_test.go
Fixes & improvements:
- `/kms/import` accepts BLS12381_G2 private keys.
- `/verifiable` commands try to pick verification methods that match
the requested crypto suite for signing.
- Supports raw base64 fields in proof parsing.
- Supports bbs signature verification through public key verifier
SignatureVerifier.
- time.Time wrapper handles timestrings without a timezone suffix,
and will transparently marshal with/without the suffix, as its
source string was.
Interop tweaks:
- Fixes for handling acapy "peer" DID docs.
> feat: acapy issue-credential v2 interop support

- pkg/client/didexchange/client.go
- pkg/client/didexchange/client_test.go
- pkg/client/vcwallet/client.go
- pkg/controller/command/didexchange/command.go
- pkg/controller/command/vcwallet/command.go
- pkg/controller/rest/didexchange/operation.go
- pkg/controller/rest/vcwallet/operation.go
- pkg/didcomm/packager/packager.go
- pkg/didcomm/packer/authcrypt/pack.go
- pkg/didcomm/protocol/didexchange/keys.go
- pkg/didcomm/protocol/didexchange/keys_test.go
- pkg/didcomm/protocol/didexchange/service_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/transport/ws/pool.go
- pkg/framework/aries/api/vdr/vdr.go
- pkg/framework/aries/framework.go
- pkg/framework/aries/framework_test.go
- pkg/store/did/didconnection.go
- pkg/store/did/didconnection_test.go
- pkg/vdr/peer/creator.go
- pkg/vdr/peer/creator_test.go
- pkg/wallet/wallet.go
- test/bdd/agent/agent_sdk_steps.go
- test/bdd/features/didexchange_e2e_sdk.feature
- test/bdd/features/didexchange_e2e_sdk_didcommv2.feature
This change adds DIDCommV2 support to use KeyAgreement.ID when a DID doc is available.
Default behaviour is to use did:key for pre DIDCommV2 or where DID doc is not available to the recipient.
The Peer VDR creator now uses DIDCommV2 service type matching the media porfile version: DIDCommMessaging (for V2).
Default is did-communication (for pre V2) if media profile is missing or is not DIDCommV2.
> feat: support DID Doc KeyAgreement.ID as kid/skid for DIDCommV2

- pkg/client/outofband/client.go
- pkg/client/outofband/client_test.go
- pkg/controller/command/mediator/command.go
- pkg/controller/rest/mediator/operation.go
- pkg/didcomm/common/service/destination.go
- pkg/didcomm/common/service/destination_default.go
- pkg/didcomm/dispatcher/outbound.go
- pkg/didcomm/dispatcher/outbound_test.go
- pkg/didcomm/packager/packager.go
- pkg/didcomm/packager/packager_test.go
- pkg/didcomm/protocol/didexchange/states.go
- pkg/didcomm/protocol/didexchange/states_test.go
- pkg/didcomm/transport/media_type.go
- pkg/internal/gomocks/client/outofband/mocks.gen.go
- test/bdd/features/outofband_e2e_sdk.feature
- test/bdd/pkg/outofband/outofband_sdk_steps.go
This change adds support for selection of the DIDComm service version based on
the OOB invitation's Accept header.
> feat: support different Accept header values for DIDcomm versions

- pkg/controller/command/verifiable/command.go
- pkg/controller/command/verifiable/command_test.go
- pkg/internal/ldtestutil/contexts/third_party/trustbloc.github.io/trustbloc-authorization-credential_v1.jsonld
- pkg/internal/ldtestutil/document_loader.go
when didDoc.VM.ID has a #key-X suffix, the kms KID must be built from the VM.Value or VM.JWK() instead of being extracted from VM.ID
> fix: verifiable command building KID from didDoc.VM

- pkg/doc/presexch/definition.go
- pkg/doc/signature/jsonld/processor.go
- pkg/doc/signature/jsonld/processor_test.go
- pkg/doc/verifiable/credential.go
- test/bdd/features/presentproof_controller.feature
- test/bdd/pkg/presentproof/testdata/presentation_bbs_dl.json
- test/bdd/pkg/presentproof/testdata/request_presentation_bbs_dl.json
- support embedded contexts: include custom contexts in bbs limited credential template
- support ID being optional: allow json-ld Processor to Frame docs with blank ID
> feat: extend support cases for VC BBS derivation

- pkg/client/presentproof/client.go
- pkg/client/presentproof/client_test.go
- pkg/controller/command/presentproof/command_test.go
- pkg/controller/rest/presentproof/operation_test.go
- pkg/didcomm/protocol/middleware/presentproof/middlewares.go
- pkg/didcomm/protocol/presentproof/service.go
- pkg/didcomm/protocol/presentproof/service_test.go
- pkg/didcomm/protocol/presentproof/states.go
- pkg/didcomm/protocol/presentproof/states_test.go
- pkg/doc/signature/signer/signer.go
- pkg/doc/signature/signer/signer_default.go
- pkg/doc/signature/signer/signer_interop.go
- pkg/wallet/wallet_test.go
- Add present proof ack status
- Separate inbound/outbound message handling in present proof
- Set presentation format attach_id when constructing presentation message
- Use interop-compatible time format for LD signing when in interop mode
> feat: support present proof v2 interop with acapy

- pkg/crypto/tinkcrypto/crypto_test.go
- pkg/crypto/tinkcrypto/withkms_test.go
- pkg/kms/localkms/localkms.go
- pkg/kms/localkms/privkey_import.go
- pkg/kms/localkms/pubkey_export_import_test.go
- pkg/kms/localkms/pubkey_reader.go
Since P-384 DER format was using Tink's default signature template which uses SHA512, it was causing keys imported from a JWK to fail.
This change uses a template with SHA384 instead to keep signature/verification consistent in all cases (native kms key vs JWK imported key).
> fix: Crytpo signature verification using P384 key from JWK import 

- pkg/controller/rest/vcwallet/operation.go
**Title:**
VC wallet: REST endpoint /vcwallet/profile/{id} responds with 404
Closes #3051
**Summary:**
Adds a missing `/` to the rest endpoint.
> fix(vcwallet): correct path to profile existence endpoint

- pkg/kms/localkms/internal/keywrapper/kms_aead.go
- pkg/kms/localkms/internal/keywrapper/kms_aead_test.go
- pkg/kms/localkms/localkms_test.go
**Title:**
Add support of general key prefixes for LocalKMS
**Summary:**
Now LocalKMS support not only local key prefix but other prefixes with the form "anyprefixname://".
> feat: add support of general key prefixes for LocalKMS

- pkg/secretlock/local/masterlock/hkdf/master_secret_lock.go
- pkg/secretlock/local/masterlock/hkdf/master_secret_lock_test.go
- pkg/secretlock/local/masterlock/pbkdf2/master_secret_lock.go
- pkg/secretlock/local/masterlock/pbkdf2/master_secret_lock_test.go
> fix: allow payloads of any size in hkdf and pbkdf2 encrypt

- pkg/doc/credentialmanifest/common.go
- pkg/doc/credentialmanifest/credentialapplication.go
- pkg/doc/credentialmanifest/credentialapplication_test.go
- pkg/doc/credentialmanifest/credentialmanifest.go
- pkg/doc/credentialmanifest/credentialmanifest_test.go
- pkg/doc/credentialmanifest/testdata/valid_credential_application.json
- pkg/doc/credentialmanifest/testdata/valid_credential_application_with_format.json
- pkg/doc/credentialmanifest/testdata/valid_credential_application_with_presentation_submission.json
- pkg/doc/credentialmanifest/testdata/valid_credential_manifest_with_format.json
- pkg/doc/credentialmanifest/testdata/valid_credential_manifest_with_presentation_definition.json
Added a library for parsing Credential Application objects and ensuring they're valid against given Credential Manifests, per the specification at https://identity.foundation/credential-manifest/#credential-application.
> feat: Credential Application

- pkg/didcomm/protocol/outofbandv2/service.go
> fix: OOB V2 db name can't use . or / for mongodb compatibility

- pkg/doc/credentialmanifest/credentialfulfillment.go
- pkg/doc/credentialmanifest/credentialfulfillment_test.go
- pkg/doc/credentialmanifest/credentialmanifest.go
- pkg/doc/credentialmanifest/credentialmanifest_test.go
- pkg/doc/credentialmanifest/testdata/valid_credential_fulfillment.json
- pkg/doc/credentialmanifest/testdata/valid_issue_credential_message.json
- Added a library that allows you to parse Credential Fulfillment objects and resolve VCs from them based on an Issue Credential Message's attachment. This Credential Fulfillment implementation is based on the specification at https://identity.foundation/credential-manifest/#credential-fulfillment.
- Refactored the CredentialManifest.ResolveOutputDescriptors method to take in a *verifiable.Credential object instead of a []byte, in order to make the expected type more explicit.
> feat: Credential Fulfillment

- spi/storage/storage.go
This error is used when a call to Store.Batch using the IsNewKey PutOption with a key that already exists in the database. Callers can use this to react accordingly.
> feat: Added ErrDuplicateKey to storage interface

- pkg/client/vcwallet/client.go
- pkg/client/vcwallet/client_test.go
- pkg/controller/command/issuecredential/command.go
- pkg/controller/command/issuecredential/models.go
- pkg/controller/command/vcwallet/command.go
- pkg/controller/command/vcwallet/command_test.go
- pkg/controller/command/vcwallet/models.go
- pkg/controller/rest/issuecredential/models.go
- pkg/controller/rest/vcwallet/models.go
- pkg/controller/rest/vcwallet/operation.go
- pkg/controller/rest/vcwallet/operation_test.go
- pkg/wallet/models.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- refactored WACI request credential to rely on state message rather
than action events, to fix event notification issues in JavaScript
bindings
- other minor fixes
- Part of #3073
> fix: vcwallet WACI issuance fixes

- pkg/kms/webkms/remotekms.go
- pkg/kms/webkms/remotekms_test.go
**Title:**
Fix remote kms create keystore response format
Change type of Capability field in createKeyStoreResp to  []byte from string
**Summary:**
[Include a brief summary of your changes]
> fix: remote kms create keystore response format

- pkg/wallet/contents.go
- pkg/wallet/wallet_test.go
- fixing issue with `wallet.Remove()` where mapping data with collection
wasn't deleted.
> fix: removing item tagged by collection

- pkg/client/outofbandv2/client.go
- pkg/client/outofbandv2/client_test.go
- pkg/controller/command/outofbandv2/command.go
- pkg/controller/command/outofbandv2/models.go
- pkg/didcomm/protocol/outofbandv2/models.go
- pkg/didcomm/protocol/outofbandv2/service.go
- pkg/didcomm/protocol/outofbandv2/service_test.go
- pkg/wallet/invitation.go
- test/bdd/pkg/outofband/outofband_controller_steps.go
- test/bdd/pkg/outofband/outofband_sdk_steps.go
As per the DIDComm V2 spec, the From field should be in the oobv2 struct directly, not in the attachment.
> refactor: move oobv2 'From' field up from attachment

- pkg/didcomm/protocol/issuecredential/models.go
- pkg/didcomm/protocol/issuecredential/params.go
- pkg/wallet/wallet.go
- WACI way of using invitation as parent threadID may not work with
DIDCommV1 where parent thread ID gets reset by messenger while sending
propose credential message
- As a work around, invitation ID can be explicitly used while sending
propose credential message
- Part of #3073
> feat: correlating invitation with propose credential message

- cmd/aries-agent-mobile/pkg/wrappers/command/aries.go
- cmd/aries-agent-mobile/pkg/wrappers/config/options.go
when enabled, documents that are not available locally will be fetch remotely for mobile bindings.
Does replace pull request #3053.
Signed-off-by: Michel Sahli <michel.sahli@adnovum.ch>
> Add option to enable remote document loading for mobile bindings

- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/aries.js
- pkg/controller/command/vcwallet/command.go
- pkg/controller/command/vcwallet/command_test.go
- pkg/controller/command/vcwallet/models.go
- pkg/controller/rest/vcwallet/operation_test.go
- pkg/doc/cm/credentialmanifest.go
- pkg/doc/cm/credentialmanifest_test.go
- pkg/wallet/options.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- added new option in vcwallet to resolve credential saved in wallet
content store just by providing credential ID
- refcatored credential mabnifest API to accept raw credential to avoid
repeated marshal/unmarshaling of credential object
- Part of #3120
> feat: vc wallet resolve manifest by credential ID

- pkg/controller/command/vcwallet/models.go
- pkg/wallet/contents.go
fixed problem with collections where 2 different content types share
same id
> fix: vcwallet - collection data key collision

- test/bdd/pkg/waci/common.go
- test/bdd/pkg/waci/waci_issuance_didcomm_v1_sdk_steps.go
- test/bdd/pkg/waci/waci_issuance_didcomm_v2_sdk_steps.go
Refactored the WACI Issuance tests using V1 and V2 so that there's less code duplication.
closes #3143
> refactor: Reduce code duplication in WACI Issuance tests

- pkg/controller/command/issuecredential/command.go
- pkg/controller/command/issuecredential/models.go
- pkg/controller/rest/issuecredential/operation.go
- pkg/controller/rest/issuecredential/operation_test.go
The Accept Offer endpoint in the REST API can now accept an optional RequestCredential object. This object will get passed to the underlying client instead of just assuming a blank RequestCredential. This is a required feature for the WACI issuance flow.
> feat: Added RequestCredential argument for Accept Offer endpoint

- cmd/aries-agent-mobile/pkg/wrappers/command/aries.go
- cmd/aries-agent-mobile/pkg/wrappers/config/options.go
- cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go
- cmd/aries-agent-rest/startcmd/start.go
- cmd/aries-agent-rest/startcmd/start_test.go
- cmd/aries-js-worker/main.go
- pkg/didcomm/transport/ws/inbound.go
- pkg/didcomm/transport/ws/inbound_test.go
- pkg/didcomm/transport/ws/outbound.go
- pkg/didcomm/transport/ws/outbound_test.go
This PR adds support for setting read limit for outbound web socket transport (in addition to inbound that was already supported).
Closes #3155
> feat: websocket read limit support

- pkg/didcomm/common/middleware/middleware.go
- pkg/didcomm/common/middleware/middleware_test.go
- pkg/didcomm/dispatcher/inbound/inbound_message_handler.go
- pkg/framework/context/context_test.go
- add invitation ID to inviter's implicit didcomm v2 connection
- allow all non-didexchange messages to use didcomm v2 handlers
> fix: create oobv2 inviter's connection record on v1 messages, with invitation ID

- pkg/didcomm/common/middleware/middleware.go
> fix: outbound didcomm v2 messages always have 'body' and 'from' fields

- spi/storage/storage.go
Updated the documentation for the Put method to indicate that in the set of tags used on a single Put call, those tags must have unique tag names. The reason for this is because several of our major storage implementations in aries-framework-go-ext have this implementation, so this note was added to help ensure consistent behaviour.
> docs: Updated storage interface documentation

- component/storageutil/mem/mem.go
- component/storageutil/mem/mem_test.go
The method always returns nil. It's there just to allow it to implement a "Pinger" sort of interface which may be defined somewhere.
> feat: In-memory store "ping" method

- pkg/didcomm/common/model/ack.go
- pkg/didcomm/protocol/issuecredential/models.go
- pkg/didcomm/protocol/issuecredential/service.go
- pkg/didcomm/protocol/presentproof/states.go
Following this DIDcomm V2 spec udpate:
https://github.com/decentralized-identity/didcomm-messaging/pull/363
web-redirect is now web_redirect.
> refactor: web-redirector with underscore

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
- pkg/doc/verifiable/support_test.go
- pkg/doc/verifiable/testdata/credential_without_issuancedate.jsonld
**Title:**
Add an option for CredentialParse to use customized vc default schema.
https://github.com/trustbloc/vcs/issues/725
**Summary:**
Now CredentialParse can use a customized vc default schema. 
CreateDefaultSchema function added to simplify the creation of custom default schema.
> feat: add an option to disable required properties for CredentialParse.

- component/storageutil/mem/mem.go
- component/storageutil/mem/mem_test.go
The mem DB now supports queries with multiple tags using the '&&' operator.
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
> feat: Add multi-tag support to mem DB

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/signature/proof/proof.go
- pkg/doc/signature/proof/proof_test.go
- pkg/doc/signature/suite/bbsblssignatureproof2020/testdata/doc_with_many_proofs.jsonld
**Title:**
Add support of multibase encoding for proofValue.
https://github.com/hyperledger/aries-framework-go/issues/3228
**Summary:**
Add support of multibase encoding for proofValue and update unit tests to reflect this change.
> feat: add support of multibase encoding for proofValue.

- pkg/kms/webkms/crypto_box.go
- pkg/kms/webkms/crypto_box_test.go
- test/bdd/features/didexchange_e2e_sdk.feature
- test/bdd/features/webkms.feature
this change updates the remote CryptoBox api URIs to point to remote KMS's key /wrap and /unwrap to match ECDH-ES and ECDH-1PU key wrapping.
This change requires the KMS server to udpate /easy to /wrap, /easyOpen and /sealOpen to /unwrap
> refactor: remote cryptobox URLs renamed to /wrap and /unwrap

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/did/schema.go
- pkg/doc/did/testdata/valid_doc.jsonld
- pkg/doc/did/testdata/valid_doc_resolution.jsonld
- pkg/doc/did/testdata/valid_doc_v0.11.jsonld
- pkg/doc/did/testdata/valid_doc_with_base.jsonld
Signed-off-by: Chris Abernethy <brownoxford@gmail.com>
**Title:**
Add `alsoKnownAs` support to DID document
Implement support for `alsoKnownAs` DID document element [as described in DID Core v1](https://www.w3.org/TR/did-core/#dfn-alsoknownas)
**Summary:**
Add `AlsoKnownAs` element to `did.Doc` and populate value in `did.ParseDocument()`
Add `AlsoKnownAs` element to `did.rawDoc` and populate value in `did.Doc.JSONBytes()`
Add `did.populateRawAlsoKnownAs()` helper function to convert `alsoKnownAs` from `[]string` to `[]interface{}`
Add `alsoKnownAs` to schemas used for DID Schema Validation
> feat: add did document support for alsoKnownAs

- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/did/helpers.go
- pkg/doc/did/helpers_test.go
- pkg/vdr/key/creator_test.go
Signed-off-by: Chris Abernethy <brownoxford@gmail.com>
**Title:**
Implement did-core JSON-LD `@context` representation
Current implementation assumes `@context` can only be `[]string`, but did-core v1 defines `@context` for DID documents in JSON-LD representation to be either a string or a list containing maps and/or strings.
**Summary:**
* Created `type Context {}interface` to represent did document contexts with appropriate comment for IDE integration.
* Modified `did.parseContext` to add parsing of `string` and `[]interface{}` context representations.
* Added `LookupContextString` helper to search for context string through entire context (used by `requiresLegacyHandling`)
* Added `LookupSchemaFromContext` helper to peek first string in context. Replaces direct …
> feat: implement did-core JSON-LD `@context` representation

- pkg/secretlock/local/local_secret_lock.go
Removed a warning that would happen if trying to read in a master key using raw bytes, as this is actually a normal scenario. Also updated some related documentation to make it more clear that raw byte master keys are an expected use case.
> feat: Remove warning from secret lock and update documentation

- pkg/controller/command/didcommwallet/command.go
- pkg/controller/command/didcommwallet/command_test.go
- pkg/controller/command/didcommwallet/models.go
- pkg/controller/command/vcwallet/command.go
- pkg/controller/command/vcwallet/command_test.go
- pkg/controller/command/vcwallet/models.go
- pkg/controller/rest/vcwallet/models.go
- pkg/controller/rest/vcwallet/operation_test.go
**Title:**
Move ResolveCredentialManifest from didcommwallet to vcwallet.
**Summary:**
ResolveCredentialManifest is related to vcwallet.
> fix: move resolve credential manifest from didcommwallet to vcwallet.

- pkg/doc/cm/common.go
- pkg/doc/cm/credentialapplication.go
- pkg/doc/cm/credentialapplication_test.go
- pkg/doc/cm/credentialfulfillment.go
- pkg/doc/cm/credentialmanifest.go
- pkg/doc/cm/credentialmanifest_test.go
- pkg/doc/cm/resolve.go
- test/bdd/pkg/waci/waci_issuance_didcomm_v1_sdk_steps.go
- test/bdd/pkg/waci/waci_issuance_didcomm_v2_sdk_steps.go
**Summary:**
- Refactored credentialmanifest.go 
- moved everything related to resolving the different types into a separate file called resolve.go to make it clearer as to what is coming from the credential manifest and wallet rendering specs and what is needed for displaying 
- moved common functions to common.go
- Changes to match specs:
- Fixed display mapping object to use text property if paths is empty 
- validateDisplayMappingObject to check for if both the text field and the paths field is empty
- update unit tests for this
- ValidateCredentialApplication 
- Added check for case where manifest's format is empty but credential application's is not (credential application's formats should be a subset of credential manifest's)
- Removed duplicate code for checking credential …
> refactor: credential manifest enhancements to match wallet-rendering specs

- pkg/controller/controller.go
**Title:**
Change aries default wallet to didcommwallet.
**Summary:**
Didcomm functionality was moved from vcwallet to didcommwallet, to agent-sdk work properly default wallet should be changes to didcommwallet.
> fix: change aries default wallet to didcommwallet.

- pkg/doc/cm/credentialmanifest.go
Changed `mediatype` -> `contentMediaType`
and `encoding` -> `contentEncoding` in schema for better clearness in credential manifests
> fix: small change in schema format for clearness

- pkg/doc/verifiable/presentation.go
- pkg/doc/verifiable/presentation_test.go
This change fixes how a presentation is marshalled with empty credential field which wrongly outputs:
'"verifiableCredential": null'
This change skips this field if the presentation Credential field is empty
> fix: presentation with empty credential fix

- pkg/didcomm/dispatcher/outbound/outbound.go
- pkg/didcomm/dispatcher/outbound/outbound_test.go
- pkg/didcomm/packager/packager.go
- pkg/didcomm/protocol/legacyconnection/event.go
- pkg/didcomm/protocol/legacyconnection/event_test.go
- pkg/didcomm/protocol/legacyconnection/keys.go
- pkg/didcomm/protocol/legacyconnection/keys_test.go
- pkg/didcomm/protocol/legacyconnection/models.go
- pkg/didcomm/protocol/legacyconnection/service.go
- pkg/didcomm/protocol/legacyconnection/service_test.go
- pkg/didcomm/protocol/legacyconnection/states.go
- pkg/didcomm/protocol/legacyconnection/states_test.go
- pkg/didcomm/transport/media_type.go
- pkg/doc/util/kmsdidkey/kmsdidkey.go
- pkg/doc/util/kmsdidkey/kmsdidkey_test.go
**Title:**
[Connection](https://github.com/hyperledger/aries-rfcs/tree/main/features/0160-connection-protocol#0160-connection-protocol) protocol (RFC-0160) DIDCommV1 implementation
**Summary:**
- On this PR only part related to protocol package is implemented (client part is not implemented yet)
- Enable to handle "did:key" keys while creating legacy forwards.
- Add legacy profile types and use them while checking transport types.
closes https://github.com/hyperledger/aries-framework-go/issues/3299
> feat: Connection protocol (RFC-0160) DIDCommV1 implementation

- pkg/client/mediator/client.go
- pkg/client/mediator/models.go
- pkg/controller/command/mediator/command.go
- pkg/controller/command/mediator/command_test.go
- pkg/controller/command/mediator/models.go
- pkg/didcomm/protocol/mediator/api.go
- pkg/didcomm/protocol/mediator/service.go
- pkg/didcomm/protocol/mediator/service_test.go
- pkg/didcomm/protocol/mediator/util_test.go
- pkg/mock/didcomm/protocol/mediator/mock_mediator.go
> feat: allow mediator GetConnections APIs to filter by didcomm version.

- pkg/doc/cm/credentialmanifest.go
Changed credentialManifest's `validate()` back to `Validate() `as it needs to be exported
Signed-off-by: heidihan0000 <daeun.han@avast.com>
> fix: change validate->Validate

- pkg/doc/jwt/verifier.go
- scripts/check_go_integration.sh
- test/bdd/bddtests_test.go
- test/bdd/features/jwt.feature
- test/bdd/pkg/jwt/credential.go
- test/bdd/pkg/jwt/did.go
- test/bdd/pkg/jwt/jwt_steps.go
- test/bdd/pkg/jwt/presentation.go
- test/bdd/pkg/jwt/signer.go
- test/bdd/pkg/waci/common.go
- test/bdd/pkg/waci/waci_issuance_didcomm_v1_sdk_steps.go
- test/bdd/pkg/waci/waci_issuance_didcomm_v2_sdk_steps.go
**Title:**
Support ability in AFGO to create and parse vc and vp in JWT format
Added BDD tests with creating and verifying VC and VP in JWT format.
Solves: https://github.com/hyperledger/aries-framework-go/issues/3314
**Summary:**
Algorithms included:
- Ed25519
- ECDSA secp256r1
- ECDSA secp384r1
> test/support ability in AFGO to create and parse vc and vp in JWT format

- pkg/doc/cm/credentialapplication.go
- pkg/doc/cm/credentialfulfillment.go
- pkg/doc/cm/credentialmanifest.go
- pkg/doc/cm/credentialmanifest_test.go
- pkg/doc/cm/resolve.go
- pkg/doc/cm/testdata/credential_manifest_drivers_license_with_no_display_or_styles.json
Closes #3335 
**Summary:**
- `omitempty` tag for mandatory properties were removed
- optional properties (with the `omitempty` tag) of custom types were changed to pointers so they can be omitted with the `omitempty` tag
- additional validation checks which were missing and more unit tests
> fix: credential manifest omit optional properties

- pkg/doc/cl/api.go
- pkg/doc/cl/model.go
- pkg/doc/cl/ursa/crypto_test.go
- pkg/doc/cl/ursa/helpers.go
- pkg/doc/cl/ursa/issuer.go
- pkg/doc/cl/ursa/prover.go
- pkg/doc/cl/ursa/verifier.go
**Title:**
CL Anoncreds Crypto services
* Fourth PR to support CL in `af-go` [#180](https://github.com/hyperledger/aries-framework-go/issues/180)
* This PR adds high-level Crypto services to work with CL Anoncreds with help of `ursa` lib
**Summary:**
* added high-level CL crypto Issuer API
* added high-level CL crypto Prover API
* added high-level CL crypto Verifier API
* added ursa-implementations for the services
* added unit tests for issue credential flow with CL crypto
* added unit tests for present proof flow with CL crypto
> feat: CL Anoncreds Crypto services

- pkg/crypto/tinkcrypto/cl_crypto.go
- pkg/crypto/tinkcrypto/cl_crypto_test.go
- pkg/crypto/webkms/cl_remotecrypto_test.go
- pkg/crypto/webkms/remotecrypto.go
- pkg/crypto/webkms/remotecrypto_test.go
- pkg/kms/localkms/localkms_ursa_test.go
- pkg/kms/webkms/remotekms.go
- pkg/kms/webkms/remotekms_test.go
**Title:**
CL Anoncreds Remote KMS/Crypto
* Fifth PR to support CL in `af-go` [#180](https://github.com/hyperledger/aries-framework-go/issues/180)
* This PR implements/supports CL methods in remote Crypto
* This PR adds support for KMS extension for remote KMS 
* "server"-side changes will be implemented in the separate PR in both `trustbloc/kms`
**Summary:**
* added client calls to CL methods in remote crypto
* added attrs propagation for remote kms
* added unit tests for remote kms/crypto
* added more failed cases for localkms ursa tests
> feat: CL Anoncreds Remote KMS/Crypto

- pkg/didcomm/dispatcher/inbound/inbound_message_handler.go
- pkg/didcomm/protocol/legacyconnection/keys.go
- pkg/didcomm/protocol/legacyconnection/models.go
- pkg/didcomm/protocol/legacyconnection/models_test.go
- pkg/didcomm/protocol/legacyconnection/service.go
- pkg/didcomm/protocol/legacyconnection/service_test.go
- pkg/didcomm/protocol/legacyconnection/states.go
- pkg/didcomm/protocol/legacyconnection/states_test.go
- pkg/didcomm/protocol/legacyconnection/testdata/valid_conn_data.jsonld
- pkg/didcomm/transport/http/inbound.go
- pkg/didcomm/transport/http/inbound_test.go
- pkg/didcomm/transport/http/outbound.go
- pkg/doc/did/doc.go
- pkg/doc/did/legacy.go
- pkg/doc/did/legacy_test.go
- pkg/internal/didkeyutil/util.go
- pkg/internal/didkeyutil/util_test.go
- pkg/store/connection/connection_lookup.go
**Title:**
Refactor legacy-connection package due to interoperability issues
**Summary:**
- Add new legacy http header to handle legacy requests. Cover with unit tests
- Encode invitation Recipient key to base58
- Change embedded verification to referenced while creating verification methods
- Add legacy file into doc package to convert DIDdoc to raw doc. Cover with unit test
- Add handling DID id's where did method is not specified
- Add JSONBytes and ParseConnection methods to use them while handling connection data
- Change AckMsgType content to proper one
- Add method to convert array of did-keys to base58 keys
- Enable saving decryption key while handling envelope at connection-request state
- Add new InvitationRecipientKeys into connection.Record model
- Refactor requestMsgRecord, …
> refactor: A few refactoring of legacy-connection package

- test/bdd/bddtests_test.go
- test/bdd/features/wallet_jsonld.feature
- test/bdd/go.mod
- test/bdd/go.sum
- test/bdd/pkg/walletjsonld/agent.go
- test/bdd/pkg/walletjsonld/credential.go
- test/bdd/pkg/walletjsonld/did.go
- test/bdd/pkg/walletjsonld/presentation.go
- test/bdd/pkg/walletjsonld/query.go
- test/bdd/pkg/walletjsonld/signer.go
- test/bdd/pkg/walletjsonld/testdata/presentation_definition_fmt.json
- test/bdd/pkg/walletjsonld/testdata/query_by_example_fmt.json
- test/bdd/pkg/walletjsonld/wallet.go
- test/bdd/pkg/walletjsonld/wallet_steps.go
**Title:**
Support for JSON-LD in universal wallet implementation.
Solves: https://github.com/hyperledger/aries-framework-go/issues/3344
**Summary:**
Added BDD tests for universal wallet JSON-LD support.
Included the next actions:
- Sign JSON-LD Credential - Add it to wallet - get from wallet - verify Credential.
- Get JSON-LD Credential (without proof) - Call wallet.Issue() - get signed credential back - verify credential.
- Use signed credentials from previous steps - call wallet.Prove() - get presentation back - verify presentation.
- Add all the credentials from previous steps to holder's wallet - call wallet.Add(json-ld Credential) - wallet.Query() - get query result as json-ld presentation. (Included …
> test: BDD tests for universal wallet JSON-LD support

- pkg/doc/jsonld/validate.go
- pkg/doc/jsonld/validate_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
**Title:**
JSON LD Contexts in JWT VCs
Solves: https://github.com/hyperledger/aries-framework-go/issues/3351
**Summary:**
Added extra option to `ValidateJSONLD` function called `WithStrictContextURIPosition` that sets strict validation of URI position within context property. The index of uri in underlying slice represents the position of given URI in parsed context array.
Also, added this option as a default to `*verifiable.Credential.validateJSONLD(.... docjsonld.WithStrictContextURIPosition(baseContext))` function in order to make base context URI required.
> JSON LD Contexts in JWT VCs

- pkg/doc/didconfig/didconfig.go
- pkg/doc/didconfig/didconfig_test.go
Parse and validate DID configuration bytes.
Search through domain linkage credential(s) for specified did and domain. 
Validate domain linkage credential for Linked Data (JWT validation will be handled in different issue).
Closes #3371
> feat: Validate did configuration for did and domain

- pkg/doc/signature/proof/proof.go
- pkg/doc/signature/proof/proof_test.go
**Title:**
Do not panic when creating new Proof object with string map that contains invalid interfaces
This PR fixes #3384 by guarding the type assertion in `proof.stringEntry()` and returning the empty string if it fails.
**Summary:**
Updated `proof.stringEntry()` so that the empty string is returned if the type assertion for `entry.(string)` fails (precedent from [`did.stringEntry()`](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/did/doc.go#L1039-L1049)). Previously, this function would panic if the provided interface was not either `nil` or a `string`.
Added unit testing to ensure that all options passed through `proof.stringEntry()` by `proof.NewProof()` can handle invalid interfaces without a panic.
> fix: don't panic on malformed proof properties

- pkg/doc/presexch/api.go
- pkg/doc/presexch/api_test.go
- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_test.go
**Title:**
Support of vp referencing in descriptor_map's path.
**Summary:**
Previous code expected that all items referenced in descriptor_map's path should be valid VC.
Now, this is required only for the most nested path.
> fix: support of vp referencing in descriptor_map's path.

- pkg/doc/did/doc.go
Controller information should be filled in even if relative URL (@base) is present.
Closes #3424
> chore: Controller should be filled in even with relative URL(@base)

- pkg/didcomm/protocol/outofband/service_test.go
- pkg/doc/did/doc.go
- pkg/doc/did/doc_test.go
- pkg/doc/did/helpers.go
- pkg/doc/did/helpers_test.go
- pkg/doc/did/legacy.go
- pkg/doc/did/serialize_interop.go
- pkg/mock/diddoc/mock_diddoc.go
Service.Priority should be an interface so it can be omitted if not set.
Closes #3426
> chore: Service priority should be an interface

- pkg/doc/did/doc.go
**Title:**
Add did core support in resolving service endpoints function
Solves: https://github.com/hyperledger/aries-framework-go/issues/3428
**Summary:**
Added support of the next structure of service in DID:
```
"service": [
{
"id": "#linkeddomains",
"type": "LinkedDomains",
"serviceEndpoint": {
"origins": [
"https://did.rohitgulati.com/"
]
}
},
{
"id": "#hub",
"type": "IdentityHub",
"serviceEndpoint": {
"instances": [
"https://hub.did.msidentity.com/v1.0/a492cff2-d733-4057-95a5-a71fc3695bc8"
],
"origins": []
}
}
]
```
Covered in unit test here: https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/didconfig/interop_test.go#L37
> feat: add did core support in resolving service endpoints function

- pkg/doc/util/didsignjwt/signjwt.go
- pkg/internal/kmssigner/kmssigner.go
Minimized the interfaces required by the didsignjwt.SignJWT method by replacing the usage of the kms.KeyManager, crypto.Crypto, and vdr.Registry interfaces with minimized interfaces that define only the functionality needed for the SignJWT function. This makes it easier for consumers to inject in their own implementations. The method signatures of the new minimized interfaces still line up with the method signatures of the kms.KeyManager, crypto.Crypto, and vdr.Registry interfaces, so implementations of those interfaces can still be used without making any changes.
> refactor: Minimize interfaces required by didsignjwt.SignJWT

- pkg/framework/aries/api/vdr/vdr.go
- pkg/mock/vdr/mock_vdr.go
- pkg/vdr/httpbinding/vdr.go
- pkg/vdr/key/vdr.go
- pkg/vdr/peer/vdr.go
- pkg/vdr/registry.go
- pkg/vdr/registry_test.go
- pkg/vdr/web/vdr.go
Currently VDR makes decision on whether to accept or reject request based on method only. Add options to VDR Accept function so VDR can make more complex decisions.
Closes #3438
> feat: Add options to VDR Accept

- pkg/doc/util/didsignjwt/signjwt.go
Fixed an issue with the didsignjwt.SignerGetter function signature that's used as a parameter to the SignJWT function. Since the return type of SignerGetter is an unexported interface, it means that external packages could not create a custom SignerGetter function and pass it in (which was the intent). This PR simply exports the Signer interface to make this possible.
> fix: didsignjwt Signer interface not exported

- pkg/client/didconfig/didconfig.go
- pkg/client/didconfig/didconfig_test.go
DID Config Client is not passing options to DID Config API 
Current unit tests are using did:key so add unit test with did resolver option
Closes #3445
> chore: DID Config Client is not passing options to DID Config API

- pkg/client/didconfig/didconfig.go
- pkg/doc/didconfig/didconfig.go
Currently, the DID config validate functionality has an option for injecting in a VDR, however most of the methods in the interface are not actually used.
This change switches the option to use a minimal version of that interface that is itself a subset of the full VDR interface. With this change, a caller can now use the VDR option with a more minimal implementation that only has a Resolve method. The minimal interface still lines up with the larger VDR interface, so another caller can still use a full VDR interface implementation without making any changes.
> refactor: Minimize VDResolver interface needed for did config validate

- pkg/doc/sdjwt/common/common.go
- pkg/doc/sdjwt/common/common_test.go
- pkg/doc/sdjwt/holder/holder.go
- pkg/doc/sdjwt/holder/holder_test.go
- pkg/doc/sdjwt/issuer/issuer.go
- pkg/doc/sdjwt/issuer/issuer_test.go
- pkg/doc/sdjwt/verifier/verifier.go
- pkg/doc/sdjwt/verifier/verifier_test.go
Added utility function to decode disclosures (used by both holder and verifier) Created disclose claims function for holder that re-creates SD-JWT with disclosures for selected claims only.
Created get verified payload function for verifier (removes _sd and _sd_alg from claims and inserts into payload disclosed claims).
Closes #3459
> feat: SD-JWT Holder/Verifier - Process Disclosures

- pkg/doc/sdjwt/common/common.go
- pkg/doc/sdjwt/common/common_test.go
- pkg/doc/sdjwt/holder/holder.go
- pkg/doc/sdjwt/holder/holder_test.go
- pkg/doc/sdjwt/integration_test.go
- pkg/doc/sdjwt/issuer/issuer.go
- pkg/doc/sdjwt/issuer/issuer_test.go
- pkg/doc/sdjwt/verifier/verifier.go
- pkg/doc/sdjwt/verifier/verifier_test.go
Fix: Presentation Without Holder Binding should end with ~
Also, rename SDJWT to CombinedPresentation and JWTSerialized to SDJWT to follow spec terms.
And add parsing and serializing of combined presentation parts with holder binding. 
Holder Binding functionality will be added in separate PRs. 
Closes #3467
> fix: Presentation Without Holder Binding should end with ~

- pkg/doc/sdjwt/common/common.go
- pkg/doc/sdjwt/issuer/issuer.go
- pkg/doc/sdjwt/issuer/issuer_test.go
If the Issuer wants to enable Holder Binding, it MAY include a public key associated with the Holder, or a reference thereto.
We use confirmation "cnf" claim to include raw public key by value in SD-JWT.
In this first iteration of "cnf" claim we will use "jwk" confirmation method and include public key information in JWK format. Other confirmation methods such as "jwe", "kid" and "jku" may be implemented at later time (if required).
Closes #3469 
> feat: SD-JWT Issuer: Add Holder Public Key Claim (JWK)

- pkg/doc/jwt/jwt.go
- pkg/doc/jwt/jwt_test.go
- pkg/doc/sdjwt/holder/holder.go
- pkg/doc/sdjwt/integration_test.go
- pkg/doc/sdjwt/issuer/issuer.go
- pkg/doc/sdjwt/issuer/issuer_test.go
- pkg/doc/sdjwt/verifier/verifier.go
- pkg/doc/sdjwt/verifier/verifier_test.go
If Holder Binding is required, verify that the Holder Binding JWT is signed by the Holder and valid.
Closes #3471
> feat: SD-JWT Verifier: Verify Holder Binding

- pkg/doc/sdjwt/holder/holder.go
- pkg/doc/sdjwt/holder/holder_test.go
- pkg/doc/sdjwt/integration_test.go
- pkg/doc/sdjwt/verifier/verifier_test.go
Currently the holder releases disclosures based on claim name. If we have same name in different objects within claims this will not work.
Closes #3484
> fix: Release claims by claim disclosure not by claim name

- pkg/doc/presexch/definition.go
- pkg/doc/presexch/definition_test.go
- pkg/doc/presexch/example_v1_test.go
- pkg/doc/presexch/example_v2_test.go
**Title:**
Fix for Presentation Exchange descriptor format
[Link to the GitHub issue it solves (if any)]
**Summary:**
Presentation Exchange creates verifiable presentations with presentation submission descriptors with invalid format value.
> fix: presex desctiptor format.

- pkg/doc/sdjwt/common/common.go
- pkg/doc/sdjwt/holder/holder.go
- pkg/doc/sdjwt/integration_test.go
- pkg/doc/sdjwt/issuer/issuer.go
- pkg/doc/sdjwt/issuer/issuer_test.go
From spec: The Issuer may also make certain claims or sub-claims non-selectively disclosable. 
Added option WithNonSelectivelyDisclosableClaims() for specifying non-selectively disclosable claims to issuer.
Closes: #3497
> feat: SD-JWT: Add option for non-selectively disclosable claims (issuer)

- pkg/doc/verifiable/common.go
- pkg/doc/verifiable/common_test.go
- pkg/doc/verifiable/jws.go
**Title:**
Make JWSAlgorithm.Name() method exportable
**Summary:**
To be able to create JWS signer from external packages and avoid code duplication, I made  JWSAlgorithm.Name() method as exportable
> chore: make JWT alg name method exportable

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_sdjwt_test.go
> fix: allow SD-JWT parsing when sd alg is in cred subject

- pkg/controller/webnotifier/webhook.go
**Title:**
Webhook message has no content type
Add the content type to the request header in webhook
Issue: https://github.com/hyperledger/aries-framework-go/issues/3158
> add content type to webhook request

- cmd/aries-js-worker/src/agent-rest-client.js
- cmd/aries-js-worker/src/aries.js
Function was available in the core but was missing from the JavaScript
wrapper.
Signed-off-by: Boran Car <boran.car@gmail.com>
> Add RemoveCredentialByName to aries js helpers

- pkg/doc/verifiable/credential.go
- pkg/doc/verifiable/credential_sdjwt.go
- pkg/doc/verifiable/credential_test.go
> feat: Credential.MarshalJSON now marshals all SD-JWT disclosures

- pkg/doc/verifiable/presentation.go
**Title:**
Fix decoding presentation credential in SD JWT combined format for presentation.
> chore: decode presentation credential in SD JWT format

- pkg/doc/verifiable/credential_sdjwt.go
- pkg/doc/verifiable/credential_sdjwt_test.go
instead of turning subject ID into an SD field.
> feat: creating SD-JWT from VC will leave subject ID as regular field

- pkg/doc/presexch/definition_test.go
- pkg/doc/sdjwt/integration_test.go
- pkg/doc/sdjwt/issuer/issuer.go
- pkg/doc/sdjwt/issuer/issuer_test.go
- pkg/doc/sdjwt/verifier/verifier_test.go
Included:
- resolve merge conflict in unit-tests between Filip's id PR and add SD-JWT to presexch PR
- add audience option to issuer
- remove irrelevant to-do(s)
- remove one integration test (was replaced by NewFromVC)
- add sha-384 to integration tests
> chore: Add audience option to issuer

- pkg/doc/sdjwt/verifier/verifier.go
- pkg/doc/sdjwt/verifier/verifier_interop_test.go
- pkg/doc/sdjwt/verifier/verifier_test.go
Add interop tests for verifier - this is also to prove that we will not have issues with json libraries for interop (string hardening vs. canonicalization note in spec).
Since disclosures are created by the issuer the value can be influenced by marshalling (e.g. spaces, map order etc.) however it will not influence functionality since we are not supposed to re-create disclosures at any point.
Closes #3518
> chore: Add interop test for verifier

- pkg/doc/sdjwt/common/common.go
- pkg/doc/sdjwt/common/common_test.go
- pkg/doc/sdjwt/issuer/issuer.go
Additional validation when processing disclosures to assemble disclosed claims:
- If there is more than one place where the digest is included, the Verifier MUST reject the Presentation.
- If the claim name already exists at the same level, the Verifier MUST reject the Presentation.
- If the claim value contains an object with an _sd key (at the top level or nested deeper), the Verifier MUST reject the Presentation.
Closes #3519
> chore: Additional validation when creating disclosed claims (verifier)

- pkg/doc/presexch/schema.go
Signed-off-by: Stas D <stanislav.dmytryshyn@securekey.com>
During stress testing for vcs, we realized some slowness inside CreateVP method.
After some research, we find out that the performance issue is related to gojsonschema as it will request https://identity.foundation/claim-format-registry/schemas/presentation-definition-claim-format-designations.json every time https://github.com/xeipuuv/gojsonschema/blob/b076d39a02e5015af0a2a96636e4cc479ecd9f45/jsonLoader.go#L188
gojsonschema, by default, has a possibility to cache some records, https://github.com/xeipuuv/gojsonschema/blob/b076d39a02e5015af0a2a96636e4cc479ecd9f45/draft.go but there is no possibility to add additional records to the cache.
also with the current approach we have one additional failure point (if identity.foundation …
> feat: embed claim format designations

- .github/workflows/version_var.sh
https://github.com/hyperledger/aries-framework-go/releases/tag/v0.1.9
> ci: complete release 0.1.9 and prepare 0.2.0

- pkg/doc/presexch/definition.go
- pkg/internal/ldtestutil/contexts/third_party/w3c-ccg.github.io/revocation-list-2021.jsonld
- pkg/internal/ldtestutil/document_loader.go
- pkg/wallet/wallet_test.go
If we have two input descriptors with two credentials and one descriptor is satisfied with two credentials then we have failure depending on the order of processing.
Closes #3543
> fix: Wallet query multi-descriptor fix

- pkg/doc/presexch/api.go
- pkg/doc/presexch/api_test.go
- pkg/doc/presexch/definition.go
- pkg/doc/presexch/example_v1_test.go
- pkg/doc/presexch/example_v2_test.go
- CreateVP methods set VP IDs
- Match supports merged submission map[string]interface{} and VP submission fields of PresentationSubmission type.
> feat: PresentationDefinition API improvements:

- pkg/doc/didconfig/didconfig_test.go
This test is accessing remote URL, and it is often failing in CI.
Closes #3548
> chore: Remove test without loader for domain linkage

- .github/workflows/bbs-interop.yml
- .github/workflows/build.yml
- .github/workflows/test-suite.yml
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
> ci: update ubuntu runner to 22.04 as 18.4 is deprecated in GitHub Actions

- .github/workflows/version_var.sh
- CHANGELOG.md
- Set release flag to true
- Add CHANGELOG for 0.2.0
- Add CHANGELOG for 0.1.9 (missed previously) : point to github release page
> chore: release 0.2.0

- pkg/doc/presexch/definition.go
- pkg/doc/presexch/match_submission_requirements_test.go
**Title:**
MatchSubmissionRequirement no longer applies limited disclosure on its results, now it just filters applicable credentials.
**Summary:**
Functionality that applies limited disclosure was factored from `filterConstraints` to separate function limitDisclosure.
> fix: Match submission requirements not apply limited disclosure.

- pkg/doc/jwt/verifier.go
- pkg/doc/jwt/verifier_test.go
- pkg/doc/signature/verifier/verifier.go
- pkg/doc/verifiable/embedded_proof.go
- pkg/doc/verifiable/linked_data_proof.go
verifySignature does not require parsed claims to do that functionality. we already parsing claims in many other places.
> perf: remove extra parsing

- pkg/doc/presexch/definition.go
- pkg/doc/presexch/match_submission_requirements_test.go
**Title:**
Fix invalid creds IDs returned from MatchSubmissionRequirement.
**Summary:**
Credential returned MatchSubmissionRequirement had IDs with some random prefix. Now this is fixed.
> fix: invalid creds IDs returned from match submission requirements.

- pkg/doc/presexch/schema.go
**Title:**
Support for optional field in presexch.
**Summary:**
Extended PresentationDefinition JSON Schema V1 with field `optional` and `contains`
This filed is already exist in the [relevant struct](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/presexch/definition.go#L181), but wasn't a part of the Schema.
> feat: support for optional field in presexch

- component/models/presexch/definition.go
- go.mod
- pEx implementation no longer needs to replace Credential ID temporarily
- assorted cleanup
> refactor: cleanup messy code in pEx implementation

- component/kmscrypto/kms/localkms/localkms.go
- component/kmscrypto/kms/localkms/pubkey_export_import_test.go
- component/kmscrypto/kms/localkms/pubkey_reader.go
- component/models/dataintegrity/integration_test.go
- component/models/dataintegrity/models/models.go
- component/models/dataintegrity/suite/ecdsa2019/ecdsa2019.go
- component/models/dataintegrity/suite/ecdsa2019/ecdsa2019_test.go
- component/models/go.mod
**Title:**
Change KMS interface for Data Integrity.
**Summary:**
1. Introduced private KMS interface for ecdsa2019 Data integrity suite with only onte method.
2. Made `publicKeyBytesToHandle` function as exported from localkms package and used it in ecdsa2019 Data integrity suite verifier. The reason for it is that method
```
func (l *LocalKMS) PubKeyBytesToHandle(pubKey []byte, kt kmsapi.KeyType, opts ...kmsapi.KeyOpts) (interface{}, error) {
return publicKeyBytesToHandle(pubKey, kt, opts...)
}
```
does not use receiver and func `PublicKeyBytesToHandle` can be used independently.
> feat: change KMS interface for Data Integrity

- component/models/dataintegrity/integration_test.go
- component/models/dataintegrity/suite/ecdsa2019/ecdsa2019.go
- component/models/dataintegrity/verifier.go
- component/models/dataintegrity/verifier_test.go
- component/models/ld/testutil/contexts/third_party/w3id.org/data-integrity-v1.jsonld
- component/models/ld/testutil/document_loader.go
- component/models/verifiable/data_integrity_proof_test.go
**Title:**
Added data integrity JSON-LD context
Because of the missed DI JSON LD context (and disabled strict validation), Aries on issuance stage generated invalid `canonicalProofConfig` considering only `type` field.
Example:
```
_:c14n0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <DataIntegrityProof> .
```
Verification part was successful because Aries considered same `type` field. And because of that, Unit tests did not catch the typo that on verification stage field `created` was empty.
According to [Spec](https://www.w3.org/TR/vc-di-ecdsa/#base-proof-configuration-ecdsa-sd-2023), another fields must be also included in `canonicalProofConfig`.
After this PR, Aries generates the following `canonicalProofConfig`:
```
_:c14n0 <http://purl.org/dc/terms/created> …
```
> feat: added data integrity jsonld context

- component/models/dataintegrity/integration_test.go
- component/models/dataintegrity/models/models.go
- component/models/dataintegrity/signer.go
- component/models/dataintegrity/signer_test.go
- component/models/dataintegrity/suite/ecdsa2019/ecdsa2019.go
- component/models/dataintegrity/suite/ecdsa2019/ecdsa2019_test.go
- component/models/dataintegrity/suite/ecdsa2019/integration_test.go
- component/models/dataintegrity/support_test.go
- component/models/dataintegrity/verifier_test.go
Using [ResolveSigningVMWithRelationship](https://github.com/hyperledger/aries-framework-go/blob/50313f0971cff8b74e4ad0cb1ce45910f6653352/component/models/jwt/didsignjwt/signjwt.go#L189) function causes a bug in VM relationship verification for Data integrity.
1. For instance, let's take issuer's DID, that after resolving has the following structure:
```
{
"verificationMethod": [
ID: "abc",
.....
],
"authentication": [
ID: "abc",
.....
]
}
```
3. Function [docRes.DIDDocument.VerificationMethods()](https://github.com/hyperledger/aries-framework-go/blob/50313f0971cff8b74e4ad0cb1ce45910f6653352/component/models/jwt/didsignjwt/signjwt.go#L221) with empty arguments returns a map with 2 elements: key `VerificationRelationshipGeneral` and `Authentication`. 
Values for those keys are verification …
> feat: change DI VM purpose resolution
