cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/client/didexchange/models.go, pkg/controller/command/didexchange/command.go, pkg/controller/command/didexchange/command_test.go, pkg/controller/rest/didexchange/models.go, pkg/controller/rest/didexchange/operation.go, pkg/controller/rest/didexchange/operation_test.go, pkg/store/connection/connection_lookup_test.go, pkg/store/connection/connection_recorder.go, pkg/store/connection/connection_recorder_test.go
=> feat: Save Connection API

cmd/aries-js-worker/src/aries.js, cmd/aries-js-worker/src/worker-loader-node.js, cmd/aries-js-worker/src/worker-loader-rest.js, cmd/aries-js-worker/src/worker-loader-web.js, test/aries-js-worker/init.js, test/aries-js-worker/karma.conf.js, test/aries-js-worker/package.json, test/aries-js-worker/test/common.js, test/aries-js-worker/test/didexchange/didexchange_e2e.js, test/aries-js-worker/test/messaging/messaging.js, test/aries-js-worker/test/outofband/outofband.js
Fixes CI failure.
This PR also includes:
* refactoring
* multiple subscribers for events
closes #1970 
=> fix: Fixes warning in JS tests

pkg/client/introduce/client.go, pkg/client/introduce/client_test.go, pkg/client/introduce/example_test.go, pkg/controller/command/introduce/command.go, pkg/controller/command/introduce/models.go, pkg/controller/rest/introduce/models.go, pkg/didcomm/protocol/introduce/properties.go, pkg/didcomm/protocol/introduce/properties_test.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, test/bdd/pkg/context/context.go, test/bdd/pkg/introduce/introduce_controller_steps.go, test/bdd/pkg/introduce/introduce_sdk_steps.go, test/bdd/pkg/redeemableroutes/redeemable_routes.go
Adds correlation id for the Introduce protocol.
=> feat: Introduce - added correlation id

test/aries-js-worker/test/common.js, test/aries-js-worker/test/introduce/introduce.js, test/aries-js-worker/test/issuecredential/issuecredential.js, test/aries-js-worker/test/outofband/outofband.js, test/aries-js-worker/test/presentproof/presentproof.js, test/bdd/pkg/util/util.go
JS tests were refactored.
Closes https://github.com/hyperledger/aries-framework-go/issues/1980
Closes https://github.com/hyperledger/aries-framework-go/issues/1957
=> test: JS tests refactoring

pkg/storage/mysql/mysqlstore.go, pkg/storage/mysql/mysqlstore_test.go
=> fix: Mysql Iterator and adding db prefix

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_extension_test.go, pkg/doc/verifiable/credential_jwt.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/json.go, pkg/doc/verifiable/json_test.go, pkg/store/verifiable/store.go
=> refactor: VC extension of Credential Subject

README.md, docs/concepts/00_what_is_hl_aries.md
**Title:**
Added a "What is Aries?" doc
Part of https://github.com/hyperledger/aries-framework-go/issues/2005
Closes https://github.com/hyperledger/aries-framework-go/issues/2006
Summary:
Overview on Aries. Initial steps towards documenting key concepts about the project.
=> added brief overview of Aries

cmd/aries-js-worker/src/aries.js
=> fix: JS-Worker -  panic during multiple issueCredential.SendRequest

go.sum, test/aries-js-worker/fixtures/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/sidetree/sidetree.go
Update sidetree-mock/sidetree-core versions in tests
Closes #2013
=> chore: update sidetree-mock/sidetree-core in tests

cmd/aries-agent-mobile/README.md, cmd/aries-agent-mobile/go.sum, cmd/aries-agent-mobile/main.go, cmd/aries-agent-mobile/main_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/command.go, cmd/aries-agent-mobile/pkg/wrappers/command/introduce.go, cmd/aries-agent-mobile/pkg/wrappers/command/introduce_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/verifiable.go, cmd/aries-agent-mobile/pkg/wrappers/command/verifiable_test.go, cmd/aries-agent-mobile/pkg/wrappers/config/options.go, cmd/aries-agent-mobile/pkg/wrappers/models/models.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/introduce.go, cmd/aries-agent-mobile/pkg/wrappers/rest/introduce_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/rest.go, cmd/aries-agent-mobile/pkg/wrappers/rest/verifiable.go, cmd/aries-agent-mobile/pkg/wrappers/rest/verifiable_test.go
**Title:**
Minor refactoring for mobile bindings on iOS
Closes https://github.com/hyperledger/aries-framework-go/issues/2021
Summary:
- clean ups
- reduced stuttered method names for objective-c
- updated code samples in the README
=> chore: light refactoring to improve iOS library usage

cmd/aries-agent-mobile/README.md, cmd/aries-agent-mobile/pkg/api/didexchange.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/didexchange.go, cmd/aries-agent-mobile/pkg/wrappers/command/didexchange_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/didexchange.go, cmd/aries-agent-mobile/pkg/wrappers/rest/didexchange_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/introduce.go, cmd/aries-agent-mobile/pkg/wrappers/rest/verifiable.go, docs/concepts/00_what_is_hl_aries.md, docs/concepts/01_terminologies.md, pkg/controller/command/didexchange/command.go, pkg/controller/rest/didexchange/operation.go, pkg/controller/rest/didexchange/operation_test.go
**Title:**
Added DIDExchange protocol controller mobile bindings
Closes https://github.com/hyperledger/aries-framework-go/issues/2025
Part of https://github.com/hyperledger/aries-framework-go/issues/2005
Summary:
- Added a new interface with local and remote agent implementations
- Added documentation for DIDExchange and related terminologies
=> feat: added didexchange protocol controller mobile bindings

cmd/aries-agent-mobile/pkg/api/api.go, cmd/aries-agent-mobile/pkg/api/introduce.go, cmd/aries-agent-mobile/pkg/api/issuecredential.go, cmd/aries-agent-mobile/pkg/api/verifiable.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/issuecredential.go, cmd/aries-agent-mobile/pkg/wrappers/command/issuecredential_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/didexchange.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/introduce.go, cmd/aries-agent-mobile/pkg/wrappers/rest/issuecredential.go, cmd/aries-agent-mobile/pkg/wrappers/rest/issuecredential_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/verifiable.go, pkg/controller/command/issuecredential/command.go, pkg/controller/command/issuecredential/command_test.go, pkg/controller/rest/issuecredential/operation.go, pkg/controller/rest/issuecredential/operation_test.go
**Title:**
Added IssueCredential protocol controller mobile bindings
Closes https://github.com/hyperledger/aries-framework-go/issues/2030
Summary:
- added interface
- added local agent implementation
- added remote agent implementation
=> feat: added issue credential controller mobile bindings

.github/workflows/build.yml, .golangci.yml, cmd/aries-js-worker/go.sum, pkg/storage/couchdb/couchdbstore.go, pkg/storage/couchdb/couchdbstore_test.go, pkg/storage/jsindexeddb/jsindexeddb.go, pkg/storage/jsindexeddb/jsindexeddb_test.go, pkg/storage/leveldb/leveldb_store.go, pkg/storage/leveldb/leveldb_store_test.go, pkg/storage/mem/mem_store.go, pkg/storage/mem/mem_store_test.go, pkg/storage/mysql/mysqlstore.go, pkg/storage/mysql/mysqlstore_test.go, pkg/storage/providers_test.go, pkg/storage/providers_wasm_test.go, pkg/storage/store_test.go, scripts/check_lint.sh, scripts/check_unit_wasm.sh, test/bdd/dockerutil/compose.go
=> fix: Fixes storage behavior

pkg/didcomm/protocol/presentproof/models.go, pkg/didcomm/protocol/presentproof/service.go, pkg/didcomm/protocol/presentproof/service_test.go, pkg/didcomm/protocol/presentproof/states.go, pkg/didcomm/protocol/presentproof/states_test.go, test/aries-js-worker/test/presentproof/presentproof.js, test/bdd/pkg/presentproof/presentproof_controller_steps.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
Added `WillConfirm` field to the `RequestPresentatation` model.
=> feat: Present Proof - added WillConfirm to the RequestPresentation

.github/workflows/build.yml, cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/client/issuecredential/client.go, pkg/client/issuecredential/client_test.go, pkg/client/presentproof/client.go, pkg/client/presentproof/client_test.go, pkg/controller/command/issuecredential/command.go, pkg/controller/command/issuecredential/command_test.go, pkg/controller/command/issuecredential/models.go, pkg/controller/command/presentproof/command.go, pkg/controller/command/presentproof/command_test.go, pkg/controller/command/presentproof/models.go, pkg/controller/rest/issuecredential/models.go, pkg/controller/rest/issuecredential/operation.go, pkg/controller/rest/issuecredential/operation_test.go, pkg/controller/rest/presentproof/models.go, pkg/controller/rest/presentproof/operation.go, pkg/controller/rest/presentproof/operation_test.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/presentproof/service.go, pkg/didcomm/protocol/presentproof/service_test.go, pkg/didcomm/protocol/presentproof/states.go, test/bdd/features/issue_credential.feature, test/bdd/features/presentproof.feature, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
Adds action event support for the following protocols:
* Issue Credential
* Present Proof
NOTE: Also increased timeout for CI
=> feat: Adds action event (Issue Credential,Present Proof)

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/rest/verifiable/operation_test.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_testsuite.go, pkg/doc/verifiable/credential_testsuite_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/embedded_proof_test.go, pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_ldp_test.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/test-suite/verifiable_suite_test.go, pkg/store/verifiable/store.go, pkg/store/verifiable/store_test.go
=> fix: check VP embedded proof

cmd/aries-agent-mobile/pkg/api/api.go, cmd/aries-agent-mobile/pkg/api/presentproof.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/presentproof.go, cmd/aries-agent-mobile/pkg/wrappers/command/presentproof_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/presentproof.go, cmd/aries-agent-mobile/pkg/wrappers/rest/presentproof_test.go, pkg/controller/command/presentproof/command.go, pkg/controller/command/presentproof/command_test.go, pkg/controller/rest/presentproof/operation.go, pkg/controller/rest/presentproof/operation_test.go
**Title:**
Added wrappers for PresentProof protocol
Closes https://github.com/hyperledger/aries-framework-go/issues/2039
**Summary:**
- PresentProof interface
- Local agent implementation
- Remote agent implementation
=> feat: added mobile bindings for the presentproof protocol controller

cmd/aries-agent-mobile/pkg/api/api.go
Signed-off-by: Leung Wai Hang Cyril <cyrilhl@gmail.com>
Use the following template for your PR (make sure you follow our
[guidelines](CONTRIBUTING.md#pull-request):
**Title:**
Add GetDIDExchangeController in AriesController interface
Update api.go and add GetDIDExchangeController function
**Summary:**
=> Add GetDIDExchangeController function in AriesController

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/mediator/command.go, pkg/controller/command/mediator/command_test.go, pkg/controller/command/mediator/models.go, pkg/controller/rest/mediator/models.go, pkg/controller/rest/mediator/operation.go, pkg/controller/rest/mediator/operation_test.go
- Closes #2074
TODO: bdd tests will follow in next PR
=> feat: command controller for mediator status & batchpickup

cmd/aries-agent-mobile/pkg/api/api.go, cmd/aries-agent-mobile/pkg/api/vdri.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/vdri.go, cmd/aries-agent-mobile/pkg/wrappers/command/vdri_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/vdri.go, cmd/aries-agent-mobile/pkg/wrappers/rest/vdri_test.go, pkg/controller/command/vdri/command.go, pkg/controller/rest/vdri/operation.go, pkg/controller/rest/vdri/operation_test.go
**Title:**
Mobile bindings for the VDRI controller.
Closes https://github.com/hyperledger/aries-framework-go/issues/2080
Closes https://github.com/hyperledger/aries-framework-go/issues/2081
**Summary:**
Adds an interface and local agent implementation.
=> feat: added mobile bindings for a local VDRI agent controller

docs/concepts/00_what_is_hl_aries.md, docs/concepts/01_terminologies.md
**Title:**
Includes an overview of VDRIs
Closes https://github.com/hyperledger/aries-framework-go/issues/2082
=> docs: added VDRI concepts

cmd/aries-agent-mobile/pkg/api/api.go, cmd/aries-agent-mobile/pkg/api/mediator.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/issuecredential_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/mediator.go, cmd/aries-agent-mobile/pkg/wrappers/command/mediator_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/presentproof_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/vdri_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/verifiable_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/issuecredential_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/mediator.go, cmd/aries-agent-mobile/pkg/wrappers/rest/mediator_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/presentproof_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/vdri_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/verifiable_test.go, pkg/controller/command/mediator/command.go, pkg/controller/rest/mediator/operation.go, pkg/controller/rest/mediator/operation_test.go
**Title:**
Added wrapper for the Mediator controller
Closes https://github.com/hyperledger/aries-framework-go/issues/2086
=> feat: added mobile bindings for mediator controller

Makefile
=> chore: Update Alpine version (3.11 to 3.12)

go.mod, go.sum, pkg/storage/mysql/mysqlstore_test.go
=> fix: mysql storage tests are not properly waiting for db readiness

docs/concepts/00_what_is_hl_aries.md, docs/concepts/01_terminologies.md
**Title:**
Added definitions related to the Mediator controller
Closes https://github.com/hyperledger/aries-framework-go/issues/2085
**Summary:**
=> docs: added definitions related to the Mediator controller

cmd/aries-agent-mobile/pkg/api/api.go, cmd/aries-agent-mobile/pkg/api/messaging.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/messaging.go, cmd/aries-agent-mobile/pkg/wrappers/command/messaging_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/messaging.go, cmd/aries-agent-mobile/pkg/wrappers/rest/messaging_test.go, pkg/controller/command/messaging/command.go, pkg/controller/rest/messaging/operation.go, pkg/controller/rest/messaging/operation_test.go
**Title:**
Added mobile wrappers for the Messaging controller
Closes https://github.com/hyperledger/aries-framework-go/issues/2091
=> feat: added mobile wrappers for the Messaging controller

pkg/controller/command/mediator/command.go, pkg/didcomm/protocol/messagepickup/service.go, pkg/didcomm/protocol/messagepickup/service_test.go, pkg/framework/aries/framework.go, test/aries-js-worker/test/didexchange/didexchange_e2e.js, test/aries-js-worker/test/messaging/messaging.js
- added JS bdd tests for mediator status checks when agent is offline
- added JS bdd tests for mediator pickup message
- Closes #2097
=> feat: bdd tests for mediator status & reconnect

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, docs/concepts/00_what_is_hl_aries.md, docs/concepts/01_terminologies.md, test/bdd/go.sum
**Title:**
Added a summary of the OutOfBand protocol and its related terms
Closes #2094
=> docs: added summary of the OutOfBand protocol and related terms

docs/concepts/00_what_is_hl_aries.md
**Title:**
Summarised Messaging controller
Closes https://github.com/hyperledger/aries-framework-go/issues/2092
=> docs: summarised messaging controller

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-mobile/pkg/api/api.go, cmd/aries-agent-mobile/pkg/api/outofband.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/outofband.go, cmd/aries-agent-mobile/pkg/wrappers/command/outofband_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/outofband.go, cmd/aries-agent-mobile/pkg/wrappers/rest/outofband_test.go, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, go.mod, pkg/controller/command/outofband/command.go, pkg/controller/rest/outofband/operation.go, pkg/controller/rest/outofband/operation_test.go, test/bdd/go.sum
**Title:**
Added OutOfBand protocol controller mobile bindings
Closes #2095
=> feat: added mobile bindings for the OutOfBand protocol

cmd/aries-agent-mobile/go.mod, cmd/aries-agent-mobile/pkg/api/api.go, cmd/aries-agent-mobile/pkg/api/kms.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/command/kms.go, cmd/aries-agent-mobile/pkg/wrappers/command/kms_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries.go, cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/kms.go, cmd/aries-agent-mobile/pkg/wrappers/rest/kms_test.go, pkg/controller/command/kms/command.go, pkg/controller/rest/kms/operation.go, pkg/controller/rest/kms/operation_test.go
=> feat: added mobile wrappers for the KMS controller

docs/concepts/00_what_is_hl_aries.md, docs/concepts/01_terminologies.md
**Title:**
Added docs for the KMS controller
Closes #2005
=> docs: added kms controller summary and definition

cmd/aries-agent-rest/startcmd/start.go, cmd/aries-agent-rest/startcmd/start_test.go, pkg/controller/controller_test.go, pkg/didcomm/protocol/presentproof/service_test.go, pkg/didcomm/transport/http/inbound.go, pkg/didcomm/transport/http/inbound_test.go, pkg/didcomm/transport/ws/inbound.go, pkg/didcomm/transport/ws/inbound_test.go, pkg/didcomm/transport/ws/pool_test.go, pkg/framework/aries/defaults/defaults.go, pkg/framework/aries/defaults/defaults_test.go, test/bdd/agent/agent_sdk_steps.go
Adds TLS support for the inbound transports.
=> feat: Adds TLS support for the inbound transports (https, wss)

pkg/client/issuecredential/example_test.go
This PR adds examples for the `Issue Credential` protocol.
Part of #1790 
=> feat: Issue Credential - adds examples

pkg/crypto/tinkcrypto/crypto.go, pkg/crypto/tinkcrypto/crypto_test.go
=> fix: correct a signature of the Decrypt function in tinkcrypto

pkg/client/issuecredential/doc.go
This PR adds `godoc` for the Issue Credential protocol.
Part of #1790 
=> docs: Issue Credential documentation (godoc)

images/agent-rest/Dockerfile, pkg/client/didexchange/client_test.go, pkg/store/connection/connection_lookup_test.go, scripts/generate_test_keys.sh, test/bdd/agent/agent_controller_steps.go, test/bdd/features/aries_e2e_route_option.feature, test/bdd/features/aries_mediator_e2e_controller.feature, test/bdd/features/didexchange_e2e_controller.feature, test/bdd/features/didexchange_public_did.feature, test/bdd/features/introduce_controller.feature, test/bdd/features/issue_credential_controller.feature, test/bdd/features/messaging_e2e_controller.feature, test/bdd/features/outofband_controller.feature, test/bdd/features/presentproof_controller.feature, test/bdd/fixtures/agent-rest/docker-compose.yml, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/util/util.go
Added TLS support for BDD tests.
Closes #2117 
=> feat: BDD tests are using TLS.

pkg/kms/api.go, pkg/kms/localkms/kid_creator.go, pkg/kms/localkms/localkms_writer.go, pkg/kms/localkms/localkms_writer_test.go
closes #2134
signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>
=> refactor: change KMS KeyID encoding from base64 to base58

test/aries-js-worker/fixtures/.env, test/bdd/fixtures/sidetree-mock/.env
=> chore: update sidetree-mock image to 0.1.4

README.md, cmd/aries-agent-mobile/doc/project_structure.md
Explains how the package was designed.
=> docs: added explanations for the architecture of the mobile bindings

pkg/didcomm/transport/http/outbound.go, pkg/didcomm/transport/http/outbound_test.go, pkg/didcomm/transport/ws/outbound.go
=> refactor: Log transport error message

ci/version_var.sh
=> chore: Aries Framework Go v0.1.4 release

ci/version_var.sh
=> chore: Aries Framework Go 0.1.4 release complete commit

cmd/aries-agent-rest/go.mod, cmd/aries-agent-rest/go.sum, cmd/aries-agent-rest/startcmd/start.go
Also refactored the code that inits the storage provider to make it D.R.Y.
=> fix: agent-rest - database timeout flag name

test/aries-js-worker/fixtures/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/sidetree/sidetree.go
Update sidetree-mock in tests
Closes #2164
=> chore: update sidetree in tests

pkg/storage/base58wrapper/base58wrapper_test.go, pkg/storage/couchdb/couchdbstore_test.go, pkg/storage/providers_test.go
Checks CouchDB before running tests.
=> refactor: Checks CouchDB before running tests

docs/rest/openapi_demo.md
Adds documentation of how to create a did-connection through the out-of-band protocol.
=> doc: Create a did-connection through the out-of-band protocol

pkg/didcomm/transport/ws/support_test.go, pkg/internal/gomocks/client/introduce/mocks.go, pkg/internal/gomocks/client/issuecredential/mocks.go, pkg/internal/gomocks/client/outofband/mocks.go, pkg/internal/gomocks/client/presentproof/mocks.go, pkg/internal/gomocks/controller/webnotifier/mocks.go, pkg/internal/gomocks/didcomm/common/service/mocks.go, pkg/internal/gomocks/didcomm/dispatcher/mocks.go, pkg/internal/gomocks/didcomm/messenger/mocks.go, pkg/internal/gomocks/didcomm/protocol/introduce/mocks.go, pkg/internal/gomocks/didcomm/protocol/issuecredential/mocks.go, pkg/internal/gomocks/didcomm/protocol/middleware/issuecredential/mocks.go, pkg/internal/gomocks/didcomm/protocol/middleware/presentproof/mocks.go, pkg/internal/gomocks/didcomm/protocol/presentproof/mocks.go, pkg/internal/gomocks/framework/aries/api/vdri/mocks.go, pkg/internal/gomocks/storage/mocks.go, pkg/internal/gomocks/store/verifiable/mocks.go, test/bdd/agent/agent_controller_steps.go
This PR includes:
* updates gomocks
* fixes linter warnings
=> chore: Updates gomocks

docs/rest/openapi_demo.md
Adds `Present Proof` documentation (REST usage).
Closes #1791 
=> doc: Present Proof - REST usage

cmd/aries-agent-mobile/README.md
**Title:**
Added code snippet for notification handlers on android.
Closes #2188.
=> docs: added code snippet for notification handlers on android

docs/rest/openapi_demo.md
Adds `Issue Credential` documentation (REST usage).
Closes #1790 
=> doc: Issue Credential - REST usage

docs/rest/openapi_demo.md
Improves documentation formatting.
=> doc: Present Proof - improves formatting

cmd/aries-agent-mobile/README.md, cmd/aries-agent-mobile/doc/project_structure.md
**Title:**
Added code snippet that makes use of the Handler interface implemented in Objective-C
Closes #2152
=> docs: added example code for iOS notification handler

pkg/storage/mysql/errors.go, pkg/storage/mysql/mysqlstore.go, pkg/storage/mysql/mysqlstore_test.go, pkg/storage/store.go
=> fix: mysql storage provider: No database selected

cmd/aries-agent-mobile/README.md
**Title:**
Added Kotlin/Swift snippets
Closes https://github.com/hyperledger/aries-framework-go/issues/2203
=> docs: added more code snippets

.github/workflows/build.yml
PRs have been raised w/o coverage being reported.
=> chore: update codecov-action version

pkg/didcomm/protocol/presentproof/service_test.go, test/aries-js-worker/test/didexchange/edgeagent_mediator.js, test/bdd/features/aries_mediator_e2e_controller.feature, test/bdd/features/aries_mediator_e2e_sdk.feature, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/mediator/mediator_controller_steps.go
Adds BDD tests for multiple router support.
Closes #2205 
=> test: BDD tests for multiple router support

pkg/didcomm/common/service/did_comm_msg.go, pkg/didcomm/common/service/did_comm_msg_test.go
=> feat: didcomm message map to decode json RawMessage types

pkg/common/log/mocklogger/mocklogger.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/outofband/service_test.go, pkg/internal/gomocks/storage/mocks.go, pkg/kms/localkms/localkms.go, pkg/mock/storage/mock_store.go, pkg/storage/couchdb/couchdbstore.go, pkg/storage/couchdb/couchdbstore_test.go, pkg/storage/jsindexeddb/jsindexeddb.go, pkg/storage/leveldb/leveldb_store.go, pkg/storage/mem/mem_store.go, pkg/storage/mysql/mysqlstore.go, pkg/storage/store.go, pkg/storage/wrapper/prefix/prefix_wrapper.go
- Added CouchDB implementation
- Other implementations are left as stubs for now
closes #2220
=> feat: Store query method

.github/workflows/build.yml, .gitignore, Makefile, scripts/check_unit.sh
=> fix: codecov

pkg/controller/command/messaging/command.go, pkg/controller/command/messaging/command_test.go, pkg/controller/command/messaging/models.go, pkg/didcomm/common/service/messenger.go, pkg/didcomm/messenger/messenger.go, pkg/didcomm/messenger/messenger_test.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go, pkg/didcomm/protocol/presentproof/service_test.go, pkg/didcomm/protocol/presentproof/states.go, pkg/didcomm/protocol/presentproof/states_test.go, pkg/internal/gomocks/didcomm/common/service/mocks.go, pkg/mock/didcomm/service/mock_service.go, test/aries-js-worker/test/messaging/messaging.js
- added reply nested (reply by starting new thread) feature in all
command controllers
- added JS bddtests
- closes #2251
=> feat: reply nested feature in command controller

test/aries-js-worker/fixtures/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: update sidetree-mock revision

docs/didcomm_mediator.md
=> docs: Describe mediator setup

docs/didcomm_mediator.md
=> docs: fix mediator doc - add http instead of ws

component/storage/jsindexeddb/jsindexeddb.go, component/storage/leveldb/leveldb_store.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/outofband/service_test.go, pkg/internal/gomocks/storage/mocks.go, pkg/mock/storage/mock_store.go, pkg/storage/edv/documentprocessor/documentprocessor.go, pkg/storage/edv/documentprocessor/documentprocessor_test.go, pkg/storage/edv/formatprovider/formatprovider.go, pkg/storage/edv/formatprovider/formatprovider_test.go, pkg/storage/edv/models.go, pkg/storage/mem/mem_store.go, pkg/storage/mem/mem_store_test.go, pkg/storage/store.go, pkg/storage/wrapper/prefix/prefix_wrapper.go, pkg/storage/wrapper/prefix/prefix_wrapper_test.go
=> feat: Enforce EDV document ID format in EDVFormatProvider

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-mobile/main.go, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go
This PR includes:
* `autoAccept` support for `didexchange` protocol
* possibly to set `log level`
=> feat: Adds autoAccept and log level support for mobile

pkg/didcomm/messaging/service/basic/basicmsgsvc_test.go
=> chore: update basic message test uri

pkg/doc/verifiable/credential_ldp_test.go
In this PR, we use BBS+ signature suite to create a new Linked Data Proof for VC and then use the same suite to make VC verification.
closes #2222
=> test: BBS+ VC Signer example

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, pkg/storage/edv/common.go, pkg/storage/edv/encryptedformatter.go, pkg/storage/edv/encryptedformatter_test.go, pkg/storage/edv/models.go, pkg/storage/edv/restprovider.go, pkg/storage/edv/restprovider_test.go, pkg/storage/formattedstore.go, pkg/storage/formattedstore_test.go, test/bdd/go.sum
=> feat: SDS REST provider

test/bdd/features/aries_e2e_route_option.feature, test/bdd/features/aries_mediator_e2e_controller.feature, test/bdd/features/didexchange_e2e_controller.feature, test/bdd/features/didexchange_public_did.feature, test/bdd/features/introduce_controller.feature, test/bdd/features/issue_credential_controller.feature, test/bdd/features/messaging_e2e_controller.feature, test/bdd/features/outofband_controller.feature, test/bdd/features/presentproof_controller.feature
Adds controller tag for BDD tests.
Tests can be executed by this command `go test -v -run controller`.
=> chore: Adds controller tag for BDD tests

cmd/aries-agent-mobile/pkg/wrappers/storage/storage.go
Maps custom error to storage error.
=> fix: Maps custom error to storage error (mobile)

pkg/storage/store.go
=> refactor: Removes redundant errors

pkg/kms/localkms/localkms_writer.go
=> fix: assertion for ErrDataNotFound when checking if keyset ID is used

pkg/crypto/tinkcrypto/primitive/composite/api/composite_decrypt.go, pkg/crypto/tinkcrypto/primitive/composite/api/composite_encrypt.go, pkg/kms/webkms/remotekms.go, pkg/kms/webkms/remotekms_test.go
=> feat: remoteKMS client implementation

pkg/mock/edv/edv.go, pkg/storage/edv/restprovider.go, pkg/storage/edv/restprovider_test.go
=> feat: EDV REST provider delete method

pkg/storage/edv/restprovider.go
=> fix: Remove incorrect EDV REST client delete document status code check

.github/workflows/build.yml, .github/workflows/test-suite.yml
See error here https://github.com/hyperledger/aries-framework-go/runs/1408834335#step:3:17
=> ci: Fixes publish job

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/mediator/command.go, pkg/controller/command/mediator/command_test.go, pkg/controller/command/mediator/models.go, pkg/controller/rest/mediator/operation.go, pkg/controller/rest/mediator/operation_test.go, pkg/mock/didcomm/protocol/outofband/outofband.go
- also added REST & JS bindings
- closes #2328
TODO: mobile bindings
=> feat: reconnect all & create-invitation in mediator command

pkg/client/messaging/client.go, pkg/client/messaging/client_test.go, pkg/client/messaging/notifier.go, pkg/controller/command/messaging/command.go, pkg/controller/command/messaging/command_test.go, pkg/controller/command/messaging/models.go, pkg/controller/rest/messaging/models.go, pkg/controller/rest/messaging/operation.go, pkg/controller/rest/messaging/operation_test.go, test/aries-js-worker/test/messaging/messaging.js
=> feat: messaging command - await response feature for send/reply

pkg/storage/edv/restprovider.go, pkg/storage/edv/restprovider_test.go
=> feat: add HeadersOpt optional function to edv provider

cmd/aries-agent-mobile/pkg/api/mediator.go, cmd/aries-agent-mobile/pkg/wrappers/command/mediator.go, cmd/aries-agent-mobile/pkg/wrappers/command/mediator_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/mediator.go, cmd/aries-agent-mobile/pkg/wrappers/rest/mediator_test.go, pkg/controller/command/mediator/command.go
=> feat: mediator reconnect all mobile bindings

pkg/crypto/webkms/wrapkey_util.go, pkg/kms/webkms/remotekms.go
Fixes/updates json tags in remotekms and remotecrypto requests/responses.
=> fix: json tags in remote kms/crypto

cmd/aries-js-worker/src/aries.js
=> fix: aries agent JS reconnect all issue

pkg/didcomm/common/service/did_comm_msg.go, pkg/didcomm/common/service/did_comm_msg_test.go, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/vdr/peer/did_test.go
closes #2149 
Implemented json.Marshaler and json.Unmarshaler. Also changed
DIDCommMsgMap to use did.ParseDocument.
Original work by @gnarula 
Signed-off-by: Phil Feairheller <pfeairheller@gmail.com>
=> DIDDoc: Fix JSON Marshaling

pkg/storage/edv/restprovider.go
=> fix: edv provider http request

pkg/storage/formattedstore/formattedstore.go, pkg/storage/formattedstore/formattedstore_test.go
=> feat: Add cache provider to edv rest

docs/didcomm_mediator.md
- Update limitations
- Link to Pickup protocol
=> docs: Update mediator document

cmd/aries-agent-mobile/Makefile
Fixes mobile agent build (ios).
Issue #2339 
Signed-off-by: Andriy Soluk <soluchok@Andriys-MacBook-Pro.local>
=> fix: Fixes mobile agent build (ios)

pkg/didcomm/messenger/messenger.go, pkg/didcomm/messenger/messenger_test.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
Removes metadata from the messenger.
It decreases one `Get` call to the database every time the agent receives a message.
=> refactor: Removes metadata from the messenger

pkg/mock/edv/edv.go, pkg/storage/edv/restprovider.go, pkg/storage/edv/restprovider_test.go
=> fix: Wrong EDV REST query parameter and use optimization for Iterator

pkg/kms/webkms/remotekms.go, pkg/kms/webkms/remotekms_test.go
=> bug: remoteKMS GET methods should not have a request body

pkg/kms/webkms/remotekms.go, pkg/kms/webkms/remotekms_test.go
The JS/wasm clients can access only [simple headers when making cross-origin requests](https://javascript.info/fetch-crossorigin#response-headers) and location is not part of it.
closes #2363
=> feat: read keyURL from resp body of remoteKMS.Create()

pkg/mock/edv/edv.go, pkg/storage/edv/models/models.go, pkg/storage/edv/restprovider.go, pkg/storage/edv/restprovider_test.go
=> feat: EDV REST provider batch support

pkg/mock/edv/edv.go, pkg/storage/edv/restprovider_test.go
=> fix: Improper usage of vault operations in EDV REST provider unit tests

pkg/crypto/webkms/remotecrypto.go, pkg/crypto/webkms/remotecrypto_test.go, pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/packer/legacy/authcrypt/pack.go, pkg/didcomm/packer/legacy/authcrypt/unpack.go, pkg/kms/api.go, pkg/kms/webkms/crypto_box.go, pkg/kms/webkms/crypto_box_test.go
=> feat: add internal remoteCryptoBox service for legacyPacker

pkg/storage/edv/encryptedformatter.go, pkg/storage/edv/encryptedformatter_test.go, pkg/storage/formattedstore/batchwrite.go, pkg/storage/formattedstore/batchwrite_test.go, pkg/storage/formattedstore/formattedstore.go, pkg/storage/formattedstore/formattedstore_test.go
=> feat: Add batch write for edv rest provider

go.sum, pkg/doc/did/doc.go, pkg/framework/aries/api/vdr/vdr.go, pkg/vdr/web/creator.go, pkg/vdr/web/creator_test.go, pkg/vdr/web/did.go, pkg/vdr/web/resolver.go, pkg/vdr/web/resolver_test.go, pkg/vdr/web/store.go, pkg/vdr/web/store_test.go, pkg/vdr/web/vdr.go, pkg/vdr/web/vdr_test.go
Adds ability to resolve did:web dids, addresses issue #2246 
Signed off by: Amod Kala <amod.kala@securekey.com>
=> feat: #2246 Support for DID Web Method

pkg/storage/formattedstore/batchwrite.go, pkg/storage/formattedstore/batchwrite_test.go, pkg/storage/formattedstore/formattedstore.go, pkg/storage/formattedstore/formattedstore_test.go
=> feat: switch batch write to explicit flush

pkg/crypto/webkms/remotecrypto.go, pkg/kms/webkms/crypto_box.go, pkg/kms/webkms/remotekms.go
=> chore: add duration logs for webkms calls

pkg/storage/formattedstore/batchwrite.go, pkg/storage/formattedstore/batchwrite_test.go, pkg/storage/formattedstore/formattedstore.go, pkg/storage/formattedstore/formattedstore_test.go
=> fix: remove unsed variable

pkg/storage/formattedstore/batchwrite.go, pkg/storage/formattedstore/batchwrite_test.go, pkg/storage/formattedstore/formattedstore.go, pkg/storage/formattedstore/formattedstore_test.go
=> feat: add batch size to batch write

go.mod, go.sum, pkg/crypto/webkms/remotecrypto.go, pkg/crypto/webkms/remotecrypto_test.go, pkg/kms/webkms/headers_opts.go, pkg/kms/webkms/remotekms.go, pkg/kms/webkms/remotekms_test.go
=> feat: add cache for compute MAC

pkg/storage/formattedstore/batchwrite.go
=> chore: remove goroutines from batch write

pkg/doc/bbs/api.go, pkg/doc/bbs/bbs12381g2pub/bbs.go, pkg/doc/bbs/bbs12381g2pub/bbs_test.go, pkg/doc/bbs/bbs12381g2pub/fr.go, pkg/doc/bbs/bbs12381g2pub/keys.go, pkg/doc/bbs/bbs12381g2pub/proof_of_knowledge.go, pkg/doc/bbs/bbs12381g2pub/signature.go, pkg/doc/bbs/bbs12381g2pub/signature_message.go, pkg/doc/bbs/bbs12381g2pub/signature_proof.go, pkg/doc/bbs/bbs12381g2pub/utils.go, pkg/doc/bbs/bbs12381g2pub/utils_test.go
=> feat: BBS+ selective disclosure

docs/encrypted_storage.md, docs/project_structure.md
=> docs: Encrypted storage

pkg/storage/formattedstore/batchwrite.go
=> fix: batch write

ci/version_var.sh
=> chore: Aries Framework Go v0.1.5 release

ci/version_var.sh
=> chore: Complete release 0.1.5

pkg/doc/verifiable/credential_ldp_test.go, test/bbs/data/revealDocument.json, test/bbs/package-lock.json, test/bbs/src/main.go, test/bbs/src/vc.js, test/bbs/test/bbs.js
=> test: BSS+ signature proof (selective disclosure) interop tests with Mattr

pkg/doc/presexch/api.go, pkg/doc/presexch/api_test.go, pkg/doc/presexch/example_test.go
Defines PresentationDefinition fields according to spec. See https://identity.foundation/presentation-exchange/#presentation-definition
=> feat: Defines PresentationDefinition fields according to spec

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, test/bdd/go.sum
Adds the possibility to create VP based on the definition.
=>  feat: Adds the possibility to create VP based on the definition

pkg/doc/presexch/api.go, pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
Adds presentation submission support.
=>  feat: Adds presentation submission support

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
=> feat: Presentation definition - adds constraints filtering

pkg/client/messaging/client_test.go
=> fix: Fixes unit test failure

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
=> feat: Presentation Exchange - adds predicate support

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
Adds subject is issuer support.
=> feat: Presentation Exchange - adds subject is issuer support

pkg/newstorage/newstorage.go
- Improved documentation.
- Moved CloseStore method from Provider to Store.
- Introduced custom error type for bulk methods so the caller can determine which operation failed.
=> feat: Improvements to new storage interface

pkg/didcomm/packer/anoncrypt/pack_test.go, pkg/didcomm/packer/authcrypt/pack_test.go
=> add JWE pack using recipient keys with different curves

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
Adds submission requirement support.
=> feat: Presentation Exchange - adds submission requirement support

pkg/secretlock/local/local_secret_lock.go, pkg/secretlock/local/local_secret_lock_test.go, pkg/secretlock/local/masterlock/pbkdf2/master_secret_lock.go, pkg/secretlock/local/masterlock/pbkdf2/master_secret_lock_test.go
=> feat: add pbkdf2 masterlock + ref NIST in docs

.github/workflows/build.yml, docs/test/build.md, images/agent-rest/Dockerfile
=> ci: migrate to ghcr

cmd/aries-agent-mobile/go.mod, cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, pkg/doc/presexch/example_test.go
This PR includes:
* adds examples
* go mod tidy
* minor bug fixes
=> docs: Presentation Exchange - adds examples

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/client/didexchange/models.go, test/bdd/pkg/introduce/introduce_controller_steps.go, test/bdd/pkg/introduce/introduce_sdk_steps.go, test/bdd/pkg/outofband/outofband_controller_steps.go
Adds the possibility to query connections by InvitationID and ParentThreadID
=> feat: Adds the possibility to query connections by InvitationID

.github/workflows/build.yml, README.md
=> chore: rename master branch to main

.github/settings.yml
=> chore: add repo settings

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, pkg/doc/presexch/example_test.go
=> feat: Presentation Exchange - BBS+ support

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go
=> feat: add JSONBytes to DocResolution

pkg/framework/aries/api/vdr/vdr.go, pkg/mock/vdr/mock_registry.go, pkg/mock/vdr/mock_vdr.go, pkg/vdr/httpbinding/vdr.go, pkg/vdr/httpbinding/vdr_test.go, pkg/vdr/key/vdr.go, pkg/vdr/key/vdr_test.go, pkg/vdr/peer/vdr.go, pkg/vdr/peer/vdr_test.go, pkg/vdr/registry.go, pkg/vdr/registry_test.go, pkg/vdr/web/vdr.go
=> refactor: VDR support for deactivate/update

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, pkg/client/messaging/client_test.go, pkg/didcomm/protocol/middleware/presentproof/middlewares.go, pkg/didcomm/protocol/middleware/presentproof/middlewares_test.go, pkg/framework/aries/default.go, test/bdd/go.sum
=> feat: 0510: Presentation-Exchange Attachment

component/newstorage/formattedstore/formattedstore.go, component/newstorage/formattedstore/formattedstore_test.go
=> feat: Caching support for new formatted storage provider

pkg/didcomm/protocol/outofband/models.go, pkg/doc/did/doc.go
* fix: json tags on did.Service
* fix: json tag on outofband.Invitation
=> fix: json tags

pkg/crypto/webkms/remotecrypto.go, pkg/kms/webkms/headers_opts.go, pkg/kms/webkms/remotekms.go, pkg/kms/webkms/remotekms_test.go, test/bdd/agent/agent_sdk_steps.go
=> fix: KMS returns now XRootCapability

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
For every field from constraints, do not just set `@explicit` in the reveal doc, but also copy special fields like `type` and `context` from the source VC document to the reveal document if present. Also, we need to copy the parent special fields if present as well.
closes #2488
=> feat: presexch: copy @context and type from doc to BBS+ JSON-LD frame

.github/workflows/build.yml, .repolint.json, CODE_OF_CONDUCT.md, CONTRIBUTING.md, MAINTAINERS.md, SECURITY.md, pkg/doc/bbs/bbs12381g2pub/internal/kilic/bls12-381/g1.go, pkg/doc/bbs/bbs12381g2pub/internal/kilic/bls12-381/hash_to_field_custom.go, pkg/doc/util/signature/utils_test.go
Added repolinter action and missing repo files.
Need followup for: CHANGELOG.md
=> chore: add repolint

.repolint.json, CHANGELOG.md
=> Add initial CHANGELOG

component/newstorage/mem/go.mod, component/newstorage/mem/mem.go, component/newstorage/mem/mem_test.go
=> fix: Incorrect checks in new in-memory iterator implementation

component/newstorage/mock/go.mod, component/newstorage/mock/go.sum, component/newstorage/mock/mock.go, scripts/check_lint.sh, test/component/go.mod, test/component/go.sum, test/component/storage/storage.go
=> chore: update mock and test components to use spi

test/component/storage/storage.go
=> feat: Additional common storage tests

scripts/check_lint.sh, spi/log/log.go
Also added spi module to lint check
=> feat: Add logger to SPI

.github/workflows/build.yml, .github/workflows/version_var.sh
=> ci: restore version_var.sh

cmd/aries-agent-mobile/pkg/wrappers/command/outofband_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/outofband_test.go, docs/rest/openapi_demo.md, pkg/client/outofband/client_test.go, pkg/didcomm/protocol/outofband/service.go, pkg/didcomm/protocol/outofband/service_test.go
=> fix: Invitation Msg Type

pkg/doc/util/signature/internal/signer/crypto_signer.go, pkg/doc/util/signature/internal/signer/crypto_signer_test.go
=> feat: Adds the possibility to retrieve KID (signer)

pkg/client/messaging/client.go, pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/client/vcwallet/models.go
- closes #2541
- part of #2433
=> feat: vcwallet client

test/component/storage/storage.go
=> feat: Additional common storage test cases

pkg/controller/command/verifiable/command.go, pkg/didcomm/protocol/middleware/presentproof/middlewares.go, pkg/doc/presexch/api_test.go, pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, pkg/doc/presexch/example_test.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_bbs.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/jsonld.go, pkg/doc/verifiable/linked_data_proof_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/support_test.go, pkg/store/verifiable/store.go, scripts/check_license.sh, test/bbs/src/main.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
=> refactor: remove ParseUnverified functions

pkg/doc/presexch/definition_test.go, pkg/doc/signature/suite/bbsblssignature2020/suite_test.go, pkg/doc/signature/suite/bbsblssignature2020/support_test.go, pkg/doc/signature/suite/bbsblssignature2020/testdata/context/ldp-bbs2020.jsonld, pkg/doc/signature/suite/bbsblssignatureproof2020/signer_test.go, pkg/doc/signature/suite/bbsblssignatureproof2020/suite_test.go, pkg/doc/signature/suite/bbsblssignatureproof2020/support_test.go, pkg/doc/signature/suite/bbsblssignatureproof2020/testdata/context/ldp-bbs2020.jsonld, pkg/doc/signature/verifier/public_key_verifier_test.go, pkg/doc/verifiable/credential_bbs_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/example_support_test.go, pkg/doc/verifiable/support_test.go, pkg/doc/verifiable/testdata/context/bss2020.jsonld, test/bbs/data/context/ldp-bbs2020.jsonld, test/bbs/data/inputDocument.json, test/bbs/data/revealDocument.json, test/bbs/package-lock.json, test/bbs/package.json, test/bbs/src/support_jsonld_loader.go, test/bbs/test/bbs.js
=> chore: update BBS context URI

spi/storage/storage.go
=> feat: Add JSON tags to new storage structs

pkg/crypto/tinkcrypto/primitive/bbs/bbs.go, pkg/crypto/tinkcrypto/primitive/bbs/bbs_key_template.go, pkg/crypto/tinkcrypto/primitive/bbs/bbs_key_template_test.go, pkg/crypto/tinkcrypto/primitive/bbs/bbs_signer_key_manager.go
=> feat:KMS support for BBS+ keys: create Tink key templates

spi/storage/storage.go
Addresses https://github.com/hyperledger/aries-framework-go/pull/2543#discussion_r581112430
=> feat: Close Iterator helper function

test/component/storage/storage.go
=> test: Additional common storage GetOpenStores testing

pkg/vdr/key/creator.go
=> fix: Initializes a map to prevent panic

test/component/storage/storage.go
=> test: Add common storage tests ensuring that Put after Delete works

pkg/crypto/api.go, pkg/crypto/primitive/bbs12381g2pub/bbs.go, pkg/crypto/tinkcrypto/crypto.go, pkg/crypto/tinkcrypto/crypto_test.go, pkg/crypto/tinkcrypto/primitive/bbs/bbs.go, pkg/crypto/webkms/remotecrypto.go, pkg/crypto/webkms/remotecrypto_test.go, pkg/mock/crypto/mock_crypto.go
=> feat: add BBS+ support to crypto.Crypto and webkms

pkg/doc/verifiable/embedded_proof.go
=> fix: base64 decode nonce value in bbsblssignatureproof2020

pkg/crypto/primitive/bbs12381g2pub/bbs.go, pkg/crypto/primitive/bbs12381g2pub/bbs_test.go, pkg/crypto/primitive/bbs12381g2pub/proof_of_knowledge.go, pkg/crypto/primitive/bbs12381g2pub/utils.go, pkg/crypto/primitive/bbs12381g2pub/utils_test.go
=> fix: BBS+ DeriveProof panic

pkg/crypto/primitive/bbs12381g2pub/bbs.go, pkg/crypto/primitive/bbs12381g2pub/bbs_test.go, pkg/doc/signature/verifier/public_key_verifier_test.go
=> test: add test case for BBS case 19

pkg/didcomm/protocol/middleware/presentproof/middlewares.go, pkg/didcomm/protocol/middleware/presentproof/middlewares_test.go, pkg/doc/presexch/definition.go, pkg/store/verifiable/store.go, test/bdd/features/presentproof.feature, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
=> test: Presentation exchange - BBS+ BDD test

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go
- command controller & tests for derive credential feature
- added REST & JS support
- closes #2592
=> feat: derive credential

component/storageutil/batchedstore/batchedstore_test.go, component/storageutil/cachedstore/cachedstore_test.go, component/storageutil/formattedstore/formattedstore_test.go, component/storageutil/mock/mock.go
=> feat: Simple implementation of remaining mock storage methods

pkg/kms/webkms/remotekms.go
=> feat: support key ID during import

pkg/controller/command/verifiable/command.go
=> fix: public key fetcher for generate bbs signature command

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/operation_test.go, pkg/didcomm/protocol/middleware/presentproof/middlewares.go, pkg/doc/presexch/definition_test.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
=> feat: Sign credential - support BBS+ (API)

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, test/bdd/features/presentproof_controller.feature, test/bdd/fixtures/agent-rest/docker-compose.yml, test/bdd/fixtures/agent-rest/schema/schema.json, test/bdd/pkg/presentproof/presentproof_controller_steps.go
=> feat: BBS+ BDD tests for PE

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go
=> fix: did.Doc.UnmarshalJSON panic if parsing fails

scripts/start_edv_test_docker_images.sh
=> chore: Update EDV server version used in EDV REST Provider unit tests

.github/workflows/bbs-interop.yml, pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go
=> fix: include context loader when framing

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation_test.go
temp fix for JS binding causing date parsing issues
=> fix: derive credential response model

scripts/start_edv_test_docker_images.sh
=> chore: Update EDV image used in EDV REST storage provider unit tests

.github/workflows/version_var.sh, CHANGELOG.md
=> Release 0.1.6

.github/workflows/version_var.sh
=> chore: complete release

.github/workflows/version_var.sh
=> fix: package image tag

scripts/start_edv_test_docker_images.sh, test/bdd/fixtures/agent-rest/.env
=> chore: update fixture versions

pkg/didcomm/protocol/issuecredential/models.go, pkg/didcomm/protocol/presentproof/models.go, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go
=> fix: json tags for issuecredV2 and presentproofV2

test/component/storage/storage.go
=> test: Add storage tests for ensuring that Put/Get work with URLs as keys

pkg/doc/presexch/api.go, pkg/doc/presexch/definition.go, pkg/doc/presexch/schema.go
=> chore: presexch - expose JSONSchema, add JSONLD context

pkg/controller/command/verifiable/command.go
=> fix: /verifiable/presentation/generate: load presentation-exchange JSONLD context

cmd/aries-js-worker/go.mod, cmd/aries-js-worker/go.sum, docs/test/bdd_tests.md, test/aries-js-worker/test/messaging/messaging.js
Messaging js tests did not work. The root cause was in the import part.
```
// good
import { newAries } from "../common.js";
// bad
import {newAries} from "../common";
```
=> test: Fixes JS messaging tests

test/bdd/fixtures/agent-rest/docker-compose.yml, test/bdd/pkg/presentproof/testdata/presentation_bbs.json, test/bdd/pkg/presentproof/testdata/presentation_multiple_attachments.json, test/bdd/pkg/presentproof/testdata/request_presentation_bbs.json, test/bdd/pkg/presentproof/testdata/request_presentation_multiple_attachments.json
**Title:**
Modify the port number of static-file-server.
**Summary:**
When the command "make run-openapi-demo" executes, the port number of the static-file-server container and the alice.openapi.demo.com container are conflicting and it does not run.
So I change the port number(8089) of static-file-server to 7089.
=> Modify the port number of static-file-server

pkg/vdr/fingerprint/fingerprint.go, pkg/vdr/fingerprint/fingerprint_test.go, pkg/vdr/key/resolver.go, pkg/vdr/key/resolver_test.go
=> feat: add support for BBS+ G1G2 DID Keys

pkg/vdr/web/did.go, pkg/vdr/web/resolver.go, pkg/vdr/web/resolver_test.go, pkg/vdr/web/testdata/alice/did.json
=> fix: did:web uses did.json

test/bdd/fixtures/demo/openapi/docker-compose.yml
**Title:**
Correct the typo of container name.
**Summary:**
Change a typo "openpi" in the container name to "openapi".
=> Correct the typo.

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, pkg/doc/presexch/example_test.go, pkg/doc/presexch/schema.go, pkg/doc/presexch/testdata/sample_1.json, pkg/doc/presexch/testdata/sample_3.json, test/aries-js-worker/test/presentproof/presentproof.js, test/bdd/pkg/presentproof/presentproof_sdk_steps.go, test/bdd/pkg/presentproof/testdata/request_presentation_bbs.json
The `limit_disclosure` field is a string now.
Possible values are:
* required (old true)
* preferred  (old false)
=> fix: Presentation Exchange - limit_disclosure field is string

pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/client/vcwallet/contents.go, pkg/client/vcwallet/contents_test.go, pkg/client/vcwallet/profile.go, pkg/client/vcwallet/profile_test.go
- fixed: UUID for dbnamespacing instead of user ID.
- added add/get/remove features for credential, collection, diddocument,
metadata, connection data models.
- closes #2651
=> feat: VC wallet contents - add/get/remove

cmd/aries-agent-mobile/pkg/api/vdr.go, cmd/aries-agent-mobile/pkg/wrappers/command/vdr.go, cmd/aries-agent-mobile/pkg/wrappers/command/vdr_test.go, cmd/aries-agent-mobile/pkg/wrappers/rest/endpoints.go, cmd/aries-agent-mobile/pkg/wrappers/rest/vdr.go, cmd/aries-agent-mobile/pkg/wrappers/rest/vdr_test.go, cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/vdr/command.go, pkg/controller/command/vdr/command_test.go, pkg/controller/command/vdr/models.go, pkg/controller/rest/vdr/models.go, pkg/controller/rest/vdr/operation.go, pkg/controller/rest/vdr/operation_test.go
=> feat: Add create DID command

pkg/didcomm/dispatcher/outbound.go, pkg/didcomm/packager/package_test.go, pkg/didcomm/packager/packager.go, pkg/didcomm/packer/anoncrypt/pack.go, pkg/didcomm/packer/anoncrypt/pack_test.go, pkg/didcomm/packer/api.go, pkg/didcomm/packer/authcrypt/pack.go, pkg/didcomm/packer/authcrypt/pack_test.go, pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/packer/legacy/authcrypt/pack.go, pkg/didcomm/packer/legacy/authcrypt/unpack.go, pkg/didcomm/transport/transport_interface.go, pkg/doc/jose/common.go, pkg/doc/jose/encrypter.go, pkg/doc/jose/encrypter_decrypter_test.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context_test.go, pkg/mock/didcomm/mock_authcrypt.go, pkg/mock/didcomm/packer/noop.go, pkg/mock/didcomm/packer/noop_test.go
=> feat: add DIDComm supported envelope types

docs/rest/openapi_demo.md
=> docs: add vdr create docs

pkg/client/didexchange/client_test.go, pkg/controller/command/didexchange/command_test.go, pkg/controller/rest/didexchange/operation_test.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/doc/verifiable/common_test.go, pkg/framework/aries/api/vdr/vdr.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/mock/vdr/mock_vdr.go, pkg/vdr/httpbinding/vdr.go, pkg/vdr/key/creator.go, pkg/vdr/key/creator_test.go, pkg/vdr/peer/creator.go, pkg/vdr/peer/creator_test.go, pkg/vdr/registry.go, pkg/vdr/registry_test.go, pkg/vdr/verifiable_compat_test.go, pkg/vdr/web/creator.go, test/aries-js-worker/test/vdr/vdr.js, test/bdd/pkg/vdr/vdr_controller_steps.go
=> refactor: remove kms from vdr create

pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/client/vcwallet/contents.go, pkg/client/vcwallet/contents_test.go, pkg/client/vcwallet/kmsclient.go, pkg/client/vcwallet/models.go
- Implementation for universal wallet Issue interface.
- Support for Ed25519Signature2018, JSONWebSignature2020,
BbsBlsSignature2020
- Issue credential can happen only on unlocked wallet.
- Signer to use user profile based KMS.
- Fallback from VDR to profile based DID store while resolving DID.
- Validation on proof options (controller, verification method etc)
- Closes #2668
=> feat: VC wallet - Issue

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go
PR #2588 changed the way `myDID` and `theirDID` were fetched before invoking the message handlers: they are now fetched from the `did.ConnectionStore`. This created misalignment with `didexchange.Client.CreateConnection()` since it was not saving myDID nor theirDID to the `did.ConnectionStore`, rendering it ineffective and resulting in an error once an agent attempted to send a DIDComm message from a connection created using this method.
=> fix: ineffective didexchange.Client.CreateConnection()

test/component/storage/storage.go
=> test: Added additional common storage tests for Batch method

pkg/didcomm/packer/anoncrypt/pack_test.go, pkg/didcomm/packer/authcrypt/pack_test.go
This change enhances the JWE packers tests in order to print
real JWE envelopes with full keys for external testing (support interop)
=> chore: enhance packer tests for examples

pkg/client/messaging/client_test.go, pkg/client/vcwallet/client_test.go, pkg/controller/command/messaging/command_test.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/rest/messaging/operation_test.go, pkg/controller/rest/verifiable/operation_test.go, pkg/didcomm/protocol/mediator/service_test.go, pkg/framework/aries/api/vdr/vdr.go, pkg/internal/gomocks/framework/aries/api/vdr/mocks.gen.go, pkg/mock/vdr/mock_registry.go, pkg/mock/vdr/mock_vdr.go, pkg/vdr/httpbinding/resolver.go, pkg/vdr/key/resolver.go, pkg/vdr/key/vdr.go, pkg/vdr/peer/resolver.go, pkg/vdr/registry.go, pkg/vdr/registry_test.go, pkg/vdr/web/resolver.go, pkg/vdr/web/resolver_test.go, pkg/wallet/wallet_test.go
=> refactor: replace ResolveOption with Generic DIDMethodOption

pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/wallet/options.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: vc wallet verify

pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/wallet/options.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: verify presentation

pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: wallet.Verify - verify credentials inside presentation

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/rest/verifiable/operation_test.go, pkg/didcomm/protocol/middleware/issuecredential/middlewares.go, pkg/didcomm/protocol/middleware/presentproof/middlewares.go, pkg/doc/presexch/api_test.go, pkg/doc/verifiable/common.go, pkg/doc/verifiable/common_test.go, pkg/doc/verifiable/credential_jwt_proof_test.go, pkg/vdr/verifiable_compat_test.go, pkg/wallet/wallet.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> chore: rename DIDKeyResolver

docs/rest/openapi_demo.md, pkg/controller/command/vdr/command_test.go, pkg/controller/command/vdr/models.go
=> fix: create vdr did opts type

pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/wallet/models.go, pkg/wallet/options.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: vc wallet - derive credential

pkg/doc/jose/jwk.go, pkg/doc/jose/jwk_test.go
=> feat: add BBS+ JWK support

pkg/doc/jose/jwk.go, pkg/doc/jose/jwk_test.go
=> refactor: consolidate BBS JWK call with JWKFromPublicKey()

pkg/doc/jose/jwk.go, pkg/doc/jose/jwk_test.go, pkg/doc/util/jwkkid/kid_creator.go, pkg/doc/util/jwkkid/kid_creator_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/linked_data_proof_test.go, pkg/internal/gomocks/client/introduce/mocks.gen.go, pkg/internal/gomocks/client/issuecredential/mocks.gen.go, pkg/internal/gomocks/client/outofband/mocks.gen.go, pkg/internal/gomocks/client/presentproof/mocks.gen.go, pkg/internal/gomocks/controller/webnotifier/mocks.gen.go, pkg/internal/gomocks/didcomm/common/service/mocks.gen.go, pkg/internal/gomocks/didcomm/dispatcher/mocks.gen.go, pkg/internal/gomocks/didcomm/messenger/mocks.gen.go, pkg/internal/gomocks/didcomm/protocol/introduce/mocks.gen.go, pkg/internal/gomocks/didcomm/protocol/issuecredential/mocks.gen.go, pkg/internal/gomocks/didcomm/protocol/middleware/issuecredential/mocks.gen.go, pkg/internal/gomocks/didcomm/protocol/middleware/presentproof/mocks.gen.go, pkg/internal/gomocks/didcomm/protocol/presentproof/mocks.gen.go, pkg/internal/gomocks/framework/aries/api/vdr/mocks.gen.go, pkg/internal/gomocks/spi/storage/mocks.gen.go, pkg/internal/gomocks/store/did/mocks.gen.go, pkg/internal/gomocks/store/verifiable/mocks.gen.go, test/bdd/cmd/sidetree/main.go, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/didresolver/didresolver_steps.go, test/bdd/pkg/verifiable/verifiable_steps.go
this change also update mocks as per latest mockgen update and Go 1.16 update
closes #2709
=> feat: JWK support for both private/public BBS keys

pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/mock/storage/mock_store.go, pkg/wallet/contents.go, pkg/wallet/contents_test.go, pkg/wallet/models.go, pkg/wallet/query.go, pkg/wallet/query_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- PresentationExchange query support
- GetAll by content type support
- Closes #2712
- Closes #2713
=> feat: VC Wallet Query By PresentationExchange

pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go, pkg/wallet/models.go, pkg/wallet/options.go, pkg/wallet/query.go, pkg/wallet/query_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- Added DID authorization query type support from 'vp-request-spec'
- wallet Prove option to support presentation as input
- Closes #2721
=> feat: VC Wallet query - DID Auth

spi/storage/storage.go
=> feat: Storage interface support for sort order and initial page options

cmd/aries-agent-mobile/go.mod, cmd/aries-agent-rest/go.mod, cmd/aries-js-worker/go.mod, test/bdd/go.mod, test/component/go.mod, test/component/go.sum, test/component/storage/storage.go
=> test: Add common storage tests for sort order and initial page options

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go
- added create & update profile command controllers
=> feat: vc wallet command controller for managing profiles

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/wallet/kmsclient.go
=> feat: wallet lock/unlock command controller

test/bbs/test/bbs.js
=> ci: restore bbs interop test

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/wallet/contents.go, pkg/wallet/contents_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: wallet content management command controllers

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go
=> feat: wallet command controllers for issue, prove, verify, derive

pkg/client/vcwallet/client_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/wallet/options.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: wallet controller - option to prove presentation

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/controller/rest/vcwallet/models.go, pkg/controller/rest/vcwallet/operation.go, pkg/controller/rest/vcwallet/operation_test.go, pkg/wallet/wallet.go
=> feat: REST binding for vc wallet commands

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js
=> feat: JS command controller for VC wallet

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/rest/vcwallet/models.go, pkg/controller/rest/vcwallet/operation.go, pkg/controller/rest/vcwallet/operation_test.go
=> feat: wallet controller EDV & webkms customization

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go
=> feat: wallet command - get all by collection

pkg/client/didexchange/client_test.go, pkg/controller/command/didexchange/command_test.go, pkg/didcomm/common/service/destination.go, pkg/didcomm/common/service/destination_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/didcomm/protocol/outofband/invitation_default.go, pkg/didcomm/protocol/outofband/invitation_interop.go, pkg/didcomm/protocol/outofband/models.go, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/doc/did/serialize_default.go, pkg/doc/did/serialize_interop.go
=> feat: didexchange interop between acapy and afgo

pkg/doc/did/doc.go
=> fix: change EquivalentID to array

pkg/client/issuecredential/rfc0593/dependencies.go, pkg/client/issuecredential/rfc0593/event.go, pkg/client/issuecredential/rfc0593/event_test.go, pkg/didcomm/protocol/issuecredential/properties.go, pkg/didcomm/protocol/issuecredential/properties_test.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go, pkg/doc/signature/suite/bbsblssignature2020/suite.go
=> feat: RFC0593 - JSONLD credentials for issue-credential V2

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, go.mod, go.sum, pkg/crypto/tinkcrypto/crypto_test.go, pkg/crypto/tinkcrypto/primitive/bbs/bbs_signer_key_manager_test.go, pkg/crypto/tinkcrypto/primitive/composite/keyio/composite_key_export_import_test.go, pkg/mock/kms/mock_kms.go, test/bdd/go.sum
=> chore: update tink

pkg/client/issuecredential/rfc0593/dependencies.go, pkg/client/issuecredential/rfc0593/event.go, pkg/client/issuecredential/rfc0593/event_test.go, pkg/client/issuecredential/rfc0593/middleware.go, pkg/client/issuecredential/rfc0593/middleware_test.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/framework/aries/default.go, test/bdd/bddtests_test.go, test/bdd/features/rfc0593.feature, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/rfc0593/steps.go
=> test: RFC0593: Go SDK BDD tests

cmd/aries-agent-rest/startcmd/start.go, cmd/aries-agent-rest/startcmd/start_test.go, pkg/client/issuecredential/rfc0593/event.go, pkg/client/issuecredential/rfc0593/event_test.go, pkg/client/issuecredential/rfc0593/middleware.go, pkg/controller/command/errors.go, pkg/controller/command/issuecredential/command.go, pkg/controller/command/issuecredential/command_test.go, pkg/controller/command/rfc0593/command.go, pkg/controller/command/rfc0593/models.go, pkg/controller/controller.go, pkg/controller/controller_test.go, pkg/controller/rest/issuecredential/operation.go, pkg/controller/rest/issuecredential/operation_test.go, pkg/controller/rest/rfc0593/models.go, pkg/controller/rest/rfc0593/operation.go, pkg/controller/rest/rfc0593/operation_test.go, pkg/didcomm/protocol/issuecredential/states.go, test/bdd/bddtests_test.go, test/bdd/features/issue_credential_controller.feature, test/bdd/features/rfc0593_controller.feature, test/bdd/fixtures/agent-rest/docker-compose.yml, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go, test/bdd/pkg/rfc0593/steps_go.go, test/bdd/pkg/rfc0593/steps_rest.go
=> feat: RFC0593 REST API

pkg/kms/webkms/remotekms.go, pkg/kms/webkms/remotekms_test.go
Part of https://github.com/trustbloc/vct/issues/41
=> fix: CreateKeyStore returns an error.

pkg/controller/command/vdr/command.go, pkg/controller/command/vdr/command_test.go, pkg/controller/rest/vdr/models.go, pkg/controller/rest/vdr/operation.go, pkg/controller/rest/vdr/operation_test.go, test/aries-js-worker/test/vdr/vdr.js, test/aries-js-worker/test/verifiable/verifiable.js
- VDR command controller ResolveDID to return document resolution
response
- Closes #2817
=> feat: vdr command controller fix

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/controller/rest/vcwallet/models.go, pkg/controller/rest/vcwallet/operation.go, pkg/controller/rest/vcwallet/operation_test.go, pkg/wallet/models.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: vc wallet create key pair

cmd/aries-agent-mobile/go.mod, cmd/aries-agent-mobile/pkg/wrappers/storage/storage.go, cmd/aries-agent-rest/go.mod, cmd/aries-js-worker/go.mod, component/storage/edv/restprovider.go, component/storage/indexeddb/indexeddb.go, component/storage/leveldb/leveldb.go, component/storageutil/formattedstore/formattedstore.go, component/storageutil/mem/mem.go, pkg/wallet/storage.go, spi/storage/storage.go
=> feat: Add TotalItems method to Iterator interface

cmd/aries-agent-mobile/go.mod, cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.mod, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.mod, cmd/aries-js-worker/go.sum, test/bdd/go.mod, test/component/go.mod, test/component/go.sum, test/component/storage/storage.go
=> test: Add tests for Iterator TotalItems method

MAINTAINERS.md
=> chore: update active maintainer list

pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> feat: support published sov DIDs as returned by uniresolver

pkg/vdr/key/creator.go, pkg/vdr/key/creator_test.go, pkg/vdr/key/resolver.go, pkg/vdr/peer/creator.go, pkg/vdr/peer/resolver.go, pkg/wallet/wallet.go
fixed for DID key & peer
- Closes #2829
=> fix: 'null' contexts in document resolution responses

pkg/doc/jsonld/contexts.go, pkg/doc/jsonld/contexts/third_party/w3c-ccg.github.io/did_docres_v1.jsonld, pkg/doc/jsonld/document_loader_test.go
=> chore: add document resolution context to document loader

pkg/didcomm/protocol/didexchange/didex_interop.go, pkg/didcomm/protocol/didexchange/states.go, pkg/vdr/httpbinding/resolver.go, pkg/vdr/httpbinding/resolver_default.go, pkg/vdr/httpbinding/resolver_interop.go
=> fix: did sov support for implicit invitations

.github/workflows/test-suite.yml, pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go, pkg/doc/signature/suite/jsonwebsignature2020/suite.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/example_credential_test.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> feat: JsonWebKey2020 support

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/controller/rest/vcwallet/models.go, pkg/controller/rest/vcwallet/operation.go, pkg/controller/rest/vcwallet/operation_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: wallet - check profile exists

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go
=> feat: vcwallet - auth capability support for WebKMS & EDV unlock

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go
=> feat: vcwallet command controller - expire token option

pkg/wallet/storage.go, pkg/wallet/storage_test.go
=> fix: wallet - incorrect crypto for EDV with WebKMS profiles

pkg/vdr/fingerprint/fingerprint_test.go, pkg/vdr/key/creator.go, pkg/vdr/key/creator_test.go, pkg/vdr/key/resolver_test.go
Signed-off-by: david.stark <david.stark@securekey.com>
Added test cases to cover the changes to did:key NIST curve implementation from previous pull request.
=> added test cases for nist curves for did:key and fingerprint

pkg/mock/storage/mock_store.go
=> fix: Implemented iterator interface in pkg/mock/storage

pkg/didcomm/common/service/destination.go, pkg/didcomm/common/service/destination_default.go, pkg/didcomm/common/service/destination_interop.go, pkg/didcomm/common/service/destination_interop_test.go, pkg/didcomm/common/service/destination_test.go, pkg/didcomm/protocol/didexchange/models.go
=> chore: refactor CreateDestination interop behaviour behind flag

pkg/vdr/web/did.go, pkg/vdr/web/resolver.go, pkg/vdr/web/resolver_test.go
=> feat: add option to use http for web vdr

pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> fix: resolve local did key references when handling request via implicit invitation

.github/dependabot.yml
=> ci: npm dependabot config

cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, go.mod, go.sum, pkg/crypto/primitive/bbs12381g2pub/bbs.go, pkg/crypto/primitive/bbs12381g2pub/fr.go, pkg/crypto/primitive/bbs12381g2pub/keys.go, pkg/crypto/primitive/bbs12381g2pub/proof_of_knowledge.go, pkg/crypto/primitive/bbs12381g2pub/signature.go, pkg/crypto/primitive/bbs12381g2pub/signature_proof.go, test/bdd/go.sum
=> chore: update to latest bbs12-381 module

cmd/aries-agent-mobile/go.mod, cmd/aries-agent-mobile/pkg/wrappers/command/aries.go, cmd/aries-agent-mobile/pkg/wrappers/command/introduce_test.go, cmd/aries-agent-mobile/pkg/wrappers/config/options.go
- added document loader as an option for agent mobile
=> feat: Document loader for agent-mobile

pkg/kms/webkms/crypto_box.go, pkg/kms/webkms/crypto_box_test.go, pkg/kms/webkms/remotekms.go, pkg/kms/webkms/remotekms_test.go
=> fix: Checks API error (webkms)

.github/workflows/build.yml, cmd/aries-agent-mobile/pkg/wrappers/storage/storage_test.go, test/aries-js-worker/test/didexchange/didexchange_e2e.js, test/aries-js-worker/test/issuecredential/issuecredential.js
=> fix: Unit tests for mobile

pkg/framework/context/context.go, pkg/framework/context/context_test.go
=> fix: Fixes DIDs resolution when inbound message received.

pkg/crypto/webkms/remotecrypto.go, pkg/kms/webkms/crypto_box.go, pkg/kms/webkms/remotekms.go
=> switch remote kms logs from info to debug

pkg/doc/presexch/definition.go, pkg/doc/presexch/package_test.go, pkg/doc/presexch/testdata/contexts/mdl-broken.jsonld, pkg/doc/presexch/testdata/contexts/mdl-v1.jsonld
=> fix: schema uri matching handles IRIs expanded in nested contexts

docs/jsonld_context.md
=> docs: JSON-LD Context API

test/component/storage/storage.go
=> test: Additional common storage tests

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/controller/rest/vcwallet/models.go, pkg/controller/rest/vcwallet/operation.go, pkg/controller/rest/vcwallet/operation_test.go, pkg/mock/didcomm/protocol/presentproof/mock_presentproof.go, pkg/wallet/options.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- Implemented Universal wallet interfaces discussed in
https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/99
- Added bindings for SDK, REST, JS
- Closes #2928
=> feat: WACI holder APIs for vcwallet

docs/vc_wallet.md
- added docs for connect, proposePresentation & presentProof interfaces
in vcwallet.
- part of #2433
=> docs: vcwallet didcomm interfaces

cmd/aries-agent-mobile/go.mod, cmd/aries-agent-mobile/go.sum, cmd/aries-agent-rest/go.sum, cmd/aries-js-worker/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Updated json-gold module

docs/jsonld_context.md, pkg/store/ld/context_store.go, pkg/store/ld/context_store_test.go
=> fix: context store Import when underlying storage is mysql

pkg/vdr/httpbinding/resolver.go
=> fix: add close request

pkg/controller/command/ld/command.go, pkg/store/ld/remote_provider_store.go, pkg/store/ld/remote_provider_store_test.go
=> fix: set config for remote provider store

test/component/storage/storage.go
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
=> test: Add unit tests for storing JSON strings

pkg/vdr/fingerprint/fingerprint.go, pkg/vdr/fingerprint/fingerprint_test.go
=> Add support for X25519/Ed25519 keys in fingerprint.CreateDIDKeyByJwk()

test/component/storage/storage.go
=> fix: Common storage query test methods could not be called directly

pkg/didcomm/common/service/destination.go, pkg/didcomm/common/service/destination_default.go, pkg/didcomm/common/service/destination_test.go, pkg/didcomm/dispatcher/outbound.go, pkg/didcomm/dispatcher/outbound_test.go, pkg/didcomm/packager/packager.go, pkg/didcomm/packager/packager_test.go, pkg/didcomm/packer/anoncrypt/pack.go, pkg/didcomm/packer/anoncrypt/pack_test.go, pkg/didcomm/packer/api.go, pkg/didcomm/packer/authcrypt/pack.go, pkg/didcomm/packer/authcrypt/pack_test.go, pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/doc/jose/decrypter.go, pkg/doc/jose/kid/resolver/resolver.go, pkg/doc/jose/kid/resolver/resolver_test.go, pkg/doc/util/jwkkid/kid_creator.go, pkg/doc/util/jwkkid/kid_creator_test.go, pkg/framework/aries/framework.go, pkg/mock/diddoc/mock_diddoc.go
closes #2953
And introduce DIDComm V2 service bloc in the did Doc.
=> feat: kid/skid as didDoc.keyAgreement.ID

pkg/didcomm/packer/anoncrypt/pack_test.go, pkg/didcomm/packer/authcrypt/pack.go, pkg/didcomm/packer/authcrypt/pack_test.go, pkg/didcomm/transport/ws/pool.go, pkg/doc/jose/kid/resolver/resolver.go, pkg/doc/jose/kid/resolver/resolver_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, test/bdd/features/didexchange_e2e_sdk.feature
Also update new Authcrypt packer to return FromKey in Unpack() as it's needed in the framework to fetch DID connections.
=> feat: update context getDIDs() with didComm V2 format

spi/storage/storage.go
Added clarification about how JSON-formatted objects are treated.
=> docs: Update to SPI documentation for Store Put method

pkg/controller/command/presentproof/command.go, pkg/controller/command/presentproof/command_test.go, pkg/controller/command/presentproof/models.go, pkg/controller/rest/presentproof/models.go, pkg/controller/rest/presentproof/operation.go, pkg/controller/rest/presentproof/operation_test.go
=> feat: Present Proof v3 - REST API

cmd/aries-agent-mobile/pkg/wrappers/rest/aries_test.go, pkg/didcomm/packager/packager.go, pkg/didcomm/packer/anoncrypt/pack.go, pkg/didcomm/packer/anoncrypt/pack_test.go, pkg/didcomm/packer/authcrypt/pack.go, pkg/didcomm/packer/authcrypt/pack_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go
=> fix: Gets MyDID and TheirDID when kid is KeyAgreement.ID

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/didcomm/common/service/did_comm_msg.go, pkg/didcomm/common/service/service_test.go, pkg/didcomm/protocol/presentproof/service.go, test/aries-js-worker/fixtures/docker-compose.yml, test/bdd/agent/agent_sdk_steps.go, test/bdd/features/presentproof.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
=> test: Present Proof v3 - BDD tests (sdk)

pkg/doc/did/doc.go
=> chore: add anchorOrigin to MethodMetadata

pkg/doc/did/doc.go
=> fix: anchor origin to string

cmd/aries-agent-rest/startcmd/start.go, cmd/aries-agent-rest/startcmd/start_test.go
=> feat: add mediatype profiles and key types to agent-rest

.github/workflows/version_var.sh, CHANGELOG.md
=> chore: Release 0.1.7

.github/workflows/version_var.sh
=> chore: complete release 0.1.7

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go
=> chore: increase coverage for verifiable command fix

pkg/didcomm/packager/packager.go, pkg/didcomm/packager/packager_test.go, pkg/didcomm/protocol/didexchange/didex_default.go, pkg/didcomm/protocol/didexchange/didex_interop.go, pkg/didcomm/protocol/didexchange/states.go, pkg/mock/diddoc/mock_diddoc.go
=> fix: add interop support to new didexchange key handling

pkg/client/messaging/client_test.go, pkg/controller/command/messaging/command_test.go, pkg/controller/rest/messaging/operation_test.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/framework/aries/api/vdr/vdr.go, pkg/vdr/httpbinding/resolver.go, pkg/vdr/httpbinding/resolver_test.go, pkg/wallet/contents_test.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/didresolver/didresolver_steps.go
=> chore: add error for did not found

pkg/didcomm/protocol/didexchange/keys.go, pkg/didcomm/protocol/didexchange/service.go, pkg/vdr/fingerprint/fingerprint.go, pkg/vdr/peer/creator.go, test/bdd/agent/agent_sdk_steps.go, test/bdd/features/didexchange_public_did.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/didresolver/didresolver_steps.go, test/bdd/pkg/introduce/introduce_sdk_steps.go, test/bdd/pkg/outofband/outofband_sdk_steps.go, test/bdd/pkg/sidetree/sidetree.go
=> fix: dynamic keyType, keyAgreementType and mediaTypeProfiles in bdd tests

spi/storage/storage.go
=> docs: Added optional multi-tag querying to SPI store query docs

pkg/didcomm/protocol/issuecredential/states.go
=> fix: include status in issue-cred ack

pkg/crypto/tinkcrypto/crypto.go, pkg/kms/localkms/localkms_test.go
**Title:**
Fix tinkcrypto.Decrypt to work properly for rotated keys.
**Summary:**
Iterate through all key prefixes in the keyset to try to decrypt data.
=> fix: now decrypt work properly for rotated keys

pkg/controller/rest/presentproof/models.go, pkg/controller/rest/presentproof/operation.go, pkg/controller/rest/presentproof/operation_test.go, test/bdd/features/presentproof_controller.feature, test/bdd/pkg/presentproof/presentproof_controller_steps.go
- fixed issues where request body payloads are being ignored by present
proof REST controllers
=> fix: present proof issues in REST controllers

pkg/client/issuecredential/client.go, pkg/client/issuecredential/client_test.go, pkg/client/issuecredential/example_test.go, pkg/client/issuecredential/rfc0593/event.go, pkg/client/issuecredential/rfc0593/event_test.go, pkg/client/issuecredential/rfc0593/middleware.go, pkg/client/issuecredential/rfc0593/middleware_test.go, pkg/controller/command/rfc0593/command.go, pkg/controller/rest/rfc0593/operation_test.go, pkg/didcomm/protocol/issuecredential/models.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go, pkg/didcomm/protocol/middleware/issuecredential/middlewares_test.go, test/bdd/pkg/outofband/outofband_sdk_steps.go
V3 spec: https://github.com/trustbloc/wallet/tree/main/docs/waci-credential-manifest/issue_credential
=> feat: add issue credential V3

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/issuecredential/command.go, pkg/controller/command/issuecredential/command_test.go, pkg/controller/command/issuecredential/models.go, pkg/controller/rest/issuecredential/models.go, pkg/controller/rest/issuecredential/operation.go, pkg/controller/rest/issuecredential/operation_test.go
=> feat: add issue credential V3 to command

pkg/didcomm/protocol/middleware/issuecredential/middlewares.go, pkg/didcomm/protocol/middleware/issuecredential/middlewares_test.go, scripts/check_go_integration.sh, test/bdd/features/issue_credential.feature, test/bdd/features/issue_credential_controller.feature, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go
=> feat: add bdd test for issue credential V3

Makefile, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go, scripts/check_go_integration.sh, test/bdd/features/presentproof_controller.feature
=> chore: fix bdd test run flag

Makefile, test/aries-js-worker/test/issuecredential/issuecredential.js
=> feat: add issue credential V3 wasm test

pkg/client/outofbandv2/client.go, pkg/client/outofbandv2/client_test.go, pkg/client/outofbandv2/doc.go, pkg/client/outofbandv2/example_test.go, pkg/controller/command/outofband/command.go, pkg/didcomm/common/model/forward.go, pkg/didcomm/common/service/constants.go, pkg/didcomm/dispatcher/api.go, pkg/didcomm/dispatcher/outbound/outbound.go, pkg/didcomm/protocol/mediator/service.go, pkg/didcomm/protocol/outofband/service.go, pkg/didcomm/protocol/outofbandv2/models.go, pkg/didcomm/protocol/outofbandv2/service.go, pkg/didcomm/protocol/outofbandv2/service_test.go, pkg/didcomm/protocol/outofbandv2/states.go, pkg/didcomm/protocol/outofbandv2/states_test.go, pkg/didcomm/transport/media_type.go, pkg/framework/context/context.go, pkg/mock/didcomm/protocol/mock_protocol.go, test/bdd/features/aries_mediator_e2e_controller.feature, test/bdd/pkg/outofband/outofband_controller_steps.go
This change introduces OOB V2 service and client first draft.
It also injects the Accept oob property in the BDD tests.
=> feat: OOB V2

pkg/doc/credentialmanifest/credentialmanifest.go, pkg/doc/credentialmanifest/credentialmanifest_test.go, pkg/doc/credentialmanifest/testdata/valid_credential.jsonld, pkg/doc/credentialmanifest/testdata/valid_credential_manifest.json
=> feat: Credential Manifest

pkg/didcomm/protocol/outofbandv2/service.go, pkg/didcomm/protocol/outofbandv2/service_test.go, pkg/mock/didcomm/protocol/mock_protocol.go
=> feat: add target service triggering in OOBv2 invitations

pkg/controller/command/vdr/command.go, pkg/controller/command/vdr/command_test.go, pkg/controller/rest/vdr/models.go, pkg/controller/rest/vdr/operation.go, pkg/controller/rest/vdr/operation_test.go, test/aries-js-worker/test/vdr/vdr.js, test/aries-js-worker/test/verifiable/verifiable.js
=> fix: incorrect DID resolution response from vdr controller

pkg/doc/did/doc.go
=> feat: Add unpublishedOperations and publishedOperations to DID Doc

pkg/doc/did/doc.go
=> fix: TransactionTime in UnpublishedOperations and PublishedOperations

pkg/client/connection/client.go, pkg/controller/command/connection/command.go, pkg/controller/command/connection/models.go, pkg/controller/command/errors.go, pkg/controller/controller.go, pkg/controller/rest/connection/models.go, pkg/controller/rest/connection/operation.go, pkg/didcomm/didrotate/didrotate_test.go, pkg/didcomm/didrotate/rotate.go, pkg/didcomm/dispatcher/inbound/inbound_message_handler.go, pkg/didcomm/dispatcher/inbound/inbound_message_handler_test.go, pkg/didcomm/dispatcher/outbound/outbound.go, pkg/didcomm/dispatcher/outbound/outbound_test.go, pkg/doc/jose/jws.go, pkg/doc/jose/jws_test.go, pkg/framework/aries/framework.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/mock/provider/mock_provider.go, pkg/store/connection/connection_lookup.go, test/bdd/bddtests_test.go, test/bdd/features/didcommv2.feature, test/bdd/pkg/connection/connection_sdk_steps.go
=> feat: didcomm v2 DID rotation

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, test/bdd/agent/agent_sdk_steps.go, test/bdd/features/aries_didcommv2_mediator_e2e_sdk.feature, test/bdd/pkg/didexchange/didexchange_sdk_steps.go
=> feat: support mediator bdd tests with didcomm v2

pkg/client/issuecredential/client.go, pkg/client/issuecredential/client_test.go, pkg/client/issuecredential/example_test.go, pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/controller/command/issuecredential/command.go, pkg/controller/command/issuecredential/command_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/rest/issuecredential/operation_test.go, pkg/controller/rest/vcwallet/operation_test.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/middleware/issuecredential/middlewares.go, pkg/didcomm/protocol/middleware/issuecredential/middlewares_test.go, pkg/internal/gomocks/client/issuecredential/mocks.gen.go, pkg/mock/didcomm/protocol/issuecredential/mock_issuecredential.go, pkg/wallet/models.go, pkg/wallet/options.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go
based on [WACI Issuance in Universal
Wallet](https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/101)
- added propose credential interface
- added request credential interface
- added tests
- Closes #3073
=> feat: WACI issuance flow interfaces

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/controller/rest/vcwallet/models.go, pkg/controller/rest/vcwallet/operation.go, pkg/controller/rest/vcwallet/operation_test.go, pkg/wallet/wallet.go
- added JS, REST command controllers for wallet issuance interfaces.
- Part of  #3073
=> feat: command controllers for wallet issuance flow

pkg/doc/did/doc.go
=> fix: don't set recipientKeys and routingKeys if empty

spi/storage/storage.go
- Added the ability to set an option on a put operation that indicates that the key being used does not already exist in the database. For some storage providers, knowing this beforehand allows them to operate faster.
- Also updated some other documentation in the storage interface to make it explicit that data is normally overwritten if an existing key is being used.
=> feat: Added option for optimizing storage batch put operations

test/bdd/go.mod, test/component/go.mod, test/component/go.sum, test/component/storage/storage.go
=> test: Add tests for storage batch put operation IsNewKey option

pkg/client/issuecredential/client.go, pkg/client/issuecredential/client_test.go, pkg/controller/command/issuecredential/command.go, pkg/controller/command/issuecredential/command_test.go, pkg/controller/command/issuecredential/models.go, pkg/controller/rest/issuecredential/models.go, pkg/controller/rest/issuecredential/operation.go, pkg/controller/rest/issuecredential/operation_test.go, pkg/didcomm/common/model/ack.go, pkg/didcomm/protocol/issuecredential/models.go, pkg/didcomm/protocol/issuecredential/params.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/presentproof/states.go, pkg/internal/gomocks/client/issuecredential/mocks.gen.go, pkg/mock/didcomm/protocol/issuecredential/mock_issuecredential.go, pkg/wallet/wallet.go, test/bdd/features/issue_credential.feature, test/bdd/features/issue_credential_controller.feature, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go, test/bdd/pkg/outofband/outofband_sdk_steps.go
- added support for webredirect info for issue credential, decline
proposal & decline request steps.
- added SDK & controller bdd tests
- Closes #3099
=> feat: webredirectinfo support in issue credential protocol

pkg/didcomm/protocol/outofbandv2/models.go, pkg/wallet/invitation.go
=> refactor: update goal_code invalid name for OOB V2

pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go
=> fix: issuecredential empty metadata request should not override default message

pkg/vdr/httpbinding/resolver.go, pkg/vdr/httpbinding/resolver_test.go, pkg/vdr/httpbinding/vdr.go
=> chore: add custom http client for vdr resolve

pkg/doc/cm/credentialapplication_test.go, pkg/doc/cm/credentialfulfillment.go, pkg/doc/cm/credentialfulfillment_test.go, pkg/doc/cm/credentialmanifest.go, pkg/doc/cm/credentialmanifest_test.go, pkg/doc/cm/testdata/VP_with_drivers_license_VC_and_credential_fulfillment.json, pkg/doc/cm/testdata/VP_with_drivers_license_VC_and_display_data.json
=> feat: Method to resolve Data Display Descriptors from VP

scripts/check_go_integration.sh, test/bdd/bddtests_test.go, test/bdd/features/didcommv2.feature, test/bdd/features/webkms.feature, test/bdd/pkg/connection/connection_sdk_steps.go
=> fix: unnoticed bdd test error in didcommv2 implicit connection

pkg/didcomm/common/middleware/middleware.go, pkg/didcomm/common/middleware/middleware_test.go, pkg/didcomm/dispatcher/inbound/inbound_message_handler.go, pkg/didcomm/dispatcher/inbound/inbound_message_handler_test.go, pkg/didcomm/dispatcher/outbound/outbound.go, pkg/didcomm/dispatcher/outbound/outbound_test.go, pkg/didcomm/protocol/mediator/service.go, pkg/didcomm/protocol/mediator/service_test.go, pkg/didcomm/protocol/messagepickup/service.go, pkg/didcomm/protocol/messagepickup/service_test.go, pkg/framework/aries/framework.go
...even if message is not a DIDCommMsgMap.
=> fix: messages may need anoncrypt send if initial message with peer DID

pkg/didcomm/transport/ws/pool.go, pkg/didcomm/transport/ws/pool_test.go, test/bdd/agent/agent_sdk_steps.go, test/bdd/features/aries_didcommv2_mediator_e2e_sdk.feature, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/outofband/outofband_sdk_steps.go
=> fix: add KeyAgreement IDs from didcomm v2 peer DIDs to websocket key map

pkg/doc/cm/credentialmanifest.go, pkg/doc/cm/credentialmanifest_test.go
=> feat: credential manifest resolve - support for arbitrary type

pkg/doc/cm/credentialmanifest.go
Reworked the existing Credential Manifest and Output Descriptor validation methods so that they can be called directly outside of the cm package without requiring json.Unmarshal to be called. This gives callers more flexibility and supports more use cases.
=> feat: Export Credential Manifest and Output Descriptor validate methods

pkg/didcomm/common/service/did_comm_msg.go, pkg/didcomm/protocol/presentproof/params.go, pkg/didcomm/protocol/presentproof/params_test.go, pkg/wallet/invitation.go, pkg/wallet/invitation_test.go
=> fix: smooth out behaviour of version-agnostic didcomm models

pkg/didcomm/dispatcher/outbound/outbound.go, pkg/didcomm/dispatcher/outbound/outbound_test.go
=> feat: add pthid to the didcomm v2 message replying to an oobv2 invitation

pkg/doc/cm/credentialmanifest.go, pkg/doc/cm/credentialmanifest_test.go
- specify schema along with resolved values which will be helpful for
rendering resolved values
- Part of #3092
=> feat: credential manifest resolve - specify schema

internal/testdata/samples/wallet/VP_with_multiple_VCs_and_credential_fulfillment.json, internal/testdata/samples/wallet/credential_manifest_multiple_vcs.json, internal/testdata/samples/wallet/sample_bbs_frame.json, internal/testdata/samples/wallet/sample_content_keybase58.json, internal/testdata/samples/wallet/sample_content_metadata.json, internal/testdata/samples/wallet/sample_docresolution_response.json, internal/testdata/samples/wallet/sample_invalid_did.json, internal/testdata/samples/wallet/sample_presentation.json, internal/testdata/samples/wallet/sample_query_by_example.json, internal/testdata/samples/wallet/sample_query_by_frame.json, internal/testdata/samples/wallet/sample_udc_bbsvc_signed.json, internal/testdata/samples/wallet/sample_udc_vc.json, internal/testdata/samples/wallet/sample_udc_vc_signed.json, internal/testdata/samples/wallet/sample_udc_vc_with_credschema.json, internal/testdata/testdata.go, pkg/client/vcwallet/client.go, pkg/client/vcwallet/client_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/controller/rest/vcwallet/models.go, pkg/controller/rest/vcwallet/operation.go, pkg/controller/rest/vcwallet/operation_test.go, pkg/wallet/contents_test.go, pkg/wallet/options.go, pkg/wallet/query_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- added new resolve credential manifest interface to resolve
fulfillments and credentials
- refactores testdata files to avoid duplicate testdata files across
various packages
- Closes #3120
=> feat: credential manifest support in vcwallet

pkg/client/outofbandv2/client.go, pkg/client/outofbandv2/client_test.go, pkg/controller/command/outofbandv2/command.go, pkg/controller/command/outofbandv2/command_test.go, pkg/controller/command/outofbandv2/models.go, pkg/controller/rest/outofbandv2/models.go, pkg/controller/rest/outofbandv2/operation_test.go, pkg/didcomm/common/middleware/middleware.go, pkg/didcomm/common/middleware/middleware_test.go, pkg/didcomm/common/peerdid/creator.go, pkg/didcomm/protocol/outofbandv2/service.go, pkg/didcomm/protocol/outofbandv2/service_test.go, pkg/internal/gomocks/client/outofbandv2/mocks.gen.go, pkg/mock/didcomm/protocol/mock_protocol.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: include router connections in oobv2 acceptinvitation peer DID

test/bdd/bddtests_test.go, test/bdd/features/waci_issuance_didcomm_v1.feature, test/bdd/features/waci_issuance_didcomm_v2.feature, test/bdd/pkg/waci/common.go, test/bdd/pkg/waci/waci_issuance_didcomm_v1_sdk_steps.go, test/bdd/pkg/waci/waci_issuance_didcomm_v2_sdk_steps.go
=> test: WACI Issuance BDD tests for Go SDK using DIDComm V1/Issue Cred V2

pkg/didcomm/protocol/issuecredential/params.go, pkg/didcomm/protocol/issuecredential/params_test.go, pkg/didcomm/protocol/presentproof/params.go, pkg/didcomm/protocol/presentproof/params_test.go
Also refactors present-proof params for consistency.
=> fix: issue-credential params support unmarshaling from DIDCommMsg

cmd/aries-agent-rest/startcmd/start.go, cmd/aries-agent-rest/startcmd/start_test.go, pkg/didcomm/transport/ws/inbound.go, pkg/didcomm/transport/ws/inbound_test.go, pkg/framework/aries/defaults/defaults.go, pkg/framework/aries/defaults/defaults_test.go
=> feat: support for websocket read limit

pkg/didcomm/protocol/presentproof/service.go
=> fix: use thread id for present-proof PIID, except in problem report

pkg/didcomm/protocol/presentproof/service.go, pkg/didcomm/protocol/presentproof/states.go
=> fix: add present-proof webredirect v2 properties to Done/Abandoned state props

pkg/crypto/webkms/remotecrypto.go, pkg/didcomm/packer/authcrypt/pack.go, scripts/check_go_integration.sh, test/bdd/features/verifiable_credential.feature
=> fix: auth crypt packer

scripts/check_go_integration.sh, test/bdd/agent/agent_sdk_steps.go, test/bdd/features/aries_didcommv2_mediator_e2e_sdk.feature, test/bdd/features/didcomm_remotecrypto.feature, test/bdd/features/didexchange_e2e_sdk_didcommv2.feature, test/bdd/features/webkms.feature, test/bdd/pkg/webkms/webkms_steps.go
=> fix: didcomm with webkms tests and bugfixes

pkg/doc/cm/credentialmanifest.go, pkg/doc/cm/credentialmanifest_test.go
=> feat: credential manifest - include style in resolved results

pkg/didcomm/dispatcher/inbound/inbound_message_handler.go
=> fix: allow didcomm v1 messages to use didcomm v2 from-did

pkg/controller/command/kms/command.go, pkg/controller/command/kms/command_test.go, pkg/kms/localkms/localkms_test.go, pkg/kms/localkms/privkey_import.go
=> feat: /kms/import supports importing ecdhkw private keys

pkg/vdr/httpbinding/resolver.go, pkg/vdr/httpbinding/resolver_test.go
=> feat: add version id and version time to resolve DID

pkg/doc/did/doc.go
=> chore: add versionId to DocumentMetadata

cmd/aries-agent-mobile/README.md
=> docs: remove outdated demo app link

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/doc/ldcontext/embed/embed_contexts.go, pkg/doc/ldcontext/embed/third_party/digitalbazaar.github.io/ed25519-signature-2020-v1.jsonld, pkg/doc/signature/suite/ed25519signature2020/public_key_verifier.go, pkg/doc/signature/suite/ed25519signature2020/public_key_verifier_test.go, pkg/doc/signature/suite/ed25519signature2020/suite.go, pkg/doc/signature/suite/ed25519signature2020/suite_crypto_test.go, pkg/doc/signature/suite/ed25519signature2020/suite_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/testdata/valid_credential.jsonld, test/bdd/go.mod, test/bdd/go.sum
=> feat: add support for ed25519signature2020

pkg/doc/verifiable/embedded_proof.go
=> chore: add ed25519Signature2020 to embedded proof

pkg/doc/signature/verifier/public_key_verifier.go
=> fix: ECDSASignatureVerifier

pkg/store/ld/context_store.go, pkg/store/ld/context_store_test.go
=> fix: remove batch store in ld store

docs/vc_wallet.md
=> chore: update vcwallet docs

.github/workflows/version_var.sh
=> chore: complete release 0.1.8 and prepare 0.1.9

docs/concepts/02_standards.md
- added credential manifest specification reference
=> chore: updates to standards doc

pkg/doc/did/doc.go
=> chore: rename operationRequest to operation

pkg/doc/ldcontext/embed/embed_contexts.go, pkg/doc/ldcontext/embed/third_party/w3c-ccg.github.io/revocationList2021.jsonld
=> chore: add revocation list 2021 context

pkg/doc/ldcontext/embed/embed_contexts.go
=> fix: vc-revocation-list-2021 context

pkg/kms/localkms/localkms.go
=> feat: add HealthCheck method to localkms

test/component/storage/storage.go
=> test: Option to skip the "TestProviderOpenStoreSetGetConfig" tests

cmd/aries-js-worker/go.sum, component/storage/edv/go.mod, component/storage/edv/go.sum, component/storage/edv/models.go, component/storage/edv/restclient.go, component/storage/edv/restprovider.go, component/storage/edv/restprovider_test.go, scripts/start_edv_test_docker_images.sh
closes #2492
Also updated TrustBloc EDV image used for tests and removed some out-of-date comments.
=> feat: Use new EDV add index endpoint when setting store config

pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/packer/legacy/authcrypt/pack.go, pkg/didcomm/protocol/mediator/service.go, pkg/didcomm/protocol/mediator/service_test.go
=> chore: create didcomm v1 and v2 keys in mediator service

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/doc/did/testdata/valid_doc.jsonld
Signed-off-by: Baha Shaaban [baha.shaaban@securekey.com](mailto:baha.shaaban@securekey.com)
=> fix: did doc parsing to properly distinguish V1 vs V2 types

pkg/common/model/endpoint.go, pkg/doc/did/doc.go
=> chore: add is did comm v2 method to service endpoint

pkg/didcomm/common/service/destination_interop.go, pkg/didcomm/protocol/didexchange/states.go, pkg/doc/did/serialize_interop.go, pkg/vdr/peer/creator.go
=> feat: interop support for did service refactor

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/models.go
=> feat: vcwallet support for GNAP authorization

scripts/check_go_integration.sh, test/bdd/features/outofband_controller.feature, test/bdd/features/outofband_e2e_sdk.feature, test/bdd/features/outofbandv2_controller.feature, test/bdd/features/outofbandv2_e2e_sdk.feature
=> fix: bdd test ci

pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go
=> feat: allow custom GNAP header signer in vcwallet command

pkg/didcomm/protocol/mediator/models.go, pkg/didcomm/protocol/mediator/service.go, pkg/didcomm/protocol/mediator/service_test.go, pkg/didcomm/transport/media_type.go, scripts/check_go_integration.sh, test/bdd/features/aries_didcommv2_mediator_e2e_sdk.feature, test/bdd/features/aries_mediator_e2e_sdk.feature
=> feat: mediator supports didcomm v1/v2 per-connection

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, pkg/doc/presexch/example_v1_test.go, pkg/doc/presexch/example_v2_test.go, pkg/doc/presexch/schema.go
**Title:**
Presentation exchange v2
https://github.com/hyperledger/aries-framework-go/issues/3297
**Summary:**
Added support of changes from the latest presentation exchange draft https://identity.foundation/presentation-exchange/
=> feat: support of presentation exchange v2.

pkg/client/issuecredential/rfc0593/dependencies.go, pkg/client/issuecredential/rfc0593/event.go, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/rest/verifiable/operation_test.go, pkg/didcomm/protocol/middleware/presentproof/middlewares.go, pkg/doc/did/doc_test.go, pkg/doc/presexch/definition_test.go, pkg/doc/signature/proof/jws.go, pkg/doc/signature/proof/jws_test.go, pkg/doc/signature/signer/signer.go, pkg/doc/signature/suite/suite.go, pkg/doc/signature/suite/suite_crypto.go, pkg/doc/signature/suite/suite_test.go, pkg/doc/util/signature/api.go, pkg/doc/util/signature/internal/signer/crypto_signer.go, pkg/doc/util/signature/internal/signer/ecdsa.go, pkg/doc/util/signature/internal/signer/ed25519.go, pkg/doc/util/signature/internal/signer/rsa.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/example_support_test.go, pkg/doc/verifiable/jws.go, pkg/doc/verifiable/test-suite/verifiable_suite_test.go, pkg/vdr/verifiable_compat_test.go, pkg/wallet/kmsclient.go, test/bbs/src/support_signer.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go, test/bdd/pkg/verifiable/signer.go
=> fix: JWS algorithm for signature suite 

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/presentation_jwt.go
=> fix: vc subject marshal

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/doc/util/signature/internal/signer/crypto_signer.go, pkg/doc/util/signature/internal/signer/crypto_signer_test.go, pkg/wallet/kmsclient.go, pkg/wallet/kmsclient_test.go
=> feat: implement signer.Alg()

pkg/didcomm/common/service/destination_interop.go
=> fix: fix afgo interop build

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_jwt.go, pkg/doc/verifiable/credential_jwt_proof_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/test-suite/verifiable_suite_test.go, pkg/wallet/models.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: wallet.Issue supports jwtvc, verifiable.Credential can hold a jwtvc

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, pkg/doc/presexch/example_v1_test.go, pkg/doc/presexch/example_v2_test.go
=> feat: support multi-format VC in presentation exchange

pkg/didcomm/protocol/legacyconnection/service.go, pkg/didcomm/protocol/legacyconnection/states.go, pkg/didcomm/protocol/legacyconnection/states_test.go, test/bdd/bddtests_test.go, test/bdd/features/legacyconnection_e2e_controller.feature, test/bdd/pkg/legacyconnection/legacyconnection_controller_steps.go
**Title:**
Add BDD test for legacy-connection protocol
**Summary:**
- Add BDD test for legacy-connection protocol. Edge to edge case is fully implemented. Case through mediator is implemented partially (Only steps are added. Need to add .feature file to run test)
- Make a few refactoring
Related to #3301
=> feat: Add BDD test for legacy-connection protocol

pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_jwt.go, pkg/doc/verifiable/presentation_jwt_proof_test.go, pkg/wallet/contents.go, pkg/wallet/contents_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> feat: wallet Prove supports creating JWT presentations.

pkg/doc/presexch/definition.go, test/bdd/features/wallet_jsonld.feature, test/bdd/pkg/walletjsonld/credential.go, test/bdd/pkg/walletjsonld/presentation.go, test/bdd/pkg/walletjsonld/query.go, test/bdd/pkg/walletjsonld/wallet_steps.go
Also fixes an issue with pEx JWTVC constraint filtering.
=> test: add JWTVC coverage to wallet VC bdd tests

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go, scripts/check_go_integration.sh, test/bdd/features/presentproof.feature, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
=> test: jwt format tests in presentation exchange

pkg/doc/didconfig/didconfig.go, pkg/doc/didconfig/didconfig_test.go
Add validation for domain linkage credential in JWT format for did configuration.
Closes #3377
=> feat: Add validation for domain linkage credential in JWT format for did configuration

pkg/didcomm/protocol/didexchange/didex_interop.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/didcomm/protocol/legacyconnection/states.go, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/doc/did/schema.go, pkg/doc/did/testdata/valid_doc.jsonld, pkg/internal/didcommutil/util.go, pkg/internal/didcommutil/util_test.go, pkg/vdr/verifiable_compat_test.go
Service type property MUST be a string or a set of strings.
Closes #3383
=> fix: Service type property MUST be a string or a set of strings.

pkg/client/didconfig/didconfig.go, pkg/client/didconfig/didconfig_test.go, pkg/doc/didconfig/didconfig.go
Did configuration client will:
- retrieve did configuration from domain
- verify requested did and domain against did configuration
Closes #3390
=> feat: Add did configuration client

pkg/doc/jose/jws.go
- During unmarshal and marshal jws header we can't generate same header base64 string that we recieved because the order of json will be different and this will casue to have different base64 string.
- Solution use the original header base64 string for verify
=> fix: jws header

pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go
=> fix: id format in vp

pkg/doc/presexch/api.go
=> chore: handle PathNested in presexch

pkg/doc/did/doc.go
=> fix: parse generic ServicePoint

pkg/doc/presexch/api.go, pkg/doc/presexch/api_test.go
**Title:**
Presentation Exchange: Support for path nested
[[Link to the GitHub issue it solves (if any)](https://github.com/hyperledger/aries-framework-go/issues/3406)]
**Summary:**
Presentation submission MAY include a path_nested object to indicate the presence of a multi-[Claim] envelope format. This means the indicated is to be decoded separately from its parent enclosure.
The format of a path_nested object mirrors that of a descriptor_map property. The nesting may be any number of levels deep. The id property MUST be the same for each level of nesting.
The path property inside each path_nested property provides a relative path within a given nested value.
=> feat: suppor path_nested in presex.

pkg/vdr/httpbinding/resolver.go, pkg/vdr/httpbinding/resolver_test.go, pkg/vdr/httpbinding/vdr.go
=> chore:  Add auth token provider

pkg/controller/command/verifiable/command.go, pkg/didcomm/common/middleware/middleware.go, pkg/didcomm/common/middleware/middleware_test.go, pkg/didcomm/protocol/didexchange/didex_interop.go, pkg/doc/util/didsignjwt/signjwt.go, pkg/doc/util/didsignjwt/signjwt_test.go, pkg/doc/util/vmparse/vmparse.go, pkg/internal/kmssigner/kmssigner.go, pkg/internal/kmssigner/kmssigner_test.go, pkg/internal/test/makemockdoc/makemockdoc.go, pkg/wallet/jwt.go, pkg/wallet/jwt_test.go, pkg/wallet/kmsclient.go, pkg/wallet/kmsclient_test.go, pkg/wallet/session.go, pkg/wallet/wallet.go
=> feat: sign jwt using a key in an owned DID.

cmd/aries-js-worker/src/aries.js, pkg/controller/command/didcommwallet/command_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/doc/verifiable/common.go
=> feat: command controller for wallet.SignJWT

cmd/aries-js-worker/src/aries.js, pkg/controller/command/didcommwallet/command_test.go, pkg/controller/command/vcwallet/command.go, pkg/controller/command/vcwallet/command_test.go, pkg/controller/command/vcwallet/models.go, pkg/doc/util/didsignjwt/signjwt.go, pkg/doc/util/didsignjwt/signjwt_test.go, pkg/wallet/jwt.go, pkg/wallet/jwt_test.go
=> feat: wallet VerifyJWT API to verify compact jwt using DID.

pkg/doc/util/didsignjwt/signjwt.go, pkg/doc/util/didsignjwt/signjwt_test.go, pkg/doc/util/vmparse/vmparse.go, pkg/doc/verifiable/common.go, pkg/wallet/jwt.go
=> feat: refactor didsignjwt to allow decoupling from kms/crypto interfaces

docs/concepts/02_standards.md
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> docs: update standards for both jwt and json-ld vc

pkg/doc/verifiable/common.go
=> chore: add ECDSASecp256k1DER

pkg/doc/jwt/jwt.go, pkg/doc/jwt/jwt_test.go, pkg/doc/sdjwt/common/common.go, pkg/doc/sdjwt/common/common_test.go, pkg/doc/sdjwt/issuer/issuer.go, pkg/doc/sdjwt/issuer/issuer_test.go
Add SD-JWT Issuer (flat, no optional features).
Closes #3451
=> feat: Add SD-JWT Issuer (Flat)

pkg/doc/sdjwt/holder/holder.go, pkg/doc/sdjwt/holder/holder_test.go
Parse and verify combined presentation from issuer.
Closes #3453
=> feat: Add SD-JWT Holder (Flat)

pkg/doc/util/didsignjwt/signjwt.go
=> chore: expose didsignjwt.ResolveSigningVM as a helper API

pkg/doc/sdjwt/common/common.go, pkg/doc/sdjwt/common/common_test.go, pkg/doc/sdjwt/holder/holder.go, pkg/doc/sdjwt/holder/holder_test.go, pkg/doc/sdjwt/issuer/issuer_test.go, pkg/doc/sdjwt/verifier/verifier.go, pkg/doc/sdjwt/verifier/verifier_test.go
Parse and verify combined presentation from issuer.
Closes #3455
=> feat: Add SD-JWT Verifier (Flat)

pkg/doc/sdjwt/holder/holder.go, pkg/doc/sdjwt/holder/holder_test.go, pkg/doc/sdjwt/integration_test.go
Unit test for SD-JWT Flow.
Closes #3461
=> feat: Unit test for SD-JWT Flow (Issuer, Holder, Verifier)

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go
=> fix: disable JSON-LD validation on JWT credentials

pkg/doc/sdjwt/common/common.go, pkg/doc/sdjwt/issuer/issuer.go, pkg/doc/sdjwt/issuer/issuer_test.go
Add decoy digests to SD-JWT (if enabled)
Closes #3463
=> feat: Add decoy digests to SD-JWT

pkg/doc/sdjwt/holder/holder.go, pkg/doc/sdjwt/holder/holder_test.go
The Holder MAY add an optional JWT to prove Holder Binding to the Verifier. Nonce and aud claims are included to show that the proof is intended for the Verifier.
Closes #3470
=> feat: SD-JWT Holder: Add Holder Binding

pkg/doc/sdjwt/issuer/issuer_test.go
Add test for creating SD-JWT without signature.
Closes #3479
=> chore: Create SD-JWT without signature

pkg/doc/sdjwt/common/common.go, pkg/doc/sdjwt/common/common_test.go, pkg/doc/sdjwt/holder/holder_test.go, pkg/doc/sdjwt/issuer/issuer.go, pkg/doc/sdjwt/issuer/issuer_test.go, pkg/doc/sdjwt/verifier/verifier.go, pkg/doc/sdjwt/verifier/verifier_test.go
Added:
- structured claims option to issuer
- verify digests in structured claims for holder
- structured claims processing to verifier
Closes #3478
=> feat: Add structured claims option

pkg/doc/sdjwt/integration_test.go, pkg/doc/sdjwt/verifier/verifier_test.go
Added integration test for structured claim option.
Closes #3487
=> chore: Integration test for structured claim option

pkg/doc/sdjwt/common/common.go, pkg/doc/sdjwt/common/common_test.go, pkg/doc/sdjwt/integration_test.go, pkg/doc/sdjwt/issuer/issuer.go, pkg/doc/sdjwt/issuer/issuer_test.go, pkg/doc/sdjwt/verifier/verifier.go
Support verification of 'vc' claims with holder binding
Closes #3489
=> chore: Support verification of 'vc' claims with holder binding

pkg/doc/sdjwt/common/common.go, pkg/doc/sdjwt/integration_test.go, pkg/doc/sdjwt/issuer/issuer.go, pkg/doc/sdjwt/issuer/issuer_test.go, pkg/doc/sdjwt/verifier/verifier_test.go
Pass VC into NewFromVC and the issuer will create selective disclosures for everything in vc->credential subject and add the fields from options.
Closes #3491
=> feat: SD-JWT: Add NewFromVC to Issuer

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_jwt.go, pkg/doc/verifiable/credential_sdjwt_test.go, pkg/doc/verifiable/credential_test.go
=> feat: verifiable.ParseCredential() supports combined SD-JWT credentials

pkg/doc/sdjwt/holder/holder.go, pkg/doc/sdjwt/issuer/issuer.go, pkg/doc/verifiable/credential_sdjwt.go, pkg/doc/verifiable/credential_sdjwt_test.go
=> feat: method to marshal SD-JWT VC in combined format for presentation

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_sdjwt.go, pkg/doc/verifiable/credential_sdjwt_test.go
=> feat: method for SD-JWT VC to create non-SDJWT 'display credential'

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
=> fix: prexexch - contains check on filter

pkg/doc/verifiable/credential_sdjwt.go, pkg/doc/verifiable/credential_sdjwt_test.go
=> feat: option to pass SD hash alg into Credential.MakeSDJWT()

pkg/doc/cm/credentialapplication.go, pkg/doc/presexch/api.go, pkg/doc/presexch/api_test.go, pkg/doc/presexch/example_v1_test.go
=> feat: presentation definition can match array of presentations

pkg/doc/presexch/definition.go, pkg/doc/presexch/match_submission_requirements_test.go
**Title:**
Now get submission requirements can apply SD on result VCs
**Summary:**
The option is added to MatchSubmissionRequirement that allows to apply selective disclosure to resulting VCs.
=> fix: now get submission requirements can apply SD on result VCs

pkg/doc/presexch/definition.go, pkg/doc/presexch/schema.go
=> feat: support for optional field in presexch

pkg/doc/presexch/definition.go, pkg/doc/presexch/definition_test.go
**Title:**
Added JWT handling for limit disclosure Presentation Definition query.
**Summary:**
After new credential is created based on limit disclosure constraints:
```
credential, err = createNewCredential(constraints, credentialSrc, template, credential, opts...)
if err != nil {
return nil, fmt.Errorf("create new credential: %w", err)
}
```
it always returned in JSON-LD format.
Then, down the code, we check is it JWT in `merge` func
```
vcFormat := FormatLDPVC
if credential.JWT != "" {
vcFormat = FormatJWTVC
}
.....
desc := &InputDescriptorMapping{
PathNested: &InputDescriptorMapping{
Format: vcFormat,
},
}
```
I added a code that calculates JWT field in limited disclosure VC based on existing claims.
=> feat: added JWT handling for limit disclosure Presentation Definition query

component/models/go.mod, component/models/go.sum, component/models/ld/store/remote_provider_store.go, component/models/ld/store/remote_provider_store_test.go, pkg/didcomm/protocol/mediator/service.go, pkg/didcomm/protocol/mediator/service_test.go
- add retry to mediator.Service.GetConnections
- add retry to ld/store.RemoteProviderStore.Save
=> chore: improve stability of flaky tests

component/models/jwt/jwt.go, component/models/jwt/jwt_test.go
**Title:**
Add JWT Explicit typing basic support
**Summary:**
https://www.rfc-editor.org/rfc/rfc8725.html#section-3.11
=> feat: add JWT Explicit typing basic support

component/models/presexch/definition.go, component/models/presexch/definition_test.go, component/models/presexch/example_v1_test.go, component/models/presexch/internal/requirementlogic/combinatorics.go, component/models/presexch/internal/requirementlogic/combinatorics_test.go, component/models/presexch/internal/requirementlogic/requirementlogic.go, component/models/presexch/internal/requirementlogic/requirementlogic_test.go, component/models/presexch/internal/requirementlogic/stringset.go
Fixes https://github.com/hyperledger/aries-framework-go/issues/2109
=> feat: handle PEx nested submission requirement logic 

component/models/dataintegrity/suite/ecdsa2019/ecdsa2019.go
Follow up PR for https://github.com/hyperledger/aries-framework-go/pull/3621
=> feat: change SignerInitializerOptions KMS type

component/models/dataintegrity/integration_test.go, component/models/dataintegrity/suite/ecdsa2019/ecdsa2019.go, component/models/dataintegrity/suite/ecdsa2019/ecdsa2019_test.go, component/models/dataintegrity/suite/ecdsa2019/integration_test.go, component/models/verifiable/data_integrity_proof_test.go
Changed Data Integrity verifier interface.
=> feat: DI - change verifier interface

component/models/dataintegrity/signer.go, component/models/dataintegrity/suite/ecdsa2019/ecdsa2019.go, component/models/dataintegrity/suite/ecdsa2019/ecdsa2019_test.go
**Title:**
Update Data Integrity error handling
Given PR solves issues with error handling for Data Integrity proof signing and verification.
=> feat: update Data Integrity error handling
