hyperledger/aries-framework-go

LICENSE, README.md
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> Apache license

.circleci/config.yml, .codecov.yaml, .gitignore, .golangci.yml, Makefile, go.mod, go.sum, pkg/didcomm/protocol/exchange/exchange.go, pkg/didcomm/protocol/exchange/exchange_test.go, scripts/check_license.sh, scripts/check_lint.sh, scripts/check_unit.sh
- gitignore file
- Circle CI config file
- Scripts for licence, lint(golangci-lint) and unit test along with Makefile
- Placeholder go file along with go.mod and go.sum file
=> ci: Project setup - CI config, licence/lint check and unit test (build)

.circleci/config.yml, README.md
Add following badges to the project
- circle ci
- release
- licence
- codecov
- go report card
Closes #6
=> docs: Add project badges

go.mod, go.sum, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go
=> feat: Add DID Document data model

go.mod, go.sum, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go
=> feat: Validate DID Document

pkg/framework/didresolver/api.go, pkg/framework/didresolver/api_test.go, pkg/framework/didresolver/didresolver.go, pkg/framework/didresolver/didresolver_test.go
=> feat: Add Generic DID Resolution

.circleci/config.yml, Makefile, scripts/check_integration.sh, test/bdd/bddtests_test.go, test/bdd/features/didexchange.feature, test/bdd/go.mod
=> feat: Did Exchange feature file and bddtests initial framework

pkg/didmethod/peer/resolver.go, pkg/didmethod/peer/resolver_test.go, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go
- Resolver against configurable backing store
- ToJSON function to convert DID Document to json format
Closes #58 
=> feat: Peer DID Resolver

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
=> (#73) Add contrib, issue, and PR guidelines

README.md
Document project build info/targets in README along with prerequisites
Closes #89 
=> doc: Project Build information

pkg/didmethod/peer/resolver.go, pkg/didmethod/peer/resolver_test.go, pkg/framework/didresolver/api.go, pkg/framework/didresolver/api_test.go, pkg/framework/didresolver/didresolver.go, pkg/framework/didresolver/didresolver_test.go
=> feat: Allow DID method to Accept supported DID prefixes

README.md
Adding badge to godocs in README
=> Add godocs badge

doc.go
=> doc:  Add doc.go to enable go tooling

pkg/framework/aries/default.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go
Add support to configure DID Resolver during framework initialization
Closes #79 
=> feat: Aries Framework Init - DID Resolver configuration

pkg/didmethod/httpbinding/resolver.go, pkg/didmethod/httpbinding/resolver_test.go
closes #145 
Adopts HTTP DID Resolver to implement the changed Resolver interface.
=> fix: DidMethod interface impl by HTTP DID Resolver

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go
closes #172
Custom data verification schemas for Verifiable Credential.
After decoding of Verifiable Credential, we make its validation based on the default data schema [definition](https://w3c.github.io/vc-data-model). One way to enable VerifiableCredential extensibility and  configurability is setting `credentialSchema` field.
`credentialSchema` can take different types. In the current PR, support of `JsonSchemaValidator2018` type is implemented. The custom JSON schema is downloaded via HTTP and used for validation instead of default one.
=> feat: Custom data verification schemas for Verifiable Credential

.circleci/config.yml, Makefile, README.md, go.mod, go.sum, pkg/client/didexchange/client.go, pkg/didcomm/crypto/jwe/authcrypt/authcrypt.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/transport/http/inbound.go, pkg/didcomm/transport/http/outbound.go, pkg/didcomm/transport/http/support_test.go, pkg/didmethod/httpbinding/resolver.go, pkg/didmethod/peer/did.go, pkg/didmethod/peer/resolver.go, pkg/didmethod/peer/store.go, pkg/doc/did/doc.go, pkg/doc/verifiable/credential.go, pkg/framework/aries/api/protocol.go, pkg/framework/aries/default.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/framework/didresolver/api.go, pkg/framework/didresolver/didresolver.go, pkg/internal/common/logging/metadata/utils.go, pkg/internal/didcomm/transport/mock/mock_transport.go, pkg/restapi/restapi_test.go, pkg/storage/leveldb/leveldb_store.go
This change updates the project to Go 1.13
- CI is updated.
- README is updated.
- Built-in errors package is used.
Closes: #204
=> chore: update to Go 1.13

cmd/aries-agentd/main_test.go, pkg/didcomm/protocol/decorator/decorator.go, pkg/didcomm/protocol/didexchange/models.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/framework/aries/default.go
=> feat: did-exchange service state machine handler

cmd/aries-agentd/main.go, cmd/aries-agentd/main_test.go, pkg/framework/aries/default.go, pkg/framework/aries/defaults/defaults.go, pkg/framework/aries/defaults/defaults_test.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/restapi/restapi_test.go
- Add defaultopt package 
closes #175
=> feat: Add ability to inject custom configuration into default providers 

cmd/aries-agentd/main.go, pkg/framework/aries/defaults/defaults.go, pkg/framework/aries/defaults/defaults_test.go, pkg/restapi/restapi_test.go
=> refactor: aries framework options should not return err

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/example_credential_test.go
- Provides a mechanism for extension of model by custom data structures which embedded verifiable.Credential
#171 
=> feat: Extensibility of Verifiable Credential data model

pkg/framework/aries/default_test.go
=> test: test file for defaults.go

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/framework/aries/api/protocol.go, pkg/framework/aries/api/wallet.go, pkg/framework/aries/default_test.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/internal/mock/provider/mock_provider.go, pkg/internal/mock/wallet/mock_wallet.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/wallet/api.go
- Create Wallet interface
- Allow injectable Wallet
closes #213
=> feat: Allow injectable Wallet

cmd/aries-agentd/main_test.go, pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/client/didexchange/models.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go
- added /connections & /connections/{id} handlers
- added QueryConnections & QueryConnectionByID client functions
- closes #121
=> feat: controller API for connections

pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
* constants instead of function calls
* memory allocation
=> Used constants instead of a function call & memory allocation

pkg/didcomm/crypto/crypter.go, pkg/framework/aries/default.go, pkg/internal/mock/didcomm/mock_authcrypt.go, pkg/wallet/api.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- imlpement pack method in wallet
- implement unpack method in wallet
closes #38
=> feat: Create Pack() for Authcrypt logic

cmd/aries-agentd/main_test.go, pkg/didcomm/event/event.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/didcomm/transport/http/inbound.go
- Support to register action events(go channels) for inbound DIDExchange message types
- Support to register for auto execution of message processing
- Support to register stream events(go channels) for inbound DIDExchange message types
- Support for callback for action events
Closes #198 
=> feat: DID Exchange Inbound Message Event

pkg/didcomm/protocol/didexchange/service.go
=> refactoring: Prevent deadlock when writing to a nil channel

pkg/framework/aries/api/wallet.go, pkg/internal/mock/wallet/mock_wallet.go, pkg/wallet/api.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- added just `DIDCreator` interface inside wallet and provided default
implementation
- actual implementation will be provided in upcoming PR
- related to #283
=> feat: API for creating DID inside wallet

pkg/client/didexchange/client_test.go, pkg/didcomm/dispatcher/api.go, pkg/didcomm/dispatcher/outbound.go, pkg/didcomm/dispatcher/outbound_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/transport/http/outbound.go, pkg/didcomm/transport/http/outbound_test.go, pkg/didcomm/transport/transport_interface.go, pkg/framework/aries/default.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/internal/mock/didcomm/dispatcher/mock_outbound.go, pkg/internal/mock/didcomm/mock_transport.go, pkg/internal/mock/wallet/mock_wallet.go
- Add Outbound dispatcher implementation
closes #259
=> feat: Outbound dispatcher

pkg/didcomm/crypto/jwe/authcrypt/authcrypt.go, pkg/didcomm/crypto/jwe/authcrypt/authcrypt_test.go, pkg/didcomm/crypto/jwe/authcrypt/common.go, pkg/didcomm/crypto/jwe/authcrypt/decrypt.go, pkg/didcomm/crypto/jwe/authcrypt/encrypt.go
=> fix: update Go Encryption compatibility

.github/CONTRIBUTING.md
=> chore: Clarify max PR size

.github/workflows/go.yml
* GitHub Actions
The successful result can be found [here](https://github.com/soluchok/aries-framework-go/pull/2)
=> feat: GitHub Actions

pkg/didcomm/protocol/didexchange/service_test.go
The consumer does not have enough time to pick up event need to wait for a while
* fixed TestService_Events
=> fix: Test fails randomly

.github/workflows/go.yml
* added missing trigger `pull_request`
=> Added missing trigger 

.circleci/config.yml, .github/workflows/build.yml, README.md
=> ci: switch to GitHub Actions

go.mod, go.sum, pkg/didcomm/crypto/legacy/authcrypt/authcrypt.go, pkg/didcomm/crypto/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/crypto/legacy/authcrypt/decrypt.go, pkg/didcomm/crypto/legacy/authcrypt/encrypt.go
Implements legacy encrypter for compatibility with ACA-Py.
Closes #139
=> feat: Legacy encrypt (current aries RFC 19), compatible with ACA-Py

scripts/check_unit.sh
=> fix: Revert test count

pkg/didcomm/transport/http/inbound.go, pkg/didcomm/transport/http/inbound_test.go, pkg/didcomm/transport/transport_interface.go, pkg/internal/mock/wallet/mock_wallet.go
- Add unpack in inbound handler
closes #301
=> feat: Add unpack method to inbound handler

pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
This branch name was renamed to see old comments visit this [link](https://github.com/hyperledger/aries-framework-go/pull/285)
Issue: https://github.com/hyperledger/aries-framework-go/issues/287
=> protocol: Added states for introduce protocol

pkg/client/didexchange/client_test.go, pkg/didcomm/dispatcher/api.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/framework/aries/api/protocol.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/internal/mock/wallet/mock_wallet.go
=> feat: State actions- Requested and Responded

.circleci/config.yml, .github/workflows/build.yml
=> ci: upload coverage reports from GitHub Actions

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/doc/did/doc.go, pkg/framework/aries/api/protocol.go, pkg/framework/aries/api/wallet.go, pkg/framework/aries/default.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/internal/mock/wallet/mock_wallet.go, pkg/wallet/api.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- added create DID document feature in base wallet implementation
- closes #283
=> feat: Create DID feature in base wallet implementation

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/client/didexchange/models.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go
- Add HandleInvitation method
closes #277
=> feat: DID Exchange Client - HandleInvitation()

pkg/didcomm/protocol/didexchange/service_test.go, pkg/internal/mock/storage/mock_store.go
=> test: DIDExchange service - unit tests for error scenarios

pkg/didcomm/common/model/ack.go, pkg/didcomm/protocol/decorator/decorator.go, pkg/didcomm/protocol/didexchange/models.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/introduce/models.go, pkg/didcomm/protocol/introduce/models_test.go
* models for the protocol
Issue: https://github.com/hyperledger/aries-framework-go/issues/325
=> protocol: Added models for the introduce protocol

.gitignore, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_jwt_proof_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/support_test.go, pkg/doc/verifiable/testdata/scripts/generate_test_keys.sh, pkg/doc/verifiable/testdata/scripts/openssl_env.sh
#173
Implement decoding of Credential verified by JWT signature.
https://w3c.github.io/vc-data-model/#jwt-decoding
=> feat: decoding of Verifiable Credential proved by JWT signature

Makefile, scripts/generate-openapi-spec.sh
=> feat: adding generate spec target in checks

pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/didcomm/protocol/introduce/models.go, pkg/framework/context/context_test.go, pkg/internal/mock/wallet/mock_wallet.go
=> feat: Implement state action - sendExchangeAck status completed

pkg/client/didexchange/client_test.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go
=> test: Consolidate all Mock DIDExchange Service into one mock

pkg/client/didexchange/client_test.go, pkg/common/did/creator.go, pkg/common/did/creator_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/framework/aries/default.go, pkg/framework/context/context_test.go, pkg/internal/mock/common/did/mock_creator.go, pkg/internal/mock/wallet/mock_wallet.go
- added DID creator which hides functionality of passing DID method to
wallet DID creator
- closes #322
=> feat: DID creator for service packages

pkg/client/didexchange/client.go, pkg/didcomm/dispatcher/api.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go
- Add the ability to receive events after changing the state
closes #304
=> feat: Add post event handle

pkg/didcomm/crypto/jwe/authcrypt/authcrypt.go, pkg/didcomm/crypto/jwe/authcrypt/authcrypt_test.go, pkg/didcomm/crypto/jwe/authcrypt/common.go, pkg/didcomm/crypto/jwe/authcrypt/decrypt.go, pkg/didcomm/crypto/jwe/authcrypt/decrypt_jwk.go, pkg/didcomm/crypto/jwe/authcrypt/decrypt_jwk_test.go, pkg/didcomm/crypto/jwe/authcrypt/encrypt.go, pkg/didcomm/crypto/jwe/authcrypt/encrypt_jwk.go, pkg/didcomm/crypto/legacy/authcrypt/authcrypt.go, pkg/didcomm/crypto/legacy/authcrypt/decrypt.go, pkg/didcomm/crypto/legacy/authcrypt/encrypt.go
=> chore: cleanup jwe envelopes with proper names

pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> feat: Compute sender verification key to send to outbound dispatcher

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/restapi/operation/didexchange/didexchange.go
=> chore: Pass label value as argument to CreateInvitation func

pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
* added transitions to delivering and arranging
Issue: https://github.com/hyperledger/aries-framework-go/issues/336
=> protocol: Change state transitions for introduce protocol

pkg/doc/signature/ed25519signature2018/suite.go, pkg/doc/signature/ed25519signature2018/suite_test.go, pkg/doc/signature/proof/data.go, pkg/doc/signature/signer/signer.go, pkg/doc/signature/signer/signer_test.go
Linked Data documents (including DIDs) are signed using linked data signatures algorithm. The document is normalized before signing using Create Verify Hash Algorithm and signature is created using appropriate signature suite. At the end the signature is added to the document.
Closes #244
=> feat: Implement Linked Data Signing

pkg/framework/aries/framework.go
=> fix: Fix initialize services in aries farmework

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> feat: handleInboundInvitation creating and passing the thread id

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, test/bdd/agent_steps.go
- Support to register/unregister action events
- Support to register/unregister message events
Closes #199 
=> feat: DID Exchange Client Events

test/bdd/agent_steps.go, test/bdd/context.go, test/bdd/did_exchange_steps.go, test/bdd/features/didexchange_e2e.feature
=> feat: Add client events to did exchange bddtest basic flow

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/didexchange/persistence/connection.go, pkg/didcomm/protocol/didexchange/persistence/connection_test.go, pkg/internal/mock/provider/mock_provider.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go
=> feat: Persist Invitation during Create Invitation

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> fix: failure in state transition

pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> feat: Prepare the connection signature raw data

pkg/didcomm/crypto/legacy/authcrypt/authcrypt.go, pkg/didcomm/crypto/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/crypto/legacy/authcrypt/decrypt.go, pkg/didcomm/crypto/legacy/authcrypt/encrypt.go
This is a prelude to the wallet-crypto refactor; where the legacy Authcrypter has been refactored to implement the Crypter interface and simplify some code (for example, in generating the protected header and using it as the AAD).
=> refactor: Legacy Authcrypter implements Crypter interface

Makefile, pkg/didmethod/peer/resolver_test.go, pkg/didmethod/peer/store.go, pkg/didmethod/peer/store_test.go, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/framework/aries/framework_test.go, pkg/framework/didresolver/didresolver.go
Add VerifyProof() method to DID document
Closes #392
=> feat: Add signature verification to DID Document

pkg/client/didexchange/client.go, pkg/didcomm/dispatcher/api.go, pkg/didcomm/protocol/didexchange/service.go
- Pass connectionID and invitationID from did exchange service
closes #403
=> feat: Pass connectionID and invitationID in events

pkg/doc/signature/proof/data.go, pkg/doc/signature/proof/data_test.go, pkg/doc/signature/signer/signer.go, pkg/doc/signature/verifier/verifier.go
Rename CreateVerifyHashAlgorithm to CreateVerifyHash
Closes #430
=> chore: Rename CreateVerifyHashAlgorithm to CreateVerifyHash

pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go
- Support to consume DIDExchange Client Action and Message events in DID Exchange RestAPI
- For now, auto execute callback for Action event and log for message event
Closes #389 
=> feat: DIDExchange RestAPI - Consume Client Events

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/client/didexchange/models.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/didcomm/protocol/didexchange/persistence_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/internal/mock/provider/mock_provider.go, pkg/internal/mock/storage/mock_store.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go, pkg/wallet/wallet_test.go, test/bdd/agent_steps.go, test/bdd/context.go, test/bdd/did_exchange_steps.go, test/bdd/features/didexchange_e2e.feature
- Add query connection in did exchange persistence
closes #424 #420
=> feat: Add ability to query connection from did exchange persistence 

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_jwt_proof_test.go, pkg/doc/verifiable/test-suite/verifiable_suite_test.go
=> refactor: Improve configuration of NewCredential() regarding JWT

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/common/service/event.go, pkg/didcomm/common/service/event_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/restapi/operation/didexchange/didexchange.go, test/bdd/agent_steps.go
=> refactor: Move AutoExecute ActionEvent utility to common/service package

cmd/aries-agentd/startcmd/start_test.go, pkg/didcomm/transport/http/inbound_test.go, test/bdd/agent_steps.go
* listenFor function was simplified
=> refactor: Remove redundant error checks

pkg/common/did/creator.go, pkg/common/did/creator_test.go, pkg/internal/mock/common/did/mock_creator.go, pkg/internal/mock/storage/mock_store.go, pkg/internal/mock/wallet/mock_wallet.go, pkg/wallet/api.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
- DID Documents will be persisted inside wallet when created but in
different namespace
- Closes #486
=> feat: store DID in wallet

pkg/didcomm/common/service/event.go, pkg/didcomm/protocol/didexchange/event.go, pkg/didcomm/protocol/didexchange/event_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, test/bdd/agent_steps.go
- Update state to abandoned if the processing fails
- Trigger events if the processing fails
Closes #442 
=> feat: Protocol Failure - Update state to abandoned and trigger message notification

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/didexchange/service.go, test/bdd/agent_steps.go
Addressed the following review comments.
- https://github.com/hyperledger/aries-framework-go/pull/480#discussion_r335639034
- https://github.com/hyperledger/aries-framework-go/pull/480#discussion_r335641148
=> refactor: DIDExchange Service/Client/BDD Test - Start go routine outside the function

.codecov.yaml
=> ci: disable codecov patch commit status unless PR

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/didcomm/protocol/didexchange/persistence_test.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/internal/mock/didresolver/mock_didresolver.go
Add support for public DID in Create/Handle Invitation
Closes #503
=> feat: Support public DID in Create/Handle Invitation

README.md
=> chore: add docker-compose as prerequisite in README

cmd/aries-agentd/startcmd/start_test.go
=> test: Increase the timout for server startup

pkg/doc/verifiable/common.go, pkg/doc/verifiable/common_test.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_jws.go, pkg/doc/verifiable/credential_jws_test.go, pkg/doc/verifiable/credential_jwt.go, pkg/doc/verifiable/credential_jwt_proof_test.go, pkg/doc/verifiable/jws.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_jws.go, pkg/doc/verifiable/presentation_jws_test.go, pkg/doc/verifiable/presentation_jwt.go, pkg/doc/verifiable/presentation_jwt_proof_test.go, pkg/doc/verifiable/presentation_jwt_test.go, pkg/doc/verifiable/presentation_jwt_unsecured.go, pkg/doc/verifiable/presentation_jwt_unsecured_test.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/support_test.go, pkg/doc/verifiable/test-suite/verifiable_suite_test.go
JWS and unsecured JWT external proofs of Verifiable Presentation.
test suite stats:
- passes : 67
- failures: 8
prior to this PR:
- passes : 61
- failures: 14
closes #483
=> feat: JWT proof of Verifiable Presentation

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go
=> fix: DIDExchange PreState message event - remove duplicate trigger

test/bdd/bddtests_test.go, test/bdd/did_resolver_sidetree_node_steps.go, test/bdd/go.mod, test/bdd/go.sum
=> fix: change module name in bdd test go.mod

pkg/didmethod/httpbinding/resolver.go, pkg/framework/aries/framework.go, test/bdd/context.go, test/bdd/did_exchange_steps.go, test/bdd/did_resolver_sidetree_node_steps.go, test/bdd/features/didexchange_public_did.feature, test/bdd/go.sum
BDD test for Create Invitation with public DID
Closes #519
=> bdd: Create Invitation with Public DID

pkg/client/didexchange/client.go, pkg/restapi/operation/didexchange/didexchange.go
- Updated RestAPI files to remove closed issues and added new issues in TODO.
Setup for #539 
=> docs: Update TODOs with new GitHub Issues and remove obsolete TODOs

test/bdd/did_exchange_steps.go, test/bdd/did_resolver_sidetree_node_steps.go, test/bdd/features/did_resolver_sidetree_node.feature
=> chore: Replace wait with retry for did resolution in bdd tests

ci/azp-dependencies.yml, ci/azure-pipelines.yml
=> ci: azure pipelines config for codecov

pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
* `HandleOutbound` method implementation
* `handle` internal implementation
Issue: https://github.com/hyperledger/aries-framework-go/issues/464
=> feat: Introduce protocol service implementation

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/common/service/action.go, pkg/didcomm/common/service/action_test.go, pkg/didcomm/common/service/message.go, pkg/didcomm/common/service/message_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/restapi/operation/didexchange/didexchange_test.go
* didexchange client was extended with service.Action and service.Message
=> refactor:  Client was extended with service.Action and service.Message

pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, scripts/start-aries-agentd.sh, test/bdd/agent_controller_steps.go, test/bdd/agent_sdk_steps.go, test/bdd/bddtests_test.go, test/bdd/features/didexchange_e2e_controller.feature, test/bdd/features/didexchange_e2e_sdk.feature, test/bdd/fixtures/agent/.env, test/bdd/fixtures/agent/docker-compose.yml
- starting agents Alice and Bob in docker containers
- added agent controller feature and steps for did exchange using 
controller API
- closes #491
=> feat: Controller REST API bddtests

pkg/didcomm/protocol/didexchange/states_test.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/webhook/payloads.go
- Trigger webhook notifications for DIDExchange Post State change message events
Closes #551 
=> feat: DIDExchange - Integrate Message events with Webhook Notifications

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_extension_switch_test.go, pkg/doc/verifiable/credential_jws.go, pkg/doc/verifiable/credential_jws_test.go, pkg/doc/verifiable/credential_jwt.go, pkg/doc/verifiable/credential_jwt_proof_test.go, pkg/doc/verifiable/credential_jwt_unsecured.go, pkg/doc/verifiable/credential_jwt_unsecured_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/jws.go, pkg/doc/verifiable/jwt_unsecured.go, pkg/doc/verifiable/jwt_unsecured_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_jws.go, pkg/doc/verifiable/presentation_jws_test.go, pkg/doc/verifiable/presentation_jwt.go, pkg/doc/verifiable/presentation_jwt_proof_test.go, pkg/doc/verifiable/presentation_jwt_unsecured.go, pkg/doc/verifiable/presentation_jwt_unsecured_test.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/support_test.go
=> refactor: Improve errors wrapping in verifiable package

pkg/didcomm/protocol/didexchange/service.go, test/bdd/bddtests_test.go
- add env variable AGENT_LOG_LEVEL to change logs in bdd test
closes #495
=> chore: Cleanup log levels

pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go
=> feat: DIDExchange REST MsgEvent - Fetch Connections Details from DB

test/bdd/agent_controller_steps.go, test/bdd/agent_sdk_steps.go, test/bdd/bddtests_test.go, test/bdd/did_exchange_steps.go, test/bdd/didresolver_steps.go, test/bdd/features/didresolver.feature
=> bdd: log DID com msgs in bdd test

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/crypto/jwe/authcrypt/authcrypt_test.go, pkg/didcomm/crypto/jwe/authcrypt/encrypt.go, pkg/didcomm/crypto/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/envelope/api.go, pkg/didcomm/envelope/package_test.go, pkg/didcomm/envelope/packager.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/internal/cryptoutil/utils.go, pkg/internal/cryptoutil/utils_test.go, pkg/internal/mock/wallet/mock_wallet.go, pkg/internal/mock/wallet/mock_wallet_provider.go, pkg/wallet/api.go, pkg/wallet/crypto_box.go, pkg/wallet/crypto_box_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go, test/bdd/didresolver_steps.go
Now the Packager accepts Signature
Keys and pass them on to the Crypter
which will in turn convert them to
Encrytpion Keys.
Closes #272 
Closes #488
=> refactor: added key type in keypair

pkg/didcomm/protocol/didexchange/service.go, pkg/didmethod/peer/creator.go, pkg/didmethod/peer/did.go, pkg/didmethod/peer/resolver.go, pkg/didmethod/peer/store.go, pkg/framework/aries/api/didstore/didstore.go, pkg/framework/aries/api/protocol.go, pkg/framework/aries/default.go, pkg/framework/aries/default_test.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/framework/didstore/didstore.go, pkg/framework/didstore/didstrore_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, pkg/internal/mock/didstore/mock_didmethod.go, pkg/internal/mock/didstore/mock_didstore.go
=> feat: Create Generic did storage

pkg/client/didexchange/client.go, pkg/client/didexchange/models.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go, test/bdd/agent_controller_steps.go, test/bdd/features/didexchange_e2e_controller.feature
- added request/response params to create invitation controller rest endpoint
- Part of #552 
=> feat: request/response updates for create invitation controller api 

pkg/didcomm/crypto/legacy/authcrypt/authcrypt.go, pkg/didcomm/crypto/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/crypto/legacy/authcrypt/decrypt.go, pkg/didcomm/crypto/legacy/authcrypt/encrypt.go, pkg/framework/aries/default.go, pkg/internal/mock/wallet/mock_wallet.go, pkg/wallet/api.go, pkg/wallet/crypto_box.go, pkg/wallet/crypto_box_test.go
=> feat: set Legacy as the default packer/unpacker

pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
Add signature to outbound exchange response and verify signature in inbound exchange response
Closes #24
=> feat: Add signature to exchange response

cmd/aries-agentd/startcmd/start.go, cmd/aries-agentd/startcmd/start_test.go, go.mod, go.sum, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go, test/bdd/agent_controller_steps.go
- fixed receive-invitation issues in demo due to CORS
- also fixed other minor issues in demo
- part of #94
=> fix: Receive-invitation endpoint issues in demo

test/bdd/agent_sdk_steps.go, test/bdd/context.go, test/bdd/did_exchange_steps.go
=> fix: Concurrency failure in bdd-test

scripts/check_integration.sh
=> chore: Add race flag for bdd test

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, test/bdd/agent_controller_steps.go
- Add AcceptExchangeRequest API in DIDExchange service and client pkg
- Integrate the new client API in Rest API controller
- Integrat Action events with Webhook Notification
- Update BDD Test to invoke Controller API to accept exchange request
Closes #549 
Closes #579 
=> feat: DIDExchange Controller : Support Accept Exchange Request

test/bdd/agent_controller_steps.go, test/bdd/bddtests_test.go, test/bdd/features/didexchange_e2e_controller.feature
=> test: DIDExchange Controller - Add step to approve the exchange request

pkg/doc/verifiable/common.go, pkg/doc/verifiable/common_test.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_jws_test.go, pkg/doc/verifiable/credential_jwt.go, pkg/doc/verifiable/credential_jwt_unsecured_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/json.go, pkg/doc/verifiable/json_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/support_test.go
=> refactor: Keep extra fields of termsOfUse of VC in a map

pkg/framework/aries/default.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/storage/mem/mem_store.go, pkg/storage/mem/mem_store_test.go
- Add mem store as default transient storage
- Allow user to inject custom transient storage
closes #672
=> feat: Allow injectable transient storage

pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> refactor: Cleanup state.go in did exchange

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/didcomm/protocol/didexchange/persistence_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/framework/aries/api/protocol.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, pkg/internal/mock/provider/mock_provider.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go
=> feat: DIDExchange - Transient v Permanent Data store

test/bdd/webhook/main.go
=> test: Log event messages with connectionID in webhook server

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go
=> refactor: Remove transientStore from did exchange service

pkg/didcomm/protocol/didexchange/service_test.go
=> test: DIDExchange Service test file cleanup

cmd/aries-agentd/startcmd/start_test.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/didmethod/peer/resolver_test.go, pkg/didmethod/peer/store.go, pkg/didmethod/peer/store_test.go, pkg/framework/aries/default.go, pkg/framework/aries/default_test.go, pkg/framework/aries/defaults/defaults_test.go, pkg/framework/aries/framework_test.go, test/bdd/agent_sdk_steps.go
=> refactor: Use did resolver to get the peer did doc 

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> refactor: Cleanup state_test.go file in did Exchange

Makefile, pkg/restapi/operation/didexchange/models/invitation.go
=> fix: results shouldn't return 'null'

pkg/didcomm/protocol/introduce/service_test.go
* data race
* goroutines leak (in tests)
Part of https://github.com/hyperledger/aries-framework-go/issues/269
=> fix: fixed data race in introduce protocol

README.md
=> chore: updated readme with bddtest make target

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/restapi/operation/didexchange/didexchange_test.go
=> revert: DID exchange client refactor

pkg/didmethod/httpbinding/resolver.go, pkg/didmethod/httpbinding/resolver_test.go, pkg/didmethod/peer/resolver.go, pkg/didmethod/peer/resolver_test.go, pkg/framework/aries/framework_test.go, pkg/framework/didresolver/api.go, pkg/framework/didresolver/didresolver.go, pkg/framework/didresolver/didresolver_test.go
=> refactor: DidResolver.Read() should return a did.Doc

.gitignore, scripts/check_lint.sh, scripts/check_unit.sh
=> fix: unit test and linter not running for aries-agentd

cmd/aries-agentd/startcmd/start.go, cmd/aries-agentd/startcmd/start_test.go
=> Support environment variables in addition to command line arguments

Makefile
- adds clean targets to Makefile for docker images and containers.
Closes #757
=> test: cleanup docker images and containers

Makefile, scripts/run_openapi_demo.sh
=> fix: clean run-openapi-demo docker containers

doc.go
=> docs: Update root project doc

pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go
=> refactor: remove get did resolver from framework aries

pkg/client/didexchange/client.go, pkg/client/didexchange/doc.go, pkg/client/didexchange/example_test.go
Documentation and examples for didexchange client.
part #739
=> docs: Documentation, examples for didexchange client

README.md
=> documentation: project introduction

pkg/client/didexchange/client.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go
=> refactor: Add stateID validation to Accept Invitation and Request APIs

README.md, docs/test/bdd_instructions.md, scripts/check_unit.sh, test/bdd/features/didexchange_e2e_controller.feature, test/bdd/features/didexchange_e2e_sdk.feature, test/bdd/features/didexchange_public_did.feature, test/bdd/features/didresolver.feature
=> docs: BDD tests documentation

.golangci.yml, scripts/check_lint.sh, test/bdd/agent_controller_steps.go, test/bdd/agent_sdk_steps.go, test/bdd/bddtests_test.go, test/bdd/dockerutil/compose.go, test/bdd/dockerutil/docker.go, test/bdd/features/didresolver.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/didresolver/didresolver_steps.go, test/bdd/webhook/main.go
=> fix: linter to include bdd tests

README.md, pkg/client/didexchange/example_test.go
Also, show steps for setting up auto execute in didexchange client
part #739
=> docs: Add Documentation section

pkg/framework/aries/example_test.go
- Remove dependency on dbpath and passed it as one of the options
- Remove mock aries client init code
Based on review comments in #778 
=> docs: Framework pkg example update

README.md, docs/agentd/agent_CLI.md, docs/agentd/agent_docker_instructions.md, docs/agentd/agent_webhook.md
=> Readme for running agent locally and webhooks

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go
Set label in exchange request
closes #741
=> fix: DIDExchange Request Msg - Empty label

docs/rest/openapi_demo.md, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go
=> feat: public DID for create-invitation

test/bdd/pkg/didexchange/didexchange_sdk_steps.go
* added `autoExecuteActionEvent` function`
Closes https://github.com/hyperledger/aries-framework-go/issues/740
=> refactor: BDD tests automatically execute action events

docs/test/bdd_tests.md
=> docs: Add Running BDD tests in detached mode

README.md, docs/project_structure.md
=> docs: Project structure doc update

test/bdd/pkg/didexchange/didexchange_controller_steps.go
- fixed approve request error check.
- maximum attempt limit on pull webhook topic logic
- closes #803  
=> fix: bddtests hangs during error condition

docs/rest/openapi_demo.md
=> chore: tweaked and clarified instructions for openapi demo

pkg/framework/aries/api/vdri/vdri.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/internal/mock/vdri/mock_registry.go, pkg/internal/mock/vdri/mock_vdri.go, pkg/vdri/httpbinding/vdri.go, pkg/vdri/httpbinding/vdri_test.go, pkg/vdri/peer/store.go, pkg/vdri/peer/store_test.go, pkg/vdri/registry.go, pkg/vdri/registry_test.go
=> feat: Add close method to VDRI

Makefile, cmd/aries-agent-wasm/index.html, cmd/aries-agent-wasm/main.go, pkg/framework/aries/default.go, pkg/framework/aries/default_js_wasm.go, pkg/framework/aries/default_srv.go, pkg/framework/aries/default_test.go, pkg/framework/aries/defaults/defaults.go, pkg/framework/aries/defaults/defaults_js_wasm.go, pkg/framework/aries/defaults/defaults_srv.go, pkg/framework/aries/defaults/defaults_test.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/storage/jsindexeddb/jsindexeddb.go, pkg/storage/leveldb/leveldb_store.go, pkg/storage/leveldb/leveldb_store_test.go, scripts/check_lint.sh, test/bdd/agent_sdk_steps.go
=> feat: Support for IndexedDB

Makefile, pkg/client/introduce/client.go, pkg/client/introduce/client_test.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go
* added dependency interface to the Client 
Closes https://github.com/hyperledger/aries-framework-go/issues/724
Part of https://github.com/hyperledger/aries-framework-go/issues/269
=> feat: Added dependency interface to the Client

pkg/didcomm/transport/ws/outbound.go, pkg/didcomm/transport/ws/outbound_test.go
=> feat: DIDComm Outbound Transport - Support for WebSocket

test/bdd/agent_sdk_steps.go, test/bdd/features/didexchange_e2e_sdk.feature, test/bdd/go.mod, test/bdd/go.sum
=> test:Agent BDD - Add scenario to run e2e using WebSocket

.github/workflows/build.yml, Makefile, docs/test/build.md, pkg/framework/aries/default.go, pkg/framework/aries/default_js_wasm.go, pkg/framework/aries/default_srv.go, pkg/framework/aries/defaults/defaults_js_wasm.go, pkg/storage/jsindexeddb/jsindexeddb.go, pkg/storage/jsindexeddb/jsindexeddb_test.go, scripts/check_unit.sh, scripts/check_unit_wasm.sh
=> feat: Add unit test for IndexedDB

Makefile, pkg/storage/jsindexeddb/jsindexeddb.go, pkg/storage/jsindexeddb/jsindexeddb_test.go, pkg/storage/mem/mem_store.go
=> feat: Add Iterator for IndexedDB

pkg/didcomm/dispatcher/api.go, pkg/didcomm/dispatcher/outbound.go, pkg/didcomm/dispatcher/outbound_test.go, pkg/framework/aries/default.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, test/bdd/agent_sdk_steps.go
=> refactor: Allow user to inject multiple outbound transport

cmd/aries-agent-rest/go.sum, cmd/aries-agent-rest/startcmd/start.go, cmd/aries-agent-rest/startcmd/start_test.go, docs/rest/agent_cli.md
=> feat: Allow user to inject multiple outbound transport in rest cli

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go
For  `Accept Exchange Request` and ` Accept Invitation`,
- added public DID in controller API for below endpoints
- added public DID and label for client & service
- closes #871
=> feat: public DIDs in Accept Invitation & Accept Request

pkg/didcomm/packager/package_test.go, pkg/didcomm/packager/packager.go, pkg/didcomm/packer/api.go, pkg/didcomm/packer/jwe/authcrypt/authcrypt_test.go, pkg/didcomm/packer/jwe/authcrypt/unpack.go, pkg/didcomm/packer/legacy/authcrypt/authcrypt_test.go, pkg/didcomm/packer/legacy/authcrypt/unpack.go, pkg/internal/mock/didcomm/mock_authcrypt.go
=> refactor: Pass SenderVerKey to inbound transport from Unpacker along with msg

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, pkg/vdri/registry.go, test/bdd/features/didexchange_public_did.feature, test/bdd/pkg/didexchange/didexchange_sdk_steps.go
Send DID exchange request without invitation
Initiator knows public DID.
Wants to request DID exchange without prior invitation.
Closes #718
=> feat: Implicit Invitation

pkg/restapi/operation/didexchange/didexchange.go, test/bdd/agent_controller_steps.go, test/bdd/bddtests_test.go, test/bdd/features/didexchange_e2e_controller.feature, test/bdd/features/didexchange_public_did.feature, test/bdd/fixtures/agent-rest/docker-compose.yml, test/bdd/fixtures/sidetree-mock/docker-compose.yml, test/bdd/pkg/didexchange/didexchange_controller_steps.go
- added steps for below scenarios,
`DID Exchange with public DID using controller`
`DID Exchange with public and peer DIDs using controller`
- closes #796
=> feat: controller bddtests for DIDExchange with public DIDs

cmd/aries-agent-rest/startcmd/start.go, cmd/aries-agent-rest/startcmd/start_test.go, docs/rest/agent_cli.md, pkg/client/didexchange/client_test.go, pkg/client/didexchange/example_test.go, pkg/didcomm/common/service/event.go, pkg/didcomm/common/service/event_test.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/restapi.go, pkg/restapi/restapi_test.go
=> feat: Add option auto-accept for rest cli

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/client/didexchange/models.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/internal/mock/didcomm/protocol/mock_didexchange.go, test/bdd/features/didexchange_public_did.feature, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/didresolver/didresolver_steps.go
Enable invitee to specify own public did for implicit invitation.
Closes #892
=> feat: Enable invitee to specify public did for implicit invitation

pkg/didcomm/protocol/didexchange/service.go, pkg/restapi/operation/didexchange/didexchange.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/restapi/operation/didexchange/models/invitation.go, test/bdd/features/didexchange_public_did.feature, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go
Add implicit Invitation endpoint to did-exchange REST API.
Closes: #897
=> feat: REST API: Implicit Invitation

pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
* added `InvitationReceived` function to  finish state machine
* the behavior of the state machine is completed
Closes #883 
Part of #269
=> feat: Introduce - finish state machine

pkg/internal/mock/packer/noop.go, pkg/internal/mock/packer/noop_test.go
=> chore: No-op Packer, useful for testing.

pkg/didcomm/dispatcher/outbound.go, pkg/didcomm/transport/http/inbound.go, pkg/didcomm/transport/ws/pool.go, pkg/framework/aries/framework.go, test/bdd/agent_sdk_steps.go, test/bdd/features/aries_e2e_route_option.feature
=> test: BDD test for Transport Return Route option

pkg/didcomm/common/model/problem_report.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
* added ProblemReport structure (a few fields)
* now, we can handle one more use case (no one responded with invitation)
* tests were refactored
Part one of issue #890 
=> feat: Introduce - Add validation to the service for incoming messages

Makefile, scripts/run-openapi-demo.sh, test/bdd/fixtures/demo/openapi/docker-compose.yml
=> fix: make run-openapi-demo fails

pkg/storage/jsindexeddb/jsindexeddb.go
=> fix: Switch from add to put for jsindexeddb

pkg/didcomm/transport/ws/upgrade_srv.go
=> feat: Enable InsecureSkipVerify for ws

.github/workflows/build.yml, ci/version_var.sh
=> chore: Push agent-rest image to Github packages

pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
This PR implements behavior when introducee stops the protocol.
Part two of issue #890 
Closes #890 
=> feat: Introduce - approval validation & service behavior

pkg/doc/verifiable/common_test.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_extension_switch_test.go, pkg/doc/verifiable/credential_jws_test.go, pkg/doc/verifiable/credential_jwt_proof_test.go, pkg/doc/verifiable/credential_jwt_test.go, pkg/doc/verifiable/credential_jwt_unsecured_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/json_test.go, pkg/doc/verifiable/jwt_unsecured_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_jws_test.go, pkg/doc/verifiable/presentation_jwt_proof_test.go, pkg/doc/verifiable/presentation_jwt_unsecured_test.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/support_test.go
=> feat: Create and verify JWS when creating new presentation

pkg/didcomm/protocol/route/models.go, pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go, pkg/didcomm/protocol/route/support_test.go
- Create New Service for Route Coordination Spec
- Implement Accept/Name functions
part of #837 
=> feat: Route Coordination (RFC 0091) - Base service structure implementation

README.md
=> docs: fix license badge URL

pkg/didcomm/protocol/route/models.go, pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go, pkg/didcomm/protocol/route/support_test.go
- Implement [Route Request](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination#route-request) handler
- Implement [Route Keylist Update](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination#keylist-update) handler
closes #940 
=> feat: Route Coordination - Implement Request and Key List Update message types

cmd/aries-agent-rest/go.sum, go.mod, go.sum, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go, test/bdd/go.sum
=> feat: A cache of custom credential schemas of Verifiable Credential

cmd/aries-agent-rest/go.sum, pkg/client/introduce/client.go, pkg/client/introduce/client_test.go, pkg/didcomm/protocol/introduce/models.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
* ability to fill To structure for Proposal messages
* tests were refactored
=> feat: Introduce - add To structure to the proposal messages

pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go, pkg/didcomm/protocol/route/support_test.go
- Implement [Route Grant](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination#route-grant) handler
- Implement [Route Keylist Update Response](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination#keylist-update-response) handler
closes #941 
=> feat: Route Coordination - Structure for Grant and  Keylist Update message types

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go
=> fix: date-time format in "default" JSON VC schema.

pkg/didcomm/protocol/didexchange/states.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go
- fix for issue with resolve their peer DID
- closes #999
=> fix: resolve theirDID after did-exchange

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/test-suite/verifiable_suite_test.go, scripts/run_vc_test_suite.sh
closes #992
A number of VC Test Suite failures:
- Before: 2
- After: 0
=> feat: VC context options

pkg/doc/verifiable/cache.go, pkg/doc/verifiable/cache_js_wasm.go, pkg/doc/verifiable/credential.go
=> fix: golangci failing for doc/verifiable

pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go, pkg/internal/mock/didcomm/dispatcher/mock_outbound.go
=> refactor: Use SendToDID instead of Send in request route

pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/states.go, pkg/didcomm/protocol/introduce/states_test.go
=> refactor: Introduce - client stops the protocol without passing an error

pkg/didcomm/common/service/service.go, pkg/didcomm/common/service/service_test.go, pkg/didcomm/protocol/decorator/decorator.go
Closes https://github.com/hyperledger/aries-framework-go/issues/1023
=> fix: Add missing fields to the thread decorator

pkg/client/route/client.go, pkg/client/route/client_test.go, pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go, pkg/framework/aries/default.go, pkg/internal/mock/didcomm/protocol/route/mock_route.go
=> feat: Add route client

cmd/aries-agent-rest/go.sum, go.mod, go.sum, test/bdd/go.sum
=> build: update json-gold dependency to get support of JSON-LD 1.1

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/client/didexchange/models.go, pkg/client/route/client.go, pkg/client/route/client_test.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/didcomm/protocol/didexchange/persistence_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/store/connection/connection_lookup.go, pkg/store/connection/connection_lookup_test.go, pkg/store/connection/connection_recorder.go, pkg/store/connection/connection_recorder_test.go
=> chore: Move connectionstore under pkg/store/connectionstore

pkg/didcomm/packager/packager.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/didcomm/protocol/didexchange/persistence_test.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/store/did/didconnection.go, pkg/store/did/didconnection_test.go
=> chore: Move didconnection under pkg/store/

pkg/store/verifiable/store.go, pkg/store/verifiable/store_test.go
=> feat: Create vc store

pkg/crypto/tinkcrypto/crypto.go, pkg/crypto/tinkcrypto/crypto_test.go
=> refactor: make tinkcrypto error messages succinct

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/support_test.go, pkg/store/verifiable/store_test.go
=> fix: support single @context definition

pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go
=> fix: Integrate route service with SendToDID function

cmd/aries-agent-rest/startcmd/start.go, pkg/didcomm/common/service/service.go, pkg/didcomm/dispatcher/api.go, pkg/didcomm/msghandler/msghandler.go, pkg/didcomm/msghandler/msghandler_test.go, pkg/framework/aries/api/protocol.go, pkg/framework/aries/default.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/restapi/restapi.go
- `framework.Messenger()` to returns messenger to support outbound messaging feature 
from agent framework
- closes #1059 
=> feat: Outbound dispatcher for message handler

pkg/framework/aries/framework.go, test/bdd/agent/agent_sdk_steps.go, test/bdd/bddtests_test.go, test/bdd/features/messaging_e2e_sdk.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/messaging/messaging_sdk_steps.go, test/bdd/pkg/messaging/msgservice.go
- added messaging test feature in bddtests to demonstrate and test
message registrating registration and handling
- closes #1079
=> feat: bddtests - msgservice registration & handling using SDK

cmd/aries-js-worker/aries.js
=> fix: invalid reference in aries.js

pkg/doc/verifiable/credential_ldp.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/embedded_proof_test.go, pkg/doc/verifiable/jsonld.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/linked_data_proof_test.go, pkg/doc/verifiable/presentation_ldp.go, pkg/doc/verifiable/presentation_ldp_test.go, pkg/internal/mock/didcomm/protocol/mock_protocol.go, pkg/restapi/operation/common/models.go, pkg/restapi/operation/common/operation.go, pkg/restapi/operation/common/operation_test.go, pkg/restapi/restapi.go
- added 2 endpoints for sending new messages and sending reply messages
- closes #1090
=> feat: REST Binding - send new message and reply message

test/bdd/bddtests_test.go, test/bdd/features/messaging_e2e_controller.feature, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/messaging/messaging_controller_steps.go, test/bdd/webhook/main.go
- added bddtests demonstrating message service registration & handling
using controller API
- closes #974 
=> feat: Message Service - REST binding bddtests

pkg/client/didexchange/client_test.go, pkg/client/didexchange/example_test.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/didcomm/protocol/route/service.go, pkg/framework/aries/api/vdri/vdri.go, pkg/framework/aries/default.go, pkg/internal/mock/didcomm/protocol/mock_protocol.go, pkg/restapi/operation/didexchange/didexchange_test.go, pkg/vdri/httpbinding/vdri.go, pkg/vdri/peer/creator.go, pkg/vdri/peer/creator_test.go
=> feat: Integrate Route Service with DIDExchange Request message

cmd/aries-js-worker/app.js, cmd/aries-js-worker/aries-worker-node.js, cmd/aries-js-worker/aries.js
Initial scaffolding for NodeJS support.
=> feat: initial scaffolding for NodeJS

docs/project_structure.md, pkg/didcomm/messaging/doc.go, pkg/didcomm/messaging/msghandler/example_test.go, pkg/didcomm/messaging/msghandler/msghandler.go, pkg/didcomm/messaging/service/http/httpmsgsvc.go, pkg/didcomm/messaging/service/http/httpmsgsvc_test.go, pkg/framework/aries/framework.go
=> feat: docs for messaging & http over didcomm

.github/workflows/build.yml
=> ci: update github actions target OS

pkg/client/introduce/doc.go
=> fix: Introduce documentation

docs/project_structure.md, pkg/doc/verifiable/common.go, pkg/doc/verifiable/example_credential_test.go
=> docs: Improve docs for verifiable package

Makefile
Added a common path for gomocks `GOMOCKS=pkg/internal/gomocks`.
=> refactor: gomocks generation improvement

pkg/restapi/operation/common/models.go, pkg/restapi/operation/common/msgservice.go, pkg/restapi/operation/common/msgservice_test.go, pkg/restapi/operation/common/operation.go, pkg/restapi/operation/common/operation_test.go
- added http over did comm message service registration endpoint
- closes #1129
=> feat: REST Binding - HTTP over DIDCOmm

docs/rest/openapi_demo.md
=> docs: demo for messaging, http-over-didcomm and vdri REST endpoints

ci/version_var.sh
=> chore: Update release flag to true for 0.1.1 release

ci/version_var.sh
- Update version to v.0.1.2
- Update release flag to false
=> chore: v0.1.1 Release complete

pkg/didcomm/messaging/service/basic/basicmsgsvc.go, pkg/didcomm/messaging/service/basic/basicmsgsvc_test.go, pkg/didcomm/messaging/service/basic/models.go, test/bdd/features/messaging_e2e_controller.feature, test/bdd/features/messaging_e2e_sdk.feature, test/bdd/pkg/messaging/messaging_controller_steps.go, test/bdd/pkg/messaging/messaging_sdk_steps.go, test/bdd/pkg/messaging/messaging_steps.go, test/bdd/webhook/main.go
=> feat: BDD tests to demonstrate basic messaging protocol

pkg/controller/command/errors.go, pkg/controller/command/vdri/command.go, pkg/controller/command/vdri/command_test.go, pkg/controller/command/vdri/models.go
- added controller command for vdri operations
- Part of #1175
=> feat: controller commands for VDRI

pkg/didcomm/common/service/did_comm_msg.go, pkg/didcomm/common/service/did_comm_msg_test.go, pkg/didcomm/messenger/messenger.go, pkg/didcomm/messenger/messenger_test.go
* Added Metadata to the ~thread decorator
* Messenger saves and provides data
Closes #1164 
=> feat: Add Metadata field to the thread decorator

pkg/didcomm/messenger/messenger.go, pkg/didcomm/messenger/messenger_test.go
Now `ReplyTo` function includes parent threadID  if the thread was started by using ReplyToNested function.
Part of https://github.com/hyperledger/aries-framework-go/issues/1092
=> feat: Support parent threadID for ReplyToNested and ReplyTo

pkg/doc/verifiable/common.go, pkg/doc/verifiable/common_test.go, pkg/doc/verifiable/credential_jws_test.go, pkg/doc/verifiable/credential_jwt_proof_test.go
#1155
To close #1155, there will be one more PR to support the use case with Linked Data Proofs.
=> feat: VC With DID Resolution

cmd/aries-agent-rest/startcmd/start.go, cmd/aries-agent-rest/startcmd/start_test.go, test/bdd/agent/agent_controller_steps.go, test/bdd/features/aries_e2e_route_option.feature, test/bdd/fixtures/agent-rest/.env, test/bdd/fixtures/agent-rest/docker-compose.yml
=> feat: Transport Return Route Option - Rest Binding BDD tests

pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/linked_data_proof_test.go
=> fix: keyResolverAdapter id

test/bdd/features/aries_e2e_route_option.feature, test/bdd/features/aries_router_e2e_sdk.feature, test/bdd/features/didexchange_e2e_controller.feature, test/bdd/features/didexchange_e2e_sdk.feature, test/bdd/features/didexchange_public_did.feature, test/bdd/features/introduce.feature, test/bdd/features/messaging_e2e_controller.feature, test/bdd/features/messaging_e2e_sdk.feature
=> fix: BDD/Gherkin format of feature files

pkg/doc/verifiable/linked_data_proof.go
=> fix: add # to key

pkg/didcomm/protocol/didexchange/states_test.go, pkg/doc/did/helpers.go, pkg/store/did/didconnection.go, pkg/vdri/httpbinding/vdri.go, pkg/vdri/peer/creator.go
=> fix: Decode public key value

pkg/client/route/client.go, pkg/client/route/client_test.go, pkg/controller/command/route/command.go, pkg/controller/command/route/command_test.go, pkg/controller/rest/route/operation.go, pkg/controller/rest/route/operation_test.go, pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go, pkg/internal/mock/didcomm/protocol/route/mock_route.go
- New route service, client, controller functions
- REST Binding for this new feature
part of #1210 
=> feat: Support to unregister Router

cmd/aries-js-worker/index.html, cmd/aries-js-worker/main.go, cmd/aries-js-worker/src/aries.js, pkg/controller/command/didexchange/command.go
- exposed current command handlers as functions in `aries-js-worker`
- closes #1221
=> feat: command handlers in JS worker

cmd/aries-js-worker/src/aries.js, pkg/controller/command/route/command.go, pkg/controller/command/route/command_test.go, pkg/controller/rest/route/operation.go
=> feat: Add Router unregister function to command handler/wasm and update swagger annotations

cmd/aries-js-worker/App.js, cmd/aries-js-worker/src/aries.js, cmd/aries-js-worker/vue-aries-framework-go/package-lock.json, cmd/aries-js-worker/vue-aries-framework-go/src/components/HelloFrameworkGo.vue, cmd/aries-js-worker/vue-aries-framework-go/src/main.js
* Exposed as a constructor that accepts options
* Refactored to use camelCase
* Unexported the worker and the pending task map
=> fix: aries-js-worker - camelCase

cmd/aries-js-worker/index.html, cmd/aries-js-worker/src/aries.js
* fixed exports
* Aries is now a singleton
* TODO: refactor to have a getter for the singleton
=> fix: aries-js-worker fixed exports

pkg/doc/signature/ed25519signature2018/suite.go, pkg/doc/signature/proof/data.go, pkg/doc/signature/proof/data_test.go, pkg/doc/signature/proof/jws.go, pkg/doc/signature/proof/jws_test.go, pkg/doc/signature/proof/proof.go, pkg/doc/signature/proof/proof_test.go, pkg/doc/signature/signer/signer.go, pkg/doc/signature/signer/signer_test.go, pkg/doc/signature/verifier/verifier.go, pkg/doc/signature/verifier/verifier_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/embedded_proof_test.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/jsonld.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/linked_data_proof_test.go, pkg/doc/verifiable/presentation_ldp_test.go
closes #1093
Based on https://github.com/digitalbazaar/jsonld-signatures
=> feature: Support "jws" Linked Data proof

cmd/aries-agent-rest/startcmd/start.go, cmd/aries-js-worker/index.html, cmd/aries-js-worker/main.go, cmd/aries-js-worker/src/aries.js
- added `log-level` aries.Start() opts
- closes #1245
=> feat: aries-js-worker log level start opts

pkg/kms/api.go, pkg/mock/kms/mock_kms.go
=> feat: Add a new KMS API and mock

cmd/aries-js-worker/index.html, cmd/aries-js-worker/main.go
- fixed issue with commands which returns no response structure
- also refactored command handling code
- closes #1250
=> fix: handling empty response in aries-js-worker

pkg/mock/storage/mock_store.go
Added missing `ErrDelete` variable in mockStore
part of #1148
=> refactor: update MockStore

pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
Fixes signature buffer format in DIDExchange protocol
Closes #1257
=> fix: DIDExchange signature buffer format

pkg/didcomm/common/service/did_comm_msg.go, pkg/didcomm/common/service/did_comm_msg_test.go, pkg/didcomm/common/service/messenger.go, pkg/didcomm/common/service/service_test.go, pkg/didcomm/messenger/messenger.go, pkg/didcomm/messenger/messenger_test.go, pkg/didcomm/protocol/introduce/service.go, test/bdd/go.sum
* added ParentThreadID() function
*  added Clone() function
Part of #1157 
=> refactor: Messenger and DIDCommMsgMap improvements (part 1)

cmd/aries-js-worker/index.html, cmd/aries-js-worker/src/aries.js
- changed `aries.waitForNotification(topics)` to
`aries.startNotifier(topics, callback)`
- added message center in presentation html to display incoming
messages/topics in table instead of alerts
- closes #1262
=> feat:aries js worker notifier to watch instead of pop

.github/workflows/build.yml
=> chore: login to docker.pkg.github.com in bddTest task

pkg/controller/command/vdri/command.go, test/bdd/fixtures/sidetree-mock/.env, test/bdd/fixtures/sidetree-mock/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/didresolver/didresolver_steps.go
Update to latest sidtree-mock; there are interface changes
Closes #1255 #1235 
=> chore: update to latest sidetree-mock

cmd/aries-js-worker/index.html, cmd/aries-js-worker/src/aries.js, cmd/aries-js-worker/src/worker-loader-node.js, cmd/aries-js-worker/src/worker-loader-web.js, cmd/aries-js-worker/webpack.config.node.js, cmd/aries-js-worker/webpack.config.web.js
=> feat: #1268 aries-js-worker - parametrize assets path

pkg/controller/command/didexchange/command.go, pkg/controller/command/messaging/command.go, pkg/controller/command/route/command.go, pkg/controller/command/vdri/command.go, pkg/didcomm/messaging/service/basic/basicmsgsvc.go, pkg/didcomm/messaging/service/http/httpmsgsvc.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/route/service.go, pkg/internal/logutil/util.go, pkg/store/connection/connection_lookup.go, pkg/store/connection/connection_lookup_test.go, pkg/store/connection/connection_recorder.go, pkg/store/connection/connection_recorder_test.go
=> chore: Add loggers for efficient debugging and Add mapping between DID - connectionID

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go
=> feat: Parse Verifiable Credential without checking proofs

cmd/aries-js-worker/index.html, cmd/aries-js-worker/src/aries.js
=> fix: stutter in aries-js-worker API for browser mode

docs/rest/openapi_demo.md, docs/test/build.md
=> docs: Add docker authentication with GitHub as the prerequisite for running the demo

pkg/store/verifiable/store.go
=> feat: Use NewUnverifiedCredential in GetVC

docs/rest/openapi_demo.md
=> fix: fix docs for openapi messaging steps

pkg/didcomm/protocol/introduce/service.go
=> fix: Introduce BDD test failure

pkg/controller/command/messaging/command.go, pkg/controller/command/messaging/command_test.go, pkg/controller/command/route/command.go, pkg/controller/command/route/command_test.go, pkg/controller/rest/messaging/operation.go, pkg/controller/rest/messaging/operation_test.go, pkg/controller/rest/route/operation.go
=> refactor: command names matching REST endpoints

cmd/aries-js-worker/src/aries.js, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/controller.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go
=> feat: Controller binding(rest/js) for VC Save operation

README.md, doc.go, docs/go/README.md
=> chore: Changed URLs for the docs

test/bdd/features/introduce.feature, test/bdd/pkg/introduce/introduce_sdk_steps.go
BDD tests improvements
Closes https://github.com/hyperledger/aries-framework-go/issues/1332
=> test: Introduce - BDD tests improvements

cmd/aries-js-worker/src/aries.js, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go
=> feat: Controller binding(rest/js) for VC Get Operation

pkg/vdri/httpbinding/resolver.go, pkg/vdri/httpbinding/resolver_test.go
=> feat: Get did doc from resolution-result in vdri http binding

cmd/aries-js-worker/src/aries.js, test/aries-js-worker/test/didexchange/edgeagent_router.js
=> chore: Aries JS API Documentation

cmd/aries-js-worker/src/agent-rest-client.js
=> feat: VC Store JS API - support for rest client

README.md, docs/kms_secretlock.md, pkg/framework/aries/api/protocol.go, pkg/framework/aries/default.go, pkg/framework/aries/default_test.go, pkg/framework/aries/framework.go, pkg/framework/aries/framework_test.go, pkg/framework/context/context.go, pkg/framework/context/context_test.go, pkg/kms/api.go, pkg/kms/localkms/localkms.go, pkg/kms/localkms/localkms_test.go, pkg/secretlock/noop/noop_secret_lock.go, pkg/secretlock/noop/noop_secret_lock_test.go, pkg/storage/jsindexeddb/jsindexeddb.go
=> chore: Hook the new KMS in the framework and Context

README.md, cmd/aries-js-worker/App.js, cmd/aries-js-worker/README.md, cmd/aries-js-worker/src/aries.js
=> doc: aries-js-worker release notes

README.md
=> doc: include link to aries-js-worker GH package

README.md, cmd/aries-js-worker/README.md
=> doc: aries-js-worker: minor tweak to README

cmd/aries-js-worker/README.md, cmd/aries-js-worker/index.html, cmd/aries-js-worker/src/worker-impl-rest.js, pkg/controller/controller.go
=> fix: added websocket notifier in REST controller handlers

ci/version_var.sh, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: Aries Framework Go v0.1.2 release

ci/version_var.sh
=> feat: v0.1.2 release complete

.github/workflows/build.yml, .github/workflows/test-suite.yml, Makefile, ci/azure-pipelines.yml, cmd/aries-agent-rest/go.mod, cmd/aries-js-worker/README.md, docs/test/build.md, go.mod, pkg/controller/webnotifier/webhook_test.go, test/bdd/go.mod
=> chore: update to Go 1.14

pkg/doc/verifiable/common.go, pkg/doc/verifiable/common_test.go
=> feat: DIDKeyResolver: check key id in did authentication

cmd/aries-js-worker/vue-aries-framework-go/package-lock.json, cmd/aries-js-worker/vue-aries-framework-go/package.json
=> fix: VueJS Sample app - Update aries-js version to use local dependency

pkg/vdri/httpbinding/resolver.go
=> feat: Add accept header in resolver http binding

pkg/vdri/httpbinding/resolver.go
=> fix: check http header Content-type contains type

cmd/aries-js-worker/src/aries.js, test/aries-js-worker/test/common.js, test/aries-js-worker/test/didexchange/edgeagent_router.js
=> test: Aries JS Worker - Router BDD tests

pkg/didcomm/common/service/did_comm_msg.go, pkg/didcomm/common/service/did_comm_msg_test.go, pkg/didcomm/common/service/errors.go, pkg/didcomm/common/service/messenger.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go
* added service common logic
Part of #1173 
=> feat: Issue Credential - protocol states skeleton

test/aries-js-worker/test/didexchange/edgeagent_router.js
* added a guarantee that two agents are started (BDD)
=> fix: Added a guarantee that two agents are started (BDD)

pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go
This PR adds proper states transitions.
Part of #1173
Depends on https://github.com/hyperledger/aries-framework-go/pull/1343
=> feat: Issue Credential - defines states transitions

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/vdri/httpbinding/vdri_test.go
=> feat: parse did v0.11

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation_test.go, pkg/store/verifiable/store.go, pkg/store/verifiable/store_test.go
=> feat: VC Store - Add support for VC name store and get feature

pkg/doc/verifiable/common.go
=> fix: add string contains to check keyID in resolvePublicKey

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go, pkg/store/verifiable/models.go, pkg/store/verifiable/store.go, pkg/store/verifiable/store_test.go
=> feat: VC Store Get Credential API along with Command/Controller Support

pkg/doc/signature/ed25519signature2018/suite_test.go, test/bdd/bddtests_test.go, test/bdd/features/verifiable_credential.feature, test/bdd/pkg/verifiable/signer.go, test/bdd/pkg/verifiable/verifiable_steps.go
closes #1342
VC signing and verification using JWS Linked Data proof.
JWS proof will be added as a follow-up PR (which should close the issue).
=> feat: VC signing bddtest

pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go, test/bdd/go.mod, test/bdd/go.sum
* `HandleOutbound` function can send a proposal.
* `HandleInbound` function can receive a proposal.
Part of #1173 
=> feat: Issue Credential - state implementation for proposal sent/received

cmd/aries-js-worker/src/aries.js, test/aries-js-worker/test/didexchange/edgeagent_router.js, test/aries-js-worker/test/vcstore/vcstore.js
=> test: VC Store BDD tests for JS/WASM API

pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go
* `HandleOutbound` function can send an offer.
* `HandleInbound` function can receive an offer.
Part of #1173 
=> feat: Issue Credential - state implementation for offer sent/received

pkg/doc/signature/proof/proof.go, pkg/doc/signature/proof/proof_test.go, pkg/doc/signature/signer/signer.go, pkg/doc/signature/verifier/verifier.go, pkg/doc/signature/verifier/verifier_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/linked_data_proof_test.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> feat: verificationMethod for proof verification

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go, test/bdd/features/verifiable_credential.feature, test/bdd/pkg/verifiable/verifiable_steps.go
closes #1342
JWS proof test will be much improved after closing of #339
=> feat: VC signing bddtest - JWS proof

.github/workflows/build.yml, ci/azure-pipelines.yml
=> ci: use actions for codecov

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go, test/aries-js-worker/test/verifiable/verifiable.js
=> feat: Controller for generate Verifiable Presentation API

cmd/aries-js-worker/src/aries.js, test/aries-js-worker/test/common.js, test/aries-js-worker/test/didexchange/didexchange_e2e.js, test/aries-js-worker/test/messaging/messaging.js
- js test for messaging covering register/unregister/send/receive
features
- added test didexchange e2e client to serve presteps features involving
didexchange between 2 agents
- closes #1412
=> feat: messaging js worker test

pkg/vdri/httpbinding/vdri.go
=> fix: print body respone when receive failure

pkg/doc/verifiable/common.go, pkg/vdri/httpbinding/vdri.go, test/bdd/fixtures/sidetree-mock/.env, test/bdd/fixtures/sidetree-mock/config/didDocument.json, test/bdd/go.mod, test/bdd/go.sum
Update to the version with controller changes
Closes #1432
=> chore: Update sidetree-mock and sidetree-core

pkg/doc/verifiable/common.go, pkg/vdri/registry.go
=> Fix: check for did parts

pkg/controller/command/messaging/command.go, pkg/controller/command/messaging/command_test.go, pkg/controller/rest/messaging/operation.go, pkg/controller/rest/messaging/operation_test.go, pkg/didcomm/common/service/messenger.go, pkg/didcomm/messenger/messenger.go, pkg/didcomm/messenger/messenger_test.go, pkg/internal/gomocks/didcomm/common/service/mocks.go, pkg/internal/mock/didcomm/protocol/mock_protocol.go, pkg/internal/mock/didcomm/service/mock_service.go, test/bdd/agent/agent_sdk_steps.go, test/bdd/features/messaging_e2e_controller.feature, test/bdd/features/messaging_e2e_sdk.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/didresolver/didresolver_steps.go, test/bdd/pkg/messaging/messaging_controller_steps.go, test/bdd/pkg/messaging/messaging_sdk_steps.go, test/bdd/pkg/messaging/messaging_steps.go, test/bdd/pkg/verifiable/verifiable_steps.go
- message service command controller to use messanger api
- send message to support out of band messages
- Part of #1058
=> feat: out of band messaging

pkg/controller/command/messaging/command.go, pkg/controller/command/messaging/command_test.go, pkg/controller/rest/messaging/operation_test.go, test/aries-js-worker/test/messaging/messaging.js, test/bdd/features/messaging_e2e_controller.feature, test/bdd/features/messaging_e2e_sdk.feature, test/bdd/pkg/messaging/messaging_controller_steps.go, test/bdd/pkg/messaging/messaging_sdk_steps.go, test/bdd/pkg/messaging/messaging_steps.go
- send reply message support in command controller, REST & JS
- added bdd tests for SDK, Controller and JS versions.
- closes #1089
=> feat: send reply message

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go
Signed-off-by: Aleksei Belezeko <aleksei.belezeko@t-systems.com>
I found a bug that Parse Document get panic in case of null string. Now it returns nil in case of null string.
Closes #1430
=> fix: fix panic in case of parsing null did document

ci/azure-pipelines.yml
- explicitly disable the pull request triggers in AZP configuration.
=> ci: disable azp pr triggers

cmd/aries-js-worker/package-lock.json
=> fix: npm transitive dependency audit issue fix

test/aries-js-worker/package-lock.json, test/aries-js-worker/package.json
=> fix: Update npm minimist dependency to fix cve

pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go, pkg/framework/aries/default.go, test/bdd/bddtests_test.go, test/bdd/features/issue-credential.feature, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go
Covers the following test cases:
* The Holder begins with a request
* The Issuer begins with an offer
* The Holder begins with a proposal
Closes #1460 
=> feat: Issue Credential - adds BDD tests

pkg/client/outofband/client.go, pkg/client/outofband/client_test.go
=> chore: out-of-band client: provide dependencies from framework Context

cmd/aries-js-worker/package-lock.json, cmd/aries-js-worker/package.json, cmd/aries-js-worker/vue-aries-framework-go/package-lock.json, test/aries-js-worker/package-lock.json, test/aries-js-worker/package.json
=> refactor: Add npm minimist to dependecy list and remove pre-install script

pkg/didcomm/packer/jwe/authcrypt/authcrypt.go, pkg/didcomm/packer/jwe/authcrypt/authcrypt_test.go, pkg/didcomm/packer/jwe/authcrypt/pack.go, pkg/didcomm/packer/jwe/authcrypt/unpack.go, pkg/doc/jose/common.go, pkg/doc/jose/jwe.go, pkg/doc/jose/jwe_test.go, pkg/doc/jose/jws.go
The existing JWE and legacy JWE will be removed in a future commit.
closes #1409
=> refactor: JWE implementation in jose 

pkg/didcomm/protocol/outofband/models.go, pkg/didcomm/protocol/outofband/service.go, pkg/didcomm/protocol/outofband/service_test.go
=> feat: hook out-of-band svc into didexchange svc

pkg/crypto/api.go, pkg/crypto/tinkcrypto/crypto.go, pkg/crypto/tinkcrypto/crypto_test.go, pkg/kms/api.go, pkg/kms/localkms/localkms.go, pkg/kms/localkms/localkms_test.go, pkg/mock/crypto/mock_crypto.go
=> feat: HMAC-SHA256 support

Makefile, cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/errors.go, pkg/controller/command/kms/command.go, pkg/controller/command/kms/command_test.go, pkg/controller/command/kms/models.go, pkg/controller/controller.go, pkg/controller/rest/kms/models.go, pkg/controller/rest/kms/operation.go, pkg/controller/rest/kms/operation_test.go, test/aries-js-worker/test/kms/kms.js
=> feat: Controller for generate public key API

test/aries-js-worker/test/didexchange/edgeagent_router.js
=> refactor: Disable DIDExchange JS tests

test/aries-js-worker/karma.conf.js, test/aries-js-worker/test/didexchange/edgeagent_router.js
=> test: JS BDD - increase karma-mocha timeout value

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/doc/did/schema.go
- added support for context 'https://www.w3.org/2019/did/v1'
- closes #1535
=> feat: DID Schema Validation - support for old context

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/doc/did/schema.go
=> feat: DID Schema validation - support for empty auth key & jwk

pkg/didcomm/protocol/presentproof/service.go, pkg/didcomm/protocol/presentproof/service_test.go, pkg/didcomm/protocol/presentproof/states.go, pkg/didcomm/protocol/presentproof/states_test.go
Functions ExecuteInbound/Outbound were merged.
Closes #1528 
=> feat: Present Proof - functions ExecuteInbound/Outbound were merged

test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go
Increases the timeout (BDD tests).
=> test: Issue Credential - increases the timeout for BDD tests

pkg/didcomm/packager/packager.go, pkg/didcomm/protocol/didexchange/persistence.go, pkg/didcomm/protocol/didexchange/persistence_test.go, pkg/didcomm/protocol/didexchange/states_test.go, pkg/store/did/didconnection.go, pkg/store/did/didconnection_test.go, pkg/store/did/models.go, pkg/store/did/store.go, pkg/store/did/store_test.go
=> feat: Create DID store

test/bdd/agent/agent_controller_steps.go, test/bdd/agent/agent_sdk_steps.go, test/bdd/bddtests_test.go, test/bdd/features/outofband_e2e_sdk.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go, test/bdd/pkg/didresolver/didresolver_steps.go, test/bdd/pkg/introduce/introduce_sdk_steps.go, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go, test/bdd/pkg/messaging/messaging_controller_steps.go, test/bdd/pkg/messaging/messaging_sdk_steps.go, test/bdd/pkg/messaging/messaging_steps.go, test/bdd/pkg/outofband/outofband_sdk_steps.go, test/bdd/pkg/route/route_controller_steps.go, test/bdd/pkg/route/route_sdk_steps.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> feat: outofband BDD SDK tests

pkg/didcomm/protocol/presentproof/service.go, pkg/didcomm/protocol/presentproof/service_test.go
The following functions were added:
* `ActionContinue` allows proceeding with the protocol
* `ActionStop` allows stopping the protocol
* `Actions` returns all available actions
Closes #1554
=> feat: Present Proof - functions were exposed for the async usage

pkg/doc/signature/proof/jws.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/linked_data_proof_test.go, pkg/doc/verifiable/support_test.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> test: do not drop Proof Type from verification data

pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier.go, pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go, pkg/doc/signature/suite/jsonwebsignature2020/suite.go, pkg/doc/verifiable/credential_ldp_test.go
=> feat: Support Ed25519 / RSA in JsonWebSignature2020 signature verifier

pkg/controller/command/vdri/command.go, pkg/controller/command/vdri/command_test.go, pkg/controller/command/vdri/models.go, pkg/controller/controller.go, pkg/controller/rest/vdri/operation.go, pkg/controller/rest/vdri/operation_test.go, pkg/store/did/store.go, pkg/store/did/store_test.go
1. Save DID 
2. Get DID 
3. Get DIDRecords
=> feat: Controller command to save did, get did handlers 

Makefile
=> chore: Update OpenAPI docker image version

pkg/doc/signature/suite/ecdsasecp256k1signature2019/public_key_verifier.go, pkg/doc/signature/suite/ecdsasecp256k1signature2019/public_key_verifier_test.go, pkg/doc/signature/suite/ecdsasecp256k1signature2019/suite.go, pkg/doc/signature/suite/ecdsasecp256k1signature2019/suite_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/support_test.go
=> feat: Support ECDSA Secp256k1 linked data signature suite

pkg/didcomm/messenger/messenger.go, pkg/didcomm/protocol/presentproof/service.go, pkg/framework/aries/default.go, test/bdd/bddtests_test.go, test/bdd/features/presentproof.feature, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
Adds BDD tests for the Present Proof protocol.
Closes #1569 
=> feat: Present Proof - adds BDD tests

pkg/controller/rest/vdri/models.go, pkg/controller/rest/vdri/operation.go, pkg/controller/rest/vdri/operation_test.go
=> feat: Rest Api for did handlers

cmd/aries-agent-rest/go.sum, go.sum, test/bdd/go.sum
=> fix: Update go.sum as tink library has 2 conflicting dependencies

test/aries-js-worker/test/kms/kms.js
Fixes BDD tests.
Closes #1445 
=> refactor: Fixes JS BDD tests

pkg/didcomm/protocol/didexchange/states.go, pkg/doc/did/doc_test.go, pkg/doc/signature/suite/ecdsasecp256k1signature2019/public_key_verifier.go, pkg/doc/signature/suite/ecdsasecp256k1signature2019/public_key_verifier_test.go, pkg/doc/signature/suite/ed25519signature2018/public_key_verifier.go, pkg/doc/signature/suite/ed25519signature2018/public_key_verifier_test.go, pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier.go, pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go, pkg/doc/signature/verifier/public_key_verifier.go, pkg/doc/signature/verifier/public_key_verifier_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/embedded_proof_test.go, pkg/doc/verifiable/linked_data_proof_test.go, pkg/kms/legacykms/kms_test.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> refactor: public key verifiers in signature suites

pkg/doc/did/doc_test.go, pkg/doc/did/schema.go
=> fix: remove required ID in service for https://www.w3.org/2019/did/v1

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/presentation.go
=> refactor: Export Signing and Verifier Suite interface

cmd/aries-agent-rest/go.sum, go.mod, go.sum, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/presentproof/service.go, pkg/storage/couchdb/couchdbstore.go, pkg/storage/couchdb/couchdbstore_test.go, pkg/storage/leveldb/leveldb_store.go, pkg/storage/store.go, pkg/store/connection/connection_lookup.go, pkg/store/connection/connection_recorder.go, pkg/store/connection/connection_recorder_test.go, pkg/store/did/store.go, pkg/store/verifiable/store.go, scripts/check_unit.sh, test/bdd/go.sum
=> feat: Add couchdb store implementation

pkg/doc/signature/proof/proof.go, pkg/doc/signature/proof/proof_test.go, pkg/doc/signature/signer/signer.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/linked_data_proof.go
=> feat: purpose, domain & challenge options  in Linked Data Proof

pkg/doc/signature/verifier/verifier.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/embedded_proof_test.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/linked_data_proof_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> refactor: support multiple signature suites for VC and VP verification

pkg/storage/couchdb/couchdbstore.go
=> feat: Get rev ID from couchdb

pkg/storage/couchdb/couchdbstore.go
=> fix: check db is exists

pkg/client/issuecredential/client.go, pkg/client/issuecredential/client_test.go, pkg/controller/command/errors.go, pkg/controller/command/issuecredential/command.go, pkg/controller/command/issuecredential/command_test.go, pkg/controller/command/issuecredential/models.go, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go
Adds `command` support based on the  Issue Credential client.
Closes #1611
=> feat: Issue Credential - adds command support

pkg/storage/couchdb/couchdbstore.go, pkg/storage/couchdb/couchdbstore_test.go
=> feat: Add couchdb prefix

pkg/storage/couchdb/couchdbstore.go, pkg/storage/couchdb/couchdbstore_test.go
=> fix: add prefix to close couchdb store

test/aries-js-worker/test/common.js
=> fix: Fixes js BDD test

pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go
=> refactor: Improve Presentation.SetCredentials()

pkg/didcomm/protocol/presentproof/service_test.go
Fixes Present Proof unit tests
Closes #1618 
=> refactor: Fixes Present Proof unit tests

pkg/crypto/tinkcrypto/crypto_test.go
=> test: Increase coverage of tinkcrypto MAC methods

pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/embedded_proof_test.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/support_test.go
=> fix: multiple proof array in VC

cmd/aries-agent-rest/startcmd/start.go
=> fix: Wrong function parameter name

pkg/doc/signature/suite/jsonwebsignature2020/public_key_verifier_test.go, pkg/doc/signature/verifier/public_key_verifier.go, pkg/doc/verifiable/embedded_proof.go, pkg/doc/verifiable/embedded_proof_test.go, pkg/doc/verifiable/linked_data_proof_test.go
=> fix: add signature suite when ldpSuites is empty

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/doc/verifiable/common.go, pkg/doc/verifiable/common_test.go, pkg/vdri/peer/did_test.go
=> refactor: DID verification methods

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/operation_test.go, test/aries-js-worker/test/verifiable/verifiable.js
- added proof options in generate presentation command
- added presentation in generate presentation request, if provided then
verifiable presentation will be created using given presentation.
- changed input credentials from string to json raw
- Closes #1643
- Closes #1644
- Closes #1664
=> feat: raw presentation & proof options in generate presentation 

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go
=> refactor: Option to disable Proof Check

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/operation_test.go
=> feat: skip verification opts in generate presentation

pkg/controller/command/issuecredential/models.go, pkg/controller/command/presentproof/models.go, pkg/controller/controller.go, pkg/controller/rest/issuecredential/models.go, pkg/controller/rest/issuecredential/operation.go, pkg/controller/rest/presentproof/models.go, pkg/controller/rest/presentproof/operation.go, pkg/controller/rest/presentproof/operation_test.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/presentproof/service.go
Adds REST support for the Present Proof protocol.
Closes #1667 
=> feat: Present Proof adds REST support

pkg/doc/signature/suite/jsonwebsignature2020/suite_crypto_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/kms/localkms/localkms.go, pkg/kms/localkms/pubkey_export_import_test.go, pkg/kms/localkms/pubkey_reader.go
=> fix: ECDSA P256 signature verification using tinkcrypto and localkms

pkg/controller/command/verifiable/command_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go
=> fix: Verifiable presentation without verifiable credentials

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go
- fixed a bug where proofoptions without verification method was causing
issues
- Part of #1664
=> fix: proof options without verification method

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go
=> fix: Generate presentaton to support key types other than ED25519

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go, pkg/doc/verifiable/presentation.go, pkg/store/verifiable/models.go, pkg/store/verifiable/store.go, pkg/store/verifiable/store_test.go, test/aries-js-worker/test/verifiable/presentation.js
- added presentation Save/Get/GetAll features in verifiable controller
- added new commands in REST and JavaScript controller
- Closes #1706
- Closes #1643
=> feat: presentation save/get/getAll commands

cmd/aries-js-worker/src/aries.js, pkg/client/didexchange/client_test.go, pkg/client/didexchange/example_test.go, pkg/client/outofband/client_test.go, pkg/client/route/example_test.go, pkg/controller/command/didexchange/command_test.go, pkg/controller/command/kms/command.go, pkg/controller/command/kms/command_test.go, pkg/controller/command/kms/models.go, pkg/controller/rest/didexchange/operation_test.go, pkg/controller/rest/kms/models.go, pkg/controller/rest/kms/operation.go, pkg/controller/rest/kms/operation_test.go, pkg/didcomm/protocol/route/service_test.go, pkg/framework/aries/framework.go, pkg/internal/mock/provider/mock_provider.go, pkg/mock/kms/legacykms/mock_kms_provider.go, pkg/vdri/registry_test.go, test/aries-js-worker/test/kms/kms.js
=> refactor: Switch to localkms in createkeyset wasm

pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go, pkg/internal/mock/provider/mock_provider.go, test/aries-js-worker/test/verifiable/presentation.js
=> feat: Use localkms in sign presentation

pkg/doc/jose/jwe.go, pkg/doc/jose/jwe_test.go
=> feat: JWE deserialize function

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/vdri/command.go, pkg/controller/command/vdri/command_test.go, pkg/controller/rest/vdri/models.go, pkg/controller/rest/vdri/operation.go, pkg/controller/rest/vdri/operation_test.go, test/aries-js-worker/test/verifiable/presentation.js
=> feat: Add resolve did to wasm

test/aries-js-worker/test/verifiable/verifiable.js
=> fix: js bdd-test

pkg/didcomm/packer/jwe/authcrypt/authcrypt_test.go, pkg/didcomm/packer/jwe/authcrypt/decrypt_jwk.go, pkg/didcomm/packer/jwe/authcrypt/pack.go, pkg/didcomm/packer/jwe/authcrypt/unpack.go, pkg/doc/jose/decrypter.go, pkg/doc/jose/encrypter.go, pkg/doc/jose/encrypter_decrypter_test.go, pkg/doc/jose/jwe.go, pkg/doc/jose/jwe_test.go
=> fix: JWE EPK and SPK deserialize error

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go
=> fix: VC Schema update to add uri constraint to issuer.id

pkg/doc/jose/encrypter_decrypter_test.go
=> test: Add interop JWE tests with Go Jose

pkg/kms/localkms/localkms.go, pkg/kms/localkms/localkms_test.go
=> feat: support ECDHES recipient key creation in KMS

pkg/doc/jose/encrypter_decrypter_test.go
This change concludes Encryption and Decryption using Go Jose and the local Aries-framework-go's JWE Encrypter. Go-Jose JWE interop is complete with this change.
part of #1726
=> test: add 2 way JWE tests with go jose

pkg/vdri/httpbinding/resolver.go, pkg/vdri/httpbinding/resolver_test.go, pkg/vdri/httpbinding/vdri.go
=> feat: Add auth token to http binding resolver

pkg/vdri/httpbinding/vdri.go
=> fix: typo in auth token

pkg/kms/localkms/localkms.go, pkg/kms/localkms/localkms_writer.go, pkg/kms/localkms/localkms_writer_test.go
=> refactor: change keyID length to 20 bytes and remove prefix URI

pkg/controller/command/kms/command.go, pkg/controller/command/kms/command_test.go, pkg/controller/command/verifiable/command.go
=> remove base64URL decode keyID from verifiable and kms commands

pkg/kms/localkms/localkms_writer.go, pkg/kms/localkms/localkms_writer_test.go
=> feature: kms KeyID - skip IDs starting with _

pkg/kms/localkms/localkms.go, pkg/kms/localkms/localkms_test.go, pkg/kms/localkms/privkey_import.go, pkg/kms/localkms/privkey_import_test.go, pkg/kms/localkms/pubkey_reader.go
=> feat: add Key import support into KMS

pkg/kms/localkms/localkms.go, pkg/kms/localkms/localkms_test.go
=> refactor: add one more test for private Key Import into kms

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/support_test.go
- adds image to the VC data model.
- should followup with #1768
=> feat: support image in issuer

pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/test-suite/verifiable_suite_test.go
=> fix: allow empty VCs in VP

pkg/client/route/client.go, pkg/client/route/client_test.go, pkg/controller/command/route/command.go, pkg/controller/command/route/command_test.go, pkg/controller/controller.go, pkg/controller/rest/route/operation.go, pkg/controller/rest/route/operation_test.go, pkg/didcomm/protocol/route/service.go, pkg/didcomm/protocol/route/service_test.go, pkg/internal/mock/didcomm/protocol/route/mock_route.go, test/bdd/features/aries_router_e2e_sdk.feature, test/bdd/features/introduce.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/introduce/introduce_sdk_steps.go, test/bdd/pkg/route/route_sdk_steps.go
=> feat: action events for routing service

pkg/kms/localkms/localkms.go, pkg/kms/localkms/localkms_test.go, pkg/kms/localkms/localkms_writer.go, pkg/kms/localkms/localkms_writer_test.go, pkg/kms/localkms/privkey_import.go
=> feat: support importing private key with a specific key ID

pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/jsonld.go
=> fix: json-ld strict validation on mapped schema elements

go.mod, go.sum, pkg/doc/signature/proof/proof.go, pkg/doc/signature/proof/proof_test.go, pkg/doc/verifiable/credential_ldp_test.go
=> fix: VC linked data proof verification

ci/version_var.sh
=> chore: Aries Framework Go v0.1.3 release

pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states_test.go, pkg/doc/verifiable/credential.go, pkg/doc/verifiable/credential_extension_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/example_credential_test.go, pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/presentation_jwt_proof_test.go, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> feat: Generic VC Issuer

docs/kms_secretlock.md
=> doc: add export pubkey import privkey

pkg/kms/localkms/localkms_test.go, pkg/kms/localkms/localkms_writer.go
=> fix: remove check length for requested KeysetID

pkg/client/didexchange/client.go, pkg/client/outofband/doc.go, pkg/client/outofband/example_test.go, pkg/client/route/models.go, pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go
=> doc: godoc and examples for outofband client pkg

pkg/crypto/api.go, pkg/crypto/tinkcrypto/crypto.go, pkg/crypto/tinkcrypto/primitive/composite/api/composite_encrypt.go, pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_aead_composite_common.go, pkg/framework/context/context.go, pkg/kms/api.go, pkg/kms/legacykms/api.go, pkg/kms/localkms/localkms.go, pkg/secretlock/local/internal/cipher/util.go, pkg/secretlock/local/masterlock/hkdf/master_secret_lock.go, pkg/secretlock/noop/noop_secret_lock.go
=> doc: update KMS/crypto/Context documentations

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/kms/command.go, pkg/controller/command/kms/command_test.go, pkg/controller/command/kms/models.go, pkg/controller/rest/kms/models.go, pkg/controller/rest/kms/operation.go, pkg/controller/rest/kms/operation_test.go, test/aries-js-worker/test/kms/kms.js
=> feat: Add import private key in controller (wasm,rest)

test/bdd/bddtests_test.go, test/bdd/features/issue_credential_controller.feature, test/bdd/features/presentproof_controller.feature, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go, test/bdd/pkg/presentproof/presentproof_controller_steps.go
Adds BDD tests for Present Proof REST API
Closes #1720
=> test: add BDD tests for Present Proof REST API

pkg/controller/command/kms/command.go, pkg/controller/command/kms/command_test.go, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go
=> refactor: Generate Presentation: Private Key as a proof option to be removed

test/aries-js-worker/fixtures/.env, test/aries-js-worker/fixtures/docker-compose.yml, test/bdd/fixtures/sidetree-mock/.env, test/bdd/fixtures/sidetree-mock/docker-compose.yml
=> ci: update sidetree-mock packages

pkg/framework/aries/framework.go
=> refactor: Update default endpoint value

pkg/client/outofband/example_test.go, pkg/client/route/models_test.go, pkg/didcomm/protocol/route/service.go
Update the URI (part of #1448)
=> refactor: Update Route Coordination type URIs (Route -> Mediator)

pkg/controller/command/verifiable/command_test.go, pkg/controller/rest/verifiable/operation_test.go, pkg/doc/signature/jsonld/processor.go, pkg/doc/signature/jsonld/processor_test.go, pkg/doc/signature/proof/data.go, pkg/doc/signature/proof/jws.go, pkg/doc/signature/signer/signer.go, pkg/doc/signature/signer/signer_test.go, pkg/doc/verifiable/credential_ldp_test.go, pkg/doc/verifiable/credential_test.go, pkg/doc/verifiable/linked_data_proof.go, pkg/doc/verifiable/support_test.go, pkg/doc/verifiable/testdata/context/trustbloc_jwk2020_example.jsonld
=> feat: verifier/signer to fail on invalid RDF

pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states.go, pkg/didcomm/protocol/issuecredential/states_test.go, pkg/internal/gomocks/didcomm/protocol/issuecredential/mocks.go
Adds WithPublicKeyFetcher option when we parse the credentials.
=> feat: Issue Credential - Adds WithPublicKeyFetcher option

pkg/doc/jose/encrypter_decrypter_test.go, pkg/doc/jose/jwe.go, pkg/doc/jose/jwe_test.go
=> feat: JWE compact serialize function

pkg/doc/did/doc.go, pkg/doc/did/doc_test.go, pkg/vdri/key/creator.go, pkg/vdri/key/resolver_test.go
=> fix: set key for KeyAgreement as embedded

pkg/doc/did/contexts.go, pkg/doc/did/doc.go, pkg/doc/did/doc_test.go
=> test: cache all JSON-LD contexts in DID tests

pkg/doc/verifiable/credential.go, pkg/doc/verifiable/presentation.go, test/bdd/go.mod, test/bdd/pkg/presentproof/presentproof_sdk_steps.go, test/bdd/pkg/verifiable/jsonld_context.go, test/bdd/pkg/verifiable/verifiable_steps.go
=> test: cache all JSON-LD contexts in BDD tests

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go, pkg/didcomm/protocol/didexchange/states.go, pkg/didcomm/protocol/didexchange/states_test.go, test/bdd/pkg/didexchange/didexchange_sdk_steps.go
=> fix: Prevents generating a new id if it already exists

pkg/client/introduce/client.go, pkg/client/introduce/client_test.go, pkg/client/introduce/example_test.go, test/bdd/pkg/introduce/introduce_sdk_steps.go, test/bdd/pkg/redeemableroutes/redeemable_routes.go
Adds type aliases to the client.
=> refactor: Introduce - adds type aliases to the client

pkg/client/introduce/client.go, pkg/client/introduce/client_test.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/internal/gomocks/client/introduce/mocks.go
Adds possibly to stop the Introduce protocol.
Closes #1870 
=> feat: Introduce - adds possibly to stop the protocol

pkg/controller/command/errors.go, pkg/controller/command/introduce/command.go, pkg/controller/command/introduce/command_test.go, pkg/controller/command/introduce/models.go
Adds controller/command support for the introduce client.
Closes #1868 
=> feat: Adds controller/command support for the introduce client

pkg/controller/controller.go, pkg/controller/rest/introduce/models.go, pkg/controller/rest/introduce/operation.go, pkg/controller/rest/introduce/operation_test.go, pkg/didcomm/protocol/introduce/models.go, pkg/didcomm/protocol/introduce/service.go
=> feat: Introduce - adds REST API support

pkg/controller/controller.go, pkg/controller/rest/outofband/models.go, pkg/controller/rest/outofband/operation.go, pkg/controller/rest/outofband/operation_test.go
=> feat: Outofband - adds REST API support

pkg/doc/jose/encrypter_decrypter_test.go
For compactSerialize (signle recipient) JWE encryption
part of #1872
This is the final change for Anoncrypt and so:
closes #1828
The new packer will not be the default one in the framework as it's for anoncrypt messages.
=> test: add Encrypt using Aries and Decrypt using go jose case

pkg/didcomm/protocol/outofband/service.go, pkg/didcomm/protocol/outofband/service_test.go
=> feat: Outofband - added actions support

pkg/controller/command/introduce/models.go, pkg/controller/command/outofband/command.go, pkg/controller/command/outofband/command_test.go, test/bdd/bddtests_test.go, test/bdd/features/introduce_controller.feature, test/bdd/fixtures/agent-rest/.env, test/bdd/fixtures/agent-rest/docker-compose.yml, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/introduce/introduce_controller_steps.go
* auto-execute `outofband` events
* adds introduce  `skip_proposal` test
Part of #1880
=> feat: Introduce - adds controller BDD tests

pkg/client/outofband/client.go, pkg/client/outofband/client_test.go, pkg/internal/gomocks/client/outofband/mocks.go
Added actions support for the client
=> feat: feat: Outofband - added actions support (client)

pkg/controller/command/outofband/command.go, pkg/controller/command/outofband/command_test.go, pkg/controller/command/outofband/models.go
=> feat: Outofband - added actions support (command)

pkg/controller/command/outofband/command.go, pkg/controller/command/outofband/command_test.go, pkg/controller/rest/outofband/models.go, pkg/controller/rest/outofband/operation.go, pkg/controller/rest/outofband/operation_test.go, pkg/controller/rest/rest.go, pkg/controller/rest/rest_test.go, test/bdd/pkg/introduce/introduce_controller_steps.go
=> feat: Outofband - added actions support (rest)

pkg/didcomm/protocol/didexchange/service.go, pkg/didcomm/protocol/didexchange/service_test.go
=> set invitationID on connection record for inbound didexchange.Request 

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, pkg/controller/command/verifiable/command.go, pkg/controller/command/verifiable/command_test.go, pkg/controller/command/verifiable/models.go, pkg/controller/rest/verifiable/models.go, pkg/controller/rest/verifiable/operation.go, pkg/controller/rest/verifiable/operation_test.go, test/aries-js-worker/test/verifiable/verifiable.js
- added REST & JS controller commands
- Closes #1900
=> feat: sign credential command in verifiable command controller

cmd/aries-js-worker/src/agent-rest-client.js, pkg/controller/command/introduce/command.go, pkg/controller/command/introduce/models.go, pkg/controller/command/issuecredential/command.go, pkg/controller/command/presentproof/command.go, pkg/controller/rest/introduce/operation.go, pkg/controller/rest/introduce/operation_test.go, pkg/controller/rest/issuecredential/models.go, pkg/controller/rest/issuecredential/operation.go, pkg/controller/rest/issuecredential/operation_test.go, pkg/controller/rest/presentproof/models.go, pkg/controller/rest/presentproof/operation.go, pkg/controller/rest/presentproof/operation_test.go, test/aries-js-worker/test/issuecredential/issuecredential.js, test/aries-js-worker/test/presentproof/presentproof.js, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go, test/bdd/pkg/presentproof/presentproof_controller_steps.go
* fixes swagger documentation
* changes `presentproof` and `issuecredential` request payload
=> refactor: Minor controller refactoring

cmd/aries-js-worker/src/agent-rest-client.js, cmd/aries-js-worker/src/aries.js, test/aries-js-worker/test/common.js, test/aries-js-worker/test/didexchange/didexchange_e2e.js, test/aries-js-worker/test/outofband/outofband.js
Adds WASM support for the `outofband` protocol.
Closes #1909 
=> feat: Outofband adds WASM support

pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_decrypt_factory.go, pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_encrypt_factory.go, pkg/crypto/tinkcrypto/primitive/composite/ecdh1pu/ecdh1pu_factory_test.go
=> feat: Create ECDH-1PU primitives factories

pkg/doc/verifiable/example_presentation_test.go, pkg/doc/verifiable/presentation.go, pkg/doc/verifiable/presentation_test.go, pkg/doc/verifiable/support_test.go, pkg/doc/verifiable/testdata/context/presentation_submission_v1.jsonld
- fixed the issue where verifiable presentation marshal/unmarshal
stripping off undefined fields
- Closes #1936
=> feat: custom fields in verifiable presentations

pkg/client/presentproof/client.go, pkg/client/presentproof/client_test.go, pkg/controller/command/presentproof/command.go, pkg/didcomm/protocol/presentproof/service.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
=> fix: #1942 (presentproof) unable to correlate requests to responses

pkg/client/didexchange/client.go, pkg/client/didexchange/client_test.go, pkg/didcomm/protocol/introduce/service.go, pkg/didcomm/protocol/introduce/service_test.go, pkg/didcomm/protocol/introduce/states_test.go, pkg/didcomm/protocol/issuecredential/service.go, pkg/didcomm/protocol/issuecredential/service_test.go, pkg/didcomm/protocol/issuecredential/states_test.go, pkg/didcomm/protocol/outofband/service.go, pkg/didcomm/protocol/presentproof/service.go, pkg/didcomm/protocol/presentproof/service_test.go, pkg/didcomm/protocol/presentproof/states_test.go, test/aries-js-worker/test/didexchange/didexchange_e2e.js, test/aries-js-worker/test/introduce/introduce.js, test/aries-js-worker/test/issuecredential/issuecredential.js, test/aries-js-worker/test/presentproof/presentproof.js, test/bdd/pkg/introduce/introduce_controller_steps.go, test/bdd/pkg/introduce/introduce_sdk_steps.go, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go, test/bdd/pkg/issuecredential/issuecredential_sdk_steps.go, test/bdd/pkg/presentproof/presentproof_controller_steps.go, test/bdd/pkg/presentproof/presentproof_sdk_steps.go
The following protocols were modified:
* presentproof
* introduce
* issuecredential
Closes #1929 
=> feat: Added MyDID and TheirDID to the action event

pkg/storage/mysql/mysqlstore.go, pkg/storage/mysql/mysqlstore_test.go
=> bug: remove nolint gosec and fix possible sql injection vulnerability

.github/workflows/build.yml, .github/workflows/test-suite.yml
Allow accessing docker.
Solves an issue with https://github.com/hyperledger/aries-framework-go/pull/1959
=> ci: Updates github actions

pkg/controller/command/presentproof/command.go, pkg/controller/command/presentproof/models.go, pkg/controller/rest/presentproof/models.go, pkg/didcomm/protocol/presentproof/properties.go, pkg/didcomm/protocol/presentproof/properties_test.go, pkg/didcomm/protocol/presentproof/service.go, test/bdd/go.mod, test/bdd/pkg/didexchange/didexchange_controller_steps.go, test/bdd/pkg/introduce/introduce_controller_steps.go, test/bdd/pkg/issuecredential/issuecredential_controller_steps.go, test/bdd/pkg/mediator/mediator_controller_steps.go, test/bdd/pkg/messaging/messaging_controller_steps.go, test/bdd/pkg/outofband/outofband_controller_steps.go, test/bdd/pkg/presentproof/presentproof_controller_steps.go, test/bdd/pkg/sidetree/sidetree.go, test/bdd/pkg/util/util.go
This PR adds a correlation id for the  Present Proof protocol.
Closes #1945 
Part of https://github.com/hyperledger/aries-framework-go/issues/1957
=> feat: Present Proof - added correlation id

cmd/aries-js-worker/README.md
Fixes readme for Aries JS usage.
=> docs: Fixes readme for Aries JS usage

pkg/didcomm/transport/ws/upgrade_srv.go
=> fix: Disables compression for websocket
